mapbox/mapbox-navigation-ios

MapboxNavigation.swift.podspec
readme.md

Closes: https://github.com/mapbox/MapboxNavigation.swift/issues/19
Should we add Carthage installation text here too? Is there anything else that needs to be done for Carthage to work?

Add installation text

---

MapboxNavigation.swift.podspec

Add s.dependency back

---

Example/Objective-C/Base.lproj/Main.storyboard
Example/Swift/AppDelegate.swift
Example/Swift/Base.lproj/Main.storyboard
Example/Swift/ViewController.swift
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-Swift.xcscheme
Podfile
Podfile.lock
readme.md

Adds:
* start/stop navigation button
* puts route under road labels
* adds destination marker
* rounds distances, also forces metric 
* updates to ios sdk rc1

Update demo app

---

Example/Swift/Base.lproj/Main.storyboard
Example/Swift/ViewController.swift
readme.md

Add instructions on how to begin route

---

MapboxNavigation/RouteVoiceController.swift

In the case where AWS does not have a voice for the user's system, we should not fallback to Joanna but fallback to the system synthesizer. 

If voice is not found, don't use Joanna

---

MapboxNavigationUI/RouteViewController.swift

Publicize mapview

---

MapboxNavigationUI/RouteVoiceController.swift

We had a regression recently where we were never resetting the `recentlyAnnouncedRouteStep` on a given step. Because of this, we were getting a single announcement per step and not up to 3.
/cc @1ec5

Fix announcemnent timer

---

MapboxNavigationUI/RouteTableViewController.swift

Fixes: https://github.com/mapbox/MapboxNavigation.swift/pull/74#pullrequestreview-26663123
/cc @1ec5

Fix time remaining text

---

MapboxNavigationUI/RouteTableViewHeaderView.swift

Closes: https://github.com/mapbox/MapboxNavigation.swift/issues/92
/cc @1ec5

Animate progress bar

---

Examples/Swift/ViewController.swift
MapboxNavigationUI/RouteViewController.swift

Setup RouteController in `route`'s didSet in order to make it accessible before the RouteViewController is presented.
@bsudekum 👀

Setup route controller

---

MapboxNavigationUI/RouteVoiceController.swift

Closes: https://github.com/mapbox/MapboxNavigation.swift/issues/98
Missing some SSML markup here.
/cc @1ec5

Fix polly continue way name

---

Docs/Storyboards.md
README.md

Rearranges the readme to emphasize the ease of using Mapbox Navigation UI.
/cc @bsudekum @1ec5

Update README to emphasize UI

---

Examples/Objective-C/ViewController.m
Examples/Swift/ViewController.swift
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/NavigationUI.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/Resources/Navigation.storyboard
MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/RouteTableViewController.swift
MapboxNavigation/RouteViewController.swift
README.md

Fixes #124, #123 
This PR renames Route->Navigation, clarifies the initializers and rearranges the table view setup so we don't try to access the route controller before it's initialized in the parent NavigationViewController.
@ericrwolfe @bsudekum @1ec5 👀

Idiomatic initializers

---

Examples/Swift/ViewController.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift

Fix pending camera

---

MapboxNavigation/RouteVoiceController.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/141

Add russian and spanish polly languages

---

MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/ManeuverDirection.swift

Organize folder structure

---

MapboxCoreNavigation.podspec
MapboxNavigation.podspec

CocoaPods parses these settings correctly from the target now.
@friedbunny 👀

Remove unwanted build settings

---

Examples/Swift/ViewController.swift
MapboxNavigation/NavigationViewController.swift

Call delegate when user arrives at destination

---

MapboxNavigation/RouteVoiceController.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/159

Set fallback volume properly

---

MapboxCoreNavigation.podspec
MapboxNavigation.podspec
README.md

Changes:
* Renamed `RouteViewController` to `NavigationViewController` https://github.com/mapbox/mapbox-navigation-ios/pull/133
* Added idiomatic initializers (`NavigationViewController.init(for:directions:)`) https://github.com/mapbox/mapbox-navigation-ios/pull/133
* Route simulation https://github.com/mapbox/mapbox-navigation-ios/pull/111
* Delegate callback when user arrives at destination https://github.com/mapbox/mapbox-navigation-ios/pull/158
* Use route options from initial directions request https://github.com/mapbox/mapbox-navigation-ios/pull/139
* Exposed route line configuration to delegates https://github.com/mapbox/mapbox-navigation-ios/pull/135
* Fall back to unsimplified shape when simplified shape not provided https://github.com/mapbox/mapbox-navigation-ios/pull/144
* Fix …

Release 0.3.0

---

README.md

Add note about 'pod repo update'

---

MapboxNavigation/Resources/Navigation.storyboard

Forgot to set the class on this separator view in #162 
@1ec5 @bsudekum

Set separator class

---

MapboxNavigation/Style.swift

Fixes #138 
Use global tint by default (from IB's global tint or code)

Use global tint by default

---

Examples/Swift/ViewController.swift
MapboxNavigation/Resources/Navigation.storyboard
MapboxNavigation/Style.swift

Add custom styling to way name label

---

MapboxNavigation/RouteMapViewController.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/194

Use `name` only for way name label

---

Examples/Objective-C/Base.lproj/Main.storyboard
Examples/Swift/Base.lproj/Main.storyboard
MapboxNavigation/Resources/Navigation.storyboard

Use traffic-day-v2 style throughout all styles

---

MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Resources/Base.lproj/Localizable.strings
MapboxNavigation/Resources/zh-Hans.lproj/Localizable.strings

Ran `extractLocStrings` over MapboxNavigation.
Working towards #168.

Extract base strings

---

MapboxNavigation.podspec

Now that the storyboard is localized, the location in the folder structure has changed.

Search deeper in resources for storyboard

---

MapboxNavigation.podspec

Addresses issues around https://github.com/mapbox/mapbox-navigation-ios/issues/174

Fix resource filepath

---

MapboxNavigation/NavigationViewController.swift

Resolves https://github.com/mapbox/mapbox-navigation-ios/issues/122

Allow custom rerouting logic.

---

MapboxNavigation/NavigationViewController.swift
MapboxNavigation/SimulatedRoute.swift

This is a cleaned up version of #209 without the Playground.
The route simulation does not take shortcuts or cruise at maximum speed through sharp turns or roundabouts anymore.

Improve route simulation

---

MapboxNavigation/SimulatedRoute.swift

The last coordinate in the given route was ignored.
@1ec5 @bsudekum

Fix route simulation

---

README.md
docs/Storyboards.md

Add "didArrive" and "shouldReroute" delegate methods to readme

---

MapboxNavigation/RouteVoiceController.swift

We should support all locales we can.

Add English, British voice

---

MapboxCoreNavigation/Constants.swift
MapboxCoreNavigation/Geometry.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/RouteProgress.swift

Use documentation comment syntax so Xcode and jazzy can detect documentation comments. Rewrote RouteController and RouteProgress documentation for accuracy.
/ref #5
/cc @ericrwolfe @bsudekum

Reformat documentation

---

Examples/Objective-C/Base.lproj/Main.storyboard
Examples/Swift/Base.lproj/Main.storyboard
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

Until congestion on the route line is rolled out, the navigation view style should include traffic.

Update map style to navigation-preview-day-v1

---

MapboxNavigation/RouteMapViewController.swift

When entering navigation mode, we need to set alignment earlier.

Fix user puck hover

---

MapboxCoreNavigation/Constants.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/RouteProgress.swift
MapboxNavigation/DistanceFormatter.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteManeuverViewController.swift
MapboxNavigation/RouteStepFormatter.swift
MapboxNavigation/RouteTableViewController.swift
MapboxNavigation/RouteVoiceController.swift

Add more documentation

---

README.md
docs/jazzy.yml
docs/theme/templates/doc.mustache

* Organizes docs sidebar
* Fixes dash link
* Adds analytics
* Minor readme updates

Minor documentation updates

---

Examples/Swift/CustomViewController.swift
Examples/Swift/ViewController.swift

Add location simulation to custom UI example

---

Examples/Objective-C/ViewController.m
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/SimulatedLocationManager.swift
MapboxNavigation/NavigationViewController.swift

Fixes #273 
RouteController and delegates were unset when using the storyboard approach.
Also fixed so that SimulatedLocationManager bridges to Obj-C
@friedbunny 👀

Fix lifecycle issue when using storyboard

---

MapboxCoreNavigation/RouteController.swift

Continue tracking after arrival

---

MapboxCoreNavigation/Geometry.swift
MapboxNavigation/RouteMapViewController.swift

Seeing a few crashes around this code. We need to guard against not finding the closest coordinate.

Guard against no closest coord

---

MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec

Update deps in podfiles

---

MapboxCoreNavigation/Constants.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/RouteProgress.swift
MapboxNavigation/DefaultLocationManager.swift
MapboxNavigation/MGLMapView.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/PollyVoiceController.swift
MapboxNavigation/RouteManeuverViewController.swift
MapboxNavigation/RouteVoiceController.swift
MapboxNavigation/Style.swift
docs/jazzy.yml

Addresses many of the undocumented methods in #299.
Hides undocumented classes/methods in Jazzy.
cc @1ec5

Improve documentation coverage

---

Examples/Swift/Info.plist
MapboxCoreNavigation/Bundle.swift
MapboxCoreNavigation/BundleAdditions.swift
MapboxCoreNavigation/NavigationLocationManager.swift
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Abbreviations.swift
MapboxNavigation/Bundle.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/PollyVoiceController.swift
MapboxNavigation/RoutePageViewController.swift
MapboxNavigation/RouteTableViewController.swift
MapboxNavigation/RouteVoiceController.swift
MapboxNavigationTests/MapboxNavigationTests.swift

Fixes #328 
This PR fixes voice guidance in background for `PollyVoiceController` and informs if `audio` is missing from `UIBackgroundModes`.

Fix voice guidance in background

---

MapboxNavigation/NavigationMapView.swift

This matches the route line to the styling applied to the motorway layer. Overall, the route line will appear a bit wider.

Match route line style to motorway widths

---

Examples/Swift/ViewController.swift
MapboxNavigation/DefaultStyle.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/Style.swift

Note, holding on this until some server side PRs are fixed.

Add congestion to route line

---

Examples/Objective-C/Base.lproj/Main.storyboard
Examples/Swift/Base.lproj/Main.storyboard
Examples/Swift/ViewController.swift
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

Update to v2 styles

---

MapboxNavigation/NavigationMapView.swift

It's just too thin.
Before:
After: 
/cc @1ec5 @ericrwolfe @nickidlugash

Wider route line

---

Examples/Objective-C/it.lproj/Main.strings
Examples/Swift/it.lproj/Main.strings
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/it.lproj/Localizable.strings
MapboxNavigation/Resources/it.lproj/Navigation.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings

Added an Italian localization from Transifex. Also updated the Spanish and Vietnamese localizations.
/cc @frederoni

Italian localization

---

MapboxCoreNavigation/MMEEventsManager.swift

`speaker`, `bluetooth`, or `headphones`
cc @bsudekum

Add audio type to telemetry events

---

MapboxCoreNavigation/RouteController.swift

The fatal we were seeing before was most likely fixed with https://github.com/mapbox/mapbox-navigation-ios/pull/399
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/371

Enable battery monitoring

---

Examples/Objective-C/zh-Hant.lproj/Main.strings
Examples/Swift/zh-Hant.lproj/Main.strings
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Resources/zh-Hant.lproj/Navigation.strings

Added a partial Traditional Chinese localization from Transifex.
/cc @lily-chai @YunjieLi @bsudekum

Added Traditional Chinese localization

---

MapboxCoreNavigation/CLLocation.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/SimulatedLocationManager.swift

Fixes #433 - Filter inaccurate locations
@ericrwolfe @bsudekum  👀

Filter inaccurate locations

---

MapboxCoreNavigation/CLLocation.swift

GPX-based locations reports a vertical and horizontal accuracy of -1.
@bsudekum 👀

Do not filter locations when using simulator

---

MapboxNavigation/RouteVoiceController.swift

Dont play reroute sound if muted

---

MapboxNavigation/RouteManeuverViewController.swift
MapboxNavigation/RouteMapViewController.swift

Fix buttons dip down

---

MapboxCoreNavigation/RouteController.swift

If a course is incorrect and the user is on the route, we should snap the user to the route and also calculate a better course then the one coming back from the device. 

Calculate a better course if user course is inaccurate

---

MapboxNavigation/MGLMapView.swift

Fixes arrow casing rotation
@ericrwolfe @bsudekum  👀

Rotate arrow casing

---

docs/theme/templates/doc.mustache

Fix analytics

---

MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec
README.md
docs/README.md
docs/jazzy.yml
docs/theme/templates/doc.mustache
scripts/document.sh

Move docs from mapbox.github.io to www.mapbox.com

---

MapboxNavigation/Style.swift

Fixed a bug in the StatusView where it could overlap the lane views while being positionally hidden.
@bsudekum 👀

Fix status view visibility

---

Cartfile
MapboxNavigation.podspec

Let's pin all dependencies to avoid breaking changes underlying dependencies.
@bsudekum 👀

Pin dependencies

---

MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec
README.md

Also updates podspec for docs to match the current versions.

Update to v0.6.1

---

MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/RoutePageViewController.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/507

Fix stale turn banner after resuming

---

MapboxCoreNavigation/Locale.swift
MapboxNavigation.xcodeproj/project.pbxproj

These locale functions actually need to be made public. Also fix the project file listing. I think there might have been a bad merge conflict resolution recently. 

Locale and project cleanup

---

Examples/Objective-C/ViewController.m

Fixed a bug in the Obj-C example.
@bsudekum 👀

Fix Obj-C example

---

Examples/Swift/ViewController.swift
MapboxNavigation/DefaultStyle.swift
MapboxNavigation/Style.swift

Added support for changing the status bar style using the same style class as the rest of the UI in case someone wants to use a darker background.
@bsudekum 👀

Add status bar to style

---

MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/RoutePageViewController.swift

Bleh, had a bad regression in https://github.com/mapbox/mapbox-navigation-ios/pull/520. But this seems to fix _everything_.

Fix swiping ahead

---

Cartfile
Cartfile.resolved
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

Updates a few minor issues:
* Uses better version of solar
* If the user requests a route with congestion, things could fail. This falls back gracefully
* Removes a `!`
* Fixes: https://github.com/mapbox/mapbox-navigation-ios/issues/533
/cc @1ec5

Better solar install, remove non-optional, default line color when no congestion

---

MapboxNavigation/RouteTableViewController.swift

Before looking up the keys.
/cc @frederoni

Check for valid indices

---

Cartfile
Cartfile.resolved
Examples/Objective-C/sl.lproj/Main.strings
Examples/Objective-C/uk.lproj/Main.strings
Examples/Swift/sl.lproj/Main.strings
Examples/Swift/uk.lproj/Main.strings
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/PollyVoiceController.swift
MapboxNavigation/Resources/sl.lproj/Navigation.strings
MapboxNavigation/Resources/uk.lproj/Navigation.strings

Added partial Slovenian and Ukrainian localizations from Transifex. Neither language is supported by Polly.
/cc @bsudekum @Andygol

Slovenian, Ukrainian localizations

---

MapboxNavigation/NavigationViewController.swift
MapboxNavigation/PollyVoiceController.swift

* Fixes the switch to night mode
* Make sure to always give fallback voice when polly fails
/cc @1ec5

Properly fallback when polly fails, fix night mode

---

MapboxNavigation/RouteTableViewController.swift

Revert #550

---

Examples/Swift/ViewController.swift
MapboxCoreNavigation/NavigationRouteOptions.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/RouteOptions.swift
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/NavigationViewController.swift

This creates a sublcass of `RouteOptions` called `NavigationRouteOptions`. 

Subclass route options

---

MapboxNavigation/DayStyle.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
MapboxNavigation/RouteTableViewController.swift
MapboxNavigation/RouteTableViewHeaderView.swift
MapboxNavigation/Style.swift

Fixes 
* status bar
* way name label
* Standardizes a few things
Still need to fix the ETA label for unknown.
/cc @frederoni

Minor night styles

---

MapboxCoreNavigation/Constants.swift
MapboxCoreNavigationTests/SpokenInstructionFormatter.swift

/cc @1ec5 @willwhite @ericrwolfe @frederoni

Highway high announcement at quarter of a mile

---

MapboxNavigation/NavigationViewController.swift

After we change the style, we need to reload the style to make sure the arrow, route line and waypoint circles are redrawn.

Reload map after changing style

---

Examples/Swift/AppDelegate.swift
MapboxNavigation/NavigationViewController.swift

This clears out old notifications when the user completes that step. 

Fix up local notifications

---

MapboxNavigation/DayStyle.swift

Increase size of way name label

---

MapboxNavigation/NavigationViewController.swift

This moves to make the switch to night mode a little earlier. This also fixes a UTC issue in solar. 
/cc @frederoni @ericrwolfe @1ec5

Use official sunset, fix UTC

---

MapboxNavigation/DayStyle.swift

Style resume and cancel button 
@bsudekum 👀

Style resume and cancel button

---

MapboxNavigation/DayStyle.swift

Reduce wayname

---

MapboxCoreNavigation/ScreenCapture.swift
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift

Exposed `didOpen/didCancel/didSend` feedback through the `NavigationViewControllerDelegate`
@bsudekum @ericrwolfe

Delegate various feedback events

---

MapboxNavigation/StyleKitArrows.swift

Updating slight right/left lane in a separate PR.
/cc @1ec5 @frederoni @ericrwolfe @willwhite

Add slight right/left maneuver icon

---

MapboxNavigation/RouteVoiceController.swift

Prefer the Alex voice over Samantha when Polly is unavailable and the preferred locale is U.S. English. Alex is higher-quality than Samantha, but you have to [download and install](https://support.apple.com/en-us/HT203077) it manually.
/cc @bsudekum

Use Alex voice as fallback voice when available

---

Examples/Swift/Base.lproj/Main.storyboard
Examples/Swift/ViewController.swift

Otherwise, the modal disappears before you can accept.

Request location permissions in demo app

---

MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

Transparent instructions background

---

Examples/Swift/ViewController.swift

This action sheet has not been performant for a long time. I think by moving the creation of this action sheet to init instead of adding it when clicking a button, a lot of memory is freed up. 
This is feeling 💯  better.

Make UIAlertController performant

---

MapboxCoreNavigation/DistanceFormatter.swift
MapboxCoreNavigationTests/DistanceFormatterTests.swift

Fixes #681 
@bsudekum 👀 
/cc @Sealos

Use lower rounding increment for shorter distances

---

MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

I also made the route line slighter thinner.
/cc @1ec5 @ericrwolfe @frederoni

Make upcoming maneuver arrow wider

---

MapboxNavigation/NavigationMapView.swift

Fixes #370, #705 
This PR throttles the frame rate to ~5 FPS when 10 seconds away from previous maneuver and 30 seconds until upcoming maneuver when the device is unplugged.

Throttle frame interval when unplugged

---

Examples/Swift/Info.plist
MapboxCoreNavigation/MMEEventsManager.swift
MapboxCoreNavigation/RouteController.swift
MapboxNavigation/FeedbackViewController.swift
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
MapboxNavigation/Resources/Base.lproj/Navigation.strings
MapboxNavigation/RouteMapViewController.swift

Still todo:
/cc @1ec5 @ericrwolfe @frederoni @JThramer

Add option to add audio recording to feedback event

---

MapboxCoreNavigation/RouteController.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/715
I'm fine with not allowing customization of the layers here.

Show spoken voice instructions on map in debug mode

---

Examples/Swift/Info.plist
Examples/Swift/ViewController.swift
MapboxCoreNavigation/Feedback.swift
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Bundle.swift
MapboxNavigation/FeedbackItem.swift
MapboxNavigation/FeedbackViewController.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/Resources/Base.lproj/Localizable.strings
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
MapboxNavigation/Resources/Base.lproj/Navigation.strings
MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/Style.swift
MapboxNavigation/Transitioning.swift
MapboxNavigation/UIView.swift

This is the PR for the partial Feedback Controller modal, now with 100% less Frankenstein! Shout-out to @ericrwolfe for working his git magic.

FeedbackViewController partial modal

---

MapboxNavigation/FeedbackViewController.swift
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
MapboxNavigation/Transitioning.swift

Fixes various layout issues introduced in #733 
@bsudekum 👀

Use autolayout to determine height of partially displayed view controller

---

MapboxNavigation/FeedbackViewController.swift

Play audio after done recording

---

MapboxCoreNavigation/Feedback.swift
MapboxNavigation/FeedbackItem.swift

* `bad_route` -> `routing_error`
* `unallowed_turn` -> `not_allowed`
* Removes `instruction_timing`
* Adds missing exit + road categories
cc @bsudekum @frederoni @danesfeder @JThramer

Tweak feedback categories

---

MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/FeedbackItem.swift
MapboxNavigation/FeedbackViewController.swift
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/Transitioning.swift
MapboxNavigation/UICollectionView.swift
MapboxNavigation/UIView.swift

- Tweaked the highlighted state.
- Increased auto dismiss interval from 5 to 10 seconds.
- Moved the long press recognizer to each individual cell and removed the delaysTouchesBegan so that it doesn't interfere with the regular `collection:didSelectItemAt:`.
- Added reroute feedback

Various feedback tweaks

---

README.md

Issue:
/cc @bsudekum @ericrwolfe

Removing Alerts section and updating README to reflect new server-side alerts narrative.

---

MapboxCoreNavigation/Constants.swift
MapboxNavigation/RouteMapViewController.swift

Dont automatically show feedback ui after reroute

---

MapboxNavigation/RouteMapViewController.swift

Show maneuver arow for first step

---

MapboxCoreNavigation/Constants.swift
MapboxCoreNavigation/MMEEventsManager.swift
MapboxCoreNavigation/RouteController.swift

Add more telem keys

---

MapboxNavigation/RouteMapViewController.swift

Update feedback category ordering

---

MapboxNavigation/PollyVoiceController.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/759
/cc @1ec5

Use NSCache instead of dictionary

---

MapboxCoreNavigation/Feedback.swift
MapboxNavigation/FeedbackItem.swift
MapboxNavigation/Resources/Base.lproj/Localizable.strings
MapboxNavigation/Resources/Base.lproj/Navigation.strings
MapboxNavigation/RouteMapViewController.swift

* Changes "General Issue" to "Other Map Issue"
* Removes "GPS Inaccurate" 
* Switches ordering of "Not Allowed" and "Closure"
cc @frederoni  @bsudekum

Update feedback item text and ordering

---

Examples/Swift/ViewController.swift
MapboxCoreNavigation/NavigationRouteOptions.swift
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/CGPoint.swift
MapboxNavigation/DayStyle.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift

Changes `showRoute` to accept an array of routes. This also adds a delegate method for selecting a route.
Issues to fix:
@1ec5 @frederoni any ideas about these issues?

Add alternate routes

---

MapboxNavigation/RouteMapViewController.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/811
/cc @frederoni

Dismiss reroute feedback button on press

---

MapboxNavigation/NavigationMapView.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/798
Fixes an issue where legs would not show up.
/cc @1ec5

Fix multi waypoint leg bug

---

MapboxNavigation/BottomBannerViewLayout.swift
MapboxNavigation/DayStyle.swift
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/Style.swift

@frederoni I've got most of it sorted out I think. The only problem I'm seeing is with the bottom bar. Can you look into having the width and height respect the superview but it's contents respect safe areas?

More iPhone X improvements

---

MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/es.lproj/Navigation.strings
MapboxNavigation/Resources/sv.lproj/Navigation.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Navigation.strings

Updated Spanish, Swedish, and Vietnamese translations from Transifex.

Update Spanish, Swedish, Vietnamese translations

---

MapboxCoreNavigation/MMEEventsManager.swift

These should be a value from 0-100 instead of 0 - 1.

Encode percentTimeInPortrait and percentTimeInForeground as Ints

---

MapboxNavigation/BottomBannerView.swift
MapboxNavigation/DashedLineView.swift
MapboxNavigation/InstructionsBannerView.swift
MapboxNavigation/LaneView.swift
MapboxNavigation/ManeuverView.swift
MapboxNavigation/NextBannerView.swift
MapboxNavigation/Style.swift

These UI components must be public/open in order to make them stylable.
@bsudekum 👀

Fix access level on newly introduced UI components

---

MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

Hide next banner by default

---

MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec

le sigh, forgot to bump the podspecs.
/cc @1ec5 @JThramer

Bump version

---

Examples/Swift/ViewController.swift
MapboxNavigation/DayStyle.swift
MapboxNavigation/Style.swift

- Remove unused DestinationLabel, CellTitleLabel, CellSubtitleLabel, CellTurnArrowView
- Style dismiss button
- Style next banner view

Minor fixes for day and night style

---

Examples/Objective-C/ViewController.m

Use NavigationRouteOptions in Obj-C example

---

MapboxNavigation/BottomBannerView.swift
MapboxNavigation/BottomBannerViewLayout.swift
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/UIView.swift

New layout for the bottom banner when using a compact vertical size class.
@bsudekum @JThramer @ericrwolfe

Compact bottom banner in landscape

---

MapboxNavigation/StepsViewController.swift

Fixes #868 
Open StepsViewController for use outside the `NavigationViewController`.

Open StepsViewController

---

MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

Fixes #882 
- Remove unknown constraint types.

Remove unknown constraint types

---

MapboxNavigation/RouteMapViewController.swift

Fixes https://github.com/mapbox/mapbox-navigation-ios/issues/878#issuecomment-347425605
@bsudekum @ashishke2m 👀

Do not show reroute feedback if general feedback is opted out

---

MapboxNavigation/NavigationMapView.swift

The block-based KVO API is the preferred way to observe keypaths in Swift >= 3.2.

Observe battery state with block-based KVO API

---

Examples/Swift/ViewController.swift

Fixes the custom style demo to show a custom style at any time, not just night.
/cc @frederoni

Fix custom style demo

---

MapboxNavigation/RouteMapViewController.swift

remove correct observer

---

MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/nl.lproj/Localizable.strings
MapboxNavigation/Resources/nl.lproj/Navigation.strings
MapboxNavigation/Resources/sv.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings

Pulled in latest localization changes from Transifex.
@1ec5 @davols @pveugen 👀

Update localizations (es, nl, sv, vi)

---

MapboxNavigation/RouteMapViewController.swift

removeTimer invalidate and set the timer to nil.
@bsudekum 👀

Nil out timer before creating a new

---

MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/758
/cc @1ec5

Fix annotatesSpokenInstructions, justify left

---

MapboxNavigation/PollyVoiceController.swift

Added regionType to PollyVoiceController init

---

MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/DayStyle.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/Style.swift
MapboxNavigation/StyleManager.swift
MapboxNavigation/UIView.swift
MapboxNavigationTests/StyleManagerTests.swift

Extracted style handling into a separate class.
The main issue before was that `RouteController.location` could be nil the very first second which resulted in solar being unable to calculate sunrise and sunset. The first coordinate on the route is now used as a fallback until the location manager received the first update.

Refactor style switching

---

MapboxNavigation/ManeuverView.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/909
> Hong Kong
/cc @frederoni

Flip roundabouts when necessary

---

MapboxCoreNavigation/Feedback.swift
MapboxNavigation/FeedbackItem.swift
MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/nl.lproj/Localizable.strings
MapboxNavigation/Resources/sv.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings

Fixes #916 
@ericrwolfe @bsudekum 👀

Add other_map_issue to feedback types

---

MapboxNavigation/NavigationMapView.swift

CADisplayLink’s `frameInterval` was deprecated in iOS 10 in favor of `preferredFramesPerSecond`.

Avoid deprecated usage of DisplayLink

---

MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/es.lproj/Navigation.strings
MapboxNavigation/Resources/nl.lproj/Localizable.strings
MapboxNavigation/Resources/nl.lproj/Navigation.strings
MapboxNavigation/Resources/sv.lproj/Localizable.strings
MapboxNavigation/Resources/sv.lproj/Navigation.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Navigation.strings

Pulled in the latest translations from Transifex
@1ec5 @bsudekum @JThramer 👀

Transifex 2017 12 19

---

Examples/Swift/CustomViewController.swift
MapboxCoreNavigation/Constants.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/SimulatedLocationManager.swift
MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/RouteVoiceController.swift
MapboxNavigation/StepsViewController.swift

Moved notifications to an extension on `Notification.Name` for improved discoverability and consistency with the settings notification.
@JThramer @bsudekum 👀

Move notifications

---

MapboxCoreNavigation/RouteController.swift

The arrive telemetry event was not reliably being sent. This consolidates the arrive event to where we're also telling the developer they have arrived at a waypoint.

Fix arrive telem event

---

LICENSE.md

Updating copyright on license to 2018.
/cc @1ec5 @bsudekum

Should Old Acquaintance be forgot, and never thought upon... 🎉

---

MapboxCoreNavigation/RouteController.swift

Instead of just grabbing the last location from the location manager, let's first throw out any unqualified locations and then grab the last location from locations.

Filter out bad locations

---

MapboxCoreNavigation/RouteController.swift

This fixes a few issues that came out of https://github.com/mapbox/mapbox-navigation-ios/pull/1013/. I will comment inline on each change.

Minor step advancement and waypoint arrival fixes

---

MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationViewController.swift

Implements #934.
*  Adding documentation for `NavigationMapViewDelegate` and `NavigationM…apViewCourseTrackingDelegate`, also a few little fixes here and there.
/cc @bsudekum @1ec5 @frederoni

NavigationMapViewDelegate documentation

---

MapboxCoreNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Navigation.strings

Updated German, Spanish, and Vietnamese translations from Transifex to reflect recent changes in the en route feedback UI, end-of-route feedback UI, and update notification.
/cc @bsudekum

Update German, Spanish, Vietnamese translations

---

CHANGELOG.md
Examples/Objective-C/he.lproj/Main.strings
MapboxCoreNavigation/Resources/he.lproj/Localizable.strings
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Resources/he.lproj/Navigation.strings
languages.md

Added a partial Hebrew localization from Transifex.
/cc @bsudekum

Add Hebrew localization

---

Examples/Swift/ViewController.swift
MapboxNavigation/RouteMapViewController.swift

close: https://github.com/mapbox/mapbox-navigation-ios/issues/996

 Send exit delegate when exiting end of route feedback ui

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Resources/da.lproj/Localizable.stringsdict
MapboxNavigation/Resources/da.lproj/Navigation.strings
MapboxNavigation/Resources/uk.lproj/Localizable.strings
MapboxNavigation/Resources/uk.lproj/Localizable.stringsdict
MapboxNavigation/Resources/uk.lproj/Navigation.strings

Updated Danish, Ukrainian translations from Transifex.
/cc @frederoni @Andygol

Update Danish, Ukrainian translations

---

CHANGELOG.md
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/UserCourseView.swift

Fixes #1079 - User puck is not flat in overview mode
This regressed in #1012
- wip
@akitchen @bsudekum 👀

Fix user puck transformation in overview

---

README.md

This text is sort of out of place and not necessary. We also have https://github.com/mapbox/mapbox-navigation-ios/blob/master/custom-navigation.md
/cc @1ec5

remove outdated text

---

MapboxCoreNavigation/Constants.swift
MapboxCoreNavigation/DistanceFormatter.swift
MapboxCoreNavigationTests/DistanceFormatterTests.swift

Removes a few unused constants.
@bsudekum 👀

Remove unused constants

---

MapboxCoreNavigation/CLLocation.swift

Fix location isQualified

---

CHANGELOG.md
MapboxCoreNavigation/DistanceFormatter.swift
MapboxCoreNavigation/NavigationSettings.swift
MapboxCoreNavigationTests/DistanceFormatterTests.swift
MapboxNavigation/NavigationViewController.swift

Fixes #589 - Option to use metric or customary units
@bsudekum @1ec5 @JThramer  👀

Support overriding default distance units

---

MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/xcshareddata/xcschemes/PodInstall.xcscheme
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall/ViewController.swift
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/process_podfile.sh

This test will ensure that integration through CocoaPods is in order by integrating MapboxNavigation and MapboxCoreNavigation on CI via CocoaPods on the current branch.
@bsudekum 👀

Re-enable pod pre-flight test

---

Examples/Swift/Base.lproj/Main.storyboard
Examples/Swift/CustomViewController.swift

Updates the custom UI example with recent changes.

Update custom example

---

MapboxCoreNavigation/DistanceFormatter.swift
MapboxCoreNavigationTests/DistanceFormatterTests.swift

Round yards so that it matches the road sign where applicable.
@bsudekum @vincethecoder @1ec5

Round yards

---

docs/guides/reduce-memory-usage.md

Minor edits to the Reducing Memory Usage guide.

Copyedit reducing memory usage guide

---

MapboxNavigation/ImageDownload.swift
MapboxNavigation/ImageDownloader.swift
MapboxNavigation/InstructionLabel.swift
MapboxNavigation/InstructionPresenter.swift
MapboxNavigationTests/ImageCacheTests.swift
MapboxNavigationTests/ImageDownloaderTests.swift
MapboxNavigationTests/ImageRepositoryTests.swift
MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
MapboxNavigationTests/Support/TestImageLoadingURLProtocol.swift

Related to #1046 - some light cleanup and refactoring.

ImageDownloader/InstructionPresenter tail work / cleanup / refactor

---

MapboxNavigation/NavigationViewController.swift
MapboxNavigation/Resources/Base.lproj/Localizable.strings
MapboxNavigation/Resources/bg.lproj/Localizable.strings
MapboxNavigation/Resources/ca.lproj/Localizable.strings
MapboxNavigation/Resources/da.lproj/Localizable.strings
MapboxNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/fr.lproj/Localizable.strings
MapboxNavigation/Resources/he.lproj/Localizable.strings
MapboxNavigation/Resources/hu.lproj/Localizable.strings
MapboxNavigation/Resources/nl.lproj/Localizable.strings
MapboxNavigation/Resources/pt-BR.lproj/Localizable.strings
MapboxNavigation/Resources/ru.lproj/Localizable.strings
MapboxNavigation/Resources/sv.lproj/Localizable.strings
MapboxNavigation/Resources/uk.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1158

remove weak gps status view update

---

MapboxNavigation/NavigationViewController.swift

As pointed out in https://github.com/mapbox/mapbox-navigation-ios/pull/1163/files#r171572957

Fix shouldDiscard delegate

---

MapboxNavigation/InstructionsBannerViewLayout.swift
MapboxNavigation/NextBannerView.swift

Fixes #1185 
Fixes aggressive abbreviations by using an RTL and layout state-agnostic width calculation.
@1ec5 👀

Fix aggressive abbreviation

---

MapboxNavigation/EndOfRouteViewController.swift
MapboxNavigation/NavigationView.swift
MapboxNavigation/RouteMapViewController.swift

Fixes #1168 - NavigationView’s initial frame is set to zero.
@JThramer @bsudekum 👀

Fix initial navigation view frame

---

MapboxNavigation/NavigationView.swift
MapboxNavigation/UIView.swift

Possibly fixes #1172 
I have a hard time trying to reproduce 1172. Successfully reproduced one time before this change but not consistently.
@JThramer @bsudekum 👀

Initial information stack view state

---

MapboxCoreNavigation/NavigationLocationManager.swift

Followup to: https://github.com/mapbox/mapbox-navigation-ios/pull/1178#discussion_r172508305

 Make desiredAccuracy a computed property

---

MapboxNavigation/RouteMapViewController.swift

Fixes #1198. It came to me just a few minutes ago. Seems to have done a pretty good job, other than a little bit of initial stutter on the puck, which I have not yet figured out.
*  Adding a (initial) layout pass, and shuffling order of operations around a little bit.

Fixing puck position

---

MapboxCoreNavigation/RouteController.swift

I noticed on [this drive](https://gist.github.com/bsudekum/0346edd592dfdd305137726cc43acc7e), we're speaking the final instruction twice after turn left onto divis. This uncovered a few issues.
1. `userSnapToStepDistanceFromManeuver` is updated when `rawLocation` is set. However, after setting `userSnapToStepDistanceFromManeuver`, the leg or step index my increment. If this is the case, we need to update `userSnapToStepDistanceFromManeuver` otherwise, it will still be calculating the distance based on the previous step.
1. https://github.com/mapbox/mapbox-navigation-ios/pull/1155 changed voice announcements to always occur when beginning a step. This assumes the first voice announcement is always the distance of the step. This is incorrect as seen in here:
```json
"distance": 61.2, …
```

Prevent two voice announcements on some final steps

---

CHANGELOG.md
MapboxCoreNavigation/String.swift
MapboxCoreNavigationTests/StringTests.swift
MapboxNavigation.xcodeproj/project.pbxproj

First adding a failing test, then will fix up the code.
/cc @JThramer

Fix minimumEditDistance with empty string

---

MapboxNavigation/InstructionsBannerView.swift
MapboxNavigation/RouteMapViewController.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1273
/cc @vincethecoder

 Properly show/hide stepListIndicatorView

---

release-process.md

Added documentation on how a release is put out.

Document release process

---

MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/DayStyle.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/UIImage.swift

Fixes #1298 - Styleable maneuver arrow
@JThramer @vincethecoder 👀

Styleable maneuver arrow

---

MapboxNavigation/NavigationMapView.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1359
/cc @1ec5

Fix lack of waypoint number bug

---

MapboxNavigation/DayStyle.swift
MapboxNavigation/NavigationMapView.swift

Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1356
Looks like the bug was introduced in: https://github.com/mapbox/mapbox-navigation-ios/pull/1342

Fix black arrow

---

MapboxNavigationTests/ImageDownloaderTests.swift
MapboxNavigationTests/ImageRepositoryTests.swift

Happy to let this sit open for a while and evaluate how it does on Xcode 9.3. I'm also planning on refactoring the URLProtocol implementation detail I think might not be correct.

Adjusting flaky test continuation criteria

---

MapboxCoreNavigation/RouteProgress.swift
MapboxNavigation/RouteVoiceController.swift

Do not use IUO

---

MapboxNavigation/InstructionPresenter.swift

Not sure how this happened. Maybe a merge clobber?

Fixing issue where exit codes weren't being detected correctly.

---

MapboxNavigation/InstructionPresenter.swift

Definitively fixes #1379, for realizes this time.

Adding support for exit signs on fork and merge exits.

---

MapboxNavigation/StepsViewController.swift

Modified code to reload the steps view controller's tableview as the data source changes whenever the user advances the steps on a route.
Closes: #1387

Fixed the crash in the steps list

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj

Reverts mapbox/mapbox-navigation-ios#1394
Unfortunately, this did not work.

Revert "Stop building i386"

---

MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/StepsViewController.swift

Hide last cell separator in each section

---

Cartfile.private
Cartfile.resolved
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/RouteVoiceController.swift
MapboxNavigationTests/LeakTest.swift
MapboxNavigationTests/LeaksSpec.swift

WIP
Brought in [Quick](https://github.com/Quick/Quick) and [Nimble](https://github.com/Quick/Nimble) which is inspired by [Cedar](https://github.com/cedarbdd/cedar) (@akitchen 👀 ) to check for leaks.
LeakTest is borrowed from [specleaks](https://github.com/leandromperez/specleaks) but it doesn't support Carthage and it doesn't build out-of-the-box.
cc @bsudekum

Test for leaks

---

Examples/Swift/Base.lproj/Main.storyboard
Examples/Swift/CustomStyles.swift
Examples/Swift/ViewController.swift
MapboxNavigation.xcodeproj/project.pbxproj

While working on the carplay example, I came to realize that the example app is a bit cluttered. This PR fixes some issues and de-clutters the codebase a bit.

Fix up example

---

MapboxNavigation/MapboxVoiceController.swift

An alternate take to https://github.com/mapbox/mapbox-navigation-ios/pull/1570.
In https://github.com/mapbox/mapbox-navigation-ios/issues/1561 be probably have a strong reference hanging around. This makes sure we're using weak self to avoid this reference.
/cc @1ec5

Use weak self in MapboxVoiceController

---

MapboxNavigation/RouteMapViewController.swift

Updates to display the drag step list handlebar when the instruction banner is reset.
Fixes #1587

Fixed the disappearance of the drag step list handlebar defect

---

CHANGELOG.md

* Updated change log to omit technical details regarding recent changes merged into the master branch.
/cc @1ec5

Revised recent entries in the change log

---

README.md

Added a CircleCI badge

---

Examples/Objective-C/ViewController.m

Forgot a super call

---

MapboxNavigation/StyleManager.swift
MapboxNavigationTests/StyleManagerTests.swift

Fix automatic night-time style switching

---

CHANGELOG.md

Added a blurb in the changelog for #1629
cc @1ec5 @Woildan

Add a blurb in the changelog for #1629

---

MapboxNavigationTests/NavigationViewControllerTests.swift

Stubbed out the only remaining audio playback from test environment.
@JThramer @akitchen

Don't play voice in testing environment

---

circle.yml

Print the raw xcodebuild log when a build fails on CI.
cc @akitchen

Print xcodebuild log when test fail

---

MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/UIEdgeInsets.swift

Hide compass when navigation bar is showing

CarPlay compass

---

circle.yml

Cherry-picked https://github.com/mapbox/mapbox-navigation-ios/pull/1693/commits/1f81439dec3715a8e411b843656f14661b264ce8

Use a more flexible destination description for pod integration test

---

MapboxCoreNavigation/DistanceFormatter.swift
MapboxCoreNavigationTests/DistanceFormatterTests.swift

Fixes #1691 Convert feet/meters to inches
@1ec5 @DavidGagne

Fix meters to inches conversion

---

MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/VisualInstruction.swift

Arrow Direction Fix

---

Examples/Objective-C/ViewController.m
MapboxNavigation/NavigationViewController.swift
MapboxNavigationTests/NavigationViewControllerTests.swift

Found the cause of the location jitter -- we had two RouteController's tick-tocking updates.

De-duping RouteControllers

---

MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift

Set `isUsedInConjunctionWithCarPlayWindow` to true when navigation starts from CarPlay.
cc @akitchen @1ec5

Reuse isUsedInConjunctionWithCarPlayWindow

---

MapboxNavigation/NavigationMapView.swift
MapboxNavigation/Style.swift
MapboxNavigationTests/NavigationMapViewTests.swift

Fixes #1592 NavigationMapView should not remove existing application-specific annotations
cc @akitchen @1ec5 @joshpuente

Persistent annotations provided by the user

---

MapboxCoreNavigation/CountdownTimer.swift
MapboxCoreNavigation/NavigationService.swift
MapboxCoreNavigationTests/MapboxNavigationServiceSpec.swift
MapboxNavigation.xcodeproj/project.pbxproj

Fixes #1776. 🇺🇸🎉 
* Fixing issue where using function as closure can result in unwanted scope capture. Rewriting to work as trailing closure.

MapboxNavigationService over-retain fix.

---

README.md
codecov.yml

Tweaked the codecov settings a bit
cc @JThramer

Ignore some paths in codecov

---

.tx/config

Updated the Transifex configuration to reflect the example application consolidation that took place in #1813.
/cc @frederoni

Update Transifex configuration for example consolidation

---

CHANGELOG.md
MapboxCoreNavigation/RouteController.swift

Fix rerouting at arrival logic

---

docs/guides/Using Map Matching.md

Fixing typo.

---

MapboxCoreNavigation/DistanceFormatter.swift
MapboxCoreNavigationTests/DistanceFormatterTests.swift

Round distances in CarPlay

---

MapboxCoreNavigation/RouteController.swift

Fixes #1984 Estimated location
cc @d-prukop @JThramer

Expose estimated location

---

BenchTests/BenchTests.swift
CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Example/ViewController.swift
MapboxNavigation/CarPlayManager.swift
MapboxNavigation/CarPlayManagerDelegate.swift
MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift
MapboxNavigationTests/CarPlayManagerTests.swift

Implements Deliverable 1 of #2017.
WIP. Will be updating this as polish is added.
To-do: 

CarPlay Continuity

---

MapboxCoreNavigation/RouteController.swift

Safely unwrap spoken instruction
cc @JThramer

Safely unwrap spoken instruction

---

MapboxNavigation/UserCourseView.swift

Fixes #2002 
The puck doesn't have any gesture recognizers so it should pass through user interactions to the map view.
@1ec5

Disable user interaction on user course view

---

MapboxCoreNavigation/Resources/de.lproj/Localizable.strings
MapboxCoreNavigation/Resources/fr.lproj/Localizable.strings
MapboxCoreNavigation/Resources/vi.lproj/Localizable.strings
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/fr.lproj/Localizable.strings
MapboxNavigation/Resources/hu.lproj/Localizable.stringsdict
MapboxNavigation/Resources/sv.lproj/Localizable.strings

Updated the German, French, Hungarian, Swedish, and Vietnamese localizations from Transifex.

Update localizations from Transifex

---

Example/ViewController.swift
MapboxNavigation/CarPlayManager.swift
MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigationTests/CarPlayManagerTests.swift

Like it says on the box. Possible fix for #2036.
* Adding logic to end CarPlay navigation when we arrive at our final destination on the phone.
To-do:

Ending Carplay on Arrival

---

Example/AppDelegate+CarPlay.swift
MapboxNavigation/CarPlayManager.swift

This code was copied into the CarPlay example application code as part of #1717.
/cc @frederoni @vincethecoder

Remove unused list template code from CarPlayManager

---

CHANGELOG.md
Example/ViewController.swift
MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationView.swift
MapboxNavigation/RouteVoiceController.swift
MapboxNavigationTests/BridgingTests.m
TestHelper/Fixture.swift

Fixes #1526 
Expose RouteVoiceController.voiceControllerDelegate and NavigationMapView.navigationMapDelegate to Obj-C
@1ec5 @JThramer

Audit Obj-C bridging

---

CHANGELOG.md
MapboxCoreNavigation/SimulatedLocationManager.swift

Fixes #2095 
I don't know if there would be a better way of fixing this issue, but this works perfectly for our needs.

Update simulator distance when rerouting occurs.

---

CHANGELOG.md
MapboxNavigation/CarPlayManager.swift
MapboxNavigation/CarPlayNavigationViewController.swift

Update CarPlay tracking icon when tracking state changes

---

CHANGELOG.md
MapboxCoreNavigation/NavigationService.swift
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Constants.swift
MapboxNavigation/MBConstants.h
MapboxNavigation/MBConstants.m
MapboxNavigation/MBRouteVoiceController.h
MapboxNavigation/MBRouteVoiceController.m
MapboxNavigation/MapboxNavigation.h
MapboxNavigation/StyleManager.swift
MapboxNavigationTests/StyleManagerTests.swift

Fixes #2139  - Post notification when a style gets applied due to change of time of day or when entering or exiting a tunnel.
cc @1ec5 @JThramer @malwoodsantoro @achhaiba

Post notification when style changes

---

CHANGELOG.md
Example/yo.lproj/Localizable.stringsdict
Example/yo.lproj/Main.strings
MapboxCoreNavigation/Resources/yo.lproj/Localizable.strings
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/fr.lproj/Localizable.strings
MapboxNavigation/Resources/hu.lproj/Localizable.strings
MapboxNavigation/Resources/ja.lproj/Localizable.strings
MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
MapboxNavigation/Resources/ru.lproj/Localizable.strings
MapboxNavigation/Resources/sv.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings
MapboxNavigation/Resources/yo.lproj/Localizable.strings
MapboxNavigation/Resources/yo.lproj/Localizable.stringsdict
MapboxNavigation/Resources/yo.lproj/Navigation.strings

Fixes #2158 
Added Yoruba localization from Transifex
Updated (de, es, fr, hu, ja, pt-PT, ru, vi, sv)
Thank you for your contribution @toblinkz
cc @1ec5

Add Yoruba localization

---

docs/jazzy.yml
scripts/document.sh

Edits Jazzy generation script to support https://github.com/realm/jazzy/pull/1077.
Requires https://github.com/mapbox/jazzy-theme/pull/9 to merge before merging.
cc @1ec5

Update Jazzy theme

---

MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/ImageDownloader.swift
MapboxNavigation/URLSession.swift

Adds user-agent http header. Format: 
```
Example/0.40.0 MapboxNavigation/0.40.0 MapboxDirections/0.33.0 iOS/13.4.0 (x86_64)
```

Add http request user-agent

---

MapboxNavigation/FeedbackViewController.swift

Builds on #2419 
This PR removes the progress bar from the FeedbackViewController as per new design direction.

[Feedback][Part 2] Remove progress bar from FeedbackViewController

---

CHANGELOG.md
MapboxNavigation/NavigationViewControllerDelegate.swift

Deprecated methods were removed. @1ec5, I've made a global search throughout the repos and there are no implementations of these methods anymore, there is a chance that I've missed something, if so please let me know.
Closes #2395.

Remove deprecated methods.

---

Example/ViewController.swift

Fix crash in example app when placing route destination marker.

---

Example/ViewController.swift

Fix crash in action sheet when presenting on iPad.

---

Example/Base.lproj/Main.storyboard

Fix crash in example app when using custom style UI.

---

MapboxNavigation/BottomBannerViewLayout.swift
MapboxNavigation/StepsViewController.swift
MapboxNavigation/TopBannerViewController.swift

Fix top banner and steps cells alignment in landscape mode.

---

MapboxNavigation/InstructionsCardViewController.swift
MapboxNavigation/JunctionView.swift
MapboxNavigation/TopBannerViewController.swift

This is to ensure we reach the distanceAlongStep specified by the Directions API before showing the JV.

Show junction views at the distance along route specified by Directions API

---

MapboxNavigation/NavigationMapView.swift

Temporary workaround for #2488.

Add temporary fix which creates separate source for main route casing.

---

MapboxNavigation/NavigationMapView.swift

Fix vanishing route line arrival crash.

---

MapboxNavigation/RouteVoiceController.swift

Stop speaking instructions in case if voice is muted.

---

CHANGELOG.md
Example/ViewController.swift
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/ImageDownloader.swift
MapboxNavigation/InstructionsCardViewController.swift
MapboxNavigation/JunctionView.swift
MapboxNavigation/TopBannerViewController.swift
MapboxNavigation/URLSession.swift

Adds junction views to navigation UX.

Add junction views.

---

CHANGELOG.md
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

Fix warnings related to styling (end of route) in Interface Builder.

---

MapboxCoreNavigationTests/OfflineRoutingTests.swift
MapboxNavigation/InstructionsCardContainerView.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/SpeechSynthesizing.swift

Adding some minor changes as part of code review of PR [here](https://github.com/mapbox/mapbox-navigation-ios/pull/2522).

Minor changes as part of code review #2522.

---

CHANGELOG.md
Example/ViewController.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationViewController.swift

Remove buildingHighlightingEnabled public property.

Remove buildingHighlightingEnabled public property.

---

MapboxNavigation/NavigationMapView.swift

Remove routes in case if removeRoutes() was called.

---

MapboxNavigation/NavigationMapView.swift

Fix map view flickering.

---

Example/ViewController.swift

Add fix which allows to remove waypoints when pressing on them.

---

Example/Base.lproj/Localizable.strings
Example/ViewController.swift
MapboxNavigation/FeedbackItem.swift
MapboxNavigation/FeedbackSubtypeViewController.swift
MapboxNavigation/Resources/Base.lproj/Localizable.strings
MapboxNavigation/Resources/en.lproj/Localizable.stringsdict

Move hard coded strings to localizable ones.
Fixes #2474.

Make Second Level Feedback strings localizable

---

MapboxNavigation/MGLStyle.swift

Update day/night style URLs.

---

MapboxNavigation/EndOfRouteViewController.swift
MapboxNavigation/UIView.swift

Remove rounding corners method which is causing presentation issues in end of route view. (#2590)
(cherry picked from commit f32f5113d515cf41f9b926a7c491504ed971173e)

Remove rounding corners method which is causing presentation issues in end of route view. (#2590)

---

MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NextBannerView.swift

Fix NextBannerView presentation.

---

CHANGELOG.md
MapboxNavigation/BottomBannerViewLayout.swift
MapboxNavigation/NavigationView.swift
MapboxNavigation/NavigationViewLayout.swift
MapboxNavigation/RouteMapViewController.swift

Fix info button alignment and improve bottom banner height constraints for various device models.

---

Example/ViewController.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift

Removed the timer and state management of building highlights within the NavigationMapView.

Removed the timer and state management for building highlights

---

MapboxCoreNavigation/EventDetails.swift

Revert use of convertToSnakeCase JSON Encoding strategy.

---

CHANGELOG.md
MapboxCoreNavigation/LegacyRouteController.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/RouteProgress.swift
MapboxCoreNavigation/Router.swift

Resolves #2602 
The issue was caused by incorrect `RouteProgress` state after refreshing it.
Added updating route progress traveled distance after route refreshing. Minor refactoring included.

Vanished Route line flickering

---

MapboxNavigation/NavigationMapView.swift

Prevent updates to `UserCourseView` when layoutSubviews() is called.

---

MapboxNavigation/NavigationMapView.swift

Fix default visibility of the UserCourseView

---

MapboxNavigation/CarPlayManager.swift

Fix CarPlay crash on iOS 14 after a navigation session

---

.circleci/config.yml

Updated metrics trigger parameter name to support `main` branch renaming

Metrics Trigger update

---

MapboxNavigation/NavigationViewController.swift

Make NavigationViewController.indexedRoute public

---

CHANGELOG.md
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/TopBannerViewController.swift

Fix speed multiplier

---

CHANGELOG.md
Example/ViewController.swift

Prevent clear map button disappearance when pressing on route.

---

CHANGELOG.md
Example/uk.lproj/Main.strings
MapboxNavigation/Resources/uk.lproj/Localizable.strings
MapboxNavigation/Resources/uk.lproj/Localizable.stringsdict
MapboxNavigation/Resources/uk.lproj/Navigation.strings

Add Ukrainian localization.

---

CHANGELOG.md

Spotted while checking generated docs.

Add a missing parenthese in changelog

---

CHANGELOG.md
MapboxNavigation/InstructionsCardViewController.swift
MapboxNavigation/NavigationViewController.swift

The scroll view will not end dragging, caused `scrollToItem(at:at:animated:)` not working properly in `snapToIndexPath(_ indexPath:)`. With paging enabled, autoLayout has issues. Implemented a workaround in `snapToIndexPath(_ indexPath:)` by disabling paging, calling `scrollToItem(at:at:animated:)`, then enabling paging again. Since the issue wasn't fixed with iOS 14.1 nor 14.2, we are going with this workaround for now.
The layout of instructions cards when switching orientations (from portrait to landscape) would not properly display the correct card. Added a fix to show the `indexBeforeSwipe`. The other option was to show the `indexPath`, but this option would show the next card (when not previewing upcoming maneuvers) instead of the current card.
Swiping is hard-coded in several …

Swipe bugs (instructions cards and right-to-left languages)

---

Sources/MapboxNavigation/NavigationMapView.swift

Fix crash in NavigationMapView if it's created via storyboard.

---

Sources/MapboxNavigation/NavigationMapViewDelegate.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift

PR adds correct stubs for waypoint customization delegates.

Add default implementations for waypoint customization delegates.

---

Sources/MapboxNavigation/NavigationMapView.swift

This PR is to fix an issue where the route line was drawn over the street layer #2814.
Removed check for empty source during parent layer initialization in `addMainRouteLayer(_:)` that was preventing the `for` loop from going through several of the map layers.

Fix route layer shown over map labels

---

MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

Update to Mapbox Geocoder `0.14.0`.

Update to Mapbox Geocoder 0.14.0.

---

CHANGELOG.md

Updates to include Route Duration Annotations into v2.

Merge v1.3 to v2.0 except route duration annotations

---

Example/ViewController.swift

Remove waypoint styling delegate methods which were added in scope of https://github.com/mapbox/navigation-ios-examples/pull/87.

Remove waypoint styling delegate methods.

---

Sources/MapboxNavigation/RouteMapViewController.swift

PR fixes memory leak when showing shield icon.

Fix memory leak when showing shield icon.

---

Sources/MapboxNavigation/NavigationMapView.swift

This PR fixes an issue where mapView annotation selection wasn't working. #2841
`setupGestureRecognizers()` now only requires failures of `mapView`'s `UITapGestureRecognizer` instead of all gesture recognizers.

Fix MapView annotation selection not working

---

.circleci/config.yml

This PR corrects Metrics Payload which was malformed.
This was not noticeable before because such incorrect config resulted in using default values on Metrics side, which still produced desired results. Introducing parameterised input revealed syntax error.

Metrics config fix

---

Sources/MapboxCoreNavigation/NavigationEventsManager.swift

Fixes https://github.com/mapbox/navigation-sdks/issues/695
Avoids disabling telemetry events after starting navigation and sending the application to the background.

 Avoid disabling telemetry events after starting navigation

---

CHANGELOG.md
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
Sources/MapboxNavigation/CarPlayManagerDelegate.swift

Minor cleanup from https://github.com/mapbox/mapbox-navigation-ios/pull/2832

Minor tail work to add missing documentation for CarPlay changes in last commit

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxNavigation/NavigationMapView.swift

PR addresses feedback from https://github.com/mapbox/mapbox-navigation-ios/pull/2930.

Address history dumping related feedback.

---

.circleci/config.yml

Fixes #2904.
I added a new optional step in `pod-job` that archives the test application. This will help us to find problems with the archivation, as we had here #2824.
We can discuss if this step is necessary and should we add it to `build-job` as well.
The new archiving step usually takes 3 minutes, but `pod-job` isn't a bottleneck for our build time, so it shouldn't affect build time for the whole workflow.

Add archiving step on Circle CI

---

MapboxNavigation.xcodeproj/project.pbxproj

This pr is to fix the file path for OrnamentsController.swift.

Fix the file path for OrnamentsController.swift

---

Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift

Fixes types inconsistency in the electronic horizon `userInfo` dictionary.

Fix `userInfo` dictionary types for electronic horizon

---

Example/Base.lproj/Main.storyboard
Example/ViewController.swift

Just noticed that we have some unused code in ViewController.swift, so here is a quick PR to fix this.

Remove unused code from ViewController.swift

---

Sources/MapboxNavigation/FeedbackSubtypeCollectionViewCell.swift

Fixes #2969.
Before fix:
After fix:

Fix feedback UI.

---

CHANGELOG.md
Cartfile.resolved
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Bench.xcscheme
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
Package.resolved
Package.swift
Sources/MapboxNavigation/CameraController.swift
Sources/MapboxNavigation/CameraStateTransition.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CredentialsManager.swift
Sources/MapboxNavigation/FollowingCameraOptions.swift
Sources/MapboxNavigation/NavigationCamera.swift
Sources/MapboxNavigation/NavigationCameraConstants.swift
Sources/MapboxNavigation/NavigationCameraDebugView.swift
Sources/MapboxNavigation/NavigationCameraStateTransition.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewportDataSource.swift
Sources/MapboxNavigation/NavigationViewportDataSourceOptions.swift
Sources/MapboxNavigation/OverviewCameraOptions.swift
Sources/MapboxNavigation/ViewportDataSource.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

PR introduces several Navigation Camera Viewport API improvements:
- Applied new Mapbox Maps camera related API changes.
- Fixed https://github.com/mapbox/mapbox-navigation-ios/issues/2945.
- Implemented https://github.com/mapbox/mapbox-navigation-ios/issues/2946.
- Fixed issue, which was causing incorrect camera course (by updating to Mapbox Maps `10.0.0-beta.18.1`).
- Fixed potential retain cycle when using `ViewportDataSourceDelegate`.
- Updated to Mapbox Maps `10.0.0-beta.18.1` and Mapbox Navigation Native `48.0.5`.

Navigation camera improvements.

---

Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift

A small fix for this issue: https://github.com/mapbox/mapbox-navigation-ios/pull/2952/files#r620228624

Fix history directory path configuration

---

CHANGELOG.md
Sources/MapboxCoreNavigation/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/RouteLegProgress.swift
Sources/MapboxNavigation/BottomBannerViewController.swift
Sources/MapboxNavigation/StatusView.swift

PR removes deprecated APIs, which are no longer used.

Remove deprecated and obsoleted APIs.

---

Sources/MapboxCoreNavigation/CoreConstants.swift
Sources/MapboxCoreNavigation/Distance/GantryDistanceInfo.swift
Sources/MapboxCoreNavigation/Distance/LineDistanceInfo.swift
Sources/MapboxCoreNavigation/Distance/PointDistanceInfo.swift
Sources/MapboxCoreNavigation/Distance/PolygonDistanceInfo.swift
Sources/MapboxCoreNavigation/Distance/RoadObjectDistance.swift
Sources/MapboxCoreNavigation/Distance/RoadObjectDistanceInfo.swift
Sources/MapboxCoreNavigation/Distance/SubgraphDistanceInfo.swift
Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdge.swift
Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdgeMetadata.swift
Sources/MapboxCoreNavigation/EHorizon/RoadGraphPath.swift
Sources/MapboxCoreNavigation/EHorizon/RoadGraphPosition.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObject.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObjectEdgeLocation.swift
Sources/MapboxCoreNavigation/Location/GantryLocation.swift
Sources/MapboxCoreNavigation/Location/OpenLRLineLocation.swift
Sources/MapboxCoreNavigation/Location/OpenLROrientation.swift
Sources/MapboxCoreNavigation/Location/OpenLRPointLocation.swift
Sources/MapboxCoreNavigation/Location/OpenLRSideOfRoad.swift
Sources/MapboxCoreNavigation/Location/PointLocation.swift
Sources/MapboxCoreNavigation/Location/PolygonLocation.swift
Sources/MapboxCoreNavigation/Location/PolylineLocation.swift
Sources/MapboxCoreNavigation/Location/RoadObjectPosition.swift
Sources/MapboxCoreNavigation/Location/RouteAlertLocation.swift

This PR adds code documentation for #2991.

Add code documentation

---

Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift

Update incorrect documentation in `PassiveLocationDataSource`.

Update incorrect documentation in `PassiveLocationDataSource`.

---

.circleci/config.yml

This PR extends CircleCI config to run test using Package.swift definition.

Add running tests using Package.swift

---

Sources/MapboxCoreNavigation/Directions.swift

`Directions.calculateOffline` uses only `path` of Directions URL and no parameters. Even with simple route options, this leads to conflict in Polyline versions and the response will be parsed with a wrong route geometry.
Full URL should be provided to a router.

Fix offline routing

---

CHANGELOG.md
Sources/MapboxNavigation/FeedbackSubtypeViewController.swift
Sources/MapboxNavigation/FeedbackViewController.swift

Fix the moment of custom feedback event creation

---

CHANGELOG.md
Sources/MapboxNavigation/FeedbackSubtypeViewController.swift
Sources/MapboxNavigation/FeedbackViewController.swift

Fix feedback event creation

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/TestHelper/NavigationServiceTestDoubles.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

This is kind of bug with a "breaking change" fix because some users can depend on this bug now as our tests have shown.

Fix #3056 RouteController shouldDiscard location logic

---

Example/AppDelegate+CarPlay.swift

Fix state switching in overview button on CarPlay.

---

CHANGELOG.md

Catch up with `main` branch.

---

.circleci/config.yml

Fixes https://github.com/mapbox/mapbox-navigation-ios/issues/2951.

Remove `--allow-warnings` flag from `config.yml`.

---

docs/jazzy.yml

Add Electronic Horizon section in docs.

---

Sources/MapboxNavigation/NavigationMapView.swift

Fix alternative route line selection.

---

Sources/MapboxNavigation/NavigationMapView.swift

Bring back `MapView.preferredFramesPerSecond` property usage.

---

Sources/MapboxNavigation/Transitioning.swift

Fix `FeedbackViewController` presentation on iPad.

---

MapboxNavigation.xcodeproj/project.pbxproj
Package.swift
Sources/CarPlayTestHelper/CPMapTemplate+MBTestable.m
Sources/CarPlayTestHelper/CPNavigationSessionFake.m
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Sources/TestHelper/XCTestCase++.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift
Tests/MapboxNavigationTests/LeaksSpec.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Tests/MapboxNavigationTests/Support/AccessToken.swift
Tests/MapboxNavigationTests/Support/XCTestCase++.swift

Restores:
- `CarPlayManagerTests.swift`
- `NavigationViewControllerTests.swift`
- `LeaksSpec.swift`
Some tests in `NavigationViewControllerTests.swift` had to be disabled due to be in not working condition.

Restore some tests

---

Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

Some of the tests fails sporadically. This is an attempt to fix that.

Fix some tests

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/Directions.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Update to Mapbox Navigation Native `v55.0.0`.

Update to Mapbox Navigation Native `v55.0.0`.

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift

Change access level of StyleManager [here](https://github.com/mapbox/mapbox-navigation-ios/blob/v2.0.0-beta.15/Sources/MapboxNavigation/CarPlayNavigationViewController.swift#L84) and [here](https://github.com/mapbox/mapbox-navigation-ios/blob/v2.0.0-beta.15/Sources/MapboxNavigation/CarPlayMapViewController.swift#L14) that enables change the style dynamically as same as [`NavigationViewController`](https://github.com/mapbox/mapbox-navigation-ios/blob/v2.0.0-beta.15/Sources/MapboxNavigation/NavigationViewController.swift#L288).
No screenshots

Change access level of styleManager in CarPlay

---

Sources/MapboxNavigation/NavigationViewController.swift

This pr is to trigger the location update when it's changing from simulated to non simulated location manager during navigation.

A quick fix for the location update under non-simulation case

---

Sources/MapboxNavigation/NavigationMapView.swift

This pr is to improve the vanishing route line during non-simulated situation, to be synced with the default userCourseView, when they have different location update rate.

fix the vanishing route line synced with userCourseView

---

scripts/update-version.sh

Fixes #3143
"agvtool" doesn't work when there are multiple "xcodeproj" in
the directory. So, we temporarily move "xcodeproj" files aside to
fulfill "agvtool" requirements.

Fix update-version.sh script

---

Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationViewController.swift

Reload `MapView` style when `StyleManager` changes its appearance.

---

Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

Fix issue, which was causing problems with adding final destination `PointAnnotation`.

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/MapView.swift
Tests/MapboxNavigationTests/MapViewTests.swift

Add `tileSetIdentifier` parameter usage.

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayMapViewController.swift

Add `SpeedLimitView` to `CarPlayMapViewController`.

---

Sources/MapboxNavigation/CarPlayManager.swift

Fix route preview on CarPlay.

---

Sources/MapboxNavigation/NavigationViewController.swift

Also remove not relevant anymore code related to lazy var because
voiceController is no longer a lazy var.

Fix redundant RouteVoiceController creation if a custom one is provided

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Feedback.swift

There was a missing feedback subtype description for `.incorrectVisual(subtype: .incorrectSpeedLimit)`.
This PR fixes this and prevent similar issues by removing `default` switch case.

Fix missing feedback subtype descriptions

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Updating `mapbox-directions-swift` to the latest beta version.

Update to `mapbox-directions-swift` to v2.0.0-beta.8

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/CarPlayTestHelper/CPMapTemplate+MBTestable.m
Sources/MapboxNavigation/NavigationGeocodedPlacemark.swift
Tests/MapboxNavigationTests/NavigationGeocodedPlacemarkTests.swift

Add `NavigationGeocodedPlacemarkTests` tests.

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/RecentItem.swift
Tests/MapboxNavigationTests/RecentItemTests.swift

Add automated tests for `RecentItem`.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/NavigationService.swift

Fix first sent location in NavigationService.start method

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Sources/TestHelper/DirectionsSpy.swift
Sources/TestHelper/Fixture.swift
Sources/TestHelper/RouterDelegateSpy.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

I've commented some code changes inline, please follow them.
Haven't added for moving puck, will cut a separate ticket, or move this task to GA? @1ec5

Rerouting after arrival

---

Sources/MapboxNavigation/NavigationViewportDataSource.swift

Closing #3272.
New behavior:
https://user-images.githubusercontent.com/1496498/129960068-31d168c0-db36-4a02-a1b3-935fd7f8e9db.mp4

Do not use bearing when navigation camera transitions to the overview mode.

---

scripts/document.sh

Fixes #3278
Thanks @1ec5 for finding [the cause of the issue](https://github.com/mapbox/mapbox-navigation-ios/pull/3026#discussion_r692213730).

Replace SHORT_VERSION in generated docs.

---

.circleci/config.yml
scripts/trigger-metrics.py

This PR adds a separate Python script to trigger the metrics pipeline.

Add python script for triggering metrics

---

.circleci/config.yml
scripts/trigger-metrics.py

Fix the CircleCI build.
Successful builds after the fix: https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios?branch=azarovalex%2Ftrigger-metrics

Fix metrics pipeline trigger

---

Sources/MapboxNavigation/NavigationCameraStateTransition.swift
Sources/MapboxNavigation/UserCourseView.swift

PR improves camera transition by removing check, which allows to detect whether final destination is off-screen.
Before:
https://user-images.githubusercontent.com/1496498/130259916-2ecb72ea-eb13-446b-8a7a-27c710b108bd.mp4
After:
https://user-images.githubusercontent.com/1496498/130259994-20943c81-d5ff-4cb4-9f89-1e90673533dd.mp4

Improve navigation camera transition.

---

.github/ISSUE_TEMPLATE/bug_report.yml

Change Navigation SDK field to input in the issue template

---

Example/AppDelegate.swift
Example/Info.plist
Example/ViewController.swift

It is beneficial for sharing history files with NavNative team.

Add ability to record NavNative history in Example

---

.circleci/config.yml
Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift

Temporary disable API Diff workflow as it has a lot of bugs

---

Sources/MapboxCoreNavigation/EHorizon/RoadObjectType.swift

Update `RoadObjectType` documentation.

Update `RoadObjectType` documentation.

---

Sources/MapboxCoreNavigation/EHorizon/RoadGraph.swift
Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdgeMetadata.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObjectStore.swift

A teaser part for #3180.
Regrouped EH-related classes members and added codemarks. This PR is a first part in attempt to improve code documentation, basically a PoC before running same update on all the codebase.

EH Mark comments

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/Resources/ca.lproj/Localizable.strings

Updated Catalan translations from Transifex. Thanks to @rroset for the translations!

Update Catalan translations

---

Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift

Restore testNotReroutingForAllSteps test

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/Feedback/FeedbackSubtypeCollectionViewCell.swift

Fix `CPMapTemplate.tripEstimateStyle` update issues.

---

Sources/MapboxNavigation/NavigationViewportDataSource.swift

Closing #3390.
Before:
After:
/cc @johnk1 @danpat

Improve viewport parameters on CarPlay.

---

Sources/MapboxCoreNavigation/BillingHandler.swift
Sources/MapboxCoreNavigation/BundleAdditions.swift
Sources/MapboxCoreNavigation/CLLocation.swift
Sources/MapboxCoreNavigation/CoreConstants.swift
Sources/MapboxCoreNavigation/DispatchTimer.swift
Sources/MapboxCoreNavigation/DistanceFormatter.swift
Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/ReplayLocationManager.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RouteLegProgress.swift
Sources/MapboxCoreNavigation/RouteProgress.swift
Sources/MapboxCoreNavigation/RouteStepProgress.swift
Sources/MapboxCoreNavigation/RouterDelegate.swift
Sources/MapboxCoreNavigation/SimulatedLocationManager.swift

2/4 part for #3180, continuing #3364.
Regrouped types members and added MARK comments to CoreNavigation module.
This PR is purely cosmetic. If you see any logic being altered - please highlight it! It might be more comfortable to checkout the code to view how it is structured now.

CoreNavigation MARK comments

---

scripts/debug_navigation_native.sh

This is MVP and by no means perfect solution. Possible improvements:

Adds a script to use debug version of MapboxNavigationNative

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/BundleAdditions.swift
Sources/MapboxNavigation/Bundle.swift
Tests/MapboxCoreNavigationTests/BundleAdditionsTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift

Improve `MapboxNavigation` bundle detection.

---

Sources/MapboxCoreNavigation/BillingHandler.swift
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/TestHelper/Fixture.swift
Sources/TestHelper/TestCase.swift
Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxNavigationTests/MapViewTests.swift

This is tail work for new pricing.

New billing trip starts on each waypoint

---

Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift

Don't update Navigator with locations after pause

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift

Make `CarPlayMapViewController` and `CarPlayNavigationViewController` subclassable.

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Sources/MapboxNavigation/CarPlayActivity.swift
Sources/MapboxNavigation/CarPlayManager.swift

Add panning functionality for `CarPlayNavigationViewController`.

---

.circleci/config.yml

Remove xcpretty

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayMapViewController.swift

Fix car play retain cycle

---

CHANGELOG.md
Sources/MapboxCoreNavigation/BillingHandler.swift
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift

Pause NavNative navigator when there are no running billing sessions

---

Sources/MapboxNavigation/NavigationMapView.swift

Fix issue, which was preventing from adding route duration layer to the map view.

---

CHANGELOG.md
MapboxNavigation-SPM.xcodeproj/project.pbxproj
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationViewController.swift

Add ability to disable dark style, while traversing through the tunnel.

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/RouteDurationAnnotationTailPosition.swift
Sources/MapboxNavigation/RoutesPresentationStyle.swift

Implement the ability to show routes based on style provided in `RoutesPresentationStyle`.

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/BuildingHighlighting.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/Constants.swift
Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
Sources/MapboxNavigation/NavigationViewController.swift

Implement the ability to highlight buildings during active-guidance on CarPlay.

---

Example/AppDelegate+CarPlay.swift

PR fixes deprecation of `NavigationService` initializer.

Fix compilation warnings in example application after Hybrid Router introduction.

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/TopBannerViewController.swift
Sources/MapboxNavigation/TopBannerViewControllerDelegate.swift

PR extracts `TopBannerViewControllerDelegate` into separate file and adds public documentation.

Add `TopBannerViewControllerDelegate` documentation.

---

scripts/debug_common_sdk.sh

Can be used to build a debug versions of the MapboxCommon SDK

Add debug common sdk script

---

Example/ViewController.swift

https://user-images.githubusercontent.com/413986/143578299-2e063cc4-7204-45db-8f8f-a6df47cdcaaa.mp4
https://user-images.githubusercontent.com/413986/143578129-acce1415-7312-497c-8105-acd23d448c6b.mp4

Improve Example app to no zoom animation after active navigation

---

Sources/MapboxNavigation/RouteVoiceController.swift

The description is misleading saying that this class only uses VoiceOver.

Update RouteVoiceController doc

---

scripts/debug_common_sdk.sh
scripts/debug_navigation_native.sh

Add a fetch tags steps to fetch new tags, otherwise the script fails
until you'll do it manually.

Fix debug scripts

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Upgrade to MapboxMaps v10.2

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift

PR fixes a problem, which prevents users from updating map buttons (map, leading and trailing navigation buttons) whenever panning interface is shown.

Force update map buttons on CarPlay during active navigation.

---

Tests/MapboxNavigationTests/VanishingRouteLineTests.swift

This pr is to fix the tests [check](https://github.com/mapbox/mapbox-navigation-ios/pull/3654#discussion_r783574813) in #3654 .

Fixed the tests check in VanishingRouteLineTests

---

CHANGELOG.md
MapboxNavigation-SPM.xcodeproj/project.pbxproj
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/BottomBannerViewController.swift
Sources/MapboxNavigation/BottomBannerViewLayout.swift
Sources/MapboxNavigation/CameraController.swift
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/Feedback/FeedbackSubtypeCollectionViewCell.swift
Sources/MapboxNavigation/InstructionsBannerView.swift
Sources/MapboxNavigation/InstructionsCardViewController.swift
Sources/MapboxNavigation/LanesView.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewDelegate.swift
Sources/MapboxNavigation/NavigationViewLayout.swift
Sources/MapboxNavigation/NextBannerView.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/StepTableViewCell.swift
Sources/MapboxNavigation/StepsViewController.swift
Sources/MapboxNavigation/StepsViewControllerDelegate.swift
Tests/MapboxNavigationTests/GuidanceCardsSnapshotTests.swift

PR improves layout in the landscape mode by minimizing space top and bottom banner use. Examples:
Fixes #1139.
/cc @lawsonkight @abhishek1508

Improve landscape layout during active navigation.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewController.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

Fix `NavigationViewController` properties change.

---

Sources/MapboxNavigation/NavigationViewLayout.swift

Fix floating buttons overlapping with iOS device notch when using right-to-left layout interfaces.

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

This Pr is to update the following dependency:

Update NN to 88.0.0 and MapboxMaps to 10.3.0

---

Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

Remove FIXME statements that are no longer needed.

Remove FIXME statements that are no longer needed.

---

Sources/MapboxNavigation/BottomBannerViewControllerLayout.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewLayout.swift
Sources/MapboxNavigation/OrnamentsController.swift

PR adds the ability to expand and collapse bottom banner container view.

Add swipeable bottom banner container view.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/SimulatedLocationManager.swift

Move location calculation to a background queue

---

CHANGELOG.md

Adds a changelog about the availability of the grace period.

Add grace-period changelog

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Upgraded to MapboxNavigationNative v98.0.0.

MapboxNavigationNative v98.0.0

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/RerouteControllerDelegate.swift
Sources/MapboxCoreNavigation/TollCollection.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/RoutesCoordinatorTests.swift

PR updates dependencies to:
* Mapbox Maps v10.5.0.
* Mapbox Navigation Native v99.0.0.

Upgrade to MapboxMaps `v10.5.0`, MapboxNavigationNative `v99.0.0`

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RoutesCoordinator.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/RoutesCoordinatorTests.swift

Bumped NN to v100
New version required some updates on the main and alternative routes setup.

Update NavNative to v100

---

Sources/MapboxCoreNavigation/RouteController.swift

https://github.com/mapbox/mapbox-navigation-ios/pull/3898 cherry pick

`vk-set-route-credentials` cherry pick

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Update to the latest Directions SDK `2.5.0-rc.1`. It has no changes since `2.5.0-beta.1` but we should use RCs for RCs.

Update Directions SDK 2.5.0-rc.1

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Cherry-picking the PR #3901 with Directions update to make `2.5.0-rc.2` depend on RC version of Directions.

Cherry-pick - Update Directions SDK 2.5.0-rc.1 (#3901)

---

CHANGELOG.md
Sources/MapboxNavigation/LanesView.swift

https://github.com/mapbox/mapbox-navigation-ios/pull/3903 cherry pick

PR #3903 cherry pick

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/RerouteController.swift
Sources/MapboxCoreNavigation/RerouteControllerDelegate.swift
Sources/MapboxCoreNavigation/RouteController.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

In this PR I update Navigation Native SDK to version `101.0.0`. It includes fixes to rerouting requests logic.
~~This is a draft as we are waiting for this release.~~

Update Navigation Native 101.0.0

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/StyleManager.swift

Fixes #3883.
PR fixes an issue where changes to `StyleManager` on one platform caused instant style updates on other platform as well.

Fixed an issue related to `StyleManager` usage on iOS and CarPlay.

---

CHANGELOG.md
Sources/MapboxNavigation/Constants.swift
Sources/MapboxNavigation/NavigationMapView.swift

This PR exposes GeoJSON tolerance property to MapView. It affects arrow, route, and restricted area sources on the map.

Expose geoJSON tolerance to MapView

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/CLLocation.swift
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/CLLocationTests.swift

This pr is to update the dependency as following:

Update NavigationNative and MapboxMaps.

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/BannerContainerView.swift
Sources/MapboxNavigation/BannerContainerViewDelegate.swift

PR allows to track various changes in `BannerContainerView` (state changes, expansion/collapse progress etc) by adding `BannerContainerViewDelegate`.

Add `BannerContainerViewDelegate`.

---

Sources/MapboxNavigation/NavigationMapView.swift

Fixes #3918.
PR fixes an issue where in case of initial application launch user course view is always drawn in initial position.

Fix issue with user course view rendering.

---

CHANGELOG.md
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/Style.swift
Sources/MapboxNavigation/StyleManager.swift
Tests/MapboxNavigationTests/CarPlayCompassViewSnapshotTests.swift

Fixes #3917.
PR adds trait collection check in default `DayStyle` and `NightStyle` to make sure that style is not updated for iOS in case if CarPlay style changes (and vice versa).

Fix `StyleManager` default style updates.

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift

Fix an issue where maneuver arrow wasn't removed after passing visual instruction on CarPlay.

---

Example/ViewController.swift
Sources/MapboxCoreNavigation/SimulatedLocationManager.swift
Sources/TestHelper/Fixture.swift
Tests/MapboxCoreNavigationTests/SimulatedLocationManagerTests.swift

Route simulation has known issues of causing user puck to jump distances and occasionally reroute. This PR refactors `SimulationLocationManager` logic to avoid that and improve it's performance especially on long routes.
Simulation speed is no controlled by the frequency of generated updates instead of increasing jump distance and speed. Reworked simulated location tick to avoid re-iterating entire route shape when looking for the next coordinate. This became especially noticeable on the long routes.

Simulation improvement

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/InstructionPresenter.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewLayout.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/SpriteRepository.swift
Sources/MapboxNavigation/UILayoutGuide.swift
Sources/MapboxNavigation/WayNameLabel.swift
Sources/MapboxNavigation/WayNameView.swift
Tests/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
Tests/MapboxNavigationTests/SpriteRepositoryTests.swift

PR improves public API of `WayNameView`:
- Adds `WayNameView.cornerRadius` public property.
- Fixed incorrect alignment of shield icon and road name label in case when `WayNameView` size was changed.
- Adds `NavigationView.wayNameViewLayoutGuide` property that allows to change default position of the `WayNameView` (internal for now).

Improve public API of `WayNameView`.

---

Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/VanishingRouteLineTests.swift

This Pr is to fix the typo of #4009 .

Fix the typo of #4009

---

LICENSE.md

Update language presented in LICENSE.md blurb including current year.

Update LICENSE.md blurb

---

CHANGELOG.md
Sources/MapboxNavigation/RouteLineController.swift

Fix crash that sometimes occurs during `NavigationViewController` dismissal.

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.swift
Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

This Pr is to update dependency to NavNative v111.0, Maps v10.7.0, Common v22.1.0

Update dependency to NavNative v111.0, Maps v10.7.0, Common v22.1.0

---

CHANGELOG.md
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/Style.swift
Sources/MapboxNavigation/StyleManager.swift
Sources/MapboxNavigation/UIColor.swift

Closing #4018.
Fixes an issue with missing style on iPads.

Fix styling issues on iPads when using `DayStyle` and `NightStyle`.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationView.swift

Fix injected map view layout bug

---

CHANGELOG.md
Sources/MapboxCoreNavigation/SimulatedLocationManager.swift

https://github.com/mapbox/mapbox-navigation-ios/pull/4058 cherry pick

vk-simulation-teleport-fix cherry-pick

---

Example/CustomStyles.swift

This Pr is to update the example for custom styling, and fix the issue of #3982 
Provide `UITraitCollection` for `UIAppearance` when customize the UI component for styling.

Update the custom style example for styling.

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdgeMetadata.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObject.swift
Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
Tests/CocoaPodsTest/PodInstall/Podfile.lock

PR updates dependencies to:
* Mapbox Maps v10.8.0-beta.1
* Navigation Native v112.0.0
* Mapbox Common v23.0.0-beta.1
* Mapbox Directions v27.0-beta.1

Upgrade dependencies

---

Sources/MapboxCoreNavigation/IncidentsOptions.swift

Exposed public init for `IncidentsOptions`

IncidentsOptions init

---

.base_api

API bump for patch release branch

Release v2.7.1 api bump

---

Example/ViewController+FreeDrive.swift

This Pr is to update the example of using Electronic Horizon updates during free drive. We need to provide the `ElectronicHorizonOptions` for `PassiveLocationManager` and call `PassiveLocationManager.startUpdatingElectronicHorizon(with:)` to start electronic horizon updates.

Update the example to use Electronic Horizon for free drive.

---

MapboxCoreNavigation.podspec
MapboxNavigation.podspec
Package.swift
README.md
docs/guides/Styling the UI.md

Update minimum required version of Xcode and Swift. Update styling example.

Update minimum required version of Xcode and Swift. Update styling example.

---

scripts/validate_releases.sh

PR adds Navigation SDK `v2.6.1` and `v2.7.2` for SPM verification.

Add Navigation SDK `v2.6.1` and `v2.7.2` for SPM verification.

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

NavNative v114.0.0

---

CHANGELOG.md
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Sources/MapboxCoreNavigation/NavigationSettings.swift

This PR is to cherry pick commits added to `release-v2.8` branch to `main`.

Cherry picks commits from 2.8.0

---

CHANGELOG.md
Cartfile.private
Package.swift
Sources/MapboxCoreNavigation/RouteController.swift

Fixed a bug where after manually switching to alternative route it's duration delta was nullified.

Alternatives delta fix

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift

https://github.com/mapbox/mapbox-navigation-ios/pull/4177 cherry pick to `main`

`alternative-delta-fix` cherry pick

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/Feedback/EventsAPI.swift
Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxNavigationTests/CarPlayManagerSpec.swift

Update Directions, Maps, NavigationNative

Update Directions, Maps, NavigationNative

---

Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Update to Mapbox Directions `v2.8.0-beta.2`.

Update to Mapbox Directions `v2.8.0-beta.2`.

---

MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/PreviewViewControllerExample.xcscheme
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/PreviewViewController.swift
Tests/MapboxNavigationTests/BannerPresentationTests.swift
Tests/MapboxNavigationTests/PreviewViewControllerTests.swift
Tests/MapboxNavigationTests/StackTests.swift

PR adds unit-tests that verify whether default preview mode functionality works as expected. These tests will also be useful while moving `NavigationViewController` to common implementation of the banner presentation.

Add tests for preview mode.

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxNavigation/Banner.swift
Sources/MapboxNavigation/BannerContainerView.swift
Sources/MapboxNavigation/BannerDismissalViewController.swift
Sources/MapboxNavigation/BannerPresentation.swift
Sources/MapboxNavigation/DestinationPreviewViewController.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/PreviewViewController.swift
Sources/MapboxNavigation/RoutesPreviewViewController.swift
Sources/MapboxNavigation/Stack.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxNavigationTests/CarPlayManagerSpec.swift
Tests/MapboxNavigationTests/MapViewTests.swift

PR fixes various issues related to banner presentation logic (along with some public API extensions).
PR also contains update to the latest Maps SDK `v10.9.0` to fix failing tests.

Fix banner presentation issues.

---

CHANGELOG.md
Sources/MapboxNavigation/OrnamentsController.swift

PR fixes an issue that occurs if top and bottom banners presentation is not animated.

Fix `NavigationViewController` presentation.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/BorderCrossing.swift

Adds an ability to create `BorderCrossing` publicly

Make BorderCrossing constructor public

---

docs/jazzy.yml

PR fixes several documentation generation issues.

Add missing navigation camera related APIs.

---

.circleci/config.yml

This PR reenables codecov for mapbox-navigation-ios.

Codecov is back!

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationView.swift

PR adds documentation for `NavigationView` APIs that are part of preview mode.

Add documentation for `NavigationView`.

---

Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxNavigationTests/URLDataCacheTests.swift

This Pr is to fix flaky tests in `MapboxNavigation` and `MapboxCoreNavigation`.

Fix flaky tests.

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/RouteStepProgress.swift
Tests/MapboxCoreNavigationTests/RouteStepProgressTests.swift

Fixes possible incorrect index for empty intersections.

Fix Fix crash in RouteStepProgress.upcomingIntersection

---

.circleci/config.yml
scripts/validate_releases.sh
scripts/validate_xcodeproj.swift

Improve `validate_releases.sh` script.

Improve `validate_releases.sh` script.

---

.circleci/config.yml
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigationIntegrationTests.xcscheme

Add optional integration tests build

Add MapboxCoreNavigationIntegrationTests run on CI

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+Annotations.swift

This PR fixes #4080 by checking for a notch and adjusting the RouteDuration image and stretch accordingly.

RouteDurations text centered in callout

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

PR updates dependencies to Mapbox Maps `v10.10.0`, Navigation Native `v123.0.0` and Common `v23.2.1`.

Mapbox Maps `v10.10.0`, Navigation Native `v123.0.0` and Common `v23.2.1`.

---

CHANGELOG.md

6121f1919f569b5ddc69042a81ad9aec84632c81 brought some inaccuracies in the changelog.

Fix incorrect changelog entries. 

---

CHANGELOG.md
Cartfile.resolved
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

This PR upgrades to NavigationNative v123.1.0.

Upgrade to NavigationNative v123.1.0

---

.circleci/config.yml
CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.xcodeproj/project.pbxproj
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/VisualInstructionComponentGuidanceViewKind.swift
Sources/MapboxNavigation/InstructionPresenter.swift
Sources/MapboxNavigation/JunctionView.swift
Sources/MapboxNavigation/VisualInstructionComponent.swift
Sources/TestHelper/Fixtures/route-with-instruction-components-with-subtype.json
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationIntegrationTests/MapboxCoreNavigationIntegrationTests.swift

PR adds `SubType` to `VisualInstruction.Component` and its conversion from Navigation Native type.

Add `SubType` to `VisualInstruction.Component`.

---

CHANGELOG.md
Example/ViewController+FreeDrive.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift

PR provides the ability to show guidance view images on CarPlay. For example:

Provide the ability to show guidance view images on CarPlay.

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift

Add panning functionality on CarPlay.

Add panning functionality on CarPlay.

---

.circleci/config.yml
codecov.yml

This PR generates the code coverage report in the correct format for codecov to display it.

Generate code coverage report in correct format

---

.github/workflows/set_reviewers.yml
scripts/reviewers/README.md
scripts/reviewers/owners.json
scripts/reviewers/set_reviewers.py
scripts/reviewers/set_reviewers_defs.py
scripts/reviewers/set_reviewers_defs_tests.py
scripts/reviewers/teams.json

https://mapbox.atlassian.net/browse/NAVSDK-828
We have already tested this tool in the [mapbox-navigation-android](https://github.com/mapbox/mapbox-navigation-android) repository and I would like to propose its usage in the iOS repository as well.
[doc](https://github.com/mapbox/mapbox-navigation-ios/tree/NAVSDK-828/scripts/reviewers#readme)

Auto-assigning reviewers

---

.circleci/config.yml
scripts/distribute-version.py

cherry pick https://github.com/mapbox/mapbox-navigation-ios/pull/4326

distribute for release

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Bumped NN to v125.0.0, Maps to 10.11.0-rc.1 and Directions to 2.10.0-beta.2

Dependency update

---

CHANGELOG.md
Sources/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

Fix NavigationViewController instantiation from the Storyboard

Fix NavigationViewController name in storyboard

---

.breakage-allowlist
CHANGELOG.md
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift
Tests/MapboxNavigationTests/CarPlayUtils.swift

Adds proposed callbacks from #4364

[CarPlay] Add delegate methods for CarPlay panning

---

MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Use more flexible constraints on the Maps SDK version

Update version constrains for Maps dependency

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/CoreConstants.swift
Sources/MapboxCoreNavigation/NavigationStatus.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/PreviewViewController.swift
Sources/TestHelper/NavNative/TestNavigationStatusProvider.swift
Tests/MapboxCoreNavigationTests/NavigationStatusTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

[NAVIOS-925](https://mapbox.atlassian.net/browse/NAVIOS-925)
Display localized road name
| Locale  | Before | After |
| ------------- | ------------- | ------------- |
| en  |  <img width="233" alt="Screenshot" src="https://user-images.githubusercontent.com/3630656/220184074-ce6599d1-6acd-4268-8bb3-0cf0b644caaa.png"> | <img width="233" alt="Screenshot" src="https://user-images.githubusercontent.com/3630656/220183178-5f6f31c6-c9c9-4b79-9c77-9878e0a331aa.png"> |
| jal  |  <img width="233" alt="Screenshot" src="https://user-images.githubusercontent.com/3630656/220184074-ce6599d1-6acd-4268-8bb3-0cf0b644caaa.png">  |  <img width="232" alt="Screenshot" src="https://user-images.githubusercontent.com/3630656/220183626-90567e4a-484b-4157-9804-80f5c9b55408.png"> |

Display localized road name

---

.breakage-allowlist
CHANGELOG.md
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift
Tests/MapboxNavigationTests/CarPlayUtils.swift

Appended [community PR](https://github.com/mapbox/mapbox-navigation-ios/pull/4376) with CHANGELOG and breaking changes accepted.

[CarPlay] Add Delegate Method Before CarPlayNavigationViewController Presented

---

CHANGELOG.md

Fix changelog for 2.11.0

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/RerouteController.swift
Sources/TestHelper/NavNative/NativeNavigatorSpy.swift
Tests/MapboxCoreNavigationTests/RerouteControllerTests.swift

Fix possible memory leak while rerouting

Fix possible memory leak while rerouting

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/CoreConstants.swift
Sources/MapboxCoreNavigation/NavigationStatus.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/PreviewViewController.swift
Sources/TestHelper/NavNative/TestNavigationStatusProvider.swift
Tests/MapboxCoreNavigationTests/NavigationStatusTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

Display localized road name cherry pick

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/RerouteController.swift
Sources/TestHelper/NavNative/NativeNavigatorSpy.swift
Tests/MapboxCoreNavigationTests/RerouteControllerTests.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

Fix possible memory leak while rerouting  cherry pick

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreConstants.swift
Sources/MapboxCoreNavigation/NavigationStatus.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/PreviewViewController.swift
Tests/MapboxCoreNavigationTests/NavigationStatusTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

* Fixed duplication of the data in the shield and the road label
| Before | After |
| ------------- | ------------- |
| <img width="233" alt="Screenshot" src="https://user-images.githubusercontent.com/3630656/223766784-404af9a0-9712-4357-950f-487be7036448.png">  | <img width="233" alt="Screenshot" src="https://user-images.githubusercontent.com/3630656/223766989-e6883370-0f63-478a-85a4-a09e1fe68de2.png"> |

Fixed duplication of the road name components

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteProgress.swift
Sources/MapboxCoreNavigation/RouteStepProgress.swift
Sources/MapboxNavigation/InstructionsCardViewController.swift
Tests/MapboxCoreNavigationTests/Progress/RouteProgressTests.swift
Tests/MapboxCoreNavigationTests/Progress/RouteStepProgressTests.swift

Fix possible '-0' label in the Guidance Cards

Fix possible '-0' label in the Guidance Cards

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+Annotations.swift

Fix callouts displacement

---

CODEOWNERS

Fixed a part of #4436
> main branch protection: Require review from Code Owners

Add сode owners

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+Annotations.swift

Time difference callouts fix

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayManager.swift

https://github.com/mapbox/mapbox-navigation-ios/pull/4477 cherry pick

CarPlay templates managing fix (#4477)

---

.circleci/config.yml
scripts/snapshot/prepare-snapshot.py

https://mapbox.atlassian.net/browse/NAVSDK-953

Force build snapshot 1tap

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/VisualInstruction.swift

CarPlay maneuver color fix (#4482)

---

.circleci/config.yml

https://mapbox.atlassian.net/browse/NAVSDK-955
notify when release-weekly-snapshot job that triggers 1tap-ios failed

notify about failed snapshot runs

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift

Fixes missing userInfo in CarPlay

Set userInfo for CarPlay Telemetry events

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

* Fix sending events to Native Telemetry on application termination

 Add subscription to applicationWillTerminate in Telemetry

---

Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

Correcting setRoutes reason (#4513)

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

Add subscription to applicationWillTerminate in Telemetry (#4508)

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/TestHelper/NavNative/TestNavigationStatusProvider.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/Progress/RouteProgressTests.swift

Update to NavNative 148.0.0, Maps 10.15.0, Common 23.7.0

Update to NavNative 148.0.0, Maps 10.15.0, Common 23.7.0

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Update to Directions 2.11.0

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Incident.swift

Added filling traffic codes info reported `Incident`s while navigating.

Jartic codes support

---

CHANGELOG.md
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/MapboxNavigation/CarPlayManager.swift

Fixes potentially not called delegate methods in `CarPlayManagerDelegate`

Fixed behavior when completion was not called in case of an error in CarPlayManager

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Update dependencies for 2.17.0-rc.1 release

Update dependencies for 2.17.0-rc.1 release

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/NavigationStatusTests.swift

bumped NN to v160; update NavigationStatus unit test

Dependencies update

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Package.swift
Sources/MapboxCoreNavigation/Resources/PrivacyInfo.xcprivacy
Sources/MapboxNavigation/Resources/PrivacyInfo.xcprivacy

Added PrivacyInfo.xcprivacy support

Added PrivacyInfo.xcprivacy support

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewportDataSource.swift

Cherry pick of #4593 into 2.18

[Cherry pick] Use camera options to calculate zoom for overview camera

---

Package.resolved

Sync Package.resolved with last resolved dependencies after #4605

Sync Package.resolved with last resolved dependencies

---

CHANGELOG.md

Update change log CarPlay

---

Examples/UIKitExample/Transitions/PresentationAnimator.swift

Restores active route guidance camera options.

Fix navigation camera in example

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Updating NN to 204.0.1 and Maps to 10.17.0.

Update NN and Maps

---

.breakage-allowlist
CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.swift
Sources/MapboxCoreNavigation/CoreConstants.swift
Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/MapboxCoreNavigation/RouterDelegate.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Adding refresh TTL data and handling.
Added checking remaining TTL when requesting a route refresh and handling corresponding returned error.
Also bumped Directions.swift version in the process to gain access to new TTL field and error type.

Refresh TTL

---

.circleci/config.yml

https://mapbox.atlassian.net/browse/NAVIOS-1791
* Restores CI builds for v2 on the `lts/v2` branch;
* Fixes failing CI builds on pull requests;
* Fixes metrics triggering

Fix v2 CI builds

---

.circleci/config.yml
scripts/validate_releases.sh

Fixes failed build like [this one](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/12680/workflows/7a3d46c1-150a-43a5-aae8-e7c894200b2d/jobs/119920).
Here's an [example](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/12685/workflows/1643a873-7239-4f0a-8d33-7980e4146c12/jobs/119955) of successful ride

Update validate_releases.sh call

---

CHANGELOG.md
MapboxNavigation-SPM.xcodeproj/project.pbxproj
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Sources/MapboxNavigation/Expression.swift
Tests/Example.xctestplan

[NAVIOS-1831](https://mapbox.atlassian.net/browse/NAVIOS-1831)
Add support for building with Xcode 16 beta
[NAVIOS-1831]: https://mapbox.atlassian.net/browse/NAVIOS-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for building with Xcode 16 beta.

---

CHANGELOG.md
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.pbxproj
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
MapboxNavigation.podspec
Package.resolved
Sources/MapboxNavigation/Expression.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/Example.xctestplan

Cherry-pick #4706 and #4709 from v2.18.x releases

Sync v2 branch after v 2.18.x releases

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Prepare 2.19.0-beta.1 dependencies

---

scripts/update-version.sh

Use `lts/v2` branch for such pull requests #4719

Fix base branch for v2 releases

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/Telemetry/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/Telemetry/NavigationMovementMonitor.swift
Tests/MapboxCoreNavigationTests/Telemetry/NavigationMovementMonitorTests.swift

https://mapbox.atlassian.net/browse/NAVIOS-2021
Adopt NavigationMovementMonitor from v3 Nav SDK

Support the movement info in v2 SDK iOS
