CHANGELOG.md
MapboxNavigation/CarPlayNavigationViewController.swift

Always hide the compass on CarPlay during the navigation activity (in other words, in CarPlayNavigationViewController’s map view). Otherwise, the compass would appear in an odd position to the left of the column of map buttons. Also, the compass has an analog design more appropriate for the browsing activity but not for the navigation activity.
The analog compass remains in the browsing activity. A digital compass will be added as part of #1217 for parity with other CarPlay navigation applications.

Always hide compass on CarPlay during navigation

---

Example/ViewController.swift

Like it says on the box. 
* Fix issue where refactor suggestion from PR introduced reentrancy that causes crash. Also weakifying view-controller's self on presentation completion block.

CarPlay crash when starting from phone

---

MapboxCoreNavigation.podspec
MapboxCoreNavigation/EventDetails.swift
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec

#2058 was a bit overzealous in removing the [`swift_version`](https://guides.cocoapods.org/syntax/podspec.html#swift_versions) specifier instead of bumping it to 4.2, as this PR does.
/cc @mapbox/navigation-ios @friedbunny

Declare supported Swift version in podspecs

---

MapboxCoreNavigation/NavigationService.swift

Modified navigation service to ensure we stop simulation for both `.always` and `.onPoorGPS` modes.

Fixed simulation not stopped when simulation mode is set to onPoorGPS bug

---

MapboxCoreNavigation/MBRouteController.h

Xcode 10.2 started to complain about the missing _Nonnull modifiers

Fixed Xcode build error

---

CHANGELOG.md
MapboxNavigation/NavigationMapView.swift

Fixes #2067 Re-enable line distance metrics on the route line source.
_this PR doesn't add a gradient, it merely enables adding a gradient._

Re-enable line distance metrics

---

.circleci/config.yml
CHANGELOG.md
MapboxCoreNavigation/CoreFeedbackEvent.swift
MapboxCoreNavigation/LegacyRouteController.swift
MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/NavigationMapViewDelegate.swift
MapboxNavigation/NavigationViewController+Obsolete.swift
MapboxNavigation/NavigationViewControllerDelegate.swift
MapboxNavigation/UIEdgeInsets.swift

Fixes #2081 
- Remove deprecated usage of `Hashable`
- Run pod linter on CI
The pod linter will fail until we bring in #2086 

Fix pod linter and compiler warnings

---

CHANGELOG.md
MapboxCoreNavigation/LegacyRouteController.swift
MapboxCoreNavigation/MBRouteController.h

Fixes #2088
Done:
- Add call to `router(_ router: Router, didPassSpokenInstructionPoint...)` in LegacyRouteController
- Add missing object to `routeControllerDidPassVisualInstructionPoint` in LegacyRouteController
- Minor code documentation fix.

Uniformise events between route controllers

---

scripts/document.sh

Link references to `CoordinateBounds` and `LaneIndicationComponent` to the MapboxDirections.swift API reference.

Link more MapboxDirections.swift symbols

---

CHANGELOG.md
MapboxCoreNavigation/NavigationRouteOptions.swift
MapboxCoreNavigationTests/OptionsTests.swift
MapboxNavigation.xcodeproj/project.pbxproj

Fixes #2069 
- Default to `.polyline6` shape format encoding for `NavigationMatchOptions` for consistency with `NavigationRouteOptions` and compatibility with nav-native.

Default to polyline6 encoding for NavigationMatchOptions

---

CHANGELOG.md
Cartfile
MapboxCoreNavigation.podspec
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock

Bumped nav-native to 6.1.3 - Fixes a regression where the puck didn't always snap when standing still or slowly moving backwards.

Bump nav-native to 6.1.3

---

MapboxNavigation/CarPlayManagerDelegate.swift

Fixes "Parameter 'template' not found in the function declaration Did you mean 'template_'?"
`template` seems to be a reserved keyword in the generated Obj-C header and
is being renamed to template_ so there is a mismatch in the
documentation parameters.

Fix CarPlay documentation warnings

---

CHANGELOG.md
MapboxCoreNavigation/LegacyRouteController.swift

In `LegacyRouteController`, if the re-routing request fails the `isRerouting` flag isn't reset as it is the case in `RouteController` for off-route rerouting and `Router` for proactive rerouting.
If that happens then no subsequent request can be sent by `LegacyRouterController` and the user becomes stuck with an outdated and irrelevant route.

Always reset rerouting flag even if request fails.

---

CHANGELOG.md
MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigationTests/CarPlayManagerTests.swift
MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift

Fixes #2118.
* Fixing issue where leg estimates were being shown instead of route estimates

CarPlay - Show route estimates.

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/CPTrip.swift
MapboxNavigation/CarPlayManager.swift
MapboxNavigation/CarPlayManagerDelegate.swift

Removed the “street address” from the CarPlay route preview pane; it was set redundantly to the destination waypoint’s name. For consistency, call `CarPlayManagerDelegate.carPlayManager(_:willPreview:)` also when programmatically starting a new route in CarPlay. Show statistics like the distance and estimated travel time when previewing a selected route.
Fixes #2090.

Clean up CarPlay route preview pane

---

MapboxCoreNavigation/NavigationRouteOptions.swift
MapboxCoreNavigation/RouteProgress.swift

If speed limit annotations were not requested then we need to guard against attempting to look them up should the client request the current speed limit.
We should return SpeedLimit.invalid in these cases.

Guard against missing speed limit data when speed limit is queried for

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec

Upgraded the Carthage Cartfile and CocoaPods podspecs to require [iOS map SDK v5._x_](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v5.0.0). With this change, developers can take advantage of [the new billing plans](https://blog.mapbox.com/new-pricing-46b7c26166e7) when using the map SDK, instead of being stuck on an older version of the map SDK that only offers an old-style billing plan.
/ref mapbox/ios-sdk-examples#222
/cc @mapbox/navigation-ios @mapbox/maps-ios @coxchapman

Map SDK v5.0.0

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/NavigationView.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/Resources/Base.lproj/Localizable.strings
MapboxNavigation/Resources/bg.lproj/Localizable.strings
MapboxNavigation/Resources/da.lproj/Localizable.strings
MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/fr.lproj/Localizable.strings
MapboxNavigation/Resources/hu.lproj/Localizable.strings
MapboxNavigation/Resources/ko.lproj/Localizable.strings
MapboxNavigation/Resources/nl.lproj/Localizable.strings
MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
MapboxNavigation/Resources/ru.lproj/Localizable.strings
MapboxNavigation/Resources/sv.lproj/Localizable.strings
MapboxNavigation/Resources/uk.lproj/Localizable.strings
MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/StatusView.swift
MapboxNavigation/String+LocalizedConstants.swift

StatusView is now a subclass of UIControl, since it can be interactive. StatusViewDelegate is deprecated in favor of calling the `UIControl.addTarget(_:action:for:)` method on `StatusView` for `UIControl.Event.valueChanged`.
Fixed an issue where the status view showed a simulated speed factor as an unformatted number. Refactored a bunch of call sites for showing and hiding StatusView to go through a bottleneck in RouteMapViewController, making the String extension unnecessary.
<details>
<summary>Blooper</summary>
</details>
/ref #2135

Streamline status view toggling and interactivity

---

CHANGELOG.md
Cartfile
MapboxCoreNavigation.podspec
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock

just as the title and changelog say: updating the native dependency to the latest to get support for walking parameters in the offline router.

update nav native dependency to 6.2.1 and changelog

---

CHANGELOG.md
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift

Fixed an issue preventing the status view from appearing while rerouting. NavigationViewController was only forwarding a few selected NavigationServiceDelegate methods to its components, whereas the components conform to the NavigationServiceDelegate protocol and should expect any NavigationServiceDelegate method to be forwarded to them. In this case, RouteMapViewController was responsible for showing the status view while rerouting and hiding it after a failed reroute.
Unfortunately, we don’t have a good mechanism to automatically ensure that all NavigationServiceDelegate methods are forwarded to the components, so we’ll have to stay vigilant as we continue to add more methods to the protocol.
Depends on #2136.

Fix status view when rerouting

---

Cartfile
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec

mapbox/mapbox-gl-native#14664 will introduce a significant change in rendering behavior in map SDK v5.1.0, obviating the workaround in #1845. As of #2133, the navigation SDK depends on v5._x_, which means `pod install` and `carthage bootstrap` will automatically pull in v5.1.0. The workaround will clash with the upstream fix, resulting in an unusable map on CarPlay and other situations where there’s a large left or right content inset.
This change tightens the dependency to v5.0._x_, allowing only patch releases, to avoid surprises when installing the SDK. Once map SDK v5.1.0 comes out, we’ll land #2134 to remove our workaround. This assumes mapbox/mapbox-gl-native#12818 is fixed either in v5.1.0 or deferred until v6.0.0. Otherwise, if that issue is fixed in another minor release of …

Depend on map SDK v5.0.x specifically

---

CHANGELOG.md
MapboxCoreNavigation/NavigationSettings.swift

Ignore the `$__lazy_storage_$_properties` key on NavigationSettings.
Fixes #2154.

Fix crash presenting NavigationViewController on iOS 13

---

CHANGELOG.md
MapboxCoreNavigation/Router.swift

Fixes #2153 
The `Router` protocol declares `reroutesProactively` non-mutable, but both `RouteController` and `LegacyRouteController` defines the variable mutable. Making this mutable on the protocol prevents excessive casting.
cc @1ec5

Make reroutesProactively mutable on Router

---

MapboxNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/hu.lproj/Localizable.strings

The new format for `USER_IN_SIMULATION_MODE` caused some strings to fall back to English. I've reverted back to the original and fixed the format here and on Transifex.
cc @1ec5

Revert untranslated strings

---

CHANGELOG.md
MapboxNavigation/InstructionsBannerViewLayout.swift
MapboxNavigation/TopBannerViewController.swift

Fixes #2166.
* Fixing issue where manual background color set at view setup time breaks UIAppearance proxy behavior.
Screencapture: 

Fixing broken UIAppearance on InstructionsBannerView

---

CHANGELOG.md
MapboxCoreNavigation/RouteProgress.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/Style.swift

Removed some unnecessary `#if canImport(CarPlay)` statements. It’s possible that the conditional compilation of `Style.previewMapStyleURL` – added for no other reason than to clarify the documentation comment! – causes Style to have incorrect Swift class metadata after unused symbols are stripped from the static, CocoaPods-generated Pods library. This would explain why whole module optimization has been observed to work around the issue.
This is a speculative fix for #2170. It needs to be tested in Interface Builder or a CocoaPods environment.

Can certain conditional CarPlay compilation

---

CHANGELOG.md
MapboxNavigation/StatusView.swift

Fixed an issue where the “iPhone Volume Low” banner would persist until replaced by another banner about simulation or rerouting. Also expanded some code golf.
Fixes #2180. Thanks to @imaginaris for the fix!
/cc @JThramer

Fix auto-hiding status view

---

.circleci/config.yml

Before linting the podspecs as part of the CocoaPods installation test, remove [@mapbox](https://twitter.com/mapbox) from the podspecs, keeping CocoaPods from checking whether Twitter is reachable. (It is, trust me.)
Fixes #2187.

Exclude Twitter reachability test from CocoaPods installation test

---

CHANGELOG.md
MapboxNavigation/TopBannerViewController.swift

Fixes #2165. Sizes the steps table container before presentation so it does not grow during animation

Fixing issue where steps controller grows from .zero when presented

---

MapboxCoreNavigation/NavigationService.swift
MapboxCoreNavigation/NavigationServiceDelegate.swift
MapboxCoreNavigation/NavigationSettings.swift
MapboxCoreNavigation/Router.swift
MapboxCoreNavigation/RouterDelegate.swift
MapboxNavigation/MapboxVoiceController.swift
MapboxNavigation/NavigationOptions.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/NavigationViewControllerDelegate.swift
MapboxNavigation/RouteVoiceController.swift

Document various Core Navigation classes

---

CHANGELOG.md
MapboxNavigation/NavigationMapView.swift

Fixed an issue where NavigationMapView showed routes without congestion attributes, such as walking routes, as translucent lines, even if the route had only one leg.
Even if a polyline represents a route that has no congestion attributes, if should still have attributes indicating whether it’s the alternative route and/or current leg so that the style can choose the appropriate opacity.
Here’s a before and after:
Meanwhile, traffic congestion and subsequent legs are still styled correctly for traffic-avoiding driving routes:
/cc @mapbox/navigation-ios @friedbunny

Add common attributes to congestionless route polylines

---

CHANGELOG.md
MapboxNavigation/NavigationViewController.swift

Fixes #2195.
* Fixing issue where "swipe down" gesture on top banner could be triggered after banner already displays
/cc @navigation-ios

Top Banner Swipe Gesture Fix

---

docs/theme/templates/header.mustache
scripts/document.sh

Reprised mapbox/jazzy-theme#9 in this repository’s copy of the Mapbox jazzy theme.
Fixes #2199.
/cc @mapbox/navigation-ios @captainbarbosa

Include docset title and version in masthead

---

Cartfile
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec

#2192 fixed the deprecation warnings arising from mapbox/mapbox-gl-native#14959 but introduced an implicit dependency on map SDK v5.2.0. This change makes the dependency on v5.2.0 explicit, so that developers don’t accidentally wind up with a broken build because of an existing copy of v5.1._x_.
/ref #2189
/cc @mapbox/navigation-ios @friedbunny @d-prukop

Require map SDK v5.2.x

---

MapboxCoreNavigation/NavigationEventsManager.swift
MapboxCoreNavigation/NavigationService.swift
MapboxCoreNavigationTests/NavigationServiceTests.swift
MapboxNavigation/NavigationViewController.swift

The user agent string for navigation events now varies based on whether the process has loaded the MapboxNavigation module. The previous implementation stopped working when mapbox/mapbox-navigation-ios#1602 decomposed the NavigationViewController initializer. The undocumented DefaultInterfaceFlag protocol is no longer relevant and has been removed.
/cc @mapbox/navigation-ios @mapbox/mobile-metrics

Determine user agent based on presence of MapboxNavigation

---

MapboxNavigation/NavigationViewController.swift
MapboxNavigation/Resources/Base.lproj/Localizable.strings
MapboxNavigation/Resources/da.lproj/Localizable.strings
MapboxNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/fr.lproj/Localizable.strings
MapboxNavigation/Resources/he.lproj/Localizable.strings
MapboxNavigation/Resources/hu.lproj/Localizable.strings
MapboxNavigation/Resources/ja.lproj/Localizable.strings
MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
MapboxNavigation/Resources/ru.lproj/Localizable.strings
MapboxNavigation/Resources/sv.lproj/Localizable.strings
MapboxNavigation/Resources/uk.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings
MapboxNavigation/Resources/yo.lproj/Localizable.strings
MapboxNavigation/Resources/zh-Hans.lproj/Localizable.strings

Replaced the low volume warning string with a new string that sounds more like a call to action. The new string is no longer a format string, so existing translations are invalid and couldn’t be reused.
Fixes #2205.

Reword low volume warning to be less passive

---

CHANGELOG.md
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/NavigationViewControllerDelegate.swift

Fixes #2212 by adding a progress update method to `NavigationViewControllerDelegate`. 

Adding method for progress updates on the NVC delegate.

---

README.md
docs/cover.md

This PR changes the recommended `NSLocationWhenInUseUsageDescription` string that iOS displays when the application requests Location Services permissions and, as of iOS 13, periodically if the application receives Always permissions.
The new wording omits mention of OpenStreetMap, because a Location Services permission prompt isn’t the right place to name-check a project that most users are unfamiliar with. To a user who has never heard of OSM before, mentioning it here would make OSM seem like some mysterious third party – even though OSM doesn’t directly use or require the requested permissions – and leave them no better informed about how the location data would be used.
/cc @mapbox/navigation-ios @mapbox/maps-ios @mapbox/mobile-telemetry @mapbox/docs @mikelmaron

Update suggested usage description

---

MapboxCoreNavigation/DispatchTimer.swift

The way the dispatch timer code is currently written, it creates an invisible strong reference to self (via fire and payload). This leads to the block keeping the timers around in memory after usage, see screenshot.
This PR fixes the issue by making the references to self explicit, and making them weak.

Timer memory leak

---

CHANGELOG.md
MapboxNavigation/CarPlayManager.swift
MapboxNavigation/CarPlayMapViewController.swift
MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

Decouple dependency content insets -> anchor point -> padding/content insets broken after https://github.com/mapbox/mapbox-gl-native/pull/14664 introduced animated interpolation for padding change.
Remove the need to specify center for puck view - use the approach where content inset is keeping it centered.
Take safeArea into account when calculating contentInsets.
[Link to video showing current state.](https://www.dropbox.com/s/wori62tfhp69feg/RPReplay_Final1565767435.mp4?dl=0) 
EDIT 9/9/2019:
Work around mapbox-gl-native/15574. Panning fix.
Fix CarPlay puck positioning, panning away from navigation, navigation -> overview transitions.
Remove syncing safeArea to contentInset, contentInset is to be used to position puck and this causes map position sudden change when panning.
Work around …

Simplify anchor point calculation and puck centering

---

CHANGELOG.md
MapboxNavigation/NavigationViewController.swift

Fixed an issue where user notifications displayed right turn arrows for left turn maneuvers. The problem is that we were relying on metadata to flip the image to the left, but that metadata doesn’t get persisted to the image file that gets attached to the notification. The fix is to rerender the image into a new context.
Fixes #2267.

Fix maneuver icon orientation in user notifications

---

MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/ru.lproj/Localizable.strings
MapboxNavigation/Resources/uk.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings

Updated Russian, Spanish, Ukrainian, Vietnamese translations from Transifex.

Update Russian, Spanish, Ukrainian, Vietnamese translations

---

CHANGELOG.md
MapboxNavigation/LaneView.swift
MapboxNavigation/ManeuverView.swift

This is needed since they implement their own draw(rect:) functions and any transparent pixels will appear as black since they are not automatically blended and composited with the rest of the view hierarchy.

Specify ManeuverView and LaneView as non-opaque

---

CHANGELOG.md
MapboxNavigation/ExitView.swift
MapboxNavigation/GenericRouteShield.swift
MapboxNavigation/InstructionPresenter.swift

Fixes https://github.com/mapbox/mapbox-navigation-ios/issues/2161 and fixes https://github.com/mapbox/mapbox-navigation-ios/issues/2191

Set the foregroundColor of the ExitView and GenericShieldView to the datasource textColor before snapshotting them

---

CHANGELOG.md
MapboxNavigation/NavigationViewController.swift

When Dark Mode is enabled, draw user notifications’ maneuver icons in white instead of black for better contrast.
Fixes #2266.

Lighten maneuver icons in user notifications in Dark Mode

---

MapboxCoreNavigation/Date.swift

Now that we’ve dropped support for iOS 9._x_, use ISO8601DateFormatter instead of rolling our own ISO&nbsp;8601 date formatter.

Use built-in ISO date formatter

---

Example/CustomViewController.swift
MapboxCoreNavigation/CoreConstants.swift
MapboxCoreNavigation/LegacyRouteController.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/Router.swift
MapboxCoreNavigation/SimulatedLocationManager.swift
MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
MapboxCoreNavigationTests/NavigationServiceTests.swift
MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/MapboxVoiceController.swift
MapboxNavigation/RouteVoiceController.swift
MapboxNavigation/Style.swift
MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
MapboxNavigationTests/MapboxVoiceControllerTests.swift

#2230 left some references to Objective-C symbols in documentation comments. This PR updates the references to the corresponding Swift symbols. It also renames RouteControllerNotificationUserInfoKey to RouteController.NotificationUserInfoKey.

Clean up RouteController user info keys

---

taginfo.json

Between MapboxDirections.swift and the navigation SDK, at least 34 OpenStreetMap keys or tags are used in notable ways beyond how [OSRM](https://github.com/Project-OSRM/osrm-backend/blob/master/taginfo.json) and [Valhalla](https://github.com/valhalla/valhalla/blob/master/taginfo.json) use them. This JSON file documents the SDK’s usage for the [taginfo](http://taginfo.openstreetmap.org/) website, which OSM contributors rely on to discover tags and learn how to use them. Documenting these tags in the context of the SDK promotes better coverage in OSM (and thus the navigation SDK) and raises awareness about the practical needs of navigation applications among members of the OSM community.
/cc @mapbox/mobile-navigation-team @mapbox/navigation-api @mapbox/docs

Add taginfo project file

---

MapboxNavigation/MapboxVoiceController.swift

URLErrors coming from MapboxSpeech are now wrapped in a SpeechError type (not to be confused with the SpeechError in MapboxNavigation).
Fixes #2305.

Fix warning about casting SpeechError to URLError

---

MapboxNavigation/MGLStyle.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

Identifiers of map data sources and style layers added by this SDK are now prefixed by the MapboxNavigation bundle identifier to avoid potential collisions with the style or other customizations made by the application. Organized the various identifiers into structs to avoid confusing source identifiers and style layer identifiers with each other. Also refactored the removal of map overlays to be less error-prone.

Clean up map layer identifiers

---

CHANGELOG.md
MapboxCoreNavigation/RouteLeg.swift
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/MGLShape.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

Factored out convenience initializers for converting Turf geometry structures into `MGLShape` and `MGLFeature` objects such as `MGLPolyline` and `MGLPolygonFeature`. These conversions happen quite frequently in the codebase but the process was too verbose.
/cc @mapbox/navigation-ios @mapbox/maps-ios

Add conversions between Turf and MGLShape

---

MapboxCoreNavigation/NavigationServiceDelegate.swift
MapboxCoreNavigation/UnimplementedLogging.swift
MapboxNavigation/CarPlayManagerDelegate.swift
MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/FeedbackViewController.swift
MapboxNavigation/InstructionLabel.swift
MapboxNavigation/InstructionsBannerView.swift
MapboxNavigation/InstructionsCardContainerView.swift
MapboxNavigation/NavigationMapViewDelegate.swift
MapboxNavigation/NavigationViewControllerDelegate.swift
MapboxNavigation/RouteVoiceController.swift
MapboxNavigation/StyleManager.swift

jazzy has built-in support for documenting default implementations: https://github.com/realm/jazzy/issues/531#issuecomment-213273044. So the approach we took in https://github.com/mapbox/mapbox-navigation-ios/pull/2230#discussion_r337097896 of calling out the default implementation in `note` blocks is unnecessary. Indeed, the [v1.0.0-alpha.1 documentation](https://docs.mapbox.com/ios/api/navigation/1.0.0-alpha.1/Protocols/NavigationMapViewDelegate.html) shows a generated “Default implementation” header right below the note callout.
This PR moves the default implementation documentation to the default implementations themselves so jazzy can pick them up and apply a standard style to them:

Document default initializers in place

---

CHANGELOG.md
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
MapboxNavigation/Resources/Base.lproj/Navigation.strings

Fixed an issue where the “End Navigation” button in the end-of-route feedback panel appeared in English regardless of the current localization. #848 set this button’s localization note to “DO NOT TRANSLATE” in the storyboard, which prevented scripts/extract_localizable.sh from detecting the string.

Make End Navigation button localizable

---

CHANGELOG.md
MapboxNavigation/InstructionPresenter.swift

Avoid force-unwrapping the window just to temporarily add the view to it during snapshotting. In SwiftUI, NavigationViewController hasn’t been added to a window by the time `NavigationViewController.viewDidLoad()` explicitly causes a view to be snapshotted. Adding the view to the window enables the style to be applied, but that’s less important than avoiding a crash.
Fixes #2300.
/cc @mapbox/navigation-ios @zacharyblank

Gracefully snapshot route shield when window is absent

---

CHANGELOG.md
MapboxNavigation/ExitView.swift
MapboxNavigation/GenericRouteShield.swift
MapboxNavigation/InstructionPresenter.swift
MapboxNavigation/LaneView.swift
MapboxNavigation/ManeuverView.swift

Cherry-picked #2279 and #2280 into the release-v0.38 branch.

Fix view background colors in banners

---

MapboxCoreNavigation/Date.swift
MapboxCoreNavigationTests/DateTests.swift
MapboxNavigation.xcodeproj/project.pbxproj

Reverted #2288. Timestamps are once again formatted according to a custom format rather than RFC 3339.
Fixes #2327.
/cc @mapbox/navigation-ios @mapbox/telemetry

Revert navigation event timestamps from RFC 3339 to previous format

---

CHANGELOG.md
MapboxNavigation/NavigationViewController.swift

Fixed an issue where spoken instructions always fell back to VoiceOver when the `MGLMapboxAPIBaseURL` key was set in the Info.plist file and the voice controller was embedded in a NavigationViewController.

Pass API hostname through to speech synthesizer

---

docs/theme/templates/doc.mustache

Some folks (👋 @captainbarbosa) noticed some stray trackers showing up on these pages. After some 🕵️‍♀️, @katydecorah noticed we had a pretty loosely configured analytics initialization happening in a template file. This PR brings that file more in line with the way we initialize analytics elsewhere on the website with configurable integrations. 
The biggest change here is in `analytics.load()`: 
```js
analytics.load=function(t){
var e=document.createElement('script');
e.type='text/javascript';
e.async=!0;
e.src('https:'===document.location.protocol?'https://':'http://') + 'cdn.segment.com/analytics.js/v1/' + t + '/analytics.min.js';
var n=document.getElementsByTagName('script')[0];
n.parentNode.insertBefore(e,n)
};
```
👇 
```js
analytics.load = function(t, e) { 
var n = …
```

Update analytics script in docs template

---

docs/theme/templates/doc.mustache

I hope I'm not giving you too much whiplash, but we had some discussion internally and decided it would be best to link to a centralized analytics script instead of inlining analytics initialization in each and every repo.

Swap to centralized analytics script

---

CHANGELOG.md
Cartfile.resolved
MapboxNavigation/ExitView.swift
MapboxNavigation/GenericRouteShield.swift
MapboxNavigation/InstructionsCardContainerView.swift

Problem:
If you provide dynamic UIColor as a color for ExitView or GenericShieldView styling, you will get a crash due to the way the hash value is calculated for storing the rendered image in the image crash.
Fix is to create our own UIColor instances based on the CGColor values of the resolved underlying UIColor.

Fix crash when using dynamic UIColors in guidance card styling

---

MapboxNavigation/DayInstructionsCardStyle.swift
MapboxNavigation/InstructionsCardContainerView.swift
MapboxNavigation/InstructionsCardStyle.swift
MapboxNavigationTests/InstructionsCardCollectionTests.swift

Nav SDK users are unable to override the secondary highlight colors for the ManeuverView or NextBanner maneuver view. Expose these values and use a transparent version of the primary color as the default value.

Expose secondary highlight colors used in guidance cards

---

MapboxCoreNavigation/MBNavigator.swift
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec
MapboxNavigation/LanesStyleKit.swift
MapboxNavigation/ManeuverView.swift
MapboxNavigation/ManeuversStyleKit.swift
MapboxNavigation/Style.swift
docs/jazzy.yml

Resolves #2314.
This PR actualizes Jazzy config with current public classes, protocols and other entities.
I tried to group all entities to where they belong.

Jazzy doc actualization

---

MapboxNavigation/NextBannerView.swift
MapboxNavigation/TopBannerViewController.swift

Fixed displaying next instructions banner at the end of current step. Code based on previous implementation. 
NavigationBannerView may be called to respect showing next  banner based on route progress (by calling as `NavigationServiceDelegate`, or called to display such info unconditionally (if called by `update(for:)` directly)

#2245: next instructions display fix

---

MapboxCoreNavigation/EndOfRouteFeedback.swift
MapboxCoreNavigation/NavigationSettings.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/RouteProgress.swift
MapboxNavigation/DataCache.swift
MapboxNavigation/FeedbackItem.swift
MapboxNavigation/MapboxVoiceController.swift
MapboxNavigation/NavigationOptions.swift
MapboxNavigation/RouteVoiceController.swift
MapboxNavigation/StyleManager.swift

Resolves #2294 
Removes some objects NSObject Inheritance. Existing KVO observers are removed in favor of using NSNotifications observations.
There are also some other Public available classes, inheriting NSObject:
- LanesStyleKit
- ManeuversStyleKit
- StyleKitMarker
- SpeedLimitStyleKit
- Style
Didn't check in detail, if such inheritance is legitimate, but quick removing NSObject from declaration showed successful compile. Should I check these too?

Minimize NSObject inheritance

---

CHANGELOG.md
MapboxNavigation/InstructionPresenter.swift
MapboxNavigation/RouteMapViewController.swift
MapboxNavigation/UIImage.swift

Simplified the code that creates the attributed string to show in the current road name label (WayNameLabel) when the current road is part of a numbered route.
Constrain the route shield in this label to twice the height of the text within the shield, maintaining the image’s aspect ratio. This fixes an issue where the shield was oversized when the current map style was a custom style created in Mapbox Studio.
When the current style uses Mapbox Streets source v8, get the foreground text color [from the road feature](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/#--road---shield_text_color-text) instead of using the hard-coded logic that’s based on v7. This corrects the text color for certain shield types that were added in v8.
Fixes #2355. Once this fix lands, we should …

Constrain current route shield; simplify current road name label

---

CHANGELOG.md
Example/AppDelegate.swift
ExampleUITests/ExampleUITests.swift
MapboxCoreNavigation/MBXAccounts+CoreNavigationAdditions.m
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigationTests/SKUTests.swift

Removed code that used a billing method that was unsupported on the server side. This billing method was turned on by default in #2151 but never included in a release or prerelease. A future release of the MapboxAccounts framework will add support for a new billing method. At that point, once all the pieces are in place, it might be possible to revert bfd8be364c38e754d5958cb72e4470a72d230120 cleanly.
This PR also reverts 7a3245e8f4e5bcb05bcaccfb09cd1e19895020ae and excludes MapboxAccounts debugging code from the example applications, since it requires OHHTTPStubs.
/cc @mapbox/navigation-ios @zugaldia @asinghal22 @mapbox/billing

Fix MapboxAccounts usage to match server-side expectations

---

MapboxNavigation-Documentation.podspec
scripts/document.sh

Added Objective-C files back to the podspec that hackily gloms MapboxCoreNavigation and MapboxNavigation together for jazzy. The Objective-C files themselves are a hack, forward-declaring the private [`-[MGLMapView mapViewDidFinishRenderingFrameFullyRendered:]`](https://github.com/mapbox/mapbox-gl-native-ios/blob/aa3f3875628a7bbda67bf687b6b2dcbcde55e9ad/platform/ios/src/MGLMapView_Private.h#L40) method from the map SDK.
Locally remove explicit references to MapboxCoreNavigation before compiling documentation. Added explicit dependencies on MapboxAccounts and MapboxNavigationNative.
Did I mention our use of CocoaPods is a hack?
/ref #285 #402
/cc @mapbox/navigation-ios @frederoni

Fix CocoaPods combined module hack for jazzy docset generation

---

CHANGELOG.md
MapboxNavigation.podspec

This is an attempt to fix #2094. I'm not sure how to test the new podspec, and I couldn't get the Xcode tests running due to some cryptic carthage errors. I would appreciate it if someone familiar with the build pipeline could test this manually, and maybe even add an automated test.

Make MapboxMobileEvents dependency explicit

---

MapboxNavigation/DayStyle.swift
MapboxNavigation/UserCourseView.swift

Resolves #2358 
I tried to find implementation that was done in Maps SDK, but had no luck.
I used Router notifications to receive location updates, and linear interpolation for transitioning between colors.
Not sure if 1 second tick is good enough but since total 'stale' timeout is 1 minute, that shouldn't become visible to a user. Anyway, I thought that these configs might be public so it is possible to adjust it as required.

Puck desaturation while Location updates are missing

---

README.md
docs/cover.md

Code snippet in docs/cover.md wasn't changed to use updated Directions API.
Code snippet in README.md wasn't correctly compiling with error:
``Implicit use of 'self' in closure; use 'self.' to make capture semantics explicit``.
Closes #2389.

Fix code snippet in Configuration section.

---

MapboxCoreNavigation/RouteController.swift

Fixes #2099 
Fixed case when RouteController Delegate did not receive arriving messages for routes without voice instructions enabled.

RouteController Delegate fix for no voice navigation

---

MapboxNavigation/CarPlayNavigationViewController.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

Fixes #2217 
Aside of the specified issue, this PR also takes care about updating user puck heading update when entering overview mode (previously it didn't rotate correctly until new location update arrives).

Resume camera update

---

MapboxNavigation/NavigationMapView.swift

Resolves [puck location issue, caused by the bottom banner update](https://github.com/mapbox/support-enterprise/issues/211).
Fixed updating Puck location on various events, including `NavigationMapView` resizing.

Puck Location fix

---

CHANGELOG.md
Cartfile
Cartfile.resolved
Example/AppDelegate.swift
ExampleUITests/ExampleUITests.swift
MapboxCoreNavigation.podspec
MapboxCoreNavigation/MBXAccounts+CoreNavigationAdditions.m
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
MapboxNavigation-Documentation.podspec
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigationTests/SKUIDTestable.swift
MapboxNavigationTests/SKUTests.swift

Resolved [mapbox/navigation-sdks/issues/129](https://github.com/mapbox/navigation-sdks/issues/129).
This PR reverts [changes](https://github.com/mapbox/mapbox-navigation-ios/pull/2375), that reverted [MAU biliing implementation](https://github.com/mapbox/mapbox-navigation-ios/pull/2151). Also updates `MapboxAccounts` dependency to version `2.3.0`.

Re-enable MAU

---

MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

This PR targets https://github.com/mapbox/mapbox-navigation-ios/pull/2377 to make the vanishing route line opt-in. 
Developers can now enable this feature by setting `NavigationMapView.fadesRouteDuringNavigation = true`. 
It is `false` by default.

Make vanishing route opt-in

---

MapboxNavigation/RouteMapViewController.swift

A fix for an issue, reported by our users, which causes the `NavigationMapView`'s `UserPuck` view to malfunction after view's bounds are updated (updating bottom banner view's height cause User Puck view to deviate from it's correct position unless new Location Update event occurs).
I feel that removing animation for updating content insets is legit because this method is called after the actual layout is done, and also because otherwise it becomes tricky to convert user location position to view's viewport coordinates while the animation is ongoing.
The problem is that User Puck view frame is set to converted real geo coordinates to view space immediately after the resizing occurs, but since `contentInsets` are updated with animation, the viewport is not yet updated to final position. …

Unanimating MapView content insets

---

.circleci/config.yml

Added a Circle CI config hook to trigger external Navigation metrics collection workflow.
This is meant to happen on each new commit to `master` branch (even though we are not working on `master` atm), to force metrics data collection. Such approach will create a data timeline for changes applied.

Mobile metrics hook

---

MapboxNavigation/NavigationMapView.swift

Fixes #2449.
I was able to reproduce crash with custom `Route` created in this [PR](https://github.com/mapbox/navigation-ios-examples/pull/61).

Update congestionColor method to return trafficUnknownColor in case if congestionLevel is nil.

---

.github/stale.yml

This PR proposes adding configuration for the [Probot Stale app](https://github.com/probot/stale), a GitHub App that closes abandoned issues and Pull Requests after a period of inactivity. The configuration proposed here is based on the one used by Mapbox Maps SDK and it's somewhat conservative:
- Ignore issues or PRs in a project or a milestone.
- Ignore issues or PRs with the `SEMVER-MAJOR` label.
- PRs go stale after 60 days, and issues after 180 days.
- Bot waits for 5 additional days for any activity before closing the ticket or PR.
- It limits the number of actions to 1 per hour (default is 30).
Note that before this bot is active it needs to be [enabled here](https://github.com/apps/stale). That can happen after this PR has approved and merged.
/cc: @mapbox/navigation-ios

Add Probot Stale configuration

---

MapboxCoreNavigation/OfflineDirections.swift
MapboxCoreNavigation/Resources/Base.lproj/Localizable.strings
MapboxCoreNavigation/Resources/de.lproj/Localizable.strings
MapboxCoreNavigation/Resources/es.lproj/Localizable.strings
MapboxCoreNavigation/Resources/fr.lproj/Localizable.strings
MapboxCoreNavigation/Resources/ja.lproj/Localizable.strings
MapboxCoreNavigation/Resources/pt-PT.lproj/Localizable.strings
MapboxCoreNavigation/Resources/ru.lproj/Localizable.strings
MapboxCoreNavigation/Resources/sv.lproj/Localizable.strings
MapboxCoreNavigation/Resources/vi.lproj/Localizable.strings
MapboxCoreNavigation/Resources/yo.lproj/Localizable.strings

Resolves #2273  
Added new error case for indicating incorrect offline router object handling.
I hope I got original idea, described in the linked issue correctly...
What is the correct way of adding new localizations here? How can I add `OFFLINE_CANCELLED` translation and verify that it's correct?

Offline Directions errors-clarification

---

MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme

Closes #2465.
Since these testable references are missing I think it's okay to remove them.

Remove old testable references.

---

MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift

Closes #2451.
Looks like this is regression which was introduced between `0.37.0` and `0.38.1` after modifying `contentInset(forOverviewing:)`. Since `topBannerContainerView.bounds.height` is used as top inset this leads to setting large content inset for map view, this in turn leads to placing maneuver below bottom banner. Fix aims to update content insets only after closing list with maneuvers and finishing animation. 
Original issue is not reproducible when using guidance cards.

Fix maneuver location.

---

CHANGELOG.md
Example/tr.lproj/Main.strings
MapboxCoreNavigation/Resources/el.lproj/Localizable.strings
MapboxCoreNavigation/Resources/tr.lproj/Localizable.strings
MapboxCoreNavigation/Resources/uk.lproj/Localizable.strings
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/Resources/Base.lproj/Localizable.strings
MapboxNavigation/Resources/bg.lproj/Localizable.strings
MapboxNavigation/Resources/ca.lproj/Localizable.strings
MapboxNavigation/Resources/da.lproj/Localizable.strings
MapboxNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/fr.lproj/Localizable.strings
MapboxNavigation/Resources/he.lproj/Localizable.strings
MapboxNavigation/Resources/hu.lproj/Localizable.strings
MapboxNavigation/Resources/ja.lproj/Localizable.strings
MapboxNavigation/Resources/ko.lproj/Localizable.strings
MapboxNavigation/Resources/nl.lproj/Localizable.strings
MapboxNavigation/Resources/pt-BR.lproj/Localizable.strings
MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
MapboxNavigation/Resources/ru.lproj/Localizable.strings
MapboxNavigation/Resources/sv.lproj/Localizable.strings
MapboxNavigation/Resources/tr.lproj/Localizable.strings
MapboxNavigation/Resources/tr.lproj/Localizable.stringsdict
MapboxNavigation/Resources/tr.lproj/Navigation.strings
MapboxNavigation/Resources/uk.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings
MapboxNavigation/Resources/yo.lproj/Localizable.strings
MapboxNavigation/Resources/zh-Hans.lproj/Localizable.strings

Added a Turkish localization. Thanks to @CosmosExmo for contributing this localization!
Added a missing Ukrainian resource to the project. It had been committed but not included in the SDK.
Removed feedback category strings that are no longer needed as of #2419. #2474 tracks making the new feedback categories and subcategories localizable.

Add Turkish localization; update translations from Transifex

---

MapboxNavigation/CarPlayMapViewController.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/RouteMapViewController.swift

As a result of fix https://github.com/mapbox/mapbox-gl-native/pull/16067, contentInsets are taken into account when calculating camera.
in iOS code, current view's contentInset is passed to calculate camera.
Simplify the approach here by passing .zero, as edgePadding in MGLMapView in cameraThatFitsShape and camera has additive character: gets appended to view's contentInset.
Patch is manually verified on top of master branch (didn't manage to resolve Carthage issues with release-v1.0-pre-registry).

Replace obsolete contentInset workaround

---

MapboxNavigationTests/CarPlayManagerTests.swift

Tests that exercise CarPlayNavigationViewController need it to be around after being presented. Presenting it requires the CarPlayMapViewController to be part of the view hierarchy. Merely making CarPlayMapViewController the root view controller of the CPWindow doesn’t automatically add the view to the view hierarchy, though it does happen in a realistic, non-testing scenario.
We previously worked around this issue in https://github.com/mapbox/mapbox-navigation-ios/pull/2360#issuecomment-615410538, but this change fixes the root cause and confirms that the issue was in our tests rather than the actual product in production, as far as I can tell.
Fixes #2441.

Fix CarPlayNavigationViewController tests

---

CHANGELOG.md
MapboxNavigation/CarPlayManager.swift
MapboxNavigation/CarPlayMapViewController.swift

This PR takes care of several CarPlay(Manager) related memory leaks:
- Fixes memory leaks in any `CPBarButton` creation without a `weak self` reference
- Ensures `CarPlayMapViewController` and the main `CPMapTemplate` are released upon disconnecting the phone from CarPlay
And: Before any navigation attempt on CarPlay a new `rootTemplate` is set, while keeping the original main `CPMapTemplate` (for browsing) still referenced in the `CarPlayManager`. Upon completing or cancelling the navigation session, this template is then to be restored (while the navigation template is popped from the stack). This seems to work fine, but we noticed that it is impossible from that moment on to update / reload the `CPBarButtons`. That's why we discard the template and completely re-create if every time a …

Fixes memory leaks and rootTemplate usage in CarPlayManager

---

.circleci/config.yml
Cartfile
Cartfile.resolved
README.md

This PR changes the source of Navigation Native dependency from Bintray to SDK Registry.
Although the changes to the release process are still in review at https://github.com/mapbox/mapbox-navigation-native/pull/1480, navigation-ios can already upgrade to manually added version.
cc: @mapbox/navigation-ios 
ref: https://github.com/mapbox/mapbox-navigation-native/issues/1479

Consume Navigation Native through SDK Registry

---

MapboxCoreNavigation/EventDetails.swift
MapboxCoreNavigationTests/NavigationEventsManagerTests.swift

Closes #2468.
I've added `testNavigationEventDetailsGlobalQueue` to `NavigationEventsManagerTests.swift`. If needed I can create separate file for `NavigationEventDetails` tests. Also if makes sense test to ensure all keys are encoded to dictionary correctly can be added.

Make sure to access application state from UI thread.

---

MapboxNavigation/MapboxSpeechSynthesizer.swift
MapboxNavigation/MultiplexedSpeechSynthesizer.swift

Updated `MapboxSpeechSynthesizer` public API to allow access Mapbox Speech and calling `speak` method.
This change is induced by [examples project](https://github.com/mapbox/navigation-ios-examples/pull/67) to simplify  `MapboxSpeechSynthesizer` subclassing.

MapboxSpeechSynthesizer API update

---

Example/ViewController.swift
MapboxNavigation/NavigationMapView.swift

Closing #2493.
Due to Swift optimization in Release mode keys in `routeGradientStops.lines` dictionary were set to `nil` after NSExpression creation. It was causing crash on certain devices only. Conversion to NSDictionary fixes this.

Fix crash when passing Dictionary to NSExpression.

---

MapboxNavigation/Style.swift

Make public some properties that were incorrectly kept private to Nav SDK.

Expose the corner radius, border width and height properties to guidance card styling

---

MapboxNavigation/MapboxSpeechSynthesizer.swift

Closing #2521.
This issue depends on fix in `mapbox-speech-swift` repo [#35](https://github.com/mapbox/mapbox-speech-swift/pull/35), so new `mapbox-speech-swift` release will be required.

Fix issue which causes speech synthesizer to fallback and speak two voice instructions at the same time.

---

Example/ViewController.swift

Avoid conflicts between map rotation animations and panning animations that could cause the map in the example application to lag behind the user location. The map is more useful as a preview map when it always faces due north.
/ref https://github.com/mapbox/mapbox-gl-native/issues/3625#issuecomment-173128298
/cc @mapbox/navigation-ios @avi-c @d-prukop

Show heading indicator instead of rotating map in example application

---

MapboxNavigation/FeedbackViewController.swift

Add fix which allows to dismiss FeedbackViewController on both iPad and iPhone.

---

MapboxCoreNavigation/BundleAdditions.swift
MapboxCoreNavigation/NavigationEventsManager.swift
MapboxCoreNavigation/URLSession.swift
MapboxNavigation-Documentation.podspec
MapboxNavigation/Bundle.swift
scripts/document.sh

The two `Bundle.mapboxNavigation` extension properties conflict when the documentation script gloms MapboxNavigation and MapboxCoreNavigation together into a single module. Make the one in MapboxNavigation public instead, since it has more certainty about the presence of MapboxNavigation.

Fix conflicts when generating documentation from combined module

---

MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationMapViewDelegate.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/NavigationViewControllerDelegate.swift
MapboxNavigation/RouteMapViewController.swift

Closing #2574.
I've slightly re-worked original implementation. Now there are such methods which allow to add route layers:
```swift
addMainRouteLayer(_:source:lineGradient:)
addMainRouteCasingLayer(_:source:lineGradient:below:)
addAlternateRoutesLayer(_:source:below:)
addAlternateRoutesCasingLayer(_:source:below:)
```
Such methods are used to create line gradient:
```swift
routeLineGradient(_:fractionTraveled:)
routeCasingGradient(_:)
```
In case if route layer was already added route line gradient with congestion segments will be retrieved out of it.
For route casing color is always the same (without congestions), but fading is also added depending on route progress.
Current PR also fixes #2423 and #2512.

Fix traffic congestion rendering issues.

---

Bench/BenchViewController.swift
BenchTests/BenchTests.swift
TestHelper/SpeechAPISpy.swift

Fixed the BenchTests target for compatibility with #2348 and #2366.
Fixes #2499.

Fix compiler errors in BenchTests

---

Example/ViewController.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/RouteMapViewController.swift

* Building highlights when the distanceRemaining on the current leg is less than 500 meters
* Guarding for redundant queries. Adjusted query so that only the current leg's building is highlighted. Responded to comments.
* Adjustments to arrival experience
* Added zoom when approaching waypoints and destination.
* Using new mapbox directions
* Use Mapbox directions v1.0.0-rc.1.
Co-authored-by: Maxim Makhun <maxim.makhun@mapbox.com>
(cherry picked from commit d295b47d6a1909d5629a1b3d354305c2739a90ac)

Building highlights before reaching the destination (#2582)

---

CHANGELOG.md
Cartfile.resolved
Example/ViewController.swift
MapboxCoreNavigation/LegacyRouteController.swift
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigation/Router.swift

The PR addresses 3 points described in https://github.com/mapbox/mapbox-navigation-ios/issues/2583 to enhance the consistency across timestamps provided to `Navigator.getStatus`.
Fixes #2583.

Make timestamps consumed by Navigator.getStatus consistent

---

MapboxNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/de.lproj/Localizable.stringsdict
MapboxNavigation/Resources/de.lproj/Navigation.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Localizable.stringsdict

Updated German and Vietnamese translations from Transifex. Thanks to @P-Zenker for the German translations!

Update German, Vietnamese translations

---

CHANGELOG.md
MapboxCoreNavigation/RouteProgress.swift

Cherry picking public API change, introduced in PR #2615 to have them in v`1.0.0` first.

Cherry-pick of making RouteProgress Congestion data readonly

---

MapboxCoreNavigation/CoreFeedbackEvent.swift
MapboxCoreNavigation/EventDetails.swift
MapboxCoreNavigation/Feedback.swift
MapboxNavigation/FeedbackItem.swift
MapboxNavigation/FeedbackSubtypeViewController.swift
MapboxNavigation/Resources/Base.lproj/Localizable.strings

Match Android feedback mechanism of sending a single event per category of feedback with an optional array of subtypes. Update JSON keys to match Android as well.

Match Android for Feedback event JSON keys and the sending of a single event per category

---

MapboxNavigation/FeedbackCollectionViewCell.swift
MapboxNavigation/FeedbackViewController.swift

Use some vertical padding instead of trying to calculate the height of the category title since it may vary due to font size fitting.

Fix sizing of FeedbackViewCategoryCell

---

CHANGELOG.md
Example/ViewController+GuidanceCards.swift
MapboxNavigation/InstructionsCardContainerView.swift
MapboxNavigation/InstructionsCardViewController.swift
MapboxNavigation/JunctionView.swift
MapboxNavigation/TopBannerViewController.swift
docs/jazzy.yml

Added class documentation comments for the minimum set of types necessary to consider the guidance cards feature from #2149 and #2296 to be publicly available. With these changes, we can finally add a blurb to the changelog announcing the introduction of this feature, even though it has been in the codebase for quite some time. This PR also adds some documentation about junction views for styling purposes.
Guidance cards, represented by the `InstructionsCardViewController` class, is an alternative presentation of maneuver instructions that is intended to be better visually integrated with the map than the traditional presentation of banners flush with the edges of the screen, represented by the default `TopBannerViewController` class. To enable guidance cards, an application would pass an …

Document guidance cards, junction views

---

CHANGELOG.md
MapboxCoreNavigation/EventDetails.swift
MapboxCoreNavigation/RouteLegProgress.swift
MapboxCoreNavigation/RouteProgress.swift
MapboxCoreNavigation/RouteStepProgress.swift
MapboxCoreNavigationTests/RouteProgressTests.swift
MapboxNavigation.xcodeproj/project.pbxproj

Resolves #1940 
Added `Codable` compliance to `RouteLegProgress`, `RouteStepProgress` and `RouteProgress` classes.
Due to some `tuple` properties ([`IndexedRoute`](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/Router.swift#L18) and [`TimedCongestionLevel`](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteProgress.swift#L165)) in `RouteProgress` I had to implement custom `encode/decode` methods.

Codable Progress classes

---

MapboxNavigation/NavigationMapView.swift

Hardened the traffic congestion coalescing code against situations where the Directions API returns fewer coordinates or more congestion attributes than expected.
Fixes #2611.

Avoid manual index arithmetic

---

MapboxCoreNavigation/PassiveLocationDataSource.swift
MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift

Avoid refetching offline routing tile versions and reconfiguring the passive location data source’s navigator’s router multiple times, because a router instance only expects to be configured once.
When we later upgrade to MapboxNavigationNative v20._x_, we’ll need to move this configuration logic into the code that initializes the navigator (currently in `PassiveLocationDataSource(directions:systemLocationManager:)`). That will be interesting to consider as part of unifying the navigators in #2593.
This is a speculative fix for #2632.
/cc @mapbox/navigation-ios @mapbox/navnative

Avoid reconfiguring passive navigator

---

MapboxNavigation/FeedbackViewController.swift

Fixed a compiler warning about an unused variable that shows up in an application’s workspace when using CocoaPods.
Fixes #2639.

Remove unused variable in FeedbackViewController

---

MapboxNavigation/RouteMapViewController.swift

Add a predicate filter for the road label MGLLineStyleLayer. Prevent the repeated recalculation of sliced current step line shape.
Fixes #2259.

Improve performance of Wayname calculation

---

Example/el.lproj/Main.strings
Example/es.lproj/Main.strings
MapboxCoreNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/de.lproj/Localizable.strings
MapboxNavigation/Resources/el.lproj/Navigation.strings
MapboxNavigation/Resources/es.lproj/Localizable.strings
MapboxNavigation/Resources/es.lproj/Localizable.stringsdict
MapboxNavigation/Resources/es.lproj/Navigation.strings
MapboxNavigation/Resources/ru.lproj/Navigation.strings
MapboxNavigation/Resources/uk.lproj/Navigation.strings
MapboxNavigation/Resources/vi.lproj/Localizable.strings
MapboxNavigation/Resources/vi.lproj/Navigation.strings

Updated a final round of translations into German, Greek, Russian, Spanish, Ukrainian, and Vietnamese for navigation SDK v1.0. Special thanks to @fabian-guerra @danpaz for help with Spanish!

Update translations for v1.0.0

---

MapboxCoreNavigation/PassiveLocationDataSource.swift
MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift

The pr add a test of `PassiveLocationDataSourec` which doesn't require network access and doesn't take much time.
Also the pr fixes the method for manually setting the location.
Resolves #2546

Add automated test of PassiveLocationDataSource

---

MapboxNavigation/NavigationMapView.swift

Detect and skip polyline and polygon annotation layers when scouring the style’s layers for the right layer to insert the route line above.
Fixes #2657.

Skip shape annotations when inserting route line into style

---

.circleci/config.yml
MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec

Temporarily modified the podspecs to exclude the arm64 simulator from the CocoaPods-generated target and application target, based on the workaround in https://github.com/CocoaPods/CocoaPods/issues/10065#issuecomment-694266259 https://github.com/CocoaPods/CocoaPods/issues/10104#issuecomment-700918704 but conditionalized for Xcode 12, just like the Carthage workaround in #2649. Unlike that workaround, this one isn’t sensitive to patch releases of Xcode, so we don’t need the extra case for Xcode 12.0.1 seen in #2663.
Unfortunately, this workaround automatically modifies the `EXCLUDED_ARCHS[sdk=iphonesimulator*]` and `EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200` build settings of the application target, which could eventually be incompatible …

Exclude arm64 simulator from CocoaPods-managed targets in Xcode 12

---

CHANGELOG.md

As Maps dependency is configured to accept any v6.x since #2565, we need to remove the outdated entry in the changelog.

Remove the outdated entry from the changelog

---

CHANGELOG.md
MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

To solve the issue for fix mapbox/mapbox-navigation-ios#2637 , I adjusted the constraint of the UI components inside the `End Of Route View Controller`. This is caused by the `safe area` is not the same as the `End Of Route View Container` under iOS 11. So I changed both the `MBSeparatorView.top` and the `Arrival Labels Container.top`  from the `safeArea.top` to the `Root.top`. It will remove the extra white padding above the `End Of Route View Container`  and display the Rating component correctly.

Solve the End of route view UI broken before iOS 11

---

MapboxNavigation/DayStyle.swift

Make sure to apply UIAppearance style values to the normalFont property and not font property since UILabel font properties are not properly exposed as UIAppearance stylable.
Similar to what was already being done for text color.
Fix for #2645.

Apply UIAppearance proxy overrides for font style to normalFont property and not font property

---

Example/CustomViewController.swift
MapboxNavigation/RouteMapViewController.swift

Fixes #2037 
Usual mechanism for displaying routes works correctly with replacing existing elements, but since after multi-leg rerouting response will contain only the last leg, data on the previous legs was not cleared correctly. Explicitly wiping existing Waypoints before presenting new route solves the issue.
Also this PR fixed `Custom UI` navigation as it had obsolete view classes used.

Rerouting waypoints fix

---

CHANGELOG.md
Cartfile.resolved
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
MapboxNavigation/NavigationMapView.swift

Closing #2660.
This PR removes previous workaround, which was added in #2659 (since root cause of this issue is in Maps SDK, which was addressed in https://github.com/mapbox/mapbox-gl-native-ios/issues/500 and available in Maps SDK `6.2.2`).

Update to Maps SDK 6.2.2 and remove previous workaround to prevent excessive calls to `layoutSubviews()`.

---

MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationMapViewDelegate.swift

Fixes #2595 
Restored calling `NavigationMapViewDelegate.navigationMapView(_:simplifiedShapeFor:)` method for shape customization and verified that custom shapes mechanism works.
There is a discussion going on around these methods on how to improve the API and make customization easy and straightforward. Eventually we should remove these methods, but decided to leave them for now because there is no alternative ideas developed atm and some clients already use that API.

Custom Route shapes fix

---

CHANGELOG.md
MapboxNavigation/NavigationMapView.swift

Tail fixes after [PR #2623 ](https://github.com/mapbox/mapbox-navigation-ios/pull/2623).
Fixed main route shape attribute setting, CHANGELOG updated.

Custom Route shape tailwork

---

MapboxNavigation/Resources/he.lproj/Localizable.strings

**Mapbox Navigation SDK version:** `v1.0.0-rc.5`
When in simulation mode, a small status banner indicating the simulation speed multiplier is displayed.
In Hebrew, an integer format specifier was used for the multiplier but a string is being passed to the formatter.
So instead of showing "Simulating navigation at 1x" (in Hebrew)
it would show "Simulating navigation at -1,103,473,346x"
The code for passing the string to the localized string is `showSimulationStatus(speed: Int)` in `StatusView.swift`

Fix wrong format specifier of speed multiplier in simulation (Hebrew)

---

CHANGELOG.md
MapboxCoreNavigation/Feedback.swift
MapboxNavigation/FeedbackItem.swift
MapboxNavigation/FeedbackSubtypeViewController.swift
MapboxNavigation/Resources/Base.lproj/Localizable.strings

Added `Speed limit incorrect` feedback subcategory for `Incorrect visual` category. Translations for newly added category and other strings will be added in another PR.

Add speed limit feedback.

---

CHANGELOG.md
MapboxNavigation/NavigationViewController.swift

Closing #2722.
Current issue is considered as a regression after update to Maps SDK `v6.2.0-beta.1`.
Here's stack trace for `v6.2.0-beta.1` when calling UI updates on Navigation SDK for iOS side:
```
0   MapboxNavigation                    0x00000001026bb2cb $s16MapboxNavigation0B14ViewControllerC7preview4step2in9remaining5route8animatedy0A10Directions9RouteStepC_AA09TopBannercD0CSayALGAJ0L0CSbtFyycfU_ + 235
1   MapboxNavigation                    0x0000000102661e80 $sIeg_IeyB_TR + 48
2   Mapbox                              0x0000000104525e96 -[MGLMapView processPendingBlocks] + 261
3   Mapbox                              0x0000000104524b18 -[MGLMapView renderSync] + 743
4   Mapbox                              0x00000001044d969b -[MGLMapViewImplDelegate glkView:drawInRect:] + 43
5   GLKit …
```

Add workaround which allows to perform maneuver view redrawing in time.

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation/DayStyle.swift
MapboxNavigation/NavigationMapView.swift
MapboxNavigation/NavigationViewController.swift
MapboxNavigation/UserCourseView.swift
MapboxNavigation/UserHaloCourseView.swift
docs/jazzy.yml

This pr will create a halo view for the iOS 14 reduced Accuracy during the navigation, similar to mapbox/mapbox-gl-native-ios#381. To solve the issue to fix mapbox/mapbox-navigation-ios#2555 following #2693 
This pr create a `UserHaloCourseView` similar to `UserCourseView` following the same protocol. Add a property in `NavigationMapView` to control the swift between the two views. Using the `navigationServiceDidChangeAuthorization` to set the value of the property. 
The following screenshot shows the new halo view during navigation under reduced location accuracy.

create a halo view for reduced accuracy in userCourseView

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This pr will create the template for Github pr and issue. 
This pr is following the github templates from  [Android team](https://github.com/mapbox/mapbox-navigation-android/tree/master/.github), with simplification of the Pr description and testing. Add the Pr template, and add components of the issue template.
1. check the preview of the `.md` file and check the tenplates
/cc @mapbox/navigation-ios 
/cc @zugaldia

create templates for github issue and pr

---

CHANGELOG.md
MapboxNavigation/NavigationMapView.swift

Initial implementation of route line styling functionality. Example:

Allow styling each route differently

---

.circleci/config.yml
Gemfile

Fixes build failures related to different CocoaPods versions being used for different environments on CircleCI. E.g.:
- `Xcode 12.2` uses CocoaPods `1.10.0`
- `Xcode 12.0.1` uses CocoaPods `1.10.0.rc.1`
- `Xcode 11.4.1` uses CocoaPods `1.9.1`
I'm not deeply familiar with CircleCI rules/syntax. Feel free to propose better appraches.

Use custom CocoaPods version for all build jobs.

---

CHANGELOG.md
MapboxNavigation/Style.swift

Makes `NavigationAnnotation` public to make it easier for external developers to filter-out annotations based on class name.

Make `NavigationAnnotation` public.

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxCoreNavigation/RouteController.swift
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
MapboxNavigation-Documentation.podspec
MapboxNavigation.podspec

This is a work in progress to upgrade to MapboxNavigationNative v28.1. ~~It doesn’t quite build yet due to a missing type declaration in MapboxNavigationNative.~~
Working towards #2672 and #2629.
/cc @SiarheiFedartsou @MaximAlien

MapboxNavigationNative v28.1

---

MapboxNavigation.xcodeproj/project.pbxproj

This PR applies #2774 to the Example-CarPlay and Bench targets so they build as well. The same input and output file lists are used for all three application targets.

Embed Example-CarPlay, Bench dependencies using Carthage

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxCoreNavigation/Tunnel.swift
MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
MapboxNavigation-Documentation.podspec

Upgraded the MapboxNavigationNative dependency to a minimum of v29.0, allowing v29._x_. Made `Tunnel.name` optional and public.
Fixes #2777.

MapboxNavigationNative v29.0

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/LaneView.swift
Sources/MapboxNavigation/LanesStyleKit.swift
Sources/MapboxNavigation/LanesView.swift
Sources/MapboxNavigation/UIImage.swift
Sources/MapboxNavigation/UIView.swift
Sources/MapboxNavigation/VisualInstruction.swift
Tests/MapboxNavigationTests/LaneTests.swift

Add support for visual lane guidance instructions in CarPlay. Addresses #1885 
Fix regression that occurred during Swift migration whereby dual use lane icons were not correctly indicating which direction to follow. Fixes #2796  
I used a slightly different approach for adding the Lane views than that which is outlines in #1885. Instead of drawing a snapshot of the `LanesView`, I instead form my own new lane image out of images of each lane.
For the lane coloring, I altered how the lanes are colored to use the Appearance proxy mechanism for the various colors. It no longer hardcodes that `invalid` or unusable lanes are colored with an alpha of 0.4. Instead they use whatever color is specified in the appearance proxy for the LaneView. This gives the client app more control over the visual …

Add lane guidance to CarPlay. Fix incorrect coloring of dual-use lane icons

---

CHANGELOG.md
Sources/MapboxNavigation/JunctionView.swift

Fixed a crash that occurred when showing a junction view on the image download queue by moving that operation to the main queue.
Fixes #2804.
/cc @mapbox/navigation-ios @bamx23

Show junction view on main queue

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
Sources/MapboxNavigation/LaneView.swift
Tests/MapboxNavigationTests/LaneTests.swift
Tests/MapboxNavigationTests/LaneViewTests.swift

Rewrote the code in LaneView that selects the LanesStyleKit drawing method. The new implementation separates the business logic from the drawing code. (Some assumptions about the repertoire of available lane configurations remains in the business logic.) In cases where the available drawing methods cannot faithfully depict the lane configuration, the closest match is drawn, biased toward the maneuver direction. The code flow goes from LaneIndication to LaneIndication.Ranking to LaneConfiguration to LanesStyleKit.
This PR comes with a battery of unit tests that’s much more comprehensive and maintainable than the existing snapshot tests, taking advantage of the new code’s testability. Some inaccuracies in the existing snapshot tests have also been fixed. (As of #2798, two test …

Rewrite lane use diagram selection logic

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/OfflineDirections.swift
Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Upgraded to [MapboxNavigationNative v31.0.1](https://github.com/mapbox/mapbox-navigation-native-ios/releases/tag/31.0.1).
Removed explicit routing tile version discovery now that the navigator can automatically choose the most recent version. Now MapboxNavigationNative automatically deletes old versions of routing tiles from the cache to save storage space. To do so, it needs access to the overall tile cache folder, not just the folder for an individual tile version.
/cc @mapbox/navigation-ios @mskurydin

MapboxNavigationNative v31.0.1

---

CHANGELOG.md
Sources/MapboxNavigation/UIView.swift
Sources/MapboxNavigation/VisualInstruction.swift

Should not be flipped when driving side is left, only when it is right. Fixes #2802.

Flip U-Turn Maneuver view when driving side is right

---

Sources/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

fix #2828 , building the link of the storyboard with EndOfRouteViewController by adding module information to its contained class.
Adding module information to its contained class.

Fix the EndOfRouteViewController crush

---

CHANGELOG.md
Sources/MapboxNavigation/InstructionsCardViewController.swift

This PR is to fix top banner swiping not being mirrored for right-to-left languages for instructions cards #2626.
I attempted to fix this issue, but the code was starting to look messy/hard to read with a bunch of cases to check whether the language was right to left. A higher-level abstraction should be able to fix this issue.
Added `UICollectionViewFlowLayout` extension to override `flipsHorizontallyInOppositeLayoutDirection`.
To fix the iPad issue, I added `InstructionsCardViewController.viewWillTransition(to:with:)`.

Right to Left Language instruction card swipe bug

---

CHANGELOG.md
Example/ViewController.swift
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
Sources/MapboxCoreNavigation/PredictiveCacheOptions.swift
Sources/MapboxNavigation/MapView.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationOptions.swift
Sources/MapboxNavigation/NavigationViewController.swift

This PR adds predictive Caching mechanism integration. It provides a configurable setting which enables predictive caching for `Navigator` and/or `Map`.
The PR introduces `PredictiveCacheLocationOptions` as a part of `NavigationOptions` which enables and configures the feature. Creation of predictive cache controllers is encapsulated in `PredictiveCacheManager` which just needs to be retained during the session.
Currently there seems to be some issue with navigation tiles. Tiles seems to be downloading after navigation has began, but it does not handle reroute events. 
Also, subjectively, MapView now takes longer to render at first launch, when there are no tiles downloaded yet. This may be related to providing a custom TileStore path, but I am not sure how and why this would matter.

Predictive Caching Integration

---

Example/ViewController+FreeDrive.swift
Example/ViewController.swift
Sources/MapboxCoreNavigation/CoreConstants.swift
Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift

This PR adds a speed limit view that updates during free-driving #2797.
Posted notifications in PassiveLocationDataSource.swift for the `speedLimit` and `signStandard`. Added methods to set up the view, observe notifications from `passiveLocationDataSource`, and update the `SpeedLimitView` accordingly.

Speed limit view updates during free-driving

---

CHANGELOG.md
Example/ViewController.swift
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/Expression.swift
Sources/MapboxNavigation/Feature.swift
Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

This Pr is to add the ability to high light choose building after long press in 3D, solving the [#728](https://github.com/mapbox/navigation-sdks/issues/728) The opacity would be varied with zoom level. The building would also appear in certain zoom level. 
Add the calling functions of `mapView.highlightBuildings(at:, in 3D:)` to highlight the chosen waypoint. Do query the feature at the waypoint on map view to find the id of the corresponding building. Then add one fillExtrusionLayer and filter the layer based on the building id. 
It would allow the building from 3D changing to 2D in `DayStyle` and `NightStyle`. The color of building would also change from blue to red when  `NightStyle` is chosen.
As the below .gif, it allow a series of long press to choose multiple buildings to …

Add ability to port building highlighting feature

---

CHANGELOG.md
Example/ViewController.swift
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/Directions.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/MapboxNavigation/CarPlayManager.swift

added Directions extension to utilize Navigatio……nNative.Router for offline routing. Extended CoreNavigationNavigator to also share cacheHandle
This PR adds usage of Navigation Native `Router` which is used for providing offline (onboard) directions utilising existing cached tile data.
Added an extension for `Directions` with 2 convenience methods: one to attempt usual online routing with automatic fallback to onboard engine, and another one for purely offline calculation.
Currently `Router` does not support Map Matching requests, so implementation covers only `directions`. In the future it may be easily extended.

Onboard Routing

---

Sources/MapboxNavigation/NavigationMapView.swift

This pr is to fix the partially visible maneuver problems during navigation session when multiple waypoints are selected.
By changing the sequence of laying addition to fix the partially visible problem caused by layer overlapping.

Fix partially visible maneuver problem

---

Sources/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

This pr is to fix #2857 
By removing the target information from the storyboard to remove the `Unknown class in Interface Builder file` error.

Fix the End-of-route feedback view

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/NavigationComponent.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/StatusView.swift
Sources/MapboxNavigation/TopBannerViewController.swift
Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
Tests/MapboxNavigationTests/StatusViewTests.swift

This PR allows the use of multiple status banners by refactoring `StatusView.swift` to manage the display statuses.

Allow the use of multiple status banners

---

.tx/config
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/Resources/ca.lproj/Localizable.stringsdict

Updated the Transifex configuration to reflect file moves in #2808 to support Swift Package Manager. Also synchronized the localizations with Transifex, pulling in some Catalan translations.

Update Transifex configuration after SPM refactor

---

.circleci/config.yml
MapboxNavigation.xcodeproj/project.pbxproj

Updated the CircleCI configuration to build the Example scheme using SPM instead of Carthage. Updated the Carthage-based MapboxCoreNavigation build to no longer link MapboxAccounts, which is unused following #2829.
Fixes #2862.

Fix Example build on CI

---

MapboxNavigation.xcodeproj/project.pbxproj
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Tests/MapboxCoreNavigationTests/SimulatedLocationManagerTests.swift

This pr is to remove TestHelper’s dependency on MapboxNavigation to fix #2820

Remove TestHelper’s dependency on MapboxNavigation

---

Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizonEdgeMetadata.swift

Exposed NN's EdgeMetadata.isRightHandTraffic value.
There is a typo generated by obj-c wrapper: `isIsRightHandTraffic` which should be corrected later. A task for corresponding fix for a wrapper generation is created.
I didn't update `CHANGELOG` because this is a part of the greater EH implementation which should cover this and other updates.

Support Driving Side flag

---

Sources/MapboxNavigation/NavigationMapView.swift

This PR is to address the destination annotation that was placed incorrectly below the route line (and all labels on the map), specifically when using building highlighting.
Changed the for loop in `NavigationMapView.addMainRouteLayer()` to exclude the `buildingExtrusionLayer` when searching for a parent layer.
Before:
Now:

Fix destination annotation incorrectly placed below route line

---

MapboxNavigation.xcodeproj/project.pbxproj
Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift
Tests/TestHelper/CoreLocation.swift

Updated test code to reflect file moves related to expanded SPM support in #2808 and the shared navigator refactor in #2823. Removed a broken file reference left over from when #2834 included a unit test of electronic horizon functionality.
Fixes #2866.

Fix MapboxCoreNavigationTests and TestHelper build errors

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewController.swift

Fixes #2786.
The main problem I see right now is that the initializer of NavigationViewController uses the `view` property and therefore triggers `viewDidLoad`. This in turn triggers `self.navigationService.start()`. It leads to the situation where a user already created NavigationViewController but hasn't presented it just yet but we've started the navigation session. 
Expected behavior for `viewDidLoad` is to be executed when the actual presentation of the NavigationViewController happens.
In fact, current behavior leads to the bug #2786. If the route is very small we can arrive at the final point during the initialization of NavigationViewController. The call stack will look like this:
`init -> viewDidLoad -> navigationService.start() -> .... -> navigationService(_:,didArrive:)`
[At …

Don't trigger viewDidLoad in NavigationViewController.init

---

CHANGELOG.md
Sources/MapboxNavigation/StyleManager.swift
Sources/MapboxNavigation/VanishingRouteLine.swift

Fixes #2766.
Currently, automatic day/night switching doesn't work at all, because we don't add [timeOfDayTimer](https://github.com/mapbox/mapbox-navigation-ios/blob/99dfa3287ffdf663c3880ef6a7dd833d5d59ff24/Sources/MapboxNavigation/StyleManager.swift#L135) inside of the RunLoop, therefore it never fires. I fixed this issue by replacing plain `Timer.init` with `Timer.scheduledTimer`. The latest one, according to the [documentation](https://developer.apple.com/documentation/foundation/timer/2091889-scheduledtimer) schedules timer on the current RunLoop. After this fix, StyleManager works as expected, but the sample app crashes inside of the [VanishingRouteLine](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Sources/MapboxNavigation/VanishingRouteLine.swift#L209) because it saves …

Fix automatic day/night switching

---

.circleci/config.yml

This PR changes the Metrics hook to trigger on `release-v2` branch instead of `main` since we are now interested in this release.
We'll need to revert this once `release-v2` branch makes it's way into `main`

CI metrics hook for V2 branch

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift

This PR fixes a crash that sometimes may occur due to a race condition when switching between day / night modes.
When switching between day / night mode via `StyleManager.applyStyle(type:)`, sometimes a crash may occur within the Mapbox iOS SDK with the following trace:
```
2021-03-29 10:24:19.829496-0500 Example[13984:7659400] *** Terminating app due to uncaught exception 'MGLInvalidStyleLayerException', reason: 'Either this layer got invalidated after the style change or -[MGLStyle removeLayer:] has been called with this instance but another style layer instance was added with the same identifier. It is an error to send any message to this layer since it cannot be recovered after removal due to the identifier collision. Use unique identifiers for all layer instances including layers of …
```

Fix crash when switching between day / night modes

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/BundleAdditions.swift
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
Sources/MapboxCoreNavigation/PredictiveCacheOptions.swift
Sources/MapboxCoreNavigation/RouteController.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Tests/MapboxCoreNavigationTests/SimulatedLocationManagerTests.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Tests/TestHelper/CoreLocation.swift
Tests/TestHelper/Fixture.swift

This pr is to fix the integration error and other errors in the MapboxcoreNavigationTest.
Creating a property called `credentials` in `Navigator` to be set before getting the shared navigator. It could take value value from `PassiveLocationDataSource` and `RouteController`.
By adding a `credentials` property to `PredictiveCacheOptions`, it also allows the `PredictiveCacheManager` passing the DirectionsCredentials to `Navigator`.

Allow the Navigator set access token other than in Info.plist

---

CHANGELOG.md
Sources/MapboxNavigation/StyleManager.swift

This PR changes the approach used by StyleManager for refreshing appearance-based UI elements to no longer touch every subview of every UIWindow instance in the application.
- Fixes #2764 
In a nutshell, the previous refresh logic was a bit too aggressive in its view hierarchy manipulation causing unexpected behavior in certain cases where multiple windows appear on screen (for example, whenever the system keyboard is presented).
For further discussion related to an instance of this issue, see the discussion in #2764 starting here: https://github.com/mapbox/mapbox-navigation-ios/issues/2764#issuecomment-806126471
In an effort to keep things DRY and since there are multiple view controllers implementing StyleManagerDelegate, there's a new method in StyleManagerDelegate …

Refactor StyleManager's appearance refresh logic to no longer use UIWindow loop

---

Sources/MapboxNavigation/NavigationMapView.swift

This PR is to address a regression introduced in [#2901](https://github.com/mapbox/mapbox-navigation-ios/pull/2901) as well as fix MapView annotation selection.
Added a target to the existing tap gesture recognizer to address route and waypoint selection. Maps team also investigated the gesture recognizer conflict and found that the logic that causes MapView's single tap gesture recognizer to fail is not implemented yet. Tested on both the Nav SDK side and in 1Tap.
cc/ @bamx23

Fix route selection regression and annotation selection

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Example/AppDelegate.swift
Example/FavoritesList.swift
Example/Info.plist
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
Sources/MapboxNavigation/CPMapTemplate.swift
Sources/MapboxNavigation/CPTrip.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/CarPlaySearchController+CPSearchTemplateDelegate.swift
Sources/MapboxNavigation/CarPlaySearchController.swift
Sources/MapboxNavigation/CongestionLevel.swift
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/RecentItem.swift
Sources/MapboxNavigation/UIScreen.swift
Sources/MapboxNavigation/VisualInstruction.swift
Tests/MapboxNavigationTests/CPMapTemplateTests.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift

In iOS 13 Apple added a Template-based mechanism for providing CarPlay support to apps. The Nav SDK needs to include support for these newer APIs while ensuring we don't break the earlier iOS 12 CarPlay delegate pattern until we drop support for iOS 12.
Fixes #2260 
The changes required within the Nav SDK are fairly minimal, mainly adding conformance to the CPTemplateApplicationSceneDelegate protocol. More extensive changes are needed to the Example app in order to adopt UIScene support.

Implement support for CPTemplateApplicationSceneDelegate UIScene-based CarPlay on iOS 13 and above

---

Sources/MapboxNavigation/RouteMapViewController.swift

Closing #2914.
Problem was due to strong reference usage when accessing `self` in closure.

Fix RouteMapViewController deallocation issue.

---

Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift

This is a quick fix that exposes history recording functionality as part of PassiveLocationDataSource for parity with RouteController. A more robust fix would entail defining a protocol that both PassiveLocationDataSource and RouteController can conform to in order to gain this functionality through default implementations, or alternatively to make Navigator itself public. The added methods are undocumented for now, in case we choose to implement a more robust fix.
/cc @mapbox/navigation-ios @bamx23

Add history methods to PassiveLocationDataSource

---

MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift

This pr is to fix #2913 , to allow the `MapboxCoreNavigationTests` passed with reset of navigator before location update each time.
The tests [failure](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/2950/workflows/920fa868-d1c5-4e45-b33a-a280266b252c/jobs/29227) of `MapboxCoreNavigationTests` , is caused by Navigator single entry point. Every time when the test cases need to update location, they're using the same navigator. So the `navigator.updateLocation` and `navigator.status(at: lastRawLocation.timestamp)` is causing problem in delivering the right location for each teat case running parallel. By adding the `try? Navigator.shared.navigator.resetRideSession()` every time before the location update would reset the navigator and remove the influence of other test …

Fix MapboxCoreNavigationTests failures with reset of navigator before location update each time

---

MapboxNavigation.xcodeproj/project.pbxproj
Package.swift
Sources/MapboxCoreNavigation/BundleAdditions.swift
Sources/MapboxCoreNavigation/EventDetails.swift
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/MBXInfo.plist
Sources/MapboxCoreNavigation/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/URLSession.swift
Sources/MapboxNavigation/MBXInfo.plist
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
scripts/update-version.sh

This pr is to fix #2922 .
When running the app generated by SPM, the `Info.plist` is also default to the one generated by SPM, which is missing some certain keys, such as the `CFBundleShortVersionString` . This pr is to create a resource file `MBXInfo.plist` same as `Info.plist`, and copy it to the MapboxCoreNavigation. When the bundle couldn't find certain keys contained in `Info.plist` , it would check the `MBXInfo.plist`.
Update the `update-script.sh` to copy the `Info.plist` to `MBXInfo.plist`.

Fix MapboxCoreNavigation bundle when building with SPM

---

.circleci/config.yml
Tests/SPMTest/SPMTest.xcodeproj/project.pbxproj
Tests/SPMTest/SPMTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Tests/SPMTest/SPMTest.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Tests/SPMTest/SPMTest/AppDelegate.swift
Tests/SPMTest/SPMTest/Assets.xcassets/AccentColor.colorset/Contents.json
Tests/SPMTest/SPMTest/Assets.xcassets/AppIcon.appiconset/Contents.json
Tests/SPMTest/SPMTest/Assets.xcassets/Contents.json
Tests/SPMTest/SPMTest/Base.lproj/LaunchScreen.storyboard
Tests/SPMTest/SPMTest/Base.lproj/Main.storyboard
Tests/SPMTest/SPMTest/Info.plist
Tests/SPMTest/SPMTest/SceneDelegate.swift
Tests/SPMTest/SPMTest/ViewController.swift
scripts/build_spm_integration_test.sh

Fixes #2903.
We already build the Example scheme on CI, where our SDKs are included via SPM, however, we added the `mapbox-navigation-ios` package to the Xcode project: 
This isn't the way our package will be integrated into the consumer apps. For example, we don't have MapboxNavigation and MapboxCoreNavigation in our [Package.resolved](https://github.com/mapbox/mapbox-navigation-ios/blob/release-v2.0/MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved) file.
On the other hand, my sample app contains an external reference to the `MapboxNavigation` package, which is the expected way to integrate our SDK:
By integrating the package this way we now have it in [Package.resolved](https://github.com/mapbox/mapbox-navigation-ios/blob/3cf0ef9b36c4ce8e2dc27b4c078098 …

Add integration test for Swift Package Manager

---

Example/ViewController.swift

This pr is to fix #2883 .  
The `ViewController` defines a `navigationMapView` , but when we request routes and form a `NavigationViewController`, it also contains a `navigationMapView`. So during the turn by turn navigation, the `ViewController` defined `navigationMapView` should be removed.  This pr is to uninstall the before defined `navigationMapView` when the turn by turn navigation starts.

Fix the simulate route options in Example

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/Array.swift
Sources/MapboxNavigation/Constants.swift
Sources/MapboxNavigation/MapView.swift
Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationMapViewDelegate.swift
Sources/MapboxNavigation/NavigationMapViewIdentifiers.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Sources/MapboxNavigation/Route.swift
Sources/MapboxNavigation/RouteLineType.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

Current PR implements functionality, which allows to override main and alternative route lines, along with refactoring which aims to simplify route line gradient generation.
Also fixes https://github.com/mapbox/mapbox-navigation-ios/issues/2907 and https://github.com/mapbox/mapbox-navigation-ios/issues/2818.

Add ability to override main and alternative route lines.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationMapViewDelegate.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift

Added delegate, which is called after adding final destination PointAnnotation.
Delegate method can be used like in Custom Waypoint Marker example in https://github.com/mapbox/mapbox-navigation-ios-examples/pull/102.

Added delegate, which is called after adding final destination PointAnnotation.

---

Sources/MapboxNavigation/NavigationViewController.swift

Resolves #2959 
The crash occurred due to incorrect views initialisation order. `NavigationViewController` has multiple embedded components, which require adding subviews to it's main view. At the same time, instantiating `view` runs the navigation session at which point all view setup should be ready to process incoming data. That also caused a side effect that actual navigation session started right after `NavigationViewController.init`, but not after it was actually presented.
This PR adds primitive "hooks queue" to delay any subview setup which requires main view to already exist, thus avoiding it's unexpected instantiation.

Active Guidance crash

---

Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Sources/MapboxNavigation/NavigationViewData.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/RouteLineController.swift

After dropping `RouteMapViewController` certain `NavigationViewControllerDelegate` delegate methods were not called anymore.
Fixes #2962.

Fix issues with calling NavigationViewControllerDelegate methods.

---

CHANGELOG.md
Sources/MapboxNavigation/LaneView.swift
Sources/MapboxNavigation/LanesView.swift
Sources/MapboxNavigation/VisualInstruction.swift

This PR highlights lanes based on active direction using new properties from Directions API. #2801
Use the preferred direction in the call to `LaneIndication.ranked(favoring:)` in `LaneView.draw(_:)` by passing it in when the `LaneView` is initialized by `LanesView.update(for:)`.
Before these changes, we would see issues like this one. The highlighted lanes conflict.
After the changes, we see the correct maneuver instruction:

Highlight lanes based on active direction

---

Sources/MapboxNavigation/CameraController.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewportDataSource.swift
Sources/MapboxNavigation/UIEdgeInsets.swift

This pr is to fix #2912 , to allow the camera on the top of the selected maneuver in preview.
By adding the constraint of padding to the CameraOptions to set the center of `maneuverLocation` to be the center of the camera of `NavigationMapView`

Fix the Maneuver selection in preview

---

Sources/MapboxNavigation/ArrivalController.swift
Sources/MapboxNavigation/NavigationViewController.swift

This pr is to fix the #2929 . After the arrival at the destination, the destination should be at the center of the mapView in an overview mode, which is the essential to display the building highlighting feature. And the user location puck should be at the destination.
By adding the center and pitch constraint to the camera, to let the destination at the center of the `mapView` and also update the `userCourseView` to be at the destination point.

bring the arrival frame back to same as 1.x

---

Sources/MapboxNavigation/OrnamentsController.swift

Fixes #2960.
Seems that issue was in strong reference to `self` which is already invalid by the time feature querying finishes its search.

Fix crash in ornaments controller.

---

Sources/MapboxNavigation/CarPlayManager.swift

Fixed crash when accessing `compassView` on `CarPlay` when presenting `CarPlayNavigationViewController`, by calling delegate method only after finishing presentation.
Since crash happens mostly because of race-condition, it's pretty hard to reproduce it. I had to add such delay to see it:
```swift
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 1.0) {
carPlayMapViewController.present(navigationViewController, animated: true)
}
self.delegate?.carPlayManager(self, didBeginNavigationWith: service)
```

Fix crash when accessing `compassView`.

---

Sources/MapboxNavigation/NavigationMapView.swift

This pr is to fix #2867 , to allow the maneuver arrow disappearing on low zoom level, same as in 1.x.
By adjusting the `minimumZoomLevel` to `14.5`, the maneuver could disappear when the zoom level is smaller than 14.5
When the zoom level is smaller than a certain number, the maneuver arrow will hide, same as in 1.x

Allow the maneuver arrow disappear on customized low zoom level

---

Package.resolved

It fixes Xcode 12.5 SPM integration and matches the version in Cartfile.resolved.

SPM: Update mapbox-events-ios to v0.10.8

---

Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStoreDelegate.swift
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/NavigationRouteOptions.swift
Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/MapboxCoreNavigation/RouterDelegate.swift
Sources/MapboxNavigation/BottomBannerViewController.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/CarPlaySearchController.swift
Sources/MapboxNavigation/FeedbackViewController.swift
Sources/MapboxNavigation/InstructionLabel.swift
Sources/MapboxNavigation/InstructionPresenter.swift
Sources/MapboxNavigation/InstructionsBannerView.swift
Sources/MapboxNavigation/NavigationComponent.swift
Sources/MapboxNavigation/NavigationMapViewDelegate.swift
Sources/MapboxNavigation/NavigationViewData.swift
Sources/MapboxNavigation/RouteVoiceController.swift
Sources/MapboxNavigation/SpeechSynthesizing.swift
Sources/MapboxNavigation/StepsViewController.swift
Sources/MapboxNavigation/StyleManager.swift
Sources/MapboxNavigation/TopBannerViewController.swift

It is Swift 5.4 warning:
> Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead

Fix "class" as protocol deprecation warnings

---

CHANGELOG.md
Sources/MapboxNavigation/MultiplexedSpeechSynthesizer.swift

`delegate` in `MultiplexedSpeechSynthesizer` [here](https://github.com/mapbox/mapbox-navigation-ios/blob/release-v2.0/Sources/MapboxNavigation/MultiplexedSpeechSynthesizer.swift#L12) is strong and causes circular reference issue when it's caller (e.g. `NavigationViewController`) implements `SpeechSynthesizingDelegate`
1. Add delegate implementation below [here](https://github.com/mapbox/mapbox-navigation-ios/blob/release-v2.0/Sources/MapboxNavigation/NavigationViewController.swift#L1060)
```swift
extension NavigationViewController: SpeechSynthesizingDelegate {
}
```
2.Set the delegate below [here](https://github.com/mapbox/mapbox-navigation-ios/blob/release-v2.0/Sources/MapboxNavigation/NavigationViewController.swift#L453)
```swift
voiceController.speechSynthesizer.delegate = self
```
3. …

Fix circular reference issue in MultiplexedSpeechSynthesizer

---

CHANGELOG.md
Sources/MapboxNavigation/InstructionLabel.swift

This pr is to fix #2938 by resetting `imageRepository` cache and reload `instruction` when style change.

Clear ImageRepository cache when style change

---

docs/cover.md

MINOR_VERSION equal to 1.4
SHORT_VERSION equal to 1.4.0
SPM doesn't even recognise 1.4 as a valid SEMVER.
Cocoapods recognize 1.4 as a valid SEMVER, but it doesn't hurt to
specify patch version (1.4.0) as well.
The fix works correctly with "release-v2.0" branch as well.

Fix versions in a jazzy docs

---

Sources/MapboxNavigation/InstructionLabel.swift

This pr is to fix #3027 
The `textColor` and `font` of the instruction label should be updated after the instruction reset.

Fix text missing in Guidance Card navigation

---

CHANGELOG.md
Example/CustomViewController.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

Fixes #2973.
Since it's not possible to call other initializers in `NavigationViewController.init(coder:)` new public `NavigationViewController.initialize(for:routeIndex:routeOptions:navigationOptions:)` method was introduced. It's meant to be called right after `NavigationViewController` instantiation in storyboard. I've also brought back `NavigationViewController` to `Navigation.storyboard` to give the ability to create it using [this](https://docs.mapbox.com/ios/navigation/guides/storyboards/) guide.

Fix NavigationViewController crash in storyboard.

---

MapboxNavigation.xcodeproj/project.pbxproj

It used to be at Carthage/Build/iOS/Cedar.framework
Correct location is Carthage/Checkouts/mapbox-events-ios/Frameworks/Cedar.framework

Fix Cedar.framework path

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/UnimplementedLogging.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxCoreNavigationTests/UnimplementedLoggingTests.swift

The method is part of the public SDK API, and there are no guarantees
that it will be called in a thread-safe manner. The fact current
implementation isn't thread-safe was proofed by running a test with
Thread Sanitizer (TSan) enabled (see the log at the end).
- UnimplementedLogging.logUnimplemented reimplemented so that it is safe
to use from multiple threads.
- Adds a test to verify that the new implementation is safe.
- Adds a test to catch performance regressions in implementation.
Below is a log from TSan when run for old implementation:
```
WARNING: ThreadSanitizer: Swift access race (pid=14419)
Modifying access of Swift variable at 0x00010a65a7a0 by thread T2:
#0 UnimplementedLogging.logUnimplemented(protocolType:level:function:) <null>:12416464 …
```

Fix UnimplementedLogging.logUnimplemented method

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Sources/MapboxCoreNavigation/TileStore.swift
Sources/MapboxCoreNavigation/TilesetDescriptorFactory.swift

Resolves #2987 
The PR adds convenience methods to verify validity of Navigation tiles in Offline Region or entire TileStore, and an accessor method for corresponding TilesetDescriptor which is required for downloading navigation tiles.
TilesetDescriptor methods are a bit awkward as they require a `CacheHandle` which is configured during Navigator instance startup. Getting a descriptor should be independent of Navigation, but share configuration values. That's why there is a chunk of duplicated logic. I was thinking about moving `CacheHandle` initialisation logic into `CoreNavigationNavigator` but could not come up with a solution which looked pretty. The problem is that `CacheHandle` construction is coupled with other entities initialisation and it messes up the Navigator init sequence.

TileStore navigation tiles API

---

CHANGELOG.md
Sources/MapboxCoreNavigation/MinimumEditDistance.swift
Sources/MapboxNavigation/OrnamentsController.swift

This pr is to fix #1440 , by improving the road label after feature query results from the EHorizon notification.
Receiving the e-horizon road names through `Notification`. During the turn-by-turn navigation, when there're multiple feature query results, comparing the road name of the feature with the e-horizon road names. And then choosing the most similar feature to label the road if it's not the nearest one.

Use  EHorizon to improve road label during turn-by-turn navigation

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/Directions.swift

Resolves #3037 
Fixed a bug where Router was deallocated before it actually schedules a route calculation, which results in callback not being called.
Moved MBNNRouter instance to be a part of Navigator wrapper. Such instance has low overhead of keeping alive, and is recommended by NN to persist it.

Offline routing

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObjectStore.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStoreDelegate.swift
Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
Sources/MapboxCoreNavigation/RouteController.swift

This pr is to fix #3041 to rename `RoadObjectsStore` and `RoadObjectsStoreDelegate` to `RoadObjectStore` and `RoadObjectStoreDelegate`.

Rename RoadObjectsStore to RoadObjectStore

---

Sources/MapboxNavigation/ImageCache.swift
Sources/MapboxNavigation/UIImage.swift

How much an image takes in memory can be different for different images:
- An image created with CGContext will have a different memory size
than the same image but loaded from a jpg file.
Example: https://stackoverflow.com/a/25706554/425838.
- Size depends on the image's colour space (how many bytes needed to
encode one pixel of the image).
The fix uses the data returned by CGImage, which is the most reliable
source of information available to estimate the size of an image in
memory.

Fix ImageCache image cost estimation logic

---

CHANGELOG.md
Sources/MapboxCoreNavigation/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/NavigationService.swift

vk-694-cancel-event-loss: added forcing EventsManager datasource to o……verride nilling weak reference during deallocation.
Resolves an issue, where `Navigation end` event was not logged if trips was cancelled.
Issue is caused by nilling weak reference to a `NavigationService` during it's deinit stage. To avoid that I've added forcing a strong reference during event logging.

Fixing Navigation end event loss of cancelling

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Example/ViewController.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Tests/MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
Tests/MapboxNavigationTests/Support/CarPlayUtils.swift

This pr is to fix #2908 by adding the `CarPlayManagerDelegate.carPlayManager(_:shouldPresentArrivalUIFor:)`, to allow the developers to decide whether to present end of route view for CarPlay.
By adding `CarPlayManagerDelegate.carPlayManager(_:shouldPresentArrivalUIFor:)` and `CarPlayNavigationViewController.navigationService(_:didArriveAt:)`, user could determine whether to call the `CarPlayNavigationViewController` to display the arrival UI.

Add ability to show arrival UI for CarPlay

---

Sources/MapboxCoreNavigation/TileStore.swift

Resolves #3051 
Fixing logical errors in methods, which ignored 'error' state.
Simplified the check a bit to force 'nil' value when encountering an error from TileStore.
Did not update a CHANGELOG because this bug is in new functionality which was not released yet.
Did not add unit tests because that would require a bit of a juggling with Commons TileStore api, and we are [trying to downstream this API directly to Common lib](https://github.com/mapbox/mapbox-navigation-android/issues/4471).

Tile verification fix

---

Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift

This pr is to fix #3071 
Updated the expression to use the `navigationMapView.userLocationStyle` in CarPlay.
NavigationMapView Preview:
During turn-by-turn navigation:

Fix the new user location layer in CarPlay

---

Sources/MapboxNavigation/ImageDownload.swift
Sources/MapboxNavigation/ImageDownloader.swift
Tests/MapboxNavigationTests/ImageDownloaderTests.swift
Tests/MapboxNavigationTests/Support/ImageLoadingURLProtocolSpy.swift

Fixes #3067
- Fix a lot of thread-safety issues.
- Fix incorrect handling of errors:
- Completions are called two times for HTTP status code >= 400.
- `ImageDownload` operation wasn't properly transition into finished
state.
- `ImageDownload` operation didn't have proper `isReady` state.
- Increase test coverage for these types.
- `ImageDownloader` is fixed by properly using Dispatch Queue: perform protected state read/write inside the queue.
-  concurrent `accessQueue` replaced by a serial one, because most accesses to the queue modifies the protected state that require a barrier to be placed. That makes the `accessQueue` merely a serial queue. 
`ImageDownload` is a subclass of NSOperation. 
- The implementation is improved with a simpler to use `State` variable. No more multiple flags …

Fix issues in ImageDownload and ImageDownloader

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
Sources/MapboxCoreNavigation/RouteController.swift
Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

[Previous PR](https://github.com/mapbox/mapbox-navigation-ios/pull/3074) accidentally enabled history recording by default. We should not do this.
Basically a reverse commit.

Disabling History recording by default

---

Sources/MapboxNavigation/ImageDownload.swift

Fixes sporadic failures in tests. 
When cancel is called, `start` method can be executed on a different thread. There is a room when cancel hasn't updated the state yet and `start` method verified it could start.
With the fix, we make sure that start can't be executed while cancel is by guarding methods in a lock.

Fixes the race in ImageDownload

---

Package.swift
Sources/MapboxNavigation/LaneView.swift
Tests/MapboxNavigationTests/LaneViewTests.swift

This PR fixes several edge cases in lane indication ranking that I missed in #2882 due to disabled unit tests. It also fixes numerous errors in the tests themselves. In some cases, the library or tests weren’t wrong, but the additional assets in #2882 make a better result possible. LaneViewTests has been reenabled, now that it passes.
Fixes #3107.

Fix more lane icon edge cases and tests

---

CHANGELOG.md
Sources/MapboxNavigation/UserCourseView.swift
Sources/TestHelper/LeakTest.swift
Tests/MapboxNavigationTests/LeaksTests.swift

Fixed #3120
Use block based API. Also added a test to catch regressions in the future.

Fix retain cycle in UserPuckCourseView

---

.circleci/config.yml
Package.swift

Fixes #3048
- Move Xcode 12.4 swift test to a new "extended-workflow". 
- Create Xcode 12.5 swift test.
- Move iOS 13.7 Xcode 12.5 swift test to the "extended-workflow".
- "extended-workflow" should run an extended set of tests once a day that will
allow us to spot regressions in more cases while saving the cost on CI.

Add Xcode 12.5 swift test job

---

Sources/MapboxNavigation/WayNameView.swift

Fixed vertical flipping of the route shield in the current road name label. As of mapbox/mapbox-maps-ios#321, the UIImage returned by `Style.image(withId:)` has `downMirrored` orientation and a specific scale by virtue of using [this conversion utility](https://github.com/mapbox/mapbox-maps-ios/blob/1a0505c37410f9629771480f34e37356d9f6ff54/Sources/MapboxMaps/Foundation/Extensions/UIImage.swift#L32). Extracting the CGImage and stuffing it in a new UIImage erases that metadata, resulting in flipping and potentially incorrect scaling. Removing that unnecessary indirection fixes the flipping:
Fixes #3124.

Fix style image flipping in current road name label

---

Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationMapViewIdentifiers.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

This pr is to fix #3098 , because the 3D puck from map side doesn't support the default topmost layer position similar as 2D puck. This pr is to check the 3D puck layer and make it above the maneuvers when we call `func navigationMapView.addArrow`.
Because the 3D puck from map side doesn't support the default topmost layer position similar as 2D puck. This pr is to check the 3D puck layer and make it above the maneuvers when we call `func navigationMapView.addArrow`

Adjust the layer position to make puck layer at topmost

---

.circleci/config.yml

Currently, we have no visibility into our failed "nightly" builds (which are run as "extended-workflow" in CircleCI). 
Failed builds on main are reported by email, but it would be good to post notifications in Slack as well. 
So this PR adds elementary Slack integration, which reports failed builds on main in Slack.

Add slack notifications for failed builds on main branch

---

Example/ViewController+FreeDrive.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/RouteLineController.swift

This pr is to fix #3105, to remove the manually puck heading update code in `navigationMapView.moveUserLocation(to:animated:)`  introduced in #2968 
Use the `simulatesLocation` to switch between the `course` and `heading` as the puck bearing source, instead of manually stop and update the puck layer.
Create a `SimulatedLocationManger` based `NavigationLocationProvider` to provide location update during simulated session.
Add the `RouteOverlayController` as the location consumer for the `mapView`, to receive the location update.
Use the `renderFrameFinished` to check the location change under simulation, and push location update to allow the vanishing route line synced with puck.
Stop the location update from the CarPlay before navigation session starts, to avoid the background navigator …

Update the mapSDK puck in NavigationMapView with location course for bearing

---

Sources/MapboxNavigation/Array.swift
Tests/MapboxNavigationTests/ArrayTests.swift

Instead of iterating by all points many times, we can solve the problem
in one iteration.

Improve performance of Array.boundingBoxPoints by 5x

---

CHANGELOG.md
Sources/MapboxCoreNavigation/EventDetails.swift
Sources/MapboxCoreNavigation/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxNavigation/CameraController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewData.swift
Sources/MapboxNavigation/OrnamentsController.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

With this change, the API for `NavigationService` is safer, although it is a breaking change. Would be good to land before RC.

Remove some redundant force unwraps

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/Dictionary+DeepMerge.swift
Sources/MapboxCoreNavigation/Dictionary.swift
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Tests/MapboxCoreNavigationTests/Extensions/Dictionary+Equality.swift
Tests/MapboxCoreNavigationTests/NativeHandlersFactoryTests.swift

Add ability to pass custom navigation config through UserDefaults. The default config will be deep-merged with the application-provided config and the second one will take preference in case of merge conflicts.
Also added new test approach, any feedback will be appreciated.

Add ability to pass custom config through `UserDefaults`

---

Sources/MapboxNavigation/MapView.swift

Closes #3130.
Issue was caused by local variable/parameter naming clash.

Fix issue, which prevents from disabling traffic.

---

CHANGELOG.md
Sources/MapboxNavigation/Expression.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift

This pr is to allow the hard stop and abrupt change of congestion level without the blurring effect on route line layer.
Use `Step` instead of the `interpolate ` in expression.

Allow the hard stop of route line gradient

---

Sources/MapboxNavigation/NavigationMapView.swift

Closing #3168.
`NavigationMapView.prepareForInterfaceBuilder()` was removed as it's only used in case if UIView is marked as `@IBDesignable`.

Remove `NavigationMapView.prepareForInterfaceBuilder()`.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/RouteController.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift

Introduced explicit methods to start and stop history recording. For performance reasons, the navigation SDK no longer automatically records history upon starting a route or free-driving session as it did in previous v2.0.0 betas. This change also makes it possible for an application to avoid the gap in history recording that was introduced in #3156.
For the next beta’s release notes:
* Renamed the `RouteController.writeHistory(completionHandler:)` method to `RouteController.stopRecordingHistory(completionHandler:)` and the `PassiveLocationManager.writeHistory(completionHandler:)` method to `PassiveLocationManager.stopRecordingHistory(completionHandler:)`. ([#3157](https://github.com/mapbox/mapbox-navigation-ios/pull/3157))
* Added the `RouteController.startRecordingHistory()` and …

Restart history recording before finishing writing history

---

Sources/MapboxCoreNavigation/EHorizon/RoadGraph.swift
Sources/MapboxCoreNavigation/EHorizon/RoadGraphPath.swift
Sources/MapboxCoreNavigation/EHorizon/RoadGraphPosition.swift

Add `.pathShape(for:)` and `.position(for:)` methods to RoadGraph.

---

Cartfile.private
Cartfile.resolved
MapboxNavigation.xcodeproj/project.pbxproj

PR removes `MapboxGeocoder` reference from Carthage as it's no longer needed for testing purposes and is only linked via SPM for CarPlay based example application.
/cc @1ec5 @jill-cardamon

Remove `MapboxGeocoder` references.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationOptions.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

Resolves #3165 
Added a property to `NavigationOptions` which forwards input `NavigationMapView` instance to `NavigationView` (and in result in `NavigationViewController`. This instance is used instead of originally created `NavigationMapView` if provided.

NavigationMapView injection

---

CHANGELOG.md
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/MapboxNavigation/NavigationViewController.swift
Tests/MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
docs/guides/Using Map Matching.md

Fixes #2948
Previous method of just updating `indexedRoute` wasn't robust enough for
cases when the new route has different waypoints than the one it is
replacing. New method allows to update route from the different set of
waypoints.

Implement a new method to change route

---

CHANGELOG.md
Example/ViewController.swift
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/NavigationRouteOptions.swift
Sources/MapboxCoreNavigation/RouteOptions.swift
Tests/MapboxCoreNavigationTests/Extensions/RouteOptionsTests.swift

Fixed an issue where copying an instance of a RouteOptions subclass resulted in an instance of RouteOptions itself. Now calling `RouteOptions.copy()` always returns the same specific type as the original object.
Along for the ride, `RouteOptions.without(waypoint:)` has been renamed `RouteOptions.without(_:)`, because the argument label is redundant to the argument type at the point of use.
Fixes #3191.
/cc @mapbox/navigation-ios @OttyLab

Copy RouteOptions as its most specific type

---

CHANGELOG.md
Sources/MapboxCoreNavigation/ActiveNavigationEventDetails.swift
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/NavigationLocationManager.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/TestHelper/NavigationServiceTestDoubles.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

Rename RouterDataSource.locationProvider to locationManagerType

---

Sources/MapboxNavigation/OrnamentsController.swift

Fixes #3093
The calculation assumed that navigation view is in full screen.

Fixes map ornaments position on non-fullscreen presentation

---

Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RouteLegProgress.swift

This pr is to add the range check of the `routeProgress.currentLeg.steps` before assign value to `routeProgress.currentLegProgress.stepIndex`, to avoid the out of bounds crush in the `RouteLegProgress.currentStep`

Fix Index out of bounds crash in RouteLegProgress.currentStep

---

Sources/MapboxNavigation/NavigationMapView.swift

This pr is to fix #2996 
This pr is to remove the usage of `JSON` in runtime styling of route duration annotation, and replaced it with the map SDK’s type-safe `Expression` type.
With the `Expression` styling:
With the `JSON` styling:

Replace JSON with Expressions in route duration annotation styling.

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Tests/MapboxNavigationTests/MapViewTests.swift

Since `CarPlayManager` always provides default `MapboxNavigationService` implementation there is no need to force user to provide another instance even if it's similar to the previous one.
This is usability improvement, which was found during implementation of https://github.com/mapbox/mapbox-navigation-ios-examples/pull/134.

Make `NavigationService` optional to be able to skip implementation of delegate method on client side.

---

Sources/MapboxNavigation/CarPlayMapViewController.swift

To match `NavigationViewController`, `NavigationMapView` and `CarPlayNavigationViewController` behavior, `CarPlayMapViewController` should not show traffic.

Do not show traffic by default in `CarPlayMapViewController`.

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/EHorizon/DistancedRoadObject.swift
Sources/MapboxCoreNavigation/EHorizon/OpenLROrientation.swift
Sources/MapboxCoreNavigation/EHorizon/OpenLRSideOfRoad.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObjectType.swift
Sources/MapboxCoreNavigation/Incident.swift
Sources/MapboxCoreNavigation/MapboxStreetsRoadClass.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/RestStop.swift
Sources/MapboxCoreNavigation/RouteState.swift
Sources/MapboxCoreNavigation/TollCollection.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxNavigationTests/NavigationCameraTests.swift

Update to Mapbox Maps `v10.0.0-rc.5` and Navigation Native `v60.0.0`.

Update to Mapbox Maps `v10.0.0-rc.5` and Navigation Native `v60.0.0`.

---

Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/RouteLineController.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

Fix route line visibility.

---

CHANGELOG.md
Sources/MapboxNavigation/GenericRouteShield.swift

There is a known issue about Route shield images being cached without addressing it's actual foreground color. This PR updates the caching key to resolve that.
Added `dataSource.textColor` to the cache key calculation. This value is related to the cache, as [it is used when generating a shield image](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Sources/MapboxNavigation/InstructionPresenter.swift#L182).

GenericRouteShield caching

---

CHANGELOG.md
Sources/MapboxNavigation/RouteLineController.swift

This PR fixes a crash due to a retain cycle caused as part of `NavigationMapView` reuse across multiple instances of `NavigationViewController` which was made available with the injection work in #3186.
`RouteOverlayController.navigationViewDidLoad` defines two closures for handling map events. Each closure captures a strong reference to `self` which will result in a retain cycle if the referenced `NavigationMapView` object is used across multiple instances of `NavigationViewController`. The crash occurs on presentation of the _subsequent_ `NavigationViewController` 
Steps to reproduce this bug are:
1. Create an instance of `NavigationMapView`
2. Create and present an instance of `NavigationViewController` and inject the map view created in step 1.
3. Dismiss the instance of …

Fix retain cycle causing crash in RouteOverlayController on NavigationMapView reuse

---

Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift
Tests/MapboxNavigationTests/Support/CarPlayUtils.swift

https://github.com/mapbox/mapbox-navigation-ios/pull/3182 incorrectly reverted some of the changes, which were brought by https://github.com/mapbox/mapbox-navigation-ios/pull/3208. Current PR brings these changes back.

Make `NavigationService` optional.

---

Sources/MapboxNavigation/NavigationViewController.swift

Make `NavigationViewController` convenience initializer public to be able to use it as an SDK user.

Make convenience initializer public in `NavigationViewController`.

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/Route.swift
Sources/MapboxNavigation/RouteLineController.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

This pr is to fix #3141  to improve the performance, reduce calculation and battery usage as below.
|                                                  | previous                     | now                                                                                |
|--------------------------------------------------|------------------------------|----------------------------------------------------------------------------------------|
| calculate route congestion features frequency    | by frame rate                | when refresh(/30s in Example), route leg change, or route congestion level info change |
| update route line gradient method per frame rate | generate route line gradient | update route line gradient                                                             |
| generate …

Improve the performance of vanishing route line feature

---

Sources/MapboxNavigation/NavigationViewController.swift

A side effect of this is that the shared navigator is updated in
quick succession in Router initialization.
Discovered during #3195 QA.

Fix buggy default MapboxNavigationService creation if custom one is provided

---

Sources/MapboxNavigation/CameraController.swift
Sources/MapboxNavigation/NavigationViewController.swift

This pr is to fix #3232 by allow the resume button to stop the preview of top instruction banner and guidance cards
Allow the `navigationViewController` to call its components when resume button is pressed and a recenter is going on.

Allow the resume button to stop preview for top banner and guidance cards

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-Documentation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift

Update dependencies to Turf `v2.0.0-rc.1`, Mapbox Common `v16.2.0`, Mapbox Navigation Native `v62.0.0` and Mapbox Maps `v10.0.0-rc.6`.

Update Mapbox Navigation dependencies.

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/EHorizon/RoadObjectLocation.swift
Sources/MapboxCoreNavigation/EHorizon/RoadSubgraphEdge.swift

The case of subgraph was missing in the `RoadObjectLocation` enum. Without it, an app crashes in the `preconditionFailure`.
I've also added a corresponding struct for subgraph edges. I would appreciate help with providing better in-code documentation for the new struct.

Add subgraph case to RoadObjectLocation

---

Example/en.lproj/Localizable.strings
Sources/MapboxCoreNavigation/Resources/en.lproj/Localizable.strings

I split off an update to the source localization files from #3187 so we can land that PR next without any of the unused strings that apparently have translation issues anyways.

Update source localization files

---

Sources/MapboxNavigation/NavigationMapView.swift

Due to the landing of the #3201, it needs the stored route location points to calculate useful `fractionTraveled`. We use the `navigationMapView.initPrimaryRoutePoints(route:)` in `navigationMapView.show(_:legIndex:)` to prepare for it in mobile. But in CarPlay, it would only be called if the route leg index change or rerouting. Thus the  route location points are not stored for the `fractionTraveled`. 
In the following .gif, it shows the we enable and disable the vanishing feature per 3 seconds during the navigation session.

CarPlay vanishing route line

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/OnMainQueue.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/IdleTimerManager.swift
Sources/MapboxNavigation/NavigationViewController.swift
Tests/MapboxCoreNavigationTests/IdleTimerManagerTests.swift

fixes #3227
I drafted a POC of how idle timer can look like. Then naming is temporary, but for some reason I really like to use token here :)
Given that behaviour in CarPlayManager is very confusing and contradicts itself, I've change the logic to the following:
- If `carPlayManagerShouldDisableIdleTimer` returns true: idle timer is disabled while CarPlay is active, otherwise, do nothing. 
- If NavigationViewController is visible: disable idle timer. 
Does this sound reasonable to you? Should the logic be different?

Introduce IdleTimerManager to streamline idle timer management and fix bugs

---

Sources/MapboxNavigation/NavigationCameraStateTransition.swift
Tests/MapboxNavigationTests/NavigationCameraTests.swift

Add `testRunningAnimators`. Fix crash in `NavigationCameraStateTransition.stopAnimators()`.

---

Sources/MapboxNavigation/RecentItem.swift
Tests/MapboxNavigationTests/RecentItemTests.swift

Fix failing `testRecentItemsSavingAndLoading` on `iOS 13`.

Fix failing `testRecentItemsSavingAndLoading`.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreConstants.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxNavigation/OrnamentsController.swift

This pr is to address some comments in #3257

Fix the tail work of the road name label based on status.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift

Fixed #3260
We are not supposed to filter out navigation statuses as per NavNative team. Android doesn't filter them out either. 
If it breaking any functionality, we must fix it without filtering out all the events.

Disable filtering by navigation status origin

---

CHANGELOG.md
Sources/MapboxNavigation/ArrivalController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/RouteLineController.swift

This pr is to fix #3254 and #3267
According to https://github.com/mapbox/mapbox-navigation-ios/issues/3254#issuecomment-901269168, the issue happened because when the user passed the destination, the route still exits because `fractionTraveled` not set to `1.0`. 
To avoid the `grow back` effect when user passed the destination and keep moving forward, while the `routeProgress` still sending update, we check whether we has passed the final leg waypoint and then remove the route. Thus if there's a rerouting event happened later, it would not generate a new route instead.

To improve the vanishing route line when rerouting happens

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/MapTemplateProvider.swift
Sources/MapboxNavigation/MapTemplateProviderDelegate.swift

PR brings some improvements and changes, which are needed for https://github.com/mapbox/mapbox-navigation-ios-examples/pull/134.
Also fixes:
- #3220
- ~~#3224~~

CarPlay refactoring and bugfixing.

---

Sources/MapboxNavigation/NavigationMapView.swift

This pr is to fix the route line shows all when refresh but the vanishing effect enabled.
Due to the following, when refresh happened, the `pendingCoordinateForRouteLine` will use the `mostRecentUserCourseViewLocation` which is the current location, thus the bottle neck distance limit will stop updating the `fractionTraveled`,  which lead to the route line shows all.
https://github.com/mapbox/mapbox-navigation-ios/blob/41ca049bd9efdb3ee91617cbc98d2f90152718f3/Sources/MapboxNavigation/NavigationMapView.swift#L565
To fix this issue, let the `pendingCoordinateForRouteLine` choose the route shape first coordinate to avoid this problem. Because the pending coordinate is aimed at stored some value for the distance limit check.

Quick fix the refresh shows all route line during navigation.

---

MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/MapboxNavigation/FollowingCameraOptions.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewportDataSource.swift
Sources/MapboxNavigation/NavigationViewportDataSourceOptions.swift
Sources/MapboxNavigation/OverviewCameraOptions.swift
Tests/MapboxNavigationTests/NavigationCameraTests.swift

Change `minimumZoomLevel` and `maximumZoomLevel` with closed range in `FollowingCameraOptions`.
Closing #3281.

Make navigation camera options more restrictive.

---

CHANGELOG.md
Sources/MapboxNavigation/OrnamentsController.swift

For large route steps we spend too much time in `LineString.sliced(from:to:)` called to find `pointAheadUser` for the code that looks for a road name. And we've been doing this call multiple times _(hundreds of times in some cases)_ for the same location update. This can even provoke crashes due to CPU consumption.
This seems to be a simple yet effective optimization.

Make `pointAheadUser` calculated once per update

---

Sources/MapboxCoreNavigation/PassiveNavigationFeedbackType.swift
Sources/MapboxNavigation/Feedback/PassiveNavigationFeedbackType+FeedbackItem.swift
Sources/MapboxNavigation/Resources/en.lproj/Localizable.strings

A couple of the feedback categories added in #3323 for passive navigation are misspelled or otherwise inconsistent with analogous feedback categories for active turn-by-turn navigation.

Copyedit feedback categories

---

Sources/MapboxCoreNavigation/URLSession.swift

Closing #3312.
Result string previously looked like this when using SPM:
`Example/2.0.0 Example/2.0.0 iOS/14.5.0 (x86_64)`
Now it looks like this:
`Example/2.0.0 MapboxNavigation/2.0.0 MapboxCoreNavigation/2.0.0 Example/2.0.0 iOS/14.5.0 (x86_64)`

Fix bundle names retrieval in `URLSession.userAgent`.

---

Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift

This pr is to fix #3333 , to allow the route line gradient be updated through the `mapView.mapboxMap.style.setLayerProperty(for:property:value:)` with only the route line gradient expression transformed to JSON, instead of retrieving the whole line layer and the whole route line JSON object.

Partially update the layer property instead of updating the whole layer.

---

Sources/MapboxCoreNavigation/RouteController.swift

Reroute does not update `indexedRouteResponse` and refresh uses old route's identifier to update route annotations. This provides unexpected speed limit, congestion information display.
Reroute does not update [`indexedRouteResponse`](https://github.com/mapbox/mapbox-navigation-ios/blob/v2.0.0-beta.25/Sources/MapboxCoreNavigation/RouteController.swift#L39). `indexedRouteResponse.routeResponse.identifier` represents route's identifier and used [when refreshing](https://github.com/mapbox/mapbox-navigation-ios/blob/v2.0.0-beta.25/Sources/MapboxCoreNavigation/Router.swift#L173). 
Therefore, `indexedRouteResponse` needs to be updated [here](https://github.com/mapbox/mapbox-navigation-ios/blob/v2.0.0-beta.25/Sources/MapboxCoreNavigation/RouteController.swift#L584-L589).
After the reroute, speed …

Fix IndexedRouteResponse handling after rerouting

---

CHANGELOG.md
Sources/MapboxNavigation/Constants.swift
Sources/MapboxNavigation/Expression.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift
docs/jazzy.yml

This pr is to allow the developer to choose the route line gradient color change style between the fading one and the steep change one.
To show the fading color gradient between different traffic congestion level, set `navigationMapView.crossfadesCongestionSegments =  true` as below
To show the fading color gradient between different traffic congestion level during active guidance navigation,  set `navigationViewController.navigationMapView.crossfadesCongestionSegments =  true` as below

Suport gradient for congestion color change.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift

In the case of off-route, we have to send the initial coordinate to Directions API. Currently we use the raw location for it (i.e. we get bearing and coordinate from the system) what can lead to awful use experience (route built in the wrong direction, problems on parallel roads, etc). For directions API requests we should always use coordinate, bearing, and other parameters provided by map matcher(i.e. by NN).

Use snapped location for reroutes

---

Example/ViewController.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/MapView.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/RouteLineController.swift
Sources/MapboxNavigation/VectorSource.swift
Tests/MapboxNavigationTests/MapViewTests.swift

Restored the `NavigationMapView.localizeLabels()` implementation for automatically localizing map labels into the user’s language. The previous implementation was removed as part of upgrading to map SDK v10 in #2808, because it relied on [an NSExpression-based localization feature](https://github.com/mapbox/mapbox-gl-native-ios/blob/ddf8e35970d1a8a46171bd798bcfa8f22d2760e0/platform/darwin/src/NSExpression%2BMGLAdditions.mm#L1494-L1637) in map SDK v6._x_. This implementation continues to be based on the map SDK’s built-in label localization functionality rather than reinventing the wheel as in #2933.
/cc @mapbox/navigation-ios @neelmistry94 @tobrun

Reimplement label localization atop Expression (redux)

---

.circleci/config.yml
Tests/SPMTest/CoreSPMTest/CoreSPMTest.xcodeproj/project.pbxproj
Tests/SPMTest/CoreSPMTest/CoreSPMTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Tests/SPMTest/CoreSPMTest/CoreSPMTest/Assets.xcassets/AccentColor.colorset/Contents.json
Tests/SPMTest/CoreSPMTest/CoreSPMTest/Assets.xcassets/AppIcon.appiconset/Contents.json
Tests/SPMTest/CoreSPMTest/CoreSPMTest/Assets.xcassets/Contents.json
Tests/SPMTest/CoreSPMTest/CoreSPMTest/ContentView.swift
Tests/SPMTest/CoreSPMTest/CoreSPMTest/CoreSPMTestApp.swift
Tests/SPMTest/CoreSPMTest/CoreSPMTest/Info.plist
Tests/SPMTest/CoreSPMTest/CoreSPMTest/Preview Content/Preview Assets.xcassets/Contents.json

Adds a CI build step to make sure that an application builds with only `MapboxCoreNavigation` dependency.

Add SPM `MapboxCoreNavigation` integration test

---

.gitignore
scripts/update-version.sh

With this change, the release script now generates a pair of prerelease podspecs if a prerelease version is being published. These podspecs can then be pushed to CocoaPods trunk under the `MapboxCoreNavigation-pre` and `MapboxNavigation-pre` names.
Fixes #3357.

Generate prerelease podspecs

---

CHANGELOG.md
Sources/MapboxNavigation/InstructionsCardCell.swift
Sources/MapboxNavigation/InstructionsCardContainerView.swift
Sources/MapboxNavigation/InstructionsCardView.swift
Sources/MapboxNavigation/InstructionsCardViewController.swift

This pr is to fix #3243 and #3381 to allow the guidance cards receiving the `VisualInstructionBanner` update and distance update from `navigationService` .
To fix #3381 , the `InstructionsCardViewController.updateCurrentVisibleInstructionCard(for:)` is added to pass the `VisualInstructionBanner` to the current active guidance card. In case the `VisualInstructionBanner` notification arrives before the guidance card configuration and set up, it's stored to prepare for the configuration of the first step.
The #3243 is caused by the sequence change of subviews of the `instructionCollectionView` during the active navigation. Thus we loop through its subviews for the casting instead of the fixed position.

Allow guidance cards to receive the instruction update

---

Sources/MapboxNavigation/NavigationViewportDataSource.swift

PR fixes an issue, which resulted in user puck going offscreen when there are sharp maneuvers.
Issue was caused by https://github.com/mapbox/mapbox-navigation-ios/pull/3275 (center coordinate of the bounding box should be used, instead of two coordinates of the bounding box itself).
/cc @bamx23

Fix issue, when user puck goes offscreen in some cases.

---

CHANGELOG.md
Sources/MapboxNavigation/UserCourseView.swift
Sources/MapboxNavigation/UserHaloCourseView.swift

This pr is to fix #3406 to allow the `UserHaloCourseView` of the approximate location circle could tilt at the same angle of the camera and `mapView` during the active guidance navigation.
This issue is fixed by allowing the `haloView` of the `UserHaloCourseView` to receive the pitch transform.

Fix the tilt of the `UserHaloCourseView`.

---

Example/ViewController+FreeDrive.swift
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.xcodeproj/project.pbxproj
Package.resolved
Sources/MapboxCoreNavigation/CLLocation.swift
Sources/MapboxCoreNavigation/EventLocation.swift
Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/FreeDriveEventDetails.swift
Sources/MapboxNavigation/Feature.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/Route.swift
Sources/MapboxNavigation/WayNameView.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

Migrated Turf GeoJSON usage to GeoJSONObject and JSONValue. Factored out EventLocation to begin migrating some ad-hoc event dictionaries to Codable structs.
Depends on mapbox/turf-swift#154, mapbox/mapbox-maps-ios#715, and #3413. There are no additional public-facing changes on top of the Turf changes.

Migrate Turf GeoJSON usage to GeoJSONObject and JSONValue

---

Sources/MapboxCoreNavigation/LegacyRouteController.swift

This new behavior won't work until #3398 is resolved.

Start new trip on each waypoint in LegacyRouteController

---

Sources/MapboxCoreNavigation/ReplayLocationManager.swift

`onTick` allows to get each replayed location with its index
`onReplayLoopCompleted` allows to stop replay after all locations
replayed.
Prevent crashes if incoming locations array is empty.

Extend ReplayLocationManager with new callbacks

---

CHANGELOG.md
Example/CustomViewController.swift
Example/ViewController.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/NavigationOptions.swift
Sources/MapboxNavigation/NavigationViewController.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift

Resolves #3216 
Adds new simulation mode, to kick the simulation while loosing GPS signal while traversing tunnels. Also exposes simulation setting though `NavigationOptions`.
PR adds new enum case, updates default settings to use `.inTunnels` instead previous default `.onPoorGPS` and adds additional property to `NavigationOptions`.

inTunnels simulation

---

Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/Route.swift
Sources/MapboxNavigation/StepsViewController.swift
Tests/MapboxNavigationTests/RouteTests.swift
Tests/MapboxNavigationTests/StepsViewControllerTests.swift

This pr is to fix #3062 and #3234 by adding the check when we select the banner instruction for preview.
The crash reported from #3062 , #3234 and a recent crash from user are all resulted from the call of the following:
https://github.com/mapbox/mapbox-navigation-ios/blob/8257c395745e18255e391978e387034f00086290/Sources/MapboxNavigation/StepsViewController.swift#L192-L206
And then we need to form a `RouetLegProgress` to preview the step as:
https://github.com/mapbox/mapbox-navigation-ios/blob/8257c395745e18255e391978e387034f00086290/Sources/MapboxNavigation/NavigationViewController.swift#L1104-L1106
But the issue is that if we scroll the table quickly, during when the `routeProgress` changed and reload the table view data, or the `routeProgress` received in the table view is different …

Fix the preview crash resulted from the table view scrolling quickly.

---

Sources/MapboxNavigation/InstructionsCardViewController.swift

While `endIndex` is equal to count, this is not guaranteed by the
documentation. It is safer and more clear to the reader to use count.

Use count instead of endIndex

---

CHANGELOG.md
Sources/MapboxNavigation/InstructionsCardCell.swift
Sources/MapboxNavigation/InstructionsCardContainerView.swift
Sources/MapboxNavigation/InstructionsCardViewController.swift

This pr is to fix #3441 by only allowing the current guidance card step highlighted.
Adding the check of the card step before the distance check, to see whether it's the current step. If false, don't allow the background color change.

Only allow the current guidance card be highlighted.

---

Sources/MapboxNavigation/NavigationCameraStateTransition.swift
Tests/MapboxNavigationTests/NavigationCameraTests.swift

PR adds preventive checks to make sure that before running camera animations coordinate is valid.

Add preventive checks to make sure that before running camera animations coordinate is valid.

---

CHANGELOG.md
Sources/MapboxNavigation/InstructionsCardViewController.swift

This pr is to fix #3502 
By adding the items count check before the` InstructionsCardViewController.handlePagingforScrollToItem(indexPath:)` would prevent the crash, which is happening of scrolling the guidance card hard during the orientation change animation.
For example, there're some cases that when the orientation change and the swiping the guidance cards hard, the remanning steps is decreasing, it would lead to the `steps.count` as `7`, while the `indexBeforeSwipe.row` as `7`, it would lead to the crash.  The items count check would prevent this rare edge case.

Fix the scrolling guidance cards during orientation change crash

---

Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift

PR fixes an issue, which was causing close panning button to stop working after several active-guidance navigation sessions. Root cause of this was that `closeButton` was always using the same `CPMapTemplate` even after several dismissals and presentations.
Closing #3539.

Fix issue, which was causing panning dismissal button to stop working on CarPlay.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift

According to #3542 , the regression cause that when there's no congestion level found in the `RouteLeg`, the route leg would display a default darker blue of `routeCasingColor ` instead of `trafficUnknownColor`. This pr is to fix this issue.
When there's no congestion level found, default show the `trafficUnknownColor` or `alternativeTrafficUnknownColor` on the current leg.
In `Example`, By setting the ` routeLeg.segmentNumericCongestionLevels` and `routeLeg.segmentCongestionLevels` as `nil` before we generate congestion features in `Route.congestionFeatures(legIndex:roadClassesWithOverriddenCongestionLevels:)`, we could get the situation when no congestion level found in the current route. 
Then we have the following before the fix, which would show the darker blue as the …

Use `trafficUnknownColor` for route line when no congestion level found.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Locale.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/NavigationSettings.swift
Sources/MapboxNavigation/NavigationViewController.swift

iOS has standard `usesMetricSystem` variable that [works differently](https://github.com/mapbox/mapbox-navigation-ios/pull/3547#discussion_r741311298) for UK locale

Deprecate custom usesMetric in favor of iOS defined usesMetricSystem

---

CHANGELOG.md
Sources/MapboxNavigation/InstructionsBannerView.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/TopBannerViewController.swift
Tests/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift

This pr is to allow the customization of `TopBannerViewController` and fix #3567 
1. `TopBannerViewController`'s `lanesView` , `nextBannerView` , `statusView` , `junctionView` are exposed publicly to allow access and modification of it's contents.
2.  `NavigationViewControllerDelegate ` right now extends `TopBannerViewControllerDelegate`,both  `TopBannerViewControllerDelegate` and `InstructionsBannerViewDelegate` extend `VisualInstructionDelegate`. So right now through the `NavigationViewControllerDelegate`, developers could call `fNavigationViewControllerDelegate.label(_:willPresent:as:)` to customize the `instructionsBannerView` of the `TopBannerViewController` during navigation.
For example, in `Example`, we allow the `ViewController` extends `NavigationViewControllerDelegate` as …

Allow the customization of TopBannerViewController.

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift

Fix issue, which was causing inability to see `SpeedLimitView` and `CarPlayCompassView` when right-to-left mode is used on CarPlay.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/DistanceFormatter.swift
Sources/MapboxCoreNavigation/NavigationRouteOptions.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/NavigationSettings.swift
Sources/MapboxNavigation/NavigationViewController.swift
Tests/MapboxCoreNavigationTests/MeasurementSystemTests.swift

Fixes #2578
Prefers distance measurement system from RouteOptions instead of just current locale. It allows having US locale and metric system distance. 
NavigationRouteOptions now reads global NavigationSettings for preferred distance measurement system. This fixes CarPlay implementation for route previews. 
Deletes misleading property from NavigationSettings.

Fix distance measurement system

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/CameraController.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/NavigationMapView+RoadNameLabeling.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewportDataSource.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/UIImage.swift
Sources/MapboxNavigation/UIView.swift
Sources/MapboxNavigation/WayNameView.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

Closing #3480.
Road name labeling on CarPlay during free-drive:
Road name labeling on CarPlay during active-guidance:

Road name labeling functionality for CarPlay.

---

.circleci/config.yml

Fix build errors similar to this one on CircleCI:
```
Command line invocation:
/Applications/Xcode-12.4.app/Contents/Developer/usr/bin/xcodebuild -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 12 Pro Max" -scheme MapboxNavigation-Package build test
Build settings from command line:
SDKROOT = iphonesimulator14.4
Resolve Package Graph
Fetching https://github.com/AliSoftware/OHHTTPStubs.git
Resolved source packages:
MapboxNavigation: /Users/distiller/project
xcodebuild: error: Could not resolve package dependencies:
The server SSH fingerprint failed to verify.
Exited with code exit status 74
```
by upgrading from Xcode `12.4` to `12.5.1`:

Upgrade from Xcode `12.4` to `12.5.1`.

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewController.swift

This pr is to stop the location update in the background of the `mapView` during the active navigation when users using the default course view for the user location indicator layer.
Right now we have 2 types of user indicator layers, the map puck and the `.courseView`. During the active navigation, if we choose the map puck, we rely on the location update from `mapView` to update the location of user location indicator and the vanishing route line, so they could keep in sync.
But when we use the default `.courseView`, the user indicator layer and the vanishing route line are both listen to the router. If there're location updates in the background of the `mapView` during the active navigation, it could trigger the navigator to gives different location and `routeProgress`, which lead to a …

Stop the location update in the background during active navigation using default course view.

---

Sources/MapboxNavigation/StyleManager.swift

The fixed word is "approriate"

Fix misspelled word

---

Sources/MapboxNavigation/NavigationMapView.swift

Maps v10 changed the API for how stretchable image assets are defined for map symbol style layers. This caused some rendering issues with the offsets that worked in Maps v6.3.
The fix is to update the offsets used to declare the stretchable regions and content area of the route duration annotation callouts.
Screenshots of the before and after:

Fix rendering issue with route preview stretchable route duration callouts

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift

Closing #3604.
Since there is no ability to detect whether CarPlay head-unit is in either left of right driving side mode (at least I was not able to find it, feel free to provide any suggestions if you have any) I had to use `safeAreaInsets` value as a criteria.

Fix excessive padding on CarPlay during active navigation.

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/RouteLineController.swift

This pr is to fix #3612 by packing the route line update methods into the `func updateRouteLine(routeProgress:coordinate:)` through `CarPlayNavigationViewController` and `RouteLineController`, to reduce code duplication and avoid the route line update delay.
Previously when style changes or when reroute event happens in CarPlay, the `CarPlayNavigationViewController` only shows the route line without updating the upcoming route point index, which cause a 1 second delay and the route line blinking. This pr is to pack the route line update methods into `CarPlayNavigationViewController.updateRouteLine(routeProgress:coordinate:)` and `RouteLineController.updateRouteLinee(routeProgress:coordinate:)`. So when the style changes, rerouting and refresh event happens, `mobile` and `CarPlay` will it …

Fix style change caused route line update delay.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewportDataSource.swift

Here are a few visual examples:
`IntersectionDensity.averageDistanceMultiplier = 100.0` (original behavior, before applying fix and regardless of value, which was set)
`IntersectionDensity.averageDistanceMultiplier = 20.0`
`IntersectionDensity.averageDistanceMultiplier = 7.0` (default value)

Fix issues in zoom calculations for cases when maneuver is further away from the current location.

---

.circleci/config.yml

Bumped Xcode version for CocoaPods CI jobs as it used a deprecated one.

Cocoapods CI Job

---

Example/ViewController.swift

Without such information, the directions API can produce a route that
starts in the wrong direction.

Update example to use course parameter for user location

---

CHANGELOG.md
Sources/MapboxNavigation/Array.swift
Sources/MapboxNavigation/Route.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

This or is to fix #3542 by changing the coordinates count issue brought by https://github.com/mapbox/mapbox-directions-swift/pull/587 in generating congesting features of route line.
https://github.com/mapbox/mapbox-directions-swift/pull/587 added one more coordinate in the final step of each route leg, it would lead to the `resolvedCongestionLevels` count larger than the coordinates count as in https://github.com/mapbox/mapbox-navigation-ios/issues/3542#issuecomment-972380046 . This pr is to fix this issue by changing the count constraint and to allow the congestion feature generation.
Much of the work is from #3603 
The refresh rate is set to 5, and we could see that the route line doesn't lost its traffic color after refresh as following.
The route line blinks is #3621 .

Fix the congestion color missing issue of route line when refresh.

---

CHANGELOG.md
Sources/MapboxNavigation/Constants.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/VanishingRouteLineTests.swift

This pr is to fix #3319 by adding the distance check of user location to pre-defined route. When the distance from user location to pre-defined route larger than `OffRouteDistanceUpdateThreshold`, the vanishing route line would stop updating until the rerouting event triggered to generate a new route line.
`OffRouteDistanceUpdateThreshold` is public and defaults to 15m. The `OffRouteDistanceUpdateThreshold` should be larger than the driving distance per second according to the speed. Otherwise, in some edge cases, such as in big turn or driving too fast, it would see the normal driving as off line behavior and stop updating the vanishing effect. Because the normal driving speed is 60km/h, it's safe to set the `OffRouteDistanceUpdateThreshold` between `15m ~ 20m`.
Add the …

Add distance check to prevent vanishing route line update when users go off the route.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreConstants.swift
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RouteProgress.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewportDataSource.swift

This PR fixes #1942 by reworking #2215.

Respect heading while walking

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift

Closing #3633.
PR updates code, which adds image, which is used for drawing maneuver arrow with `sdf` property set to `true`, as it's required for changing color.

Allow maneuver arrow styling.

---

.circleci/config.yml

`mbx-ci` CLI tool has deprecated previous token related commands and we should use new ones.

Use public token on CircleCI

---

CHANGELOG.md
Example/ViewController.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RouteProgress.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/MapboxCoreNavigation/RouterDelegate.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Sources/TestHelper/DirectionsSpy.swift
Sources/TestHelper/NavigationServiceTestDoubles.swift
Sources/TestHelper/RouterDelegateSpy.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

Added `RouterDelegate/NavigationServiceDelegate/NavigationViewControllerDelegate` method to allow overriding  `RouteOptions.avoidManeuversInOriginRadius` for rerouting. This setting is useful for adjusting rerouting logic according to current user's velocity to not force him into unexpected turns.

Rerouting avoiding Dangerous Maneuvers

---

Sources/MapboxNavigation/NavigationViewportDataSource.swift

PR removes `maxPitch` parameter, which is not used.

Remove `maxPitch` parameter, which is not used.

---

scripts/publish-docs.sh

The script fails to publish docs because previous actions could pollute the working directory. In my case, it was `Package.resolved` from `Navigation-SPM.xcodeproj` that was updated during docs generation.

Clean working directory before switching branches

---

Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift

For whatever reason, Swift 5.3 (Xcode 12.4) requires us to use a type alias if we refer to a module as a namespace and the module had been imported as `@_implementationOnly` and CocoaPods is doing its magic behind the scenes. This small change fixes building with CocoaPods in Xcode 12.4 and unblocks v2.1.1.
Cherry-pick to the release-v2.1 branch after merging.

Extract MapboxNavigationNative_Private usage into type alias

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift

Change off-route detection logic to use snapped location instead of raw location.
/cc @azarovalex

Use a snapped location instead of a raw location during off-route detection process.

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/InstructionsBannerView.swift
Sources/MapboxNavigation/InstructionsBannerViewDelegate.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
docs/jazzy.yml

This pr is to add documentation for `InstructionsBannerView`, `BaseInstructionsBannerView` and the publicly exposed properties.`InstructionsBannerViewDelegate` is moved to a separate file as well.

Add documentation for `InstructionsBannerViewDelegate`.

---

scripts/document.sh
scripts/postprocess-docs.py

Changes similar to https://github.com/mapbox/mapbox-directions-swift/pull/631, which brings dynamic symbol retrieval.
This fixes lots of broken links and adds new ones for recently added symbols.
The script is almost the same as in https://github.com/mapbox/mapbox-directions-swift/pull/631, only changing a custom string substitute.

Add more precise docs post-processing

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/NavigationLocationProvider.swift
Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/NavigationLocationProviderTests.swift

This pr is to fix #3673 to allow the `NavigationMapView.MapView` could receive the simulated location updates from our `NavigationLocationProvider`.
Because of the `MapboxMaps` upgrade and the refactoring in the `LocationManager` of `MapView`, right now the `MapView.location.locationProvider(_: didUpdateLocations:)` having issues with the locations update and notification to its consumers. Now we add the `NavigationLocationProvider.didUpdateLocations(locations:)` method to notify the `MapView` about the locations update, and the location consumers of the `MapView` such as the map puck could be noticed and updated with the locations.

Allow the mapView receives simulated location update.

---

scripts/postprocess-docs.py

`sys.stdout.write` doesn't add `\n` at the end.
Refs https://github.com/mapbox/mapbox-directions-swift/pull/641

Fix new-lines in docs HTML files

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/VanishingRouteLineTests.swift

This pr is to fix #3636 and support the instant change of `NavigationMapView.showsRestrictedAreasOnRoute` during active navigation.
When the `NavigationMapView.showsRestrictedAreasOnRoute` turns on during active navigation with `routeLineTracksTraversal` enabled, the `currentRestrictedAreasStops` will be updated, the new restricted areas layer will be added above the main route line layer and below the arrow stroke layer.
When the `NavigationMapView.showsRestrictedAreasOnRoute` turns off during active navigation with `routeLineTracksTraversal` enabled, the `currentRestrictedAreasStops` will be removed, the restricted areas layer and its source would also be removed.
When `NavigationMapView.showsRestrictedAreasOnRoute` value changes during active navigation with `routeLineTracksTraversal` …

Support instant Restricted Areas Route Line update

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationCamera.swift

Fixes and issue, where tapping `NavigationMapView` while it transitions the camera to or from `following/overview` states would leave it in `transitioning` state, and thus blocking switching to either mode.

Fix tap gesture to stop camera transitions

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift

This PR fixes a bug where building highlighting extrusion was hiding POIs and destination marker.
Issue is resolved by specifying layer order of extrusion graphic to be just above the original building layer.
Compare before and after:

Building highlighting overlaps POI icons

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/RouteController.swift
Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxNavigationTests/StepsViewControllerTests.swift

When we start active guidance navigation, we update NavNative Navigator with the route for this session. When we end active guidance navigation, though, the route isn't reset, and NavNative continues to think that it is in the Active Guidance. It is incorrect behavior. 
This change is likely to fix #3298.
After the change, some tests started to fail more because the tests were setup in a way that more than one RouteController existed and they interfered with each other. So, I had to fix the tests as well. This work also addressed #3628. 
Even after these changes, there are still some flaky tests. Can it be related to many PassiveLocationProviders at the same time? Will investigate separately. 
_The follow-up will add a debug assertion to telegraph developers that they are not supposed to …

Remove route from NavNative Navigator when transition from out of Active Guidance

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
Tests/CocoaPodsTest/PodInstall/Podfile.lock

This PR is to update `MapboxDirections` for Swift dependency to `v2.2.0`

Update directions dependency to v2.2.0.

---

Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/TestHelper/TestCase.swift
Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift

Fixes disabled before tests:
- Better Navigator reset method
- Hard retain in new reroute code
- An attempted fix to 'tripPerWaypoint' test

Restore and fix disabled tests

---

CHANGELOG.md
Sources/MapboxNavigation/LaneView.swift
Tests/MapboxNavigationTests/LaneViewTests.swift

When displaying an unrecognized turn lane indication combination, such as a U-turn-and-opposite-turn combination, we fall back to just the active indication. When that active indication is unrecognized, such as for a merge lane, there’s supposed to be a last-resort fallback to a dimmed out straight-ahead icon. However, this fallback was being short-circuited by a stray optional from the previous fallback, prematurely triggering the precondition failure. This specific case was covered by a test at a low level for the method that worked correctly but not at a higher level for the method that short-circuited it.
Fixes #3596.

Fix crash displaying unrecognized lane

---

Tests/MapboxNavigationTests/VanishingRouteLineTests.swift

Swift 5.3 (Xcode 12.4) doesn’t allow reusing a variable name for a second `guard let` statement in the same scope, so the changes in #3687 caused build errors about shadowed variables in the MapboxNavigationTests target.
/cc @ShanMa1991

Fix test build errors in Swift 5.3

---

Sources/MapboxCoreNavigation/DistanceFormatter.swift

This PR adds initializers to the now public structs `RoundingTable` and `Threshold`.

Add initializers to RoundingTable and Threshold

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Directions.swift

This PR fixes `Directions.calculateOffline` method to use strictly offline routing provider.

[bugfix] Fix Direction.calculateOffline using hybrid router

---

CHANGELOG.md
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Sources/MapboxCoreNavigation/RouteProgress.swift

Resolves #3621 
Temporarily set Directions to track [custom commit](https://github.com/mapbox/mapbox-directions-swift/pull/634) to test new Directions API before it's release.
PR reverts route refreshing methods on `RouteProgress` to utilize new refreshing protocol.

Route linke blinking on refresh

---

MapboxNavigation.podspec
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Updated the CocoaPods podspec for compatibility with any MapboxMaps v10.2–v10._x_, not just v10.2.2.
Fixes #3710.
/cc @mapbox/navigation-ios @macdrevx

MapboxMaps v10.2 or above

---

Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift
Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift

PR replaces deprecated `Navigator.resetRideSession()` with newly added `Navigator.reset()` methods.

Replace deprecated `Navigator.resetRideSession()` with `Navigator.reset()` methods.

---

CHANGELOG.md
Sources/MapboxNavigation/MapView.swift
Tests/MapboxNavigationTests/MapViewTests.swift

This pr is to allow the mapView to show and hide traffic data from traffic v2 tile set.
Right now the `MapView.showsTileSet(withIdentifiers:layerIdentifier:)` and `MapView.setShowsTileSet(_:withIdentifiers:layerIdentifier:)` are both public to allow developers to show and hide custom  TileSet IDs for the map.

Support to show and hide traffic data from V2 beta version tile set.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/BillingHandler.swift
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/HistoryRecording.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/TestHelper/TestCase.swift
Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
Tests/MapboxCoreNavigationTests/TilesetDescriptorFactoryTests.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift
Tests/MapboxNavigationTests/SKUTests.swift
Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift

This PR changes Navigator behavior to be deallocated when it is not needed anymore. This allows clearer state resetting when re-running navigation and clears up some used resources when navigation is not needed anymore.
Reworked CoreNavigationNavigator to be weak referenced, updated it's consumers to maintain a strong reference to Navigator while in use. Reworked native navigator observers to avoid retain cycle.

Navigator deinitialization

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift

This pr is to fix #3733 to allow the `route line` layers, `waypoint` layers, `route duration` layers, `arrow` layers and `voice instruction` layers not disappearing when the map style changes in preview mode.
Because in active navigation, we already have the `RouteOverlayController` and the `CarPlayNavigationViewController` to listen to the map style change, and to update the route line layers, arrow layers and the waypoint layers .
But in the preview mode and in passive navigation, we should have these layers as persistent of `navigationMapView` and won't disappear as the map style changes.

Fix the route layers disappearing in preview mode when map style changes.

---

CHANGELOG.md
Sources/MapboxNavigation/InstructionsBannerView.swift
Sources/MapboxNavigation/TopBannerViewController.swift

This Pr is to fix #2015 to hide the remaining steps when user is on final step.
When user arrives on final step, `TopBannerViewController` would dismiss the `stepsViewController` and change the `instructionsBannerView.showStepIndicator` to `false`. And the step indicator of the instruction banner would be hidden, the swiping and tapping gestures wouldn't work.
And if the mobile is in the previewing mode, the previewing process would stop. If the mobile is displaying the remaining steps in pull-down menu, the pull-down table would be dismissed.
When in final step, the indicator view would be hidden, swiping and taping gestures wouldn't trigger the remaining steps displaying.

Hide the remaining steps when user is on final step

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift

This PR fixes navigator deallocation bug before returning it's value.

Navigator lifecycle bugfix

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift

This PR:
- Adds the ability to disable `NavigationMapView` tap gesture recognizer. 
- Makes `NavigationMapView.waypoints(on:closeTo:)` and `NavigationMapView.routes(closeTo:)` public to be able to detect waypoints and routes on the map view.

Expose waypoint and route detection methods publicly.

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/BillingHandler.swift
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RoutesCoordinator.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
Tests/MapboxCoreNavigationTests/RoutesCoordinatorTests.swift

- Depending on how the app is structured it is possible that
RouteController.deinit (that switches navigator to passive navigation)
get called after a new navigation view controller is created. Creating
navigation view controller switches navigator to active navigation. This race condition is fixed by coordinating setRoutes requests to
Navigator through RoutesCoordinator.
- Fixes the crash that can occur in rare cases when we receive in invalid navigation status update.
- RouteController now filter outs navigation status updates that are not related to the route.

Reduce the likelihood of navigation incorrectly transition to passive navigation

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift
Tests/MapboxNavigationTests/CarPlayUtils.swift

PR deprecates `CarPlayManagerDelegate.carPlayManagerDidEndNavigation(_:)` and adds `CarPlayManagerDelegate.carPlayManagerDidEndNavigation(_:byCanceling:)` as a replacement.
Closing #3727.
/cc @ChristianSteffens

Add `CarPlayManagerDelegate.carPlayManagerDidEndNavigation(_:byCanceling:)`.

---

CHANGELOG.md
Sources/MapboxNavigation/EndOfRouteViewController.swift
Sources/MapboxNavigation/NavigationView.swift

This PR is to fix #3766 by setting the bottom of `EndOfRouteViewController` view to the screen bottom to remove the gap between.
Set the `bottomAnchor` of `EndOfRouteViewController` view to the bottom of `NavigationView` instead of the safeArea's bottom. Fix the `safeAreaInsets` of the `EndOfRouteViewController` view is `0` when its height needs to change.

Remove the gap between `EndOfRouteViewController` view and screen bottom.

---

CHANGELOG.md
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/StepsViewController.swift
Sources/MapboxNavigation/Style.swift

This PR is to fix #3756 to allow the leg separator view in `StepsViewController` table to be updated with style. This PR also fix the issue where the bottom padding color of `StepsViewController` is not stylable, and the issue where dragging up the table view of the  `StepsViewController` would show white color.
Because #3756 only exits in the iOS verison before 15. So before iOS15.0, we change the background color of the section header of the  `StepsViewController` to the same as the table cell , which is also the default color since iOS 15.0. And we also update the text color of the leg separator to the same as the `DistanceRemainingLabel` in the top banner.
Before iOS 15, the night mode:
After iOS 15, the night mode, which has the same width as before iOS15.
Also removed the …

Allow the leg separator view in StepsViewController updated with style.

---

CHANGELOG.md
Sources/MapboxNavigation/ImageDownloader.swift
Sources/MapboxNavigation/URLSessionDelegateProxy.swift

URLSession strongly retains its delegate.
In order to break the retain cycle, we proxy delegate calls through
URLSessionDelegateProxy.

Fix ImageDownloader memory leak

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Router.swift

Making a refresh route API call can take some time and by the time it
completes the location won't be relevant anymore. It produces a an
incorrect distance traveled calculation.

Use current location for route refresh

---

Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/NightStyle.swift

This pr is to align the road shield text color with the legacy shield color, and also to support the style change of the road shield in `WayNameView`.
Applied the legacy shield color for `Day` and `Night` style to the road shield text color, allow the color change in `WayNameView` when style changes. If no `styleManager` presented, use the `DayStyle` as default.
Day mode:
Night mode:

Support the style change of the road shield color.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewLayout.swift
Sources/MapboxNavigation/OrnamentsController.swift

This PR is to fix #3775 and to align the floatings buttons margin with the map info button during active navigation.
Update the layout of the `NavigationView` when the device orientation change instead of the `traitCollectionDidChange`. And increase the distance of the map info button to the same as the floating buttons. It could fix the issue where the map info button at the safe area margin and sometimes unclickable.
The updated `landscapeLeft` mode.
The updated `landscapeRight` mode.

Align the margin of floating buttons with map attribution button during active navigation.

---

CHANGELOG.md
Example/ViewController+StyleManager.swift
Example/ViewController.swift
MapboxNavigation-SPM.xcodeproj/project.pbxproj
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/Feedback/FeedbackViewController.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/StyleManager.swift

This pr is to fix the issue that the `FeedbackViewController` shows light theme during active navigation in Night style.

Support the style change of `FeedbackViewController` during active navigation

---

CHANGELOG.md
Sources/MapboxNavigation/MapboxSpeechSynthesizer.swift
Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift

This PR adds ability to provide custom subclasses of `SpeechSynthesizer` to be used in `MapboxSpeechSynthesizer`.

Customizing SpeechSynthesizer

---

Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/TilesetDescriptorFactory.swift

Otherwise, there will be two cache handles in our Example app:
- for driving profile
- for driving-avoiding-traffic profile.
Navigation SDK uses automobileAvoidingTraffic in most places.

Change default datasetProfileIdentifier in Navigator to match other defaults

---

CHANGELOG.md
Example/CustomViewController.swift
Sources/MapboxNavigation/InstructionsCardViewController.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/TopBannerViewController.swift

This PR is to
The `TopBannerViewController.previewInstructionsView` should conforms to `InstructionsBannerView` to match the color with top banner. And when in previewing mode and user swipe back to current step, stop previewing mode and recenter map.

Stop previewing when swipe to current banner.

---

CHANGELOG.md
Sources/MapboxNavigation/SpriteInfoCache.swift
Sources/MapboxNavigation/SpriteRepository.swift
Sources/MapboxNavigation/VisualInstructionComponent.swift
Sources/MapboxNavigation/WayNameView.swift
Tests/MapboxNavigationTests/SpriteInfoCacheTests.swift
Tests/MapboxNavigationTests/SpriteRepositoryTests.swift
Tests/MapboxNavigationTests/WayNameViewTests.swift

This Pr is to improve the functionality for the `SpriteRepository` under poor network connection.

Improve `SpriteRepository` update under poor network connection.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift

This fixes a bug that caused `RouteOptions.profileIdentifier` to be ignored in active navigation.
This happened because [`sharedNavigator` property](https://github.com/mapbox/mapbox-navigation-ios/blob/f8198e38e3e5579c22b4e46656736c0668de7180/Sources/MapboxCoreNavigation/RouteController.swift#L211) triggers Navigator singleton creation before the RouteController init is called, which [sets `profileIndentifier` to be used during the Navigator creation](https://github.com/mapbox/mapbox-navigation-ios/blob/f8198e38e3e5579c22b4e46656736c0668de7180/Sources/MapboxCoreNavigation/RouteController.swift#L557).

Add lazy initialization of Navigator.shared in RouteController

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayManager.swift

Fix crash in CarPlay while dismissing template after application was brought to the foreground after being in background.

Fix crash related to templates dismissal on CarPlay.

---

CHANGELOG.md
Sources/MapboxNavigation/SpeedLimitView.swift

The new property `SpeedLimitView.shouldShowUknownSpeedLimit` will define the speed limit view behavior if the speed limit is unknown. 
The default value is `false` which saves the old behavior – the speed limit view will be invisible if the speed limit is unknown.
Setting the new flag to `true` will cause SpeedLimitView to display `--` instead of being invisible.

Allow SpeedLimitView to display unknown speed limit values

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

PR updates dependencies to Mapbox Navigation Native `v93.0.0`.

Upgrade to MapboxNavigationNative `v93.0.0`

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Sources/MapboxCoreNavigation/RouteProgress.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayMapViewControllerDelegate.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationMapViewDelegate.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Sources/MapboxNavigation/UIColor.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Tests/MapboxNavigationTests/VanishingRouteLineTests.swift

Closing #2967.
In scope of this PR:
- Bug, which was causing inability to modify main route line and its casing when `routeLineTracksTraversal` is enabled on iOS and CarPlay was fixed.
- Delegate methods, which provide the ability to modify route line layer and its casing on CarPlay were added.
/cc @ChristianSteffens

Fix issues related to `routeLineTracksTraversal` usage and custom delegate methods for route line modification.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/HistoryRecording.swift

Resolves #3753 
This PR added instance methods to HistoryRecording protocol, deprecating static methods. Since this protocol is adopted by `RouteController` and `PassiveLocationManager`, usage of instance methods insures that `Navigator.shared` exists and history recording will be correct.

HistoryRecording instance-based methods

---

Example/ViewController.swift

This PR is to update the `Example` app by removing the `PassiveLocationManager` for active navigation. 
Because `PassiveLocationManager` shares a strong reference to an instance of `Navigator`. So when we used it for the `locationProvider` of `mapView` for previewing or passive navigation, we nil out the `NavigationMapView` to avoid its influence on the `Navigator` as in #2931. It may lead to the rerouting and simulation issues as in #2883.
And right now we have the `PassiveLocationManager` instance in `ViewController` in the `Example` app. When we start active navigation, the `NavigationMapView` for previewing is removed, but the `ViewController.passiveLocationManager` is still working while the `NavigationViewController` has no idea about it. And it would lead to the location update in …

Remove the `PassiveLocationManager ` before active navigation.

---

CHANGELOG.md
Example/CustomViewController.swift
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/CLLocationManager.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationMapView+CLLocationManagerDelegate.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationViewController.swift

`NavigationMapView` now tracks any changes to the `CLAccuracyAuthorization` and `CLAuthorizationStatus` and changes puck appearance accordingly.

Fix various edge-cases while changing `CLAccuracyAuthorization` and `CLAuthorizationStatus`. 

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayManager.swift

PR allows to show routes that are located in `RouteResponse`. This allows users to execute their own Directions requests and preview `RouteResponse` from response.

Provide the ability to preview routes that are based on a `RouteResponse` on CarPlay.

---

Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
Tests/MapboxNavigationTests/CarPlayManagerSpec.swift

SDK reported two RouteController instances. It badly influence tests
stability.

Improve tests

---

.circleci/config.yml

It appears to produce a lot of noise for no benefit.

Remove 'no breaking changes' message from pull requets

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift

PR fixes an issue when camera is not centered to the current location when `NavigationMapView` gets created. As a result long animation is executed as it's shown in https://github.com/mapbox/mapbox-navigation-ios/issues/3825.
Result of the fix:
https://user-images.githubusercontent.com/1496498/163285115-77228b05-df88-4f42-a630-cd24ade8a802.mov

Use current location from `CLLocationManager` to center camera to it.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

`routeLineFeaturesGradient` inserts a gradient stop at `lineSettings.fractionTraveled` with minimumSegment color.
Minimum segment is set to the first one (which is restricted) and never updated.
The fix is to reset the minimum segment to traversed color when it is appropriate. 
I found this method very difficult to read and understand and would propose to:
- Make logic more straightforward with less edge-case branches.
- Document the code.
- A video that demonstrates the bug: 
https://user-images.githubusercontent.com/413986/163217946-711bc2eb-a336-47ee-bcb1-852fa4cabc6e.mp4

Fixes bug where non-restricted restricted area line become restricted in an edge case.

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift

PR adds `CarPlayManagerDelegate.carPlayManager(_:shouldUpdateNotificationFor:with:in:)` and `CarPlayManagerDelegate.carPlayManager(_:shouldShowNotificationFor:in:)` methods that allow to control notifications presentation on CarPlay while application is in background.

Add notifications management delegate methods to `CarPlayManagerDelegate`.

---

CONTRIBUTING.md
Sources/MapboxCoreNavigation/TileStore.swift

This PR is to correct the iOS version of supported devices in Tests, and also remove the warning in `MapboxCoreNavigation` building on test.

Fix the tests and correct the iOS version in documentation.

---

CHANGELOG.md
Sources/MapboxNavigation/ImageCache.swift
Sources/MapboxNavigation/SpriteInfoCache.swift

This PR is to fix #3839 by making the image stored in `ImageCache`, and the `SpriteInfo` in the `SpriteInfoCache` won't be discarded when App goes into the background state.
Right now the `SpriteInfo` in the `SpriteInfoCache` and the image in the `ImageCache` are both stored in `NSCache`. And when App goes into the background, the `NSCache` will discard its memory cache. Right now we're using the `ImageCache` for the road name shield and also the top banners. The would lead to the cached image loss. 
So this Pr wrap the `UIImage` as the `ImageMemory` and make it conform to `NSDiscardableContent` and won't allowed it to be discarded, same as the `SpriteInfoWrapper`. So when the App goes to the background and then back, the cached images and `SpriteInfo` would still be available.

Fix the memory cache loss when App in the background.

---

CHANGELOG.md
Example/ViewController.swift
Sources/MapboxCoreNavigation/Feedback/EndOfRouteFeedback.swift
Sources/MapboxNavigation/ArrivalController.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift

Added a new method to `NavigationViewControllerDelegate` which is called to notify that the user submitted the end of route feedback.

Pass `EndOfRouteFeedback` to the app

---

CHANGELOG.md
Sources/MapboxNavigation/DayStyle.swift

PR fixes an issue where `EndOfRouteCommentView` is using incorrect style when dark appearance is set in iOS setting. Example of an issue:

Fix incorrect end of route comment view style.

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/BannerContainerView.swift
Sources/MapboxNavigation/BannerView.swift
Sources/MapboxNavigation/NavigationView.swift

PR adds the ability to pan, expand/collapse and have animated transitions for the `BannerContainerView` that is used as top and bottom banner in `NavigationView`. Example:
https://user-images.githubusercontent.com/1496498/165241531-cdd084a0-f23e-46cc-8bef-acfb9b60d083.mov

Add presentation transitions to `NavigationView` top and bottom banners.

---

CHANGELOG.md
Sources/MapboxNavigation/InstructionPresenter.swift
Sources/MapboxNavigation/WayNameView.swift

This Pr is to fix #3868, to allow the U.S. state route shields using the legacy icon first, then fall back to the Mapbox designed shield.
In road name label, because we ask to update the `SpriteRepository.updateRepresentation(for:completion:)` first to prepare both the Mapbox designed shield and legacy icons already. We could directly check the `shield.name` to make a choice.
In `InstructionLabel`, we're using the singleton of `SpriteRepository` since #3864 , the Mapbox designed shield could be ready to use while the legacy icon hasn't been downloaded yet. 
So for the `circle-white` road, we check whether we have the legacy icon ready to use, if we have, we use it first. Then if the legacy icon isn't ready to use, we check whether it's a U.S. state road. If it's a U.S. state road, the …

Use legacy fallback icon for U.S. state road shields first.

---

CHANGELOG.md
Sources/MapboxNavigation/LanesView.swift
Sources/MapboxNavigation/TopBannerViewController.swift

This PR fixes a bug where a transparent gap would display between the `TopBannerViewController` and `StepsTable` when instructions are updated while `StepsTable` is displayed.
Added `TopBannerViewController.currentInstruction` and `LanesView.isTopBannerDisplayingSteps` properties to be able to update `LanesView` to the current instruction when the `StepsTable` is hidden and only show the `LanesView` when the `StepsTable` is not being displayed.
Before vs After:
https://user-images.githubusercontent.com/43434254/162985983-edb7c4e1-6ca3-44a3-b509-f92920553abe.mp4
https://user-images.githubusercontent.com/43434254/162986000-722731cd-64da-4130-a616-81ace20b313d.mp4

Fix bug where transparent `LanesView` displays on update when `StepsTable` is displayed

---

CHANGELOG.md
Sources/MapboxCoreNavigation/PassiveLocationManager.swift

The value of `datasetProfileIdentifier` argument was ignored in `PassiveLocationManager` constructor as `sharedNavigator: Navigator` was created before `Navigator.datasetProfileIdentifier` is set.

Fix datasetProfileIdentifier in PassiveLocationManager constructor

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/RestStop.swift
Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Upgraded to MapboxDirections v2.5.0-beta.1. Technically, we don’t need to increase the minimum version yet, but it’ll unblock https://github.com/mapbox/mapbox-navigation-ios/pull/3869#issuecomment-1119876430. In the meantime, it’ll allow us to get some testing on mapbox/mapbox-directions-swift#669 and monitor its performance.

MapboxDirections v2.5.0-beta.1

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift

This PR fixes an issue that occurs when using CarPlay and actively navigating with more than one route leg.
Closing #3876.

Fix memory leak which occurred after presenting intermediate waypoint arrival dialog on CarPlay.

---

Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift

Resolves #3872 
Fixes some unit tests flakiness.
Modified tests log reroutes happening which are not expected. This PR disables rerouting during these tests. This is more like a symptomatic solution, we should investigate why Navigator decides to do a reroute there.

Unit tests fix

---

CHANGELOG.md
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift

This PR adds functionality to stop active navigation session without dismissing relate UI and components.
Implementation uses similar logic as on `RouteController.deinit`. It stops active billing session, unsubscribes from navigator updates and blocks any user API calls, related to updating or changing the route.

Stop navigation without dismissing UI

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Tests/MapboxNavigationTests/VanishingRouteLineTests.swift

This PR is to fix the possible crash of the `routeRemainingDistancesIndex` when it's `-1` after rerouting.
Instead of the comparison of `endIndex`, using `Array.indices.contains()` check to prevent the crash.

Fix the crash of `routeRemainingDistancesIndex` after reroute.

---

Sources/MapboxCoreNavigation/RouteController.swift

When setting a route to Navigator, we should use the correct credentials to parse it.
Replaced usage of a newly created Directions instance which uses credentials from a plist with credentials existing in incoming `indexedRouteResponse` which may be configured differently. Thus maintained credentials consistency in the SDK components.

Route response parsing credentials fix

---

CHANGELOG.md
Sources/MapboxNavigation/LanesView.swift

PR removes hiding lanes view when all of the suggested lanes are valid for the current route. This is done for parity with Android and for additional user info since it may still matter and affect lane selection to avoid slow left/right turning lanes on the way
Replaced filtering check with a sanity check that at least 1 of the proposed lanes is valid.

Lanes view filtering

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Tests/MapboxNavigationTests/VanishingRouteLineTests.swift

Cherry-pick for this fix: #3896

Cherry-pick - Fix the crash of `routeRemainingDistancesIndex` after reroute. (#3896)

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

PR adds the ability to place main route line below custom `MapboxMaps.LayerPosition` in `NavigationMapView.show(_:layerPosition:legIndex:)`. If such parameter is not provided `MapView.mainRouteLineParentLayerIdentifier` is used by default as a parent layer for the main route layer.
```swift
let layerPosition: MapboxMaps.LayerPosition? = .above("settlement-major-label")
NavigationMapView.show(routes, layerPosition: layerPosition)
```
```swift
let layerPosition: MapboxMaps.LayerPosition? = .below("settlement-major-label")
NavigationMapView.show(routes, layerPosition: layerPosition)
```

Add the ability to show route line layers based on the custom layer position.

---

CHANGELOG.md
Sources/MapboxNavigation/ExitView.swift
Sources/MapboxNavigation/GenericRouteShield.swift
Sources/MapboxNavigation/InstructionPresenter.swift

This PR is to fix the nonstop call of `SpriteRepository.updateRepresentation(for:completion:) ` when the instruction contains a road with no shield or legacy shield information in `VisualInstruction.Component.ImageRepresentation`.
Update the `SpriteRepository` with the `ImageRepresentation` only when it has valid shield or legacy shield, otherwise, keep using generic shields or plain string without downstream downloading.

Fix the crash of non-stop shield update in instruction guidance.

---

MapboxNavigation.podspec
Tests/CocoaPodsTest/PodInstall/Podfile.lock

For parity reasons between SPM and CocoaPods, we should not lock the Maps SDK version to be exact `10.5.0`.

Fix Maps SDK dependency in podspec

---

CHANGELOG.md
Example/ViewController+StyleManager.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/InstructionLabel.swift
Sources/MapboxNavigation/VisualInstruction.swift

- PR implements the ability to track changes to `Always show dark maps` option as it was described in https://github.com/mapbox/mapbox-navigation-ios/issues/3879.
- PR fixes an issue when shield icons become invisible when users drive through the tunnel. Fixes https://github.com/mapbox/mapbox-navigation-ios/issues/3878.

Allow `Always show dark maps` option on CarPlay.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/SimulatedLocationManager.swift

When SimulatedLocationManager is used and user is rerouted with alternative route, the location manager would simulate the route from the origin, which for alternatives case does not match current simulated location. This PR modifies detection logic to find the closest coordinate to continue simulating.
Before the fix:
Notice user puck is pushed backward to the alternative origin when switched.
After: 
Notice puck pushed back just a bit when switching.

Simulation Rerouting fix

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift

When a faster route is found an applied, we should skip the first voice instruction because it will be a duplicate of what was already announced by the original route.
Added a flag to skip first instruction after a proactive reroute.

Suppress departure instruction after proactive reroute

---

CHANGELOG.md
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/RouteController.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift

Fixes #3924.
PR allows to pause and resume navigator when using `RouteController` to prevent any issues with continuous status updates.
https://user-images.githubusercontent.com/1496498/171311510-52c0ae41-e5b8-489e-8b93-4d3906ccb641.mov

Pause and resume navigator when using `RouteController`.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift

Adds re-using existing line layers instead of re-creating it each time. This resolves incorrect layers ordering issue because creation mechanism ignored existing layers and thus messing up it's order. 
Added flag to try to use existing line layer instead of forcing creating new ones. This comes useful when there are both Main and Alternative routes display, but only 1 of them is updated, for example due to route refreshing. When updating Main route (via `show(routes:)`), SDK removes old layers, keeping the alternatives and vice versa. In result some of the layers persist, while other created anew, introducing incorrect layer ordering.

Route line layers reusing

---

Sources/MapboxCoreNavigation/AlternativeRoute.swift
Sources/MapboxCoreNavigation/RerouteController.swift
Sources/MapboxCoreNavigation/RerouteControllerDelegate.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift

Adds route origin value to be passed to NavNative. This value is used then inside Navigator for various checks and heuristics, thus improving the navigation quality. This PR does not introduce or fixes any features, but this is the expected way to set Routes to Navigator, specifying it's correct origin.
Added internal value which is passed when parsing a route response to set to Navigator. Whenever route is reported by NN and we know it's origin - we specify it, in all other cases we consider route to be custom built.
I don't think there should be a changelog entry since this change is obscure and does not result in visible changes.

Route Origin handling

---

CHANGELOG.md
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/Feedback/FeedbackSubtypeCollectionViewCell.swift
Sources/MapboxNavigation/Feedback/FeedbackSubtypeViewController.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/StyleManager.swift

This Pr is to allow the detailed feedback style change. And it also fixed the issue where the popped window on phone won't get appearance refreshed when style changes.
In `FeedbackSubtypeViewController`, by changing the report container to `FeedbackStyleView`, it would share the same style change as the `FeedbackViewController`.
In `FeedbackSubtypeCollectionViewCell`, by adding the stylable color at select and normal state, it would allow the circle color change in different styles.
Because the `reloadData()` after the style change in `UICollectionView` will cause the selection loss. To keep the selected color and the selection function, using the `selectedPath` to store the `indexPath` for style change and selection loss.

Allow the detailed feedback style change.

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/HandlerFactory.swift
Sources/MapboxCoreNavigation/HistoryRecorder.swift
Sources/MapboxCoreNavigation/HistoryRecording.swift
Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Tests/MapboxCoreNavigationTests/NativeHandlersFactoryTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift

vk-history-recorder: added HistoryRecorder; untied Navigation and His……toryRecorderHandler; Updated relative parts and tests to use new handler
`HistoryRecorderHandle` is aggregated by `Navigator` singleton instance so that it is not possible to control history recording without instantiating it, which leads to problems when we want to record every event, starting Navigator initialization. This PR separates `HistoryRecorderHandle` and `Navigator` lifecycles.
Introducing `HistoryRecorder` to cache and manage the `HistoryRecorderHandle` and ensure the shared instance is available on time and used by all consumers.

History Recorder

---

Sources/MapboxCoreNavigation/HistoryRecording.swift

Swapped deprecation marks for `HistoryRecording` extension methods between static and instance methods.

HistoryRecording extension methods deprecation

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift

Hide user course view in case if current user location coordinate point is invalid.

---

Example/Info.plist
MapboxCoreNavigation.podspec
MapboxNavigation.podspec
README.md
Sources/CarPlayTestHelper/Info.plist
Sources/MapboxCoreNavigation/Info.plist
Sources/MapboxCoreNavigation/MBXInfo.plist
Sources/MapboxNavigation/Info.plist
Sources/MapboxNavigation/MBXInfo.plist
Sources/TestHelper/Info.plist
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/Info.plist
Tests/MapboxNavigationTests/Info.plist
custom-navigation.md

Update Mapbox Navigation to `v2.7.0-alpha.1`.
Current PR should be only merged after landing https://github.com/mapbox/mapbox-navigation-ios/pull/3978.

Mapbox Navigation `v2.7.0-alpha.1`.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Sources/MapboxCoreNavigation/NavigationSettings.swift
Sources/MapboxCoreNavigation/RerouteController.swift

Adds a setting to `NavigationSettings` expose toggling sensors data usage by Navigator.
Also fixes `RerouteController` using a correct config handle for updating avoidance radius, since after Navigator initialization, `NavigaotrConfig` does not affect it's settings while `ConfigHandle` does.
Since this setting cannot be updated during Navigator lifetime, it has to be configured before actual navigation, for what we have `NavigationSettings`.

Exposing sensor data usage toggle

---

MapboxNavigationTests/MapboxNavigationTests.swift

PR removes deprecated methods usage in `MapboxNavigationTests`.

Stop using deprecated methods from Maps SDK in snapshot tests.

---

Sources/MapboxNavigation/CarPlayManager.swift

This PR is to pause the update from `PassiveLocationManager` for free drive in CarPlay after the active navigation session starts.  Because even the trip session is paused, it still provides updates in CarPlay.

Pause the update of free drive in CarPlay after active navigation session starts

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Tests/MapboxNavigationTests/VanishingRouteLineTests.swift

This Pr is to support using the `lineLayer.line-trim-offset` to update the route line when `routeLineTracksTraversal` is enabled during active navigation. 
in `Example` App, switch the route line property during active navigation with `Resume` button.
switch `navigationMapView.crossfadesCongestionSegments` when `routeLineTracksTraversal` enabled.
switch `navigationMapView.showsRestrictedAreasOnRoute` when `routeLineTracksTraversal` enabled with mock restricted area.
switch `routeLineTracksTraversal` in active navigation

Use `line-trim-offset` to replace the line gradient stops for route line update.

---

CHANGELOG.md
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/ResumeButton.swift

Provide the ability to modify `ResumeButton`s `borderWidth`, `cornerRadius` and `borderColor` properties.
Closing https://github.com/mapbox/mapbox-navigation-ios/issues/2107.

Provide the ability to modify certain `ResumeButton` properties.

---

Example/ViewController.swift
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
Sources/MapboxNavigation/BannerContainerView.swift
Sources/MapboxNavigation/BannerContainerViewDelegate.swift
Sources/MapboxNavigation/BannerView.swift
Sources/MapboxNavigation/BottomBannerViewController.swift
Sources/MapboxNavigation/BottomBannerViewControllerDelegate.swift
Sources/MapboxNavigation/BottomBannerViewControllerLayout.swift
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewLayout.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/TopBannerViewController.swift
Sources/MapboxNavigation/UIViewController.swift
Tests/MapboxNavigationTests/BottomBannerSnapshotTests.swift
Tests/MapboxNavigationTests/InstructionsCardSnapshotTests.swift
Tests/MapboxNavigationTests/InstructionsCardViewControllerTests.swift
Tests/MapboxNavigationTests/XCTestCase.swift

PR brings several public API changes to banner container views presentation (and other related UI elements). Some of them include:
- `BannerContainerView.state` property that allows to check whether banner is either expanded or collapsed.
- `BannerContainerView.show(animated:duration:animations:completion:)` method that allows to fully present banner container.
- `BannerContainerView.hide(animated:duration:animations:completion:)` that allows to fully hide banner container.
- `BannerContainerViewDelegate` allows to get callbacks about state changes and fraction of expansion. Possibly will be extended in future to contain more useful methods.
- `NavigationView.wayNameView`, `NavigationView.topBannerContainerView`, `NavigationView.bottomBannerContainerView` and …

Add expansion/collapsing and animated presentation APIs for banner containers.

---

Sources/MapboxNavigation/DayStyle.swift

Use dark status bar appearance on iOS 13 and higher when using `DayStyle`.

Fix status bar appearance.

---

CHANGELOG.md
Sources/MapboxNavigation/SpriteRepository.swift

This PR is to reduce the memory loss of the Sprite. 
Previously, when the Sprite image or metadata not ready to use, the Sprite cache will be cleared.  Because the Sprite only depends on style, this PR is to reduce the memory loss by only allowing style change to clear the Sprite cache.

Only clear Sprite cache when style changes.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Router.swift

Only set the initial maneuver avoidance radius when driving; avoid setting it with the cycling and walking profiles, which don’t support the `avoid_maneuver_radius` query parameter yet.
Fixes #3966.
/cc @mandeepsandhu

Only set initial maneuver avoidance radius when driving

---

CHANGELOG.md
MapboxNavigation-SPM.xcodeproj/project.pbxproj
NavigationViewExample/AppDelegate.swift
NavigationViewExample/Base.lproj/LaunchScreen.storyboard
NavigationViewExample/Base.lproj/Main.storyboard
NavigationViewExample/Info.plist
NavigationViewExample/SceneDelegate.swift
NavigationViewExample/Transitions/DismissalAnimator.swift
NavigationViewExample/Transitions/PresentationAnimator.swift
NavigationViewExample/ViewController.swift
Sources/MapboxNavigation/CameraController.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewDelegate.swift

- Added presentation and dismissal transitions for `NavigationViewController` (application side).
- Added `NavigationViewExample` that showcases transitions.
- Added the ability to inject `NavigationMapView` to `NavigationViewController` without blinking effects (requires change in public API).
Example:
https://user-images.githubusercontent.com/1496498/180327408-78c141d7-730a-422d-822d-376beac5e931.mov

Add custom `NavigationViewController` transitions.

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/RouteLineController.swift

This Pr is to fix #4035 by removing arrow when the route line is removed after arrival.

Remove arrow if the route line is removed after arrival

---

CHANGELOG.md
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/RouteController.swift

When the device doesn't provide location updates (simulator, bad network, tunnels), NavigationNative's simulation kicks in. This resolves in situations when the raw location from the device may be outdated, while matched location is usable. Since UI is updated based on the location (puck, route line) we should keep the other info updated.
Fixes #4042. 
This PR changes the location used to calculate `RouteProgress`'s `distanceTraveled`, `distanceRemaining`, `durationRemaining`, `fractionTraveled` properties from raw to matched one. This could potentially affect some subsystems using `RouteProgress`.

Use matched location from NN to calculate RouteProgress.distanceTraveled

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/CLLocationCoordinate2D.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxNavigation/BuildingHighlighting.swift
Sources/MapboxNavigation/CGPoint.swift
Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

This PR is to fix the building highlighting issues.

Fix the building highlighting loss after out of map boundary and rerouting

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Incident.swift

Some `Incident` properties were not filled when received in `RoadObject` via electronic horizon.
This PR sets the corresponding properties during the construction of the `Incident` object.
`countryCodeAlpha3`, `countryCode`, `roadIsClosed`, `longDescription`, `numberOfBlockedLanes`, `congestionLevel`, and `affectedRoadNames` properties were filled.
There are also `lanesClearDesc` and `openLR` properties that don't have a pair in the `Incident` object and its Directions API counterpart.

Fill Incident properties from IncidentInfo

---

CHANGELOG.md
Sources/MapboxCoreNavigation/SimulatedLocationManager.swift

Engaging route simulation by `inTunnels` or `onPoorGPS` may jump the user puck to the beginning of the route. This PR fixes the issue.
Added skipping the traversed distance of the shape when simulation is starting.

Simulation teleport fix

---

.circleci/config.yml

Temporarily disable tests that are based on Metal renderer and `MapboxNavigationTestHost` application.

Disable Metal based tests.

---

Example/ViewController.swift

This PR fixes #4023 by adding three new actions to the gear button in the Example application to switch the routing profile between `.automobileAvoidingTraffic`, `.cycling`, and `.walking`. Users can switch the routing profile before or after a long press.
https://user-images.githubusercontent.com/43434254/183699638-da58775e-8c34-4f97-be2b-22a4a67c2f56.mp4

Add routing profile switcher to example application

---

CHANGELOG.md
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/RouteOptions.swift

We found that `otherNavigation` activity type produces better GPS data in comparison to `automotiveNavigation` we used previously, with just marginally bigger battery consumptions. So we've decided to update the default value and expose a clear path for customizing it by anyone who still prefers `automotiveNavigation` or any other type.
Exposed `RouteOptions.activityType` `open`; changed default value to `otherNavigation`

RouteOptions activityType

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewportDataSource.swift

This Pr is to fix the overlooking issue when approaching complex intersections and the user location indicator may be out of view frame.
When approaching complex intersections, we have the `GeometryFramingAfterManeuver` to provide the distance to extend current camera view.
- After current step, if the next step distance is smaller than `GeometryFramingAfterManeuver.distanceToFrameAfterManeuver`, the next step will be included. Other wise, the trimmed next step within the `distanceToFrameAfterManeuver` will be included. And further following steps won't be included.
- After next step, if the total distance included is smaller than the `GeometryFramingAfterManeuver.distanceToCoalesceCompoundManeuvers`, the whole step or the trimmed step will be included until the total distance reach the …

Constraint the following distance after current maneuver for camera.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Sources/MapboxCoreNavigation/NavigationSettings.swift

Due to discrete location updates, Navigator always operates data "in the past" so it has to make prediction about user's current real position. NN allows to configure this interval at initialization, so we expose it to users. 
Added `NavigationSettings.navigatorPredictionInterval` to configure Navigator at init.

Navigation prediction interval

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Example/CustomViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationMapView+ContinuousAlternatives.swift
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/RouteLineController.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

This Pr is to fix the issue of route line layer position issue after rerouting. 
1. When finding the topmost non-symbol layer for route line, explicit check whether the layer is the `label` layer .  During style loading, some `label` layers exist above symbol layers, such as `poi label copy` as a `circle layer` but above the symbol layer of `poi label`. So it will cause the `NavigationMapView.layerPosition(for:route:customLayerPosition:)` found the wrong topmost non-symbol layer, especially for route line.
2. When adding casing layer and alternative route layer, check whether the parent layer added to the style already.
3. When adding route line layers, remove all the continuous alternative route layers first.
4. Added test for the custom layer position of route line and the non-symbol …

Fix the route line layer position issue after rerouting.

---

Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift
Sources/MapboxCoreNavigation/NavigationService.swift

SDK generated departure events after arriving at each waypoint which is excessive for the final waypoint.
Since it's not a user-facing change I guess we don't need a CHANGELOG entry?
This PR adds a check to detect arriving at different waypoints.

Duplicate departure events fix

---

Sources/MapboxNavigation/Feedback/FeedbackSubtypeViewController.swift
Sources/MapboxNavigation/NSAttributedString.swift
Sources/MapboxNavigation/UIView.swift

The minimum deployment target for MapboxNavigation and the Example application is iOS 11.0, so there’s no longer any need to guard for iOS 11 API availability.

Remove redundant iOS 11 availability macros

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/IncidentsOptions.swift
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Sources/MapboxCoreNavigation/NavigationSettings.swift

We need to expose public configuration for Navigator's incidents options. This is required by customers and Android already has such ability.
Added NavigationSettings.liveIncidentsOptions and forwarded this configuration to NavigatorConfig.

Incidents Options exposing

---

Sources/MapboxCoreNavigation/RouteController.swift

#4034 introduced the mapping of `targetCoordinate` in `RouteController` after rerouting event to fix the failure of building highlighting issue due to the loss of `targetCoordinate` after rerouting event. But the dependency upgrade of #4085 fixed the loss of `targetCoordinate` from root. So this PR is to remove the previously introduced fix in SDK side.

Remove the targetCoordinates mapping after reroute with the dependency upgrade

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewportDataSource.swift

PR fixes an issue where navigation viewport padding was always set to `.zero` during free-drive navigation.

Use `MapView.safeAreaInsets` as a viewport padding in free-drive navigation.

---

.circleci/config.yml

This workflow will be used by the Release train app in the **Update version** stage.
**update-version-workflow** runs the **scripts/update-version.sh** script. It's necessary to execute this script on the Circle CI because the Release train app instance running on the Linux machine and the script needs MacOS.
You can read more about this step in the Release train app doc.

Add the update version workflow

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift
Sources/MapboxNavigation/Route.swift
Sources/MapboxNavigation/RouteLineType.swift
Tests/MapboxNavigationTests/RouteLineLayerPositionTests.swift

This Pr is to fix #4105 by adding a traversed route line layer below main route casing layer with `traversedRouteColor`, to support the color customization for the traversed part of main route line. 
When `routeLineTracksTraversal` is on, add a traversed route line layer below main route casing layer, but above the alternative route layer. The traversed layer should have the same source and width as the main route casing layer, with it's color as `traversedRouteColor`.
So when the user location is updated, the main route line and route casing layer are both updated and trimmed, the below traversed layer will show up. By default, it would be transparent. But the customer could change the `NavigationMapView.traversedRouteColor` to show the traversed part with the designed color.
when we …

Add traversed route line layer to customize `traversedRouteColor`

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewLayout.swift
Sources/MapboxNavigation/OrnamentsController.swift

Closing #4117.
PR fixes crash that sometimes occurs when orientation of the view controller that contains `NavigationView` is being changed and `NavigationView`'s parent view is being deallocated at the same time.

Fix crash that occurs while rotating device and applying `NavigationView` constraints at the same time.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
Sources/MapboxCoreNavigation/NavigationSettings.swift

Some use-cases require customizing `NN.PollingConfig`. That is also configurable on Android.
Exposed `StatusPollingConfig` through `NavigationSettings` to provide configuration.

Status polling config

---

Sources/MapboxNavigation/NavigationMapView.swift
Tests/MapboxNavigationTests/RouteLineLayerPositionTests.swift

#4084 introduced the check for circle layer when adding route line without custom layer position. But when no custom `circlePitchAlignment` property set for circle layer, the property will be `nil` and take the `viewport` as the pitch alignment for labeling.
This PR is to update the check from #4084 of the `pitchAlignment == "viewport"` to `pitchAlignment != "map"`. Because when circle layer has `circlePitchAlignment = nil` value, it will default choose the `viewport` for pitch alignment for label, such as the waypoint circle layer added in `NavigationMapView`. So the route line should skip this circle layer as well.

Update the check for `circleLayer` for default route line position

---

MapboxNavigation-SPM.xcodeproj/project.pbxproj
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/MapboxNavigationTestHost.xcscheme
NavigationViewExample/Assets.xcassets/AccentColor.colorset/Contents.json
NavigationViewExample/Assets.xcassets/AppIcon.appiconset/Contents.json
NavigationViewExample/Assets.xcassets/Contents.json
Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift

PR fixes Xcode 14 related warnings.

Fix Xcode 14 warnings.

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/DefaultRerouteControllerInterface.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
Sources/MapboxCoreNavigation/RerouteController.swift
Sources/MapboxCoreNavigation/RerouteControllerDelegate.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RouterDelegate.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Sources/TestHelper/NavigationServiceTestDoubles.swift
Sources/TestHelper/RouterDelegateSpy.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

Resolves #4032 
Adding possibility to modify route options on each reroute. This does not cover proactive reroute since it's idea is to find "same but faster" route, at which point it will loose it's purpose if we modify route search criteria (a.k.a. RouteOptions). It also does not cover custom routing provider use case since it is already covering that step.
Added default reroute controller interface wrapper to chime in route options customization.  Reworked controller setup accordingly. Added delegate methods to forward the change. Unit tests updated

RouteOptions customization on reroute

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift

Make `NavigationMapView.removeAlternativeRoutes()` and `NavigationMapView.removeContinuousAlternativeRoutesDurations()` public.
Both methods are useful when removing specific parts of currently presented routes and annotations.

Make `NavigationMapView.removeAlternativeRoutes()` and `NavigationMapView.removeContinuousAlternativeRoutesDurations()` public.

---

CHANGELOG.md
Example/ViewController.swift
Sources/MapboxNavigation/CameraController.swift
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/FloatingButton.swift
Sources/MapboxNavigation/InstructionsCardViewController.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewController.swift
Sources/MapboxNavigation/NightStyle.swift
Sources/MapboxNavigation/OrnamentsController.swift
Sources/MapboxNavigation/ReportButton.swift
Sources/MapboxNavigation/Style.swift
Sources/MapboxNavigation/UIImage.swift
Sources/MapboxNavigation/UIView.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

- Remove shadow that is applied to `FloatingButton` to be aligned with other stylable views and to improve performance (shadow usage leads to such warning: `The layer is using dynamic shadows which are expensive to render. If possible try setting 'shadowPath', or pre-rendering the shadow into an image and putting it under the layer.`).
- Add the ability apply `type` and `cornerRadius` while creating `FloatingButton`.

Improve `FloatingButton` styling.

---

CHANGELOG.md
Sources/MapboxNavigation/ImageDownloader.swift
Sources/MapboxNavigation/InstructionPresenter.swift
Sources/MapboxNavigation/SpriteRepository.swift
Sources/MapboxNavigation/TopBannerViewController.swift
Sources/MapboxNavigation/WayNameLabel.swift
Tests/MapboxNavigationTests/SpriteRepositoryTests.swift

This PR is to fix #4141 to support the shields in offline navigation.
Add the time out constraint to shields request, and the error handling in  `InstructionPresenter` to avoid the nonstop shield request if it has an error. Use generic shields for offline navigation.
When switching from offline mode to online mode, the preview process by swiping top banner or opening `StepsViewController` will both trigger the downloading process of shields. And it will replace the generic shields with Mapbox designed shields or legacy shields. 
Build a route from San Francisco to San Diego, turn off the network connection, start with simulation and open the `StepsViewController` for preview. The shields in the guidance instruction will be generic shields.
Turn on the network and open the …

Support the offline mode for shields in navigation

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/VisualInstruction.swift

This PR is to fix #3977 by replacing `CPManeuver.symbolSet` with `CPManeuver. symbolImage` to generate maneuver for CarPlay during active navigation.
This Pr add the public API `VisualInstruction.maneuverImage(side:userInterfaceStyle:)` to replace the `VisualInstruction.maneuverImageSet(side:)` for iOS 13 and above.  It will generate the maneuver image for CarPlay during active navigation.

Replace symbolSet with symbolImage in CarPlay maneuver.

---

CHANGELOG.md
Example/ViewController.swift
Sources/MapboxNavigation/NavigationMapView.swift

This PR is to fix #3847 by adding the ability for users to detect the taps on duration annotations for routes and continuous alternative routes.
When users tapped the `NavigationMapView`, the `NavigationMapView` will check whether duration annotations for routes and continuous alternative routes have been tapped. If users tapped duration annotations, it will notify the `NavigationMapViewDelegate.navigationMapView(_: didTap:)` about the taps. If not, it will check the taps on Waypoints, the closest route and the closest continuous alternative route.
The `NavigationMapViewDelegate.navigationMapView(_: didTap:)` provides the route or continuous alternative route whose duration annotation has been tapped.

Add delegate methods for tapping route duration.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/MapboxNavigation/CarPlayManager.swift

Backported a small part of #4127 to the release-v2.8 branch to fix #4126, which is a regression introduced in #3824.
If the current route response contains a MatchOptions, convert it to a RouteOptions before attempting to update the navigator with it instead of reporting an internal error or, in CarPlay, tripping a precondition failure.

Convert MatchOptions to RouteOptions on the fly

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewController.swift

This PR fixes #2223 by defaulting to night style for NavigationViewController regardless of the time of day and switching to between day/night styles whenever light/dark mode is enabled.

Switch to night style when Dark Mode is enabled

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Directions+RoutingProvider.swift
Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RouteLegProgress.swift
Sources/MapboxCoreNavigation/RouteProgress.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/MapboxCoreNavigation/RoutingProvider.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Tests/MapboxCoreNavigationTests/RouteProgressTests.swift

Covers integrating `current_route_geometry_index` Route Refresh API parameter.
Depends on https://github.com/mapbox/mapbox-directions-swift/pull/733

Add shape index parameter to route refresh

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/NavigationViewController.swift
Tests/MapboxNavigationTests/NavigationViewControllerTests.swift

This Pr is to fix the issue that when two continuous active navigation using different styles, the exit views in the second session may be invisible.
https://github.com/mapbox/mapbox-navigation-ios/pull/3930 introduced the function to record the platform related style.
If there're two active active navigation sessions, If the second active navigation session is using the customized `NavigationMapView` in its `NavigationOptions` which has the same style as in the `NavigationOptions` , and hasn't change its style from the start, the shields may use the style from the previous active navigation session on current platform.  It would lead to the invisible Exit Views on the instruction label of the second active navigation session. 
The root cause is that we only update the shield when the …

Fix the issue of invisible exit views from night mode to day mode.

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RouteLegProgress.swift
Sources/MapboxCoreNavigation/RouteProgress.swift
Sources/MapboxCoreNavigation/RouteStepProgress.swift

This Pr is to fix the issue that after route refresh, the step intersections related properties will be set to default values. This Pr is to update the step intersections related properties with the updated location.
- Move the `RouteController.updateDistanceToIntersection(from:)` and `RouteController.updateIntersectionDistances()` to `RouteProgress`, and call them after the route refresh event.
- Also call the  `RouteProgress.updateIntersectionIndex()` in route refresh event to update the `RouteStepProgress.intersectionIndex`. Because it's updated by navigator status.

Fix the intersections property loss after route refresh.

---

MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/NavigationViewExample.xcscheme
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/PreviewViewControllerExample.xcscheme

Add schemes for examples that allow to test preview mode implementation that landed in https://github.com/mapbox/mapbox-navigation-ios/pull/4189 and https://github.com/mapbox/mapbox-navigation-ios/pull/4188.

Add schemes for `PreviewViewController` and `NavigationViewExample`.

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView.swift

Fixed an issue where the `NavigationMapView.localizeLabels()` method only localized map labels according to the user’s Preferred Language Order setting if the application also had a localization in the preferred language. The application’s UI language is irrelevant to whether the map should be localized into a language that the user says they prefer.
This change won’t be a problem for backwards compatibility: the method’s documentation comment says it honors the preference and doesn’t mention anything about the preference being constrained to the application bundle’s languages.
Fixes #4190.

Localize map labels into user-preferred languages

---

Sources/MapboxCoreNavigation/PassiveNavigationEventDetails.swift

Fixes a bug introduced in 2.9.0-alpha.3 after migration from MME to CoreTelemetry, that caused passive navigation feedback events to be discarded by server API since the event payload didn't contain the "created" field. 
This wasn't a problem before because MME used to add this field on their own.
Probably we don't need a changelog entry for this since this bug didn't exist in 2.8.0.

Add "created" field to passive navigation feedback events

---

.tx/config
Sources/MapboxNavigation/Resources/es-ES.lproj/Localizable.stringsdict
Sources/MapboxNavigation/Resources/es.lproj/Localizable.stringsdict
Sources/MapboxNavigation/Resources/fr.lproj/Localizable.stringsdict
Sources/MapboxNavigation/Resources/vi.lproj/Localizable.strings

[Migrated](https://developers.transifex.com/docs/migrating-from-older-versions-of-the-client) to Transifex’s v3 API and new Go-based `tx` client. Updated a few minor translations.
Fixes #4052.

Migrate to Transifex API v3

---

Sources/MapboxNavigation/Route.swift

Fixes the error in the Route extension
> Thread 1: Fatal error: Range requires lowerBound <= upperBound
Error was introduced in #4217 
[dropFirst()](https://developer.apple.com/documentation/swift/string/dropfirst(_:)) returns empty array if array is empty and has the same time complexity `O(1)` as [suffix(from:)](https://developer.apple.com/documentation/swift/array/suffix(from:)) for Arrays

Fix VanishingRouteLineTests

---

docs/jazzy.yml

Fixes failing docs generation.
There are no docs comments for the following classes/enums, some of them marked as `:nodoc:`, some just lack docs.
Docs comments for these classes/enums should be added separately if they are needed. This pill request simply excludes non-generated docs from Contents

Do not generate docs for undocumented classes/enums

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Router.swift

There is a potential race condition in case if rerouting and route refreshing events are happening at the same time.
It is potentially possible that when applying route refresh, it may select incorrect route index, if refreshing route had non 0 index or even restore the previous route. This PR preserves and checks that route was not updated during the refresh.

Crash fix during reroute and refresh

---

CHANGELOG.md

This Pr is to update the changeLog, move the entry of #4230 to `main` instead of `v2.9.0`.

Update the ChangeLog.

---

.swiftlint.yml
MapboxNavigation.xcodeproj/project.pbxproj
MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigationIntegrationTests.xcscheme
Package.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/TestHelper/CoreNavigatorSpy.swift
Sources/TestHelper/Fixture.swift
Sources/TestHelper/NavNative/NativeNavigatorSpy.swift
Sources/TestHelper/NavNative/RouteParserSpy.swift
Sources/TestHelper/NavNative/TestNavigationStatusProvider.swift
Sources/TestHelper/NavNative/TestRouteProvider.swift
Sources/TestHelper/RerouteControllerSpy.swift
Sources/TestHelper/RoutingProviderSpy.swift
Tests/MapboxCoreNavigationIntegrationTests/Info.plist
Tests/MapboxCoreNavigationIntegrationTests/MapboxCoreNavigationIntegrationTests.swift
Tests/MapboxCoreNavigationIntegrationTests/PassiveLocationManagerIntegrationTests.swift
Tests/MapboxCoreNavigationIntegrationTests/RouteControllerIntegrationTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
Tests/MapboxCoreNavigationTests/RerouteControllerTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Tests/MapboxCoreNavigationTests/RoutesCoordinatorTests.swift
codecov.yml

Adds unit tests for RouteController. 
The old tests that depended on NavNative were replaced by new test using mocked dependencies.

Use mocks in RouteControllerTests

---

.circleci/config.yml

**distribute-version-workflow** will be triggered by creating the `trigger-distribute-version-$RELEASE_VERSION` branch from the release branch by the Release train app.
Credentials for the commands in the workflow are stored in the Circle CI.

Release distibution automation

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/SpriteRepository.swift
Tests/MapboxNavigationTests/Helper/BimodalImageCacheSpy.swift
Tests/MapboxNavigationTests/Helper/ReentrantImageDownloaderSpy.swift
Tests/MapboxNavigationTests/Helper/URLCacheSpy.swift
Tests/MapboxNavigationTests/SpriteRepositoryTests.swift
Tests/MapboxNavigationTests/WayNameViewTests.swift

Uses spies instead of real cache and image loader in repository.
Fixes fails like [this one](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/10188/workflows/788164c2-000c-40e2-b769-5ef4b24bd088/jobs/95044)

Fix flaky SpriteRepositoryTests

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
Sources/TestHelper/Fixtures/DCA-Arboretum-dummy-faster-route.json
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift

This Pr is to update the dependency to Maps v10.10.0-rc.1, NavNative v122.0.0, Common v23.2.0-rc.3

Update to Maps v10.10.0-rc.1, NavNative 122.0.0, Common v23.2.0-rc.3

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxNavigation/MapboxSpeechSynthesizer.swift
Sources/MapboxNavigation/MultiplexedSpeechSynthesizer.swift
Tests/MapboxNavigationTests/MultiplexedSpeechSynthesizerTests.swift
Tests/MapboxNavigationTests/NavigationViewControllerTestDoubles.swift

When user starts offline navigation and this user previously started online navigations some of voice instructions were alredy cached. In situations like this, for `MapboxSpeechSynthesizer` is used for cached instructions and `SystemSpeechSynthesizer` for non-cached.  But we only track overlapping within one synthesizer, not across multiple synthesizers.

Fix overlapping voice instructions from offline and online Speech Synthesizers

---

Sources/MapboxNavigation/ArrivalController.swift
Sources/MapboxNavigation/NavigationView.swift
Sources/MapboxNavigation/NavigationViewLayout.swift
Sources/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard

This PR fixes the arrival feedback pop-up issue where it took up too much of the map view in landscape mode by

Fix arrival feedback pop-up to not occupy too much of the map in landscape mode

---

Tests/MapboxCoreNavigationIntegrationTests/MapboxCoreNavigationIntegrationTests.swift
Tests/MapboxCoreNavigationIntegrationTests/MapboxNavigationServiceIntegrationTests.swift
Tests/MapboxNavigationTests/DataCacheTests.swift
Tests/MapboxNavigationTests/InstructionPresenterTests.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Tests/MapboxNavigationTests/StepsViewControllerTests.swift

Performance tests in the Nav SDK repo were disabled in [2018](https://github.com/mapbox/mapbox-navigation-ios/issues/1468). There is no use in storing non-running test code for 4 years. We have separate MetricsTests for measuring memory usage. So disabled performance tests are removed in this PR.
As for non-performance, tests were modified to test the actual behavior of the SDK.

Remove long-disabled tests

---

CHANGELOG.md
Example/ViewController.swift
MapboxNavigationTests/MapboxNavigationTests.swift
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift
Sources/MapboxCoreNavigation/RoutesCoordinator.swift
Sources/MapboxNavigation/NavigationMapView+Annotations.swift
Sources/MapboxNavigation/NavigationMapView.swift
Sources/TestHelper/CoreNavigatorSpy.swift
Tests/MapboxCoreNavigationTests/RoutesCoordinatorTests.swift

PR adds functionality to extrace `AlternativeRoute`s data from a `RouteResponse` without trigering a navigation session.
Added corresponding method to `IndexedRouteResponse`. SDK internals updated to also utilize this method and unify routes setup to the NN.Navigator. Added few convenience methods to draw routes on the NavigationMapView to be set up using `IndexedRouteResponse`.

Continuous alternatives metadata

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RouteController.swift

Fixes an issue when while driving onboard route with route index !=0, switching to online route could result in using route with different geometry.
Issue is resolved by fixing usage of suggested route index from NN during the switch.

Switching to correct online route

---

Example/ViewController.swift

This Pr is to remove the continuous alternative routes remain on `NavigationMapView` after clear the routes in the `Example` App.
#4294 introduced the `NavigationMapView.showcase(_:routesPresentationStyle:legIndex:animated:duration:completion:)` and `NavigationMapView.show(_:layerPosition:legIndex:)`. Right now the alternative routes in route preview within the `IndexedRouteResponse` will be presented as continuous alternative routes. 
So to clear the route preview with `IndexedRouteResponse`, except to remove routes, which used to remove the alternative routes, it should also remove the continuous alternative routes specifically.

Fix the continuous routes remain in routes preview

---

CHANGELOG.md
Cartfile
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

This Pr is to update MapboxMaps to [v10.10.1](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.10.1) to fix the CarPlay specific issue in active navigation session that the `NavigationMapView` is not loaded. And also to align the `NavNative` minimum version from `v123.1.0` in different dependency managers.

Update Maps to v10.10.1 to fix CarPlay map view not loading issue in active navigation session

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

This Pr is to cheery pick the dependency update PRs #4310 and #4315 to adopt the patch release of `NavNative v123.1.0` and `MapboxMaps v10.10.1 ` to the `main` branch.

Dependency update for patch release from NavNative and MapboxMaps

---

Example/AppDelegate+CarPlay.swift
Example/AppDelegate.swift
Example/FavoritesList.swift
Sources/MapboxNavigation/CPInterfaceController.swift
Sources/MapboxNavigation/CPMapTemplate.swift
Sources/MapboxNavigation/CPRouteChoice.swift
Sources/MapboxNavigation/CPTrip.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift
Sources/MapboxNavigation/CarPlayMapViewControllerDelegate.swift
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift
Sources/MapboxNavigation/CarPlaySearchController+CPSearchTemplateDelegate.swift
Sources/MapboxNavigation/CarPlaySearchController.swift
Sources/MapboxNavigation/CarPlaySearchControllerDelegate.swift
Sources/MapboxNavigation/CongestionLevel+CarPlay.swift
Sources/MapboxNavigation/DayStyle.swift
Sources/MapboxNavigation/MapTemplateProvider.swift
Sources/MapboxNavigation/MapTemplateProviderDelegate.swift
Sources/MapboxNavigation/NavigationGeocodedPlacemark.swift
Sources/MapboxNavigation/VisualInstruction.swift

The current minimum deployment target for the project is iOS 12.0.
`@available(iOS 12.0, *)` and similar can be removed from the project

Remove unneeded if available iOS 12

---

CHANGELOG.md
Example/AppDelegate+CarPlay.swift
Example/ViewController.swift
Sources/MapboxNavigation/CPMapTemplate.swift
Sources/MapboxNavigation/CPRouteChoice.swift
Sources/MapboxNavigation/CPTrip.swift
Sources/MapboxNavigation/CarPlayManager.swift
Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Sources/MapboxNavigation/CarPlayMapViewController.swift

This Pr is to add the routes preview and cancel preview function in CarPlay, and also notify the delegate about the preview and cancel preview events.
- Add `CPRouteChoice.indexedRouteResponse` to extract the `IndexedRouteResponse` from CarPlay trip preview. When preview routes on CarPlay, the first route choice is the chosen route from the `IndexedRouteResponse`.
- Add `CarPlayManagerDelegate.carPlayManagerDidCancelPreview(_:)` to notify when CarPlay did cancel routes preview.
- Developers could call `CarPlayManager.cancelRoutesPreview()` and `CarPlayManager.previewRoutes(for:)` to cancel and to add route preview.
- Developers will be notified from `CarPlayManagerDelegate.carPlayManagerDidCancelPreview(_ :)` and `CarPlayManagerDelegate.carPlayManager(_:selectedPreviewFor:using:)` about …

Add the route preview and cancel function in CarPlay

---

.circleci/config.yml
scripts/distribute-version.py

https://mapbox.atlassian.net/browse/NAVSDK-772
There may be errors that occur when running the `pod trunk push` command, as well as errors that can happen when pushing the **MapboxNavigation** after a release of **MapboxCoreNavigation** due to pods not releasing instantly. I have created a retry script to help address these issues.

Distribute versions with repeats

---

CHANGELOG.md
MapboxCoreNavigation.podspec
MapboxNavigation.podspec
Package.swift

Use MapboxMaps constraint upToNextMinor(from: "10.5.1") for `v2.4.3`
The `breaking API detection` build fails because this branch is not synced with the last `develop` branch. This branch does not contain any API changes so I guess it's better to have min diff in PR than trying to fix slightly change API breakage detection in the release branch.

Create Navigation v2.4.3

---

MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme
Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift
Tests/MapboxCoreNavigationIntegrationTests/MapboxNavigationServiceIntegrationTests.swift
Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Tests/MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
Tests/MapboxNavigationTests/CarPlayManagerTests.swift

* Changes the priority for Telemetry Events
* Removes extra unused API
* Feature parity, Android mapbox/mapbox-navigation-android#6622

Use .queued event priority by default

---

codecov.yml

Let's add this file to the ignored list since it's a huge autogenerated (with paintcodeapp.com) file that makes our codecov stats look bad.
Btw it's actually tested in our screenshot tests [here](https://github.com/mapbox/mapbox-navigation-ios/tree/main/Tests/MapboxNavigationTests/__Snapshots__/iPhone15_3/16.0/ManeuverViewSnapshotTests).

Add LanesStyleKit.swift to ignored list for codecov

---

.breakage-allowlist
Sources/MapboxCoreNavigation/HistoryEvent.swift
Sources/MapboxCoreNavigation/HistoryReader.swift
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/ReplayLocationManager.swift

This PR improves history replaying capabilities by exposing more public history records types and modifying `ReplayLocationManager` to replicate all stored history events in chronological order, including `setRoute` events and actually setting them to the router.
Made `PushRecordHistoryEvent` public; refactored `ReplayLocationManager` to work with events feed and added a listener to report occurred events to.

History replay improvements

---

Sources/MapboxCoreNavigation/ReplayLocationManager.swift
Tests/MapboxCoreNavigationTests/ReplayLocationManagerTests.swift

Fixed updating initial history events and locations timestamps and pushing location update events to delegates when replaying history feed

Replay Manager fixes

---

CHANGELOG.md
Sources/MapboxCoreNavigation/NavigationService.swift
Sources/MapboxCoreNavigation/SimulatedLocationManager.swift
Tests/MapboxCoreNavigationTests/SimulatedLocationManagerTests.swift

When the reroute happens, `route`, `routeProgress`, `locations`, and `remainingRouteShape` should be updated.
The cause for a possible crash is that `route` and `shape` updates are synced on the main thread, but `locations` and `remainingRouteShape` aren't, so some additional work should be done.

Fix `Index out of bounds` crash in SimulatedLocationManager

---

Example/en.lproj/Localizable.strings
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/Resources/en.lproj/Localizable.strings

On CarPlay when there are no alternative routes available the Alternatives List Template will display an empty screen.  This PR will add an empty variant to the Alternatives List Template. This will address #4355

Adding an empty variant to the alternatives list template on CarPlay

---

Tests/MapboxNavigationTests/NavigationMapViewTests.swift

Should fix flaky `NavigationMapViewTests.testEnablePredictiveCaching()`
[Example](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/10991/workflows/9bd7c838-7e90-4c2a-a8bd-262510e58ae9) of failing builds

Fix flaky NavigationMapViewTests

---

CHANGELOG.md
Sources/MapboxCoreNavigation/NavigationService.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift

When NavigationService starts, it passes one real GPS location to the `Router`, even if the simulation mode is enabled.
This can lead to problems when simulating a route far away from the real user location.

Remove usage of real GPS position when `simulationMode == .always`

---

CHANGELOG.md
Sources/MapboxNavigation/CameraController.swift

Fixes a camera jumping issue:
https://user-images.githubusercontent.com/1976216/223154902-524b1a6a-5edd-41f7-bfec-54e07f4a1612.mp4
Now we will ignore all invalid viewports and camera won't move at all.

Fix unexpected camera jumps when showing the list of upcoming maneuvers

---

CHANGELOG.md
Sources/MapboxCoreNavigation/ReplayLocationManager.swift
Tests/MapboxCoreNavigationTests/ReplayLocationManagerTests.swift

Fixed issue when initializing ReplayLocationManager with events removed all custom history events
Avoided `events` overwriting by separating an internal storage variable.

Missing replay events fix

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/TestHelper/NavNative/TestNavigationStatusProvider.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/Progress/RouteProgressTests.swift

Updates only dependency version. The migration to `upcomingRouteAlertUpdates` should be completed after some fixes in NN in the next release.

Up dependencies to NN to 128.0.0, Maps to 10.12.0-rc.1, Common to 23.4.0-rc.1

---

.breakage-allowlist
CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/NavigationService.swift
Tests/MapboxCoreNavigationIntegrationTests/MapboxNavigationServiceIntegrationTests.swift
Tests/MapboxCoreNavigationIntegrationTests/NativeTelemetryIntegrationTests.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift

* Adds the ability to pass userInfo to NavigationService to use app metadata in Telemetry even for the first sent event.
* Adds basic Native Telemetry integration tests.

Add the ability to pass userInfo to NavigationService constructor

---

CHANGELOG.md
Sources/MapboxCoreNavigation/Telemetry/NavigationCommonEventsManager.swift
Sources/MapboxCoreNavigation/Telemetry/NavigationEventsManager.swift
Sources/TestHelper/NavigationEventsManagerTestDoubles.swift
Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Tests/MapboxCoreNavigationTests/Telemetry/NavigationCommonEventsManagerTests.swift
Tests/MapboxCoreNavigationTests/Telemetry/NavigationEventsManagerTests.swift

Fix non sent parameters for 'navigation.cancel' telemetry event

Fix non sent parameters for 'navigation.cancel' telemetry event

---

MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/RouteAlert.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/TestHelper/Fixtures/route-with-road-objects-japan.json
Tests/MapboxCoreNavigationIntegrationTests/RouteControllerIntegrationTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

Feature parity with Android mapbox/mapbox-navigation-android#7030
NN change was introduced for Android in order to 
> Fixed "global reference table overflow" by reducing the amount of objects transferred through the JNI on every route progress update.

Use upcomingRouteAlertUpdates instead of upcomingRouteAlerts

---

CHANGELOG.md
Cartfile.resolved
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Sources/MapboxCoreNavigation/PassiveLocationManager.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Telemetry/NavigationSessionManager.swift
Sources/TestHelper/NavNative/NativeNavigatorSpy.swift
Sources/TestHelper/NavigationSessionManagerSpy.swift
Tests/MapboxCoreNavigationIntegrationTests/NativeTelemetryIntegrationTests.swift
Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Tests/MapboxCoreNavigationTests/Telemetry/NavigationSessionManagerTests.swift

Closes [NAVIOS-983](https://mapbox.atlassian.net/browse/NAVIOS-983)
Implemented logic is:
* iOS SDK calls startNavigationSession if the session was not started yet, and either an instance of PassiveLocationManager is created (free drive) or the callback of Navigator.setRoutesData was called (active guidance)
* it calls stopNavigationSession when no more session running (could be deinitialization of PassiveLocationManager or Navigator.setRoutesData(null))
* it calls storeNavigationSession before switching to offline or switching back to online. And SDK calls restoreNavigationSessionForState when switching finished

 Add support for NN startNavigationSession/stopNavigationSession methods

---

Tests/MapboxCoreNavigationIntegrationTests/RouteControllerIntegrationTests.swift

Fixed [the build error](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/11295/workflows/71acceab-2a39-4dab-a6b6-50b20612907a/jobs/109354)
```
RouteControllerIntegrationTests.swift:470:9: error: switch must be exhaustive
switch self {
```

Fix navigation integration tests

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RerouteController.swift
Tests/MapboxCoreNavigationTests/RerouteControllerTests.swift

#4380 introduced a call of `Navigator.removeRerouteObserver(for:)` when navigation finished in order to avoid a memory leak of `RerouteController`. In case when navigation was started this method should be called before the `deinit` method for avoiding memory leak.
But this pull request also introduced a possible duplicate call of this method when navigation was not started. The duplicate call leads to incorrect memory management and a crash.

Fix possible crash when 'Navigator.removeRerouteObserver(for:)` was called twice

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RerouteController.swift
Tests/MapboxCoreNavigationTests/RerouteControllerTests.swift

[Cherry-pick] Fix possible crash when 'Navigator.removeRerouteObserver(for:)` was called twice

---

Sources/MapboxCoreNavigation/RerouteController.swift

Add synchronization for `isInvalidated` in RerouteController
Resolves
> @kried there is no guarantee that deinit (where this method is called) will be called on the main thread. It is better to synchronize access to isInvalidated properly.

Add synchronisation for isInvalidated in RerouteController

---

CHANGELOG.md
Sources/MapboxCoreNavigation/RerouteController.swift
Tests/MapboxCoreNavigationTests/RerouteControllerTests.swift

[Cherry-pick][2.13.0] Fix possible crash when Navigator.removeRerouteObserver(for:) was called twice

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+Annotations.swift

Fixed method for picking time diff callout coordinate
Picking exact deviation point coordinate and adding a margin distance instead of calculating route distances.

Time difference callouts fix

---

CHANGELOG.md
Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Sources/MapboxNavigation/VisualInstruction.swift

Fixed applying correct style type when generating maneuver arrow for CarPlay by using the style type instead of interface idiom

CarPlay maneuver color fix

---

CHANGELOG.md
Example/ViewController.swift
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/MapboxNavigation/NavigationViewController.swift

Added loading continuous alternatives on `NavigationViewController` startup, which previously resulted in showing only the main route when `NavigationService` was created beforehand. Fixed displaying route steps when starting navigation from CarPlay by correctly calling the connection handler

CarPlay alternative routes display

---

Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift
Tests/MapboxCoreNavigationTests/RouteControllerTests.swift

Corrected provided reason to update route when switching to alternative route. This is important to correct logging and Navigator internal functioning.
Just added a parameter to `InternalRouter`'s method instead of introducing one more (3rd) enum with cases for proactive rerouting or switching to alternative.
This is an internal change, so no need for a CHANGELOG entry.

Correcting setRoutes reason

---

CHANGELOG.md
Cartfile
Cartfile.resolved
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Package.swift
Sources/TestHelper/NavNative/TestNavigationStatusProvider.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock
Tests/MapboxCoreNavigationTests/Progress/RouteProgressTests.swift

Dependency update

---

.circleci/config.yml

Old Xcode versions were removed on CircleCI.

Update Xcode versions

---

.circleci/config.yml

Archiving the docs folder before uploading it to arctifact storage should drastically speed up the "publish documentation" job.
Right now the upload takes 7 minutes. 
[Before](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/11679/workflows/92ac3d61-babc-44f3-a517-1db7e6c3648a/jobs/113305):
[After](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/11683/workflows/d99cbd10-5a3c-499d-b142-92e193c337b9/jobs/113372):

Add archive step to speed up the job

---

Sources/MapboxCoreNavigation/NavigationRouteOptions.swift

Correct the `.numericCongestionLevel` attribute to `.congestionLevel` when using the cycling profile. This is the same as https://github.com/mapbox/mapbox-navigation-ios/issues/3495 (https://github.com/mapbox/mapbox-navigation-ios/pull/3496) but for `NavigationMatchOptions` instead of `NavigationRouteOptions`.
https://github.com/mapbox/mapbox-navigation-ios/blob/ff4873f77bd91505820e6027f1a4a43efc4a7a3d/Sources/MapboxCoreNavigation/NavigationRouteOptions.swift#L28-L34
This avoids the same error as the other issue but when using the map matching API:
```
The operation couldn’t be completed. annotations value must be one of duration, distance, speed, maxspeed, congestion
```

Correct `NavigationMatchOptions` congestion level in cycling profile

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Sources/MapboxNavigation/NavigationMapView.swift

Fixed a possible division by zero

Fix a possible crash that could happen when displaying the route with the same source, midpoint, and destination

---

Example/pl.lproj/Main.strings
MapboxNavigation-SPM.xcodeproj/project.pbxproj
MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Sources/MapboxNavigation/Resources/pl.lproj/Localizable.strings
Sources/MapboxNavigation/Resources/pl.lproj/Localizable.stringsdict
Sources/MapboxNavigation/Resources/pl.lproj/Navigation.strings

Adding Polish translations to NavSDK UI. 
Both Directions API and Mapbox Speech API already support Polish, our SDK will automatically use it if application locale is set to Polish.

Add Polish localization

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationViewportDataSource.swift
Tests/CocoaPodsTest/PodInstall/PodInstall/Assets.xcassets/AppIcon.appiconset/Contents.json

https://mapbox.atlassian.net/browse/NAVIOS-1537
Fixes the issue on iOS where navigation routes didn't take the whole available viewport because of incorrectly calculated zoom level.
Note: the viewport does not take the whole screen, it is calculated to take into account the padding to the control elements.
Note: the old implementation is still used for CarPlay to avoid hardcoding the size of the control elements to avoid the views overlap.
<details>
<summary>Screenshots</summary>
| Before |  After |
|:--:|:--:|
|![Simulator Screenshot - iPhone 15 Pro - 2024-02-07 at 12 18 13](https://github.com/mapbox/mapbox-navigation-ios/assets/3630656/5e3d595e-b604-41b2-98df-9d83a9622a9d)|![Simulator Screenshot - iPhone 15 Pro - 2024-02-07 at 12 14 …

Use camera options to calculate zoom for overview camera

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

https://mapbox.atlassian.net/browse/NAVIOS-1437
Fixes the case when the traffic was twiced filled with `.routeCasingColor`
<details open>
<summary>Screenshots</summary>
| Before  | After |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-01-23 at 20 27 21](https://github.com/mapbox/mapbox-navigation-ios/assets/3630656/a5179e14-fa74-4bf1-9f9e-00ad1439c927)  | ![Simulator Screenshot - iPhone 15 Pro - 2024-01-23 at 20 26 40](https://github.com/mapbox/mapbox-navigation-ios/assets/3630656/5cbab26d-bab3-4537-9aa5-98887993133d)  |
</details>

Fixed the possible situation when the upcoming route leg is rendered above the active route leg

---

CHANGELOG.md
Sources/MapboxNavigation/BottomBannerViewController.swift
Sources/MapboxNavigation/InstructionsBannerView.swift
Sources/MapboxNavigation/TopBannerViewController.swift

Closes #4581
https://mapbox.atlassian.net/browse/NAVIOS-1547
Makes properties public
<details>
<summary>Usage example</summary>
```swift
let top = TopBannerViewController()
top.instructionsBannerView.distanceFormatter.locale = .init(identifier: "zh-Hans")
navigationOptions.topBanner = top
let bottom = BottomBannerViewController()
bottom.distanceFormatter.locale = .init(identifier: "zh-Hans")
bottom.dateFormatter.locale = .init(identifier: "zh-Hans")
navigationOptions.bottomBanner = bottom
let navigationViewController = NavigationViewController(for: indexedRouteResponse, navigationOptions: navigationOptions)
bottom.delegate = navigationViewController
top.delegate = navigationViewController
```
</details>

Add the ability to set locale for top and bottom banner views

---

CHANGELOG.md
Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Tests/MapboxNavigationTests/NavigationMapViewTests.swift

Cherry pick of #4589 into 2.18

[Cherry pick] Fixed the possible situation when the upcoming route leg is rendered above the active route leg

---

CHANGELOG.md
Sources/MapboxNavigation/BottomBannerViewController.swift
Sources/MapboxNavigation/InstructionsBannerView.swift
Sources/MapboxNavigation/TopBannerViewController.swift

Cherry pick of #4595 into 2.18

[Cherry pick] Add the ability to set locale for top and bottom banner views 

---

CHANGELOG.md
MapboxNavigation.xcodeproj/project.pbxproj
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/Result++.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/Router.swift

Our SDK allows developers to override [RoutingProvider](https://docs.mapbox.com/ios/navigation/api/2.17.0/Protocols/RoutingProvider.html#/RoutingProvider) to implement their own logic for route calculation.
We can assume that our own implementation always returns a valid route response, however that's not a case for a custom implementation. Currently, in case the response is invalid, in some branches we silently ignore errors without reporting back to the application that the route was invalid.
This PR fixes cases where [RouteController](https://docs.mapbox.com/ios/navigation/api/2.17.0/Classes/RouteController.html) didn't report errors about invalid route to its delegate.

Improve error handing in case of invalid route responses

---

MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme

The Polish language was mistakenly set by default in the sample app for the v2 SDK in #4582

Reset Polish by default in v2 samples

---

.circleci/config.yml

The CI build failed with the error:
> Bad CPU type in executable

Fix ci release v2 builds

---

scripts/distribute-version.py

Fixes podspec uploading due to
```
- NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'MapboxMobileEvents' from project 'Pods')
- NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'Solar-dev' from project 'Pods')
```

Add `--allow-warnings` flag to cocoapods distribute script

---

CHANGELOG.md
MapboxCoreNavigation.podspec
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
MapboxNavigation.podspec
Package.resolved
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Supports Maps 10.18.2 in CocoaPods, that was supported in SPM

Match CocoaPods dependency rules to SPM

---

CHANGELOG.md
Sources/MapboxCoreNavigation/SimulatedLocationManager.swift
Sources/MapboxNavigation/TopBannerViewController.swift

Fixes blank space appearing in steps list table when next banner view should be shown. Also fixes rare issue with route simulation when puck could become stuck.
Blank space is fixed by resolving logic of next banner view which was controlled by itself and the TopBannerViewController, which resulted in conflicting visibility config.
Route simulation could sometimes become stuck in one place when expected segment travel time was not set, which resulted in simulated speed value to be calculated as NaN, which kept the puck in place.

Steps table blank space fix

---

CHANGELOG.md
Sources/MapboxNavigation/StepsViewController.swift

https://mapbox.atlassian.net/browse/NAVIOS-1628
Updates route progress in `StepsViewController`

Fixed a possibly not-updating `StepsViewController` after reroutes

---

MapboxCoreNavigation.podspec
Sources/MapboxCoreNavigation/BundleAdditions.swift
Sources/MapboxNavigation/Bundle.swift
Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
Tests/CocoaPodsTest/PodInstall/PodInstall/Info.plist
Tests/CocoaPodsTest/PodInstall/PodInstall/ViewController.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

https://mapbox.atlassian.net/browse/NAVIOS-1842
Uses the same fix that was aded in #4668 for MapboxNavigation for MapboxCoreNavigation.
The Maps SDK [declares](https://github.com/mapbox/mapbox-maps-ios/blob/fb97a45e3b4c98b220dd89acf7b29a9876f9ab56/MapboxMaps.podspec#L22) `PrivacyInfo.xcprivacy` similarly in `resource_bundle`.

Use use resource_bundle instead of resource in Core Podspec

---

CHANGELOG.md
Cartfile.resolved
MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Sources/MapboxCoreNavigation/LegacyRouteController.swift
Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
Sources/MapboxCoreNavigation/NavigationRouteOptions.swift
Sources/MapboxCoreNavigation/RouteController.swift
Sources/MapboxCoreNavigation/RouteOptions.swift
Sources/MapboxCoreNavigation/Router.swift
Tests/CocoaPodsTest/PodInstall/Podfile.lock

Fixes [NAVIOS-2276](https://mapbox.atlassian.net/browse/NAVIOS-2276)
[NAVIOS-2276]: https://mapbox.atlassian.net/browse/NAVIOS-2276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed ProfileIdentifier comparison for the custom profile identifiers, so that route refresh is enabled for custom automobileAvoidingTraffic profiles
