mapbox/mapbox-navigation-ios

MapboxNavigation.swift.podspec, MapboxNavigation.xcodeproj/project.pbxproj
Fixes #14 
The [swiftenv](https://github.com/kylef/swiftenv) inspired `.swift-version`-file is flaky despite CocoaPod's claim to support it as of 1.1.0.
This PR removes SWIFT_VERSION from the target and inherits it from the project instead.
It also specifies SWIFT_VERSION in xcconfig just like [MapboxDirections.swift.podspec](https://github.com/mapbox/MapboxDirections.swift/blob/swift3/MapboxDirections.swift.podspec#L48) which been proven to work well. These settings will continue to work when we add support for Carthage (#24)
=> Specify swift version

MapboxNavigation/Geometry.swift, MapboxNavigation/RouteController.swift, MapboxNavigationTests/MapboxNavigationTests.swift
Ran into a situation today where the maneuver final heading was `358` degrees and the user heading never crossed from 0 to `35x` (the user heading remained around 4 which is an acceptable heading for this example). Thus, the difference between the user heading and the final heading was ~354 degrees. 
This change normalizes the difference between the user and final heading further.
=> Account for values on both size of 360

MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme, MapboxNavigation/RouteController.swift, MapboxNavigationTests/MapboxNavigationTests.swift
If the user is within the high alert distance, skip the departure instruction and go right into the high alert.
/cc @1ec5
=> Skip departure announcement when user is close to maneuver

MapboxNavigationUI/RouteMapViewController.swift, MapboxNavigationUI/RoutePageViewController.swift
This PR fixes a bug where RouteMapVC did not notify the RoutePageVC about rerouting, causing it to show a non-existing step and leaving it unable to update or changing step.
=> PageViewController showing incorrect number of steps

Examples/Swift/ViewController.swift, MapboxNavigation.swift.podspec, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/RouteVoiceController.swift, MapboxNavigationUI.swift.podspec, MapboxNavigationUI/RouteStepFormatter.swift, MapboxNavigationUI/RouteViewController.swift, MapboxNavigationUI/RouteVoiceController.swift
Fixes #69 
RouteViewController now keeps a ref to a RouteVoiceController.
An optional identityPoolId can be set if Polly is preferred over default speech synthesizer.
Also added a boolean to enable/disable voice.
Tail work for this PR would be to make the AWSPolly dependency optional but we might want to wait with that until this accepted proposal has been released: https://github.com/apple/swift-evolution/blob/master/proposals/0075-import-test.md
@bsudekum 👀
=> Include voice in NavUI

MapboxNavigationUI/Resources/Navigation.storyboard, MapboxNavigationUI/RouteMapViewController.swift, MapboxNavigationUI/RouteTableViewController.swift
before
after
* Increase way name font size
* improves padding
* Now we fallback to the instruction if there is no way name or destination
/cc @1ec5
=> Minor UI adjustments

MapboxNavigationUI/RouteTableViewHeaderView.swift
Because the storyboard has default values, when the view first loads there is flash from the default values in the storyboard until the real values are shown. This is quite obvious when the users locale is metric because you see "8.3 mi" before the actual metre/km value is shown.
there are a number of ways to address this minor issue. you could update the labels in the storyboard or do it in this view or in the view controller. I thought it might be cleaner in the view awakeFromNib()?
=> clear default values from the storyboard labels

MapboxNavigationUI/Directions.swift, MapboxNavigationUI/RouteViewController.swift
- When RouteViewController is re-calculating a route, pass through original
route.profileIdentifier to make sure the new route uses the same identifier.
- Remove default value for RouteOptions.preferredOptions() profileIdentifier
argument, since there should always be a value for it.
@bsudekum @1ec5 @boundsj
=> Make RouteViewController respect original route profile identifier

MapboxNavigation/Constants.swift, MapboxNavigation/RouteController.swift, MapboxNavigationUI/RouteVoiceController.swift
- Replace RouteControllerMinimumDistanceForMediumAlert and RouteControllerMinimumDistanceForHighAlert with
RouteControllerMinimumDistanceForHighAlertDriving, RouteControllerMinimumDistanceForHighAlertCycling, RouteControllerMinimumDistanceForHighAlertWalking
RouteControllerMinimumDistanceForMediumAlertDriving, RouteControllerMinimumDistanceForMediumAlertCycling, RouteControllerMinimumDistanceForMediumAlertWalking
to allow for different minimum distance per transportation method.
- Add RouteControllerMinimumDistanceForMediumAlert(identifier:) and RouteControllerMinimumDistanceForHighAlert(identifier:)
to choose which minimum distance is approriate for which MBDirectionsProfileIdentifier type.
- Modifiy MapboxNavigation/RouteController and MapboxNavigationUI/RouteVoiceController to use
new …
=> Add custom minimum alert distances for Cycling/Walking/Driving

MapboxNavigationUI/RouteViewController.swift
In light of https://github.com/mapbox/MapboxNavigation.swift/pull/57, I realized setting the snapping option is impossible while using MapboxNavigationUI. We should expose this to the developer.
=> Make routeController public while using MapboxNavigationUI

MapboxNavigation/Constants.swift, MapboxNavigation/RouteController.swift, MapboxNavigationTests/MapboxNavigationTests.swift
This addresses two issues:
1. A user is standing still far from the route. Consider if someone starts a route in a large parking lot. Yes, they are from the route, but we don't need to reroute them. 
1. The user is moving to/from the start. Again consider a large parking lot. If the user is traveling towards the beginning of the route, we do not need to reroute them even if they are greater than the max reroute distance.
=> Don't continual reroute user if standing still, allow user time to get to route start

MapboxNavigationUI/MGLMapView.swift, MapboxNavigationUI/RouteMapViewController.swift
* Cleans up the arguments for `annotate`
* Removes the arrow sooner when rerouting
* ^ This actually solves inserting the route line below labels. Before, we were inserting below the layer `arrow` instead.
* Only redraw the arrow when it actually changes.
closes: https://github.com/mapbox/MapboxNavigation.swift/issues/90 https://github.com/mapbox/MapboxNavigation.swift/issues/89
/cc @1ec5
=> Insert route below text on reroute

MapboxNavigation/RouteProgress.swift, MapboxNavigationUI/RouteMapViewController.swift
Adds course snapping to the `snapsUserLocationAnnotationToRoute` option.
More ideas on implemenation should be explored.
/cc @1ec5
=> Add course snapping [wip]

Cartfile, Cartfile.resolved, MapboxNavigation/Geometry.swift, MapboxNavigationUI/TurnArrowView.swift
Silenced warnings by updating deprecated methods and constants.
Also updated to Mapbox iOS SDK 3.5.0
=> Adopt Swift 3.1

MapboxNavigation/Constants.swift, MapboxNavigationUI/RouteMapViewController.swift
Closes: https://github.com/mapbox/MapboxNavigation.swift/issues/99
If the difference between the calculated course and the actual course is greater than a certain threshold, we should probably not manipulate the puck.
=> Don't manipulate user puck course past certain point

MapboxNavigationUI.swift.podspec
This PR specifies minimum versions for each of the third-party library dependencies in the MapboxNavigationUI podspec. This is especially important because previous versions may be written in Swift 2.3. I left out a minimum version for MapboxNavigation.swift in this podspec, because MapboxNavigation.swift has yet to be pushed to CocoaPods trunk.
=> Specify versions in pod dependencies

README.md
Updated the readme to reflect renaming the repository from mapbox/MapboxNavigation.swift to mapbox/mapbox-navigation-ios. Left the product names of the libraries themselves intact, pending a more comprehensive rewrite of this document.
/cc @bsudekum @frederoni @ericrwolfe
=> MapboxNavigation.swift → mapbox-navigation-ios

MapboxNavigationUI/MGLMapView.swift, MapboxNavigationUI/NavigationMapView.swift, MapboxNavigationUI/RouteMapViewController.swift
This makes the annotate not only public, but also overrideable. This way, developers can specify a custom source for route line and also styling for it too.
=> Make route line more configurable

MapboxNavigationUI/MGLMapView.swift, MapboxNavigationUI/NavigationMapView.swift, MapboxNavigationUI/RoutePageViewController.swift, MapboxNavigationUI/RouteTableViewHeaderView.swift, MapboxNavigationUI/RouteViewController.swift
Hey!
This PR fixes various memory leaks, that prevents several MapboxNavigationUI components from being deallocated.
Three of them are usual non-weak delegate suspects. 
Two more are NSTimer instances retaining their target until invalidated. I chose to invalidate them in RouteViewController deinit, since after main controller deinit probably there's no use in them
=> Fix memory leaks

Examples/Objective-C/Base.lproj/Main.storyboard, Examples/Swift/Base.lproj/Main.storyboard, MapboxNavigation/DashedLineView.swift, MapboxNavigation/DistanceFormatter.swift, MapboxNavigation/LaneArrowView.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/Resources/Navigation.storyboard, MapboxNavigation/RouteStepFormatter.swift, MapboxNavigation/RouteViewController.swift, MapboxNavigation/RouteVoiceController.swift, MapboxNavigation/StyleButton.swift, MapboxNavigation/StyleKitArrows.swift, MapboxNavigation/StyleLabel.swift, MapboxNavigation/TurnArrowView.swift
Fixes #130 
TextStyle doesn't bridge to Obj-C and the public bridgeable constants and functions in Constants.swift are primarily written in Obj-C.
👀  @bsudekum @1ec5
=> Prefix Obj-C classes

Examples/Swift/ViewController.swift, MapboxNavigation/MGLMapView.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/134
Exposes 3 delegate methods:
```swift
func navigationMapView(_ mapView: NavigationMapView, routeStyleLayerWithIdenitier identifier: String, source: MGLSource) -> MGLStyleLayer?
func navigationMapView(_ mapView: NavigationMapView, routeCasingStyleLayerWithIdenitier identifier: String, source: MGLSource) -> MGLStyleLayer?
func navigationMapView(_ mapView: NavigationMapView, shapeDescribing route: Route) -> MGLShape?
```
=> Expose route line configuration to delegates

MapboxNavigation/NavigationMapView.swift, MapboxNavigation/NavigationViewController.swift
If the developer implements `shape(describing:)` but not `simplifiedShape(describing:)`, use the `shape(describing:)` return value for both the route line and its casing. Also expanded the documentation to talk about what happens when each method is unimplemented.
Followup to #135.
/cc @bsudekum
=> Fall back to unsimplified shape when simplified shape not provided

MapboxNavigation.podspec
A particular version of MapboxNavigation always needs exactly the same version of MapboxCoreNavigation.
=> Version Core Navigation and Navigation in lockstep

Examples/Swift/AppDelegate.swift, Examples/Swift/Base.lproj/Main.storyboard, Examples/Swift/ViewController.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/MGLMapView+MGLNavigationAdditions.h, MapboxNavigation/MGLMapView+MGLNavigationAdditions.m, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/SimulatedRoute.swift, MapboxNavigation/Simulation.swift
This PR adds support for simulating location updates.
Just set `RouteViewController.simulate` to true and the given route's coordinates will be used for simulation.
The route can be archived for offline use cases.
=> Route simulation

README.md
For consistency with the Directions API, the default is low resolution (simplified), which can produce wildly inaccurate timing and rerouting.
/cc @bsudekum @frederoni @ericrwolfe
=> Specify full route shape resolution in example

Examples/Objective-C/Info.plist, Examples/Swift/Info.plist, README.md
Also: 
* Adds a more obvious access token placeholder to `Info.plist`
* Adds instructions for adding your access token
/cc @bsudekum @1ec5
=> Improve instructions for running example project

MapboxNavigation/Resources/Navigation.storyboard
Fixes an issue from #133 where we used the wrong custom class for `Route/NavigationViewController` in Navigation.storyboard.
@bsudekum 👀
=> Set correct class name for NavigationViewController in storyboard.

docs/Storyboards.md
CocoaPods overrides the bundle identifier to `org.cocoapods.{{BundleIdentifier}}`
@1ec5 @ericrwolfe 👀
=> Update storyboard documentation

MapboxNavigation/RouteTableViewController.swift
Fixes #97 
The `.arrive` notification is fired within a certain radius of the destination when `fractionsTraveled` is below 1.0. This PR avoids an incomplete progress bar by setting the progress to 1.0 if `AlertLevel` is `.arrive`.
@bsudekum 👀
=> Set maximum progress upon arrival

MapboxNavigation/Style.swift
The window's tint color corresponds to the storyboard's global tint, not the rootViewController's view.
@1ec5 👀
=> Fix global tint

MapboxNavigation/RouteMapViewController.swift
When looking for closest snapped location, we were looking over the entire route instead of looking on the current step. Not only is this change faster, it is more accurate when future steps are close to the current step.
/cc @1ec5
=> Dont look for closest coordinate over the entire route

MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-Objective-C.xcscheme, MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-Swift.xcscheme
There is too much logging happening in the demo apps. Let's turn it off.
=> Turn off exceissive debug logging

MapboxNavigation/MGLMapView+MGLNavigationAdditions.h, MapboxNavigation/MGLMapView+MGLNavigationAdditions.m
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/172
=> Silence locationManager warning

MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/Locale.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/RouteTableViewCell.swift, MapboxNavigation/RouteTableViewController.swift, MapboxNavigation/RouteVoiceController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/183
`Bundle.main.preferredLocalizations.first`  only would specify `en` vs with `Locale.preferredLanguages` which produces `en-us`.  We use the same lookup for Polly voices.
/cc @incanus
=> Use Locale for deciding current language code

MapboxCoreNavigation/RouteController.swift
Looking to fix: https://github.com/mapbox/mapbox-navigation-ios/issues/199
The gist of this:
* If we do not calculate the users course is with x degrees of the exit bearing for a step, we should have a fallback to another heuristic.
* Now, we check
* if the user is not on the current step
* if they are also on the next step
* And have entered the maneuver radius on this step
* If so, we can assume they have now on the next step and we increment the step counter.
/cc @mapbox/navigation
=> Add second heuristic for calculating user did complete step

MapboxCoreNavigation/RouteProgress.swift, MapboxNavigation/RouteMapViewController.swift
I think it's confusing for users when swiping backwards and you end up past the current step.
=> Prevent users from swiping past current step

MapboxCoreNavigation/RouteProgress.swift, MapboxNavigation/RouteMapViewController.swift
We're checking for the wrong step when swiping steps since for maneuver information we're looking for the upcoming step.
=> When swiping check if upcoming step

MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/RoutePageViewController.swift
Follow up to https://github.com/mapbox/mapbox-navigation-ios/pull/230 and https://github.com/mapbox/mapbox-navigation-ios/pull/223. The combination of the two of these created some more bugs when in master together.
Beyond fixing some current/next step bugs, this also prevent sliding while in overview mode.
=> Fix swiping with overview button

README.md
The Bitrise shield now links to navigation and shows correct status for this repo instead of Mapbox Directions.
@1ec5 👀
=> Fix Bitrise shield url

MapboxNavigation/RouteMapViewController.swift
`step` was never updated after completing a step.
=> Update maneuver name

MapboxNavigation/RouteVoiceController.swift
For longer steps, when we announce the low alert, we try not to confuse the user about unnecessary information by just saying "Continue for a bit on the road your on". However, on steps where we announce this continue, we only want to say continue once. Once the user approaches the maneuver point, we need to give them the regular instruction.
For the [example](http://map.project-osrm.org/?z=16&center=37.333126%2C-122.047076&loc=37.336026%2C-122.032464&loc=37.336282%2C-122.068040&hl=en&alt=0) above, previously we would announce continue 3 times; once at each alert location. This is because the current step is greater than 2,000 meters.
Now, we will announce the continue once only at the low alert location.
/cc @frederoni @1ec5 @willwhite @ericfischer
=> Reduce to Continue for low alert only

MapboxNavigation/RouteVoiceController.swift
When there is only a single option and it is to merge onto a highway, a `high` alert becomes redundant and is noise. The removes the high alert when the upcoming maneuver is merge and the current maneuver is `takeOnRamp`.
=> Don't announce when merging onto highway

MapboxNavigation/TurnArrowView.swift
We're drawing uturns always turning to the right now. This changes to draw either to the left or right  depending on enter/exit bearings.
=> Correctly draw uturns

MapboxNavigation/DistanceFormatter.swift
Force the number formatter underlying the distance formatter to use a U.S. locale (for its customary units) and avoid replacing yards with feet.
Fixes #242.
/cc @bsudekum @andrey-str
=> Measure British distances in imperial units

MapboxCoreNavigation/RouteController.swift, MapboxNavigation/RouteMapViewController.swift
We've had reports of constant rerouting on highways. Our current thinking that this is a combination of a few factors:
* user has very high gps accuracy
* user is traveling on large highway with many lanes
* user has high horizontal distance from the route geometry (I.E. in first lane)
These combinations could produce a rerouting event since their `horizontalAccuracy ` is < 10m and the `RouteControllerUserLocationSnappingDistance` is `10m. This produces a radius threshold of only 20m. 
This change now looks at the maximum value between `RouteControllerMaximumDistanceBeforeRecalculating` (50m) and the `horizontalAccuracy` + `RouteControllerUserLocationSnappingDistance` (10m).
Here are the situations that will change:
* :+1: fewer rerouting on a highway with good accuracy 
* :-1: possibly …
=> Change reroute radius threshold calculation

MapboxNavigation/RouteManeuverViewController.swift
In cases where a user is approaching a maneuver and their speed decreases, `secondsRemaining` could dip below this threshold then go above it. This effect makes the distance remaining on step disappear then show again.
Now when the user is basically at the maneuver will it disappear. The real goal here is to never show `0ft`.
=> Fix fluttering distance label

MapboxNavigation/RouteManeuverViewController.swift, MapboxNavigation/RouteMapViewController.swift
Fixes #256 
Limit lines of destinations to show to the number of lines available in the streetLabel.
=> Limit destinations to number of lines

MapboxCoreNavigation/RouteController.swift
In simulation mode for the test above, when heading south on north de anza blvd, the alert level could flutter between high and medium. This caused many voice prompts. Really, there is no need to ever degrade an alert level from high to medium. This change makes it's so we do not move back to medium if the alert level is already high.
=> Don't move alert level backwards

MapboxNavigation/NavigationMapView.swift
Follow up to https://github.com/mapbox/mapbox-navigation-ios/pull/265
On every call to `showRoute` we only would update the source for the first check in this if statement. This now properly updates the shape for the route line casing.
/cc @frederoni
=> Fix redrawing casing

MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
This addition allows the developer to provide a custom annotation image for all annotations on the map. Note, the only annotations on the map currently is the destination marker.
/cc @frederoni
=> Allow custom (destination) annotations

MapboxNavigation/NavigationViewController.swift
You have to dismiss the navigationViewController if you implement `navigationViewControllerDidCancelNavigation(_:)` so we should provide a scope variable.
@bsudekum 👀
=> Provide scope variable

MapboxNavigation.xcodeproj/project.pbxproj
The bundle identifier usually starts with a lowercased reverse-DNS form of the vendor’s domain name.
=> Correct Core Navigation bundle identifier

README.md
Fixes the lead image on the jazzy documentation site (https://mapbox.github.io/mapbox-navigation-ios/navigation/0.4.0/index.html). Doesn't affect the main image in the readme in master right now.
=> Fix jazzy doc image

MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/RoutePageViewController.swift
Swiping the maneuver list suffers from two issues:
* The current step shows up twice
* Swiping backwards can jump from x index all the way to the current step
@frederoni I'm not really certain why this code was here or why it fixed both the issues above, but it does ¯\_(ツ)_/¯.
=> Fix maneuver swiping

MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/RouteTableViewController.swift
Fixes #236 
Besides moving the ornaments, this PR also changes the partially revealed height from 75% to 60% of the screen height.
@bsudekum 👀
=> Fix attribution and logo layout

README.md
CocoaPods is more popular among iOS developers so let's mention Carthage as the alternative way.
=> Rearrange CocoaPods and Carthage

MapboxNavigation/MGLMapView.swift
They just look sloppy when zoomed out.
/cc @frederoni
=> Don't show turn arrows when zoomed out

Examples/Swift/ViewController.swift, MapboxNavigation/RouteMapViewController.swift
Reverts https://github.com/mapbox/mapbox-navigation-ios/pull/296
We need to take a look at this in depth later on. With #296, the user never enters `.followWithCourse` mode.
Also added some camera changes so you're facing the right direction when the view loads.
/cc @frederoni
=> Revert https://github.com/mapbox/mapbox-navigation-ios/pull/296/

MapboxNavigation/RouteMapViewController.swift
We're attempting to show the shield for the current step instead of the provide step. In cases where we're swiping ahead, we should show the highway shield provided in the function call.
/cc @frederoni
=> Show shield for swiped to step

MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteManeuverViewController.swift
Fixes https://github.com/mapbox/mapbox-navigation-ios/issues/303, but these lifecycle events should be looked at more closely.
cc @frederoni
=> Don't suspend notifications on viewWillDisappear

MapboxCoreNavigation/NavigationLocationManager.swift
An application with deployment target set to iOS 8 gives an error at compile time w/o this availability check.
@ericrwolfe
=> Check availability

MapboxNavigation/NavigationViewController.swift
`NavigationViewController.navigationDelegate` must be weak; otherwise, it can lead to a retain cycle.
/cc @frederoni
=> Weaken navigation delegate

Cartfile.resolved
Upgraded example applications to v3.6.0 of the map SDK. Note that this PR doesn’t increase the minimum required version specified in either Cartfile or Podfile.
/cc @frederoni @friedbunny
=> Upgrade to map SDK v3.6.0

MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/PollyVoiceController.swift, MapboxNavigation/RouteVoiceController.swift
Fixes #280 
Split up voice controllers into RouteVoiceController and PollyVoiceController.
Replace AVSpeech with Polly:
```swift
navigationViewController.voiceController = PollyVoiceController(identityPoolId: "…")
```
=> Refactor voice controllers

MapboxCoreNavigation/Geometry.swift, MapboxNavigation/MGLMapView.swift
Referring to #283 
In _closestCoordinate_ function:
when the closest point to the polyline segment is the projection, now the index is set to the index of the coordinate closest to the intersection.
In _addArrow_ function:
shafts are now generated by concatenating the points before the maneuver **in the right order** with the points after the maneuver, making sure the **closest point to the maneuver is taken once**.
EDIT:
I now realize that the changes in _closestCoordinate_ might not be strictly necessary, but it's probably clearer and safer now anyways.
=> Fixed bugs in closestCoordinate and addArrow functions.

Examples/Swift/Info.plist, MapboxCoreNavigation/Bundle.swift, MapboxCoreNavigation/NavigationLocationManager.swift
Added the new `NSLocationAlwaysAndWhenInUseUsageDescription` to the example app to support iOS 11.
Request always authorization if `Always` or `AlwaysAndWhenInUse` keys are provided otherwise request when in use authorization.
@bsudekum @friedbunny 👀
=> Fix location permissions and adopt iOS 11 description

MapboxNavigation/RouteMapViewController.swift
Attempts to fix the black lines in https://github.com/mapbox/mapbox-navigation-ios/issues/338.
I think in some cases, https://github.com/mapbox/mapbox-navigation-ios/blob/eab11c929885b270e8c655495ed4e0b25123a78b/MapboxNavigation/RouteMapViewController.swift#L345-L358 could be causing a race condition if the style is not fully loaded.
/cc @frederoni @1ec5 @zijiazhai
=> Wait until style has loaded before doing things to it

MapboxCoreNavigation/SimulatedLocationManager.swift
Waits until next run loop to restart simulated location updates after a reroute occurs.
Otherwise, a DidReroute notification causes simulated location updates to start which triggers a AlertLevelChange notification before all of the reroute cleanup has finished.
cc @bsudekum @frederoni
=> Fix table view crash after rerouting with simulated locations

MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/345
We should only be alerting `didArriveAt` when the alert level changes and not on every progress update.
=> Did arrive once

MapboxNavigation/RouteManeuverViewController.swift, MapboxNavigation/RouteMapViewController.swift
This PR significantly increases the frequency of route shields in the turn banner. Before, the turn banner only considered the route step’s `code` for displaying a shield, but that would only be relevant when merging onto a freeway and when approaching an off-ramp that happens to be part of a route. Now the turn banner also shows a shield based on `destinationCode`, which is populated when approaching an on-ramp and when approaching an off-ramp that isn’t part of a route.
Additionally, we try to treat the route step’s `destination` as a `destinationCode` in case it begins with a route number. This is a workaround for Project-OSRM/osrm-backend#3304 to fix #320.
RouteManeuverViewController is now responsible for fetching route shield images it needs to display. This makes it easier to avoid …
=> Display shields for destinations in turn banner

.tx/config, Examples/Objective-C/en.lproj/Main.strings, Examples/Swift/Base.lproj/Main.storyboard, Examples/Swift/en.lproj/Main.strings, MapboxNavigation/Resources/en.lproj/Navigation.strings
Several PRs added strings to storyboards but didn’t update the corresponding .strings files. As a result, localizations that looked complete on Transifex couldn’t be applied completely to the storyboards.
/cc @bsudekum @frederoni @ericrwolfe
=> Update storyboard base localizations

MapboxNavigation/RouteTableViewController.swift, MapboxNavigation/RouteVoiceController.swift
The localized utterance format should be parsed from the navigationUI's bundle.
This bug resulted in partially localized voice instructions (`Sväng höger in på Stadiongatan, then Sväng vänster in på Trelleborgsvägen`) <- Swenglish.
=> Fix localizable bundle

MapboxCoreNavigation/BundleAdditions.swift
This extension needs to be made public to be used in upstream libraries.
=> Make backgroundModes extension public

MapboxNavigation/MGLMapView+MGLNavigationAdditions.h, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift
Fixes #341 
When an application is sent to the background and brought back to the foreground, `MGLMapView` calls `-validateLocationServices` and starts updating locations again.
This is easy to spot when using `SimulatedLocationManager` or `ReplayLocationManager` but _not_ if you're using the `DefaultLocationManager` since the location will be exactly the same.
The fix in this PR works, however, I think a more appropriate solution would be to expose a `manuallyUpdatesLocation` (or similar) on `MGLMapView` that would leave location updating to the user. At the same time, we would also expose that `MGLMapView` conforms to `CLLocationManagerDelegate` so that you can feed `MGLMapView` with locations without using the workaround in https://github.com/mapbox/mapbox-navigation-ios/blob/master/Map …
=> Stop updating location on map view

MapboxCoreNavigation/RouteController.swift
Turn completion boils down to two different heuristics:
* is within x meters of maneuver radius
* user course is with x degrees of the exit heading
For slight turns like on/off ramps, this falls apart quickly since the user's course is easily within x degrees of the exit heading. 
This PR looks at the difference between the initial and exit heading. If their difference is less than x degrees, then don't rely on the exit heading check. Instead, rely on their snapped distance from the maneuver location. Once the user is at or moving away from the maneuver location, their snapped distance will always be zero. If it's zero, increment the step.
=> Improve slight turn completion heuristic

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/RouteProgress.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/374
In cases where we reroute the user and the new route has a first step which has very long (1km), there is no need to alert the user about the first step. This is because they have ample time until the upcoming maneuver.
=> Suppress reroute announcement on long steps

MapboxNavigation/PollyVoiceController.swift, MapboxNavigation/RouteVoiceController.swift
The reroute ding is never unducked after player. If the reroute sound plays without a subsequent announcement, the user's music will never resume.
=> Unduck rerouteSoundPlayer

MapboxNavigation/DefaultLocationManager.swift
Fixed a memory leak in DefaultLocationManager. DefaultLocationManager observes battery state changes via KVO, not NotificationCenter.
/cc @frederoni
=> Unregister battery state observation

MapboxCoreNavigation/RouteController.swift
Followup to https://github.com/mapbox/mapbox-navigation-ios/pull/382
We got a lot of feedback that the lack of information after rerouting was troubling. Now, if the first step of the new reroute is short, alert the user of it. Otherwise when the step is long (greater than 0.5km) just let them continue.
/cc @willwhite @1ec5 @ericrwolfe @frederoni
=> Only suppress announcements on long first steps after reroute

MapboxCoreNavigation/RouteController.swift
When rerouting, use the access token and host that were used to make the initial directions request.
/cc @1ec5
=> Reroute using access token and host used to create request

MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/RouteManeuverViewController.swift, MapboxNavigation/RoutePageViewController.swift, MapboxNavigation/RouteStepFormatter.swift
If the upcoming road is a freeway, suppress its name in the turn banner in favor of a textual representation of the route number.
This is a more tightly scoped alternative to #291 based on Project-OSRM/osrm-text-instructions.swift#28. It focuses on the turn banner and leaves the current road name label alone for the time being.
/cc @ericrwolfe @frederoni
=> Suppress freeway names in turn banner

MapboxCoreNavigation/RouteController.swift
Fixed a build warning about an unmutated variable:
```
/path/to/mapbox-navigation-ios/MapboxCoreNavigation/RouteController.swift:183:13: Variable 'eventLoggingEnabled' was never mutated; consider changing to 'let' constant
```
=> Fix build warning in RouteController.startEvents(_:)

MapboxCoreNavigation/ReplayLocationManager.swift, MapboxCoreNavigation/SimulatedLocationManager.swift
Currently, querying `routeController.locationManager.location` when using a simulated location manager returns the device's current location. 
This PR has overrides the `var location: CLLocation` property to return the custom locations from SimulatedLocationManager or ReplayLocationManager
cc @frederoni @1ec5
=> Add 'location' override for NavigationLocationManager subclasses

MapboxNavigation/NavigationViewController.swift
`NavigationViewControllerDelegate.navigationViewController(_:didArriveAt:)` is getting called twice in a row. This change removes the redundant call.
/cc @bsudekum
=> Remove redundant arrival notification

MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/Resources/ca.lproj/Localizable.strings, MapboxNavigation/Resources/es.lproj/Localizable.strings, MapboxNavigation/Resources/fr.lproj/Localizable.strings, MapboxNavigation/Resources/hu.lproj/Localizable.strings, MapboxNavigation/Resources/lt.lproj/Localizable.strings, MapboxNavigation/Resources/sv.lproj/Localizable.strings, MapboxNavigation/Resources/vi.lproj/Localizable.strings, MapboxNavigation/Resources/zh-Hans.lproj/Localizable.strings, MapboxNavigation/RouteManeuverViewController.swift, MapboxNavigation/RouteStepFormatter.swift, MapboxNavigation/RouteVoiceController.swift
Refactored the post-maneuver instruction generation code to account for the road class (as in #410) and moved the code to an extension on RouteStep. Consistently mark up road names and route numbers as addresses when either (but not both) is available on the step in question. In the rare event that a motorway has no name or number, deliver a post-maneuver instruction without the “on [road name]” prepositional phrase.
Project-OSRM/osrm-text-instructions#88 tracks upstreaming this post-maneuver instruction to OSRM Text Instructions.
/cc @bsudekum @ericrwolfe @frederoni
=> Suppress freeway names in post-maneuver instructions

Examples/Swift/CustomViewController.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
This PR moves the user location snapping code from RouteMapViewController in MapboxNavigation to RouteController in CoreNavigation. Conversely, it moves the `snapsUserLocationAnnotationToRoute` property from RouteController in CoreNavigation to RouteMapViewController in MapboxNavigation, where it’s actually used.
RouteController now has public `location` and `snappedLocation` properties, while NavigationViewController has a `snapsUserLocationAnnotationToRoute` property.
Along the way, the current road name label now respects course snapping, and various NavigationMapViewDelegate methods have proper Objective-C names. (Previously, selector pieces ended in dangling prepositions instead of nouns.)
#402 partly refactors the location snapping code as well. I think this PR should land before …
=> Refactor location snapping

MapboxCoreNavigation/RouteController.swift
It is possible to complete a step and go directly from a high alert into another high alert. Because of this, the alertLevelDidChange notification is not firing although the step did increment.
Until we refactor alertLevel, this bandaid should go in as the current implementation is a bug.
/cc @ericrwolfe @1ec5
=> Always fire alertLevelDidChange after incrementing step

MapboxNavigation/RouteMapViewController.swift
Redoing https://github.com/mapbox/mapbox-navigation-ios/pull/421
When I toggled the image, it deemphasized the button. Since it's very important, I'm going to keep the location but as @1ec5 recommended, just hide the logo.
/cc @frederoni
=> Hide logo when resume is enabled

MapboxNavigation/RouteManeuverViewController.swift
A destination code such as `I 75 South` should match the Interstate shield, but a code such as `I 75 Alt` or `I 75 Truck` should not. Bannered routes are usually less important, and it’s misleading to show a bannered route shield without the banner.
For #365, we’ll have an opportunity to display the banner as text to the right of the shield.
/cc @frederoni
=> Avoid matching bannered routes to shields

MapboxCoreNavigation/RouteProgress.swift
Changed the return type for durationRemaining from CLLocationDistance to TimeInterval
=> bug fix on return type for durationRemaining

MapboxNavigation/RouteManeuverViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/434
This changes only to show the lane UI when the user is approaching the intersection. This seems like a good/safe first move.
/cc @ericrwolfe @frederoni @1ec5
=> Only show lanes for medium/high alerts

MapboxNavigation/RouteManeuverViewController.swift, MapboxNavigation/RouteMapViewController.swift
Followup to https://github.com/mapbox/mapbox-navigation-ios/pull/444
@frederoni was right, the check needs to happen inside of the showLanes function. Sometimes, the laneview grey bar shows up without any lanes, this fixes this issue.
/cc @frederoni @ericrwolfe
=> Fix phantom laneview

Examples/Swift/ViewController.swift
We've seen slow speeds when entering navigation mode. Turns out, a lot of time is spent adding actions to the UIAlertController which is not thread safe. This PR defers presenting the controller to the next tick. Feels 💯  and much snappier.
/cc @frederoni
=> Defer presenting UIAlertController

MapboxCoreNavigation/Array.swift, MapboxCoreNavigation/ReplayLocationManager.swift
After a minute, the replaying could lag behind ~10 seconds on a slow simulator due to the average discrepancy of NSTimer. This PR introduces resynchronization on each location update.
```
Started: 71.14s ago actualInterval: 70.99s ago Diff: 0.144978046417236
Total resync diff: 10.3568930029869
```
@ericrwolfe @bsudekum 👀
=> Sync ReplayLocationManager

MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/RouteManeuverViewController.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/Style.swift, MapboxNavigation/UIView.swift, scripts/extract_localizable.sh
The rerouting UI was removed in #464 
This PR adds a new reusable status view that also acts as a rerouting UI.
@bsudekum @ericrwolfe 👀 
_The rerouting ui is presented manually in this gif_
=> Add status view

MapboxNavigation/PollyVoiceController.swift
`try Data(contentsOf: url as URL)` was really blocking up UI rendering. Removing this and moving to an async method for fetching data allows the UI to continue rendering while the data is fetched and unpacked. The UI during speaking is noticeably smoother.
/cc @willwhite @ericrwolfe @frederoni
=> Prevent Polly from making UI laggy

MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/Style.swift
We should hide the status bar once the new route is fetched.
/cc @frederoni
=> Remove reroute status bar after route is fetched

MapboxCoreNavigation/RouteController.swift
While investigating using the instantaneous calculated user course for determining off routing, I discovered that our calculated user course at a given point can be improved. Prior to this, we were looking ahead at two points on a line. Instead of looking at two points at a given distance ahead of the user, we should look at the angles at points ahead and behind the user. This will give a smoother  and more accurate representation of the route snapped course.
/cc @1ec5 @ericrwolfe @frederoni
=> Look at points behind user for snapping

Examples/Swift/ViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/473
`UIAlertController` on the iPad needs to know where to anchor the action sheet.
=> Handle iPads in example app

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/RouteVoiceController.swift
Seconds remaining on a step is currently calculated using the users instantaneous speed. Seconds remaining on step is then used to figure out when to give an alert. If below x give y alert.
This PR moves away from using the users speed and instead calculates seconds remaining by looking at their percent complete and then subtracting this from the step duration. The idea here is that the server can influence a little more about when alerts are give. This also prevents the case where a user speeds up suddenly triggering a premature alert. 
This PR also adds a new `calculateNewAlert(from upcomginStep:)` function which helps in figuring out the alert level on the new step. This will also be useful when improving linked instructions when we move voice logic over to core. …
=> Use calculated speed versus user speed [WIP]

Examples/Swift/ViewController.swift, MapboxNavigation.podspec, MapboxNavigation/DefaultStyle.swift, MapboxNavigation/FeedbackViewController.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/RouteTableViewController.swift, MapboxNavigation/Style.swift
This PR supersedes #463 and fixes #478 by locking down a specific version of Pulley when installing with  CocoaPods.
- Added support for styling floating buttons and the background of the lane view.
- Increased size of the floating buttons.
- Minor tweaks on the feedback view.
@ericrwolfe @bsudekum
=> Various UI tweaks

MapboxCoreNavigation/RouteController.swift, MapboxNavigation/RouteMapViewController.swift
This tries to minimize the floating effect that occurs when initializing the navigation view. Although it's still not perfect, it is a great improvement.
=> Better initial camera

MapboxNavigation/RouteMapViewController.swift
For some reason, viewDidLayoutSubviews is called when a maneuver is completed. To prevent the UI updating the insets/alignment, we should prevent the calls if we already have the desired values.
ref https://github.com/mapbox/mapbox-navigation-ios/pull/482
=> Fix stutter

MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/Style.swift
Fixed the remaining storyboard warnings such as missing trailing constraints and overlapping issues for localized components.
The resume button should look and behave exactly as before but it doesn't suffer from UIButton's mutually exclusive title and image properties.
@bsudekum 👀
=> Fix storyboard warnings

MapboxNavigation/RouteManeuverViewController.swift
This snippet of code tries to remove `0 ft` from the UI. `0 ft` is actually not a bad thing, it indicates to the user that they are really doing something now. Additionally, removes a lot of UI changes that can be confusing.
/cc @frederoni
=> Allow zero feet

MapboxNavigation/RouteMapViewController.swift
Fixes #500 
The regression seems to be the removal of [superview.layoutIfNeeded()](https://github.com/mapbox/mapbox-navigation-ios/pull/490/files#diff-0d0ad16c83aae11e1bceb64204ae864cL627) before grabbing the camera and updating the userTrackingMode.
@bsudekum 👀
=> Fix puck jumps (#500)

MapboxNavigation/RouteMapViewController.swift
Fixed an issue causing the shield in the turn banner to go missing when swiping backwards. This redundant line was clearing the shield image; subsequently, the `roadCode` setter bailed because the `roadCode` had not changed. The `roadCode` setter is responsible for clearing the shield image when no shield should be displayed.
/cc @bhousel @frederoni
=> Avoid redundantly clearing shield image view

Examples/Swift/ViewController.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
This exposes the ability to provide a view for any annotation on the map. In the example, I show how to provide a view for the user puck.
=> Expose mapView(:ViewForAnnotation:)

MapboxCoreNavigation/NavigationLocationManager.swift
~~This PR exposes `isMonitoringBatteryState` so a user can disable it and use their own desired accuracy.~~
=> Expose battery monitoring

MapboxNavigation/RouteManeuverViewController.swift, MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/515
`routePageViewController(:RoutePageViewController:willTransitionTo:)` gets called after each maneuver completion. Because of this, this chunk of code was executing:
```swift
if step == routeController.routeProgress.currentLegProgress.upComingStep {
view.layoutIfNeeded()
mapView.camera = tiltedCamera
mapView.setUserTrackingMode(.followWithCourse, animated: true)
}
```
I'm unsure which one of these is the culprit, but if the user is already in follow with course mode, we should not re-set it or change the camera.
=> Fix camera stutter after completing maneuver

MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/Style.swift
This notifies the user they are currently viewing a route in simulation mode.
@frederoni have any ideas why the background is missing?
=> Alert the user they are in simulation mode

Cartfile, Cartfile.resolved, MapboxCoreNavigation.podspec, MapboxNavigation-Documentation.podspec, MapboxNavigation.podspec
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/522
I don't think there is anything else we should unpin.
/cc @1ec5 @aodhol @frederoni
=> Unpin Mapbox iOS SDK

MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/RouteTableViewController.swift
Undid an unexplained change to a format string that changed the string’s meaning. A couple localizations had already localized the “<” to something locally appropriate, while others had removed the “<” in keeping with the base string.
/ref https://github.com/mapbox/mapbox-navigation-ios/pull/457#discussion_r132809331
=> Restore < to format string

MapboxNavigation/RouteManeuverViewController.swift
[Changeset 51,368,737](http://www.openstreetmap.org/changeset/51368737) adds the first occurrences of Spanish cardinal directions in `destination:ref` tags. This change adds the Spanish cardinal directions alongside the English and French ones, to facilitate shield selection. (Shields.plist currently includes a generic oval shield for Puerto Rico’s routes. In order to choose the correct design among the island’s three shield designs, OSRM would need to look at the route relations instead of the way `ref` tags.)
/ref Project-OSRM/osrm-text-instructions#119
=> Add Spanish cardinal directions to ref parsing

MapboxNavigation/MGLMapView.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/523
=> Move arrow when maneuver is swiped

MapboxNavigation/NavigationViewController.swift
Follow up https://github.com/mapbox/mapbox-navigation-ios/pull/519
On load, we were applying all styles. We should only apply the styles that are needed for that time of day.
=> Only apply appropriate style on load

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/RouteController.swift
If the course is inaccurate or the speed is low and the user is on the route, we should just snap them. The case we're guarding against here is a user sitting in traffic where the course cannot be trusted.
=> Snap location and course when speed is low

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/MBRouteController.h, MapboxCoreNavigation/MBRouteController.m, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/RouteVoiceController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/530
Gives a heads up to the user that the routeController has found a faster route.
=> Indicate to the user a faster route was found

MapboxCoreNavigation/RouteController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/461
Defers the `startEvents` until `usesDefaultUserInterface` has a chance to be set with a proper value.
=> Use proper user agent identifier

MapboxNavigation/DefaultStyle.swift
If the dark style is loaded before the light style, the button tint color will not reset without this line.
=> Reset floating button color properly

MapboxNavigation/NavigationViewController.swift
This fixes an issue that caused the route line to not update after rerouting. This is a crazy codepath, but this guard was truthful too often https://github.com/mapbox/mapbox-navigation-ios/blob/e3860c9f388dd5de7b3599d984fadfe2c910024f/MapboxNavigation/NavigationViewController.swift#L433
[view.window here](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteMapViewController.swift#L542) would then remain false as we update the UI by removing and adding views.
/cc @1ec5 @frederoni @willwhite @lxbarth
=> Set styleTypeForTimeOfDay on init

MapboxNavigation/RouteTableViewController.swift
When the nav ui mounts, we momentarily show the ETA with the default `DateComponentsFormatter` options which includes seconds. It looks like setting the options in `viewWillAppear` is not early enough.
=> Don't show seconds in ETA

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/RouteController.swift
We've noticed the user puck unsnapping from the route line in cases it should not be. Larger, wider roads can see this often. By increasing the max snapping distance, the user will be snapped more often. The downfall here is that when the user is actively leaving the route, the user will appear snapped to the route for a moment longer. In my testing, it looked fine.
This also moves to not use the user's course when we deem the course or speed invalid. In this case, we snap the users location and also use a calculated course.
=> Increase snapped distance, don't use course if it is bad

MapboxCoreNavigation/RouteStepFormatter.swift, MapboxCoreNavigation/String.swift
Came across a case where polly speaks `N Street NW` as `North Street NW`. The if-first-word-in-ref code we had in place for refs should also be applied to `.wayName, .destination, .rotaryName`.
/cc @ericrwolfe @frederoni @1ec5
=> Limit interpret-as=address to numbers in road names

MapboxCoreNavigation/NavigationRouteOptions.swift
This ensures the directions API will always try and find a location to snap to. Without this option set to -1, the directions API will drop a few requests when long pressing in the example app.
/cc @1ec5
=> Set waypoint accuracy

MapboxNavigation/DayStyle.swift, MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/Style.swift
Added a new class for turn arrows so we can style them separately based on if they are in the table view or the maneuver banner.
@bsudekum 👀
=> Split turn arrow styling

MapboxNavigation/DayStyle.swift, MapboxNavigation/NavigationViewController.swift
Fixes the issue we've been seeing where the night style is using the day map style.
@ericrwolfe 👀
=> Update styleURL if needed

MapboxCoreNavigation/SpokenInstructionFormatter.swift
I mixed up the constants name in a big way... 🤦‍♂️ 
We are were linking instructions when the next step had a duration of less than 225 seconds, yikes.
/cc @frederoni @ericrwolfe @1ec5
=> Use correct linking multiplier

MapboxCoreNavigation/CLLocation.swift
A speed of -1 is not a qualified location.
/cc @1ec5 @ericrwolfe @frederoni
=> Filter out negative speeds

MapboxNavigation/TurnArrowView.swift
Use the roundabout icon in the turn banner for “take rotary” steps.
/cc @frederoni
=> Display roundabout icon for rotaries

MapboxNavigation/LaneArrowView.swift
If the maneuver direction appears to contradict the lane indication by going to the opposite side, it’s probably because of a fork in which a lane can be used to take either branch. In that case, ignore the invalid branch and show only the valid branch, going in the same direction as the maneuver.
Ideally, we’d show the invalid branch dimmed out, but we currently lack artwork for a left-right turn lane. So this is essentially a workaround for part of #576.
Here’s the before and after:
=> Fix lane arrows at forks

MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/582
When failing to reroute, we were showing the reroute UI. Since this notification user object is different from the reroute key, we'd get a crash. This was introduced in https://github.com/mapbox/mapbox-navigation-ios/commit/7334aa565a22b8ab62e027943db529dc019544d2
If we'd like to show something in the UI when failing to reroute, `RouteControllerDidFailToReroute` should call it's own unique function.
=> Dont show reroute UI when failing to reroute

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/RouteProgress.swift
If the users course is within a few degrees of a heading at an intersection along a step, we can assume they are going off course and we can reroute them sooner. 
todo: 
This will require a lot of real world testing.
/cc @1ec5 @ericrwolfe @frederoni
=> Reroute faster at intersections

MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteTableViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/594
When the user is not moving, we should still be able to give them accurate info about their trip.
This also removes a few functions that existed just to call another function.
=> Update ETA info when stale

MapboxCoreNavigation/RouteController.swift
If the first location update is not `isQualified` and the user is not moving, the user puck and other information is never shown. This makes sure we update the UI and user puck location at least once if it's the first location update.
=> Always map first location update

MapboxCoreNavigation/ScreenCapture.swift
Fixes: https://github.com/mapbox/mapbox-navigation-ios/issues/592
Verifying we're still getting an image with this change:
/cc @frederoni
=> Prevent flash when capturing screen

MapboxNavigation/NavigationViewController.swift
The timer needs to be invalidated before reseting it. This caused all sorts of memory leaks.
=> Fix timer leak

MapboxCoreNavigation/RouteProgress.swift
If you add up all the step coordinates, it will be equal to the route geometry count plus the number of steps. This is because each step shares a coordinate with the next step. Previously, our lookups into this array were a little off since we were not removing the last coordinate which is shared. 
This also adds a guard to check that our array lookup is also within bounds.
/cc @1ec5
=> Fix congestion segment and guard

MapboxCoreNavigation/DistanceFormatter.swift
This PR avoids confusion like #606 by linking `string(from:)` and `string(fromMeters:)`.
`DistanceFormatter.string(fromMeters:)` previously used `NSLengthFormatter`’s default which could result in yards. `DistanceFormatter` is a replacement for `MKDistanceFormatter` which leverage some of `NSLengthFormatter`’s functionality but there's no reason why `string(fromMeters:)` shouldn't work the same way as `string(from:)`.
@ericrwolfe @bsudekum
=> Override string fromMeters

MapboxCoreNavigation/RouteStepFormatter.swift, MapboxCoreNavigation/String.swift, MapboxNavigation/Abbreviations.swift
Rely on the standard library’s word enumeration functionality to more reliably abbreviate strings (for the road name in the turn banner) and insert SSML markup (for numbers in voice instructions). Now this code can correctly handle arbitrary punctuation surrounding words, as well as languages that don’t delimit words with spaces.
=> Abbreviate and markup with SSML more robustly

MapboxNavigation/RouteVoiceController.swift
On longer routes, since we were not cleaning up timers correctly, a user could get two announcement voices. 
=> Fix leaky announcement timer

MapboxNavigation.podspec
Added some Swift files that contain extensions on standard library classes to the MapboxNavigation podspec, reflecting the fact that these same files are shared between the MapboxCoreNavigation and MapboxNavigation targets in the Xcode project.
By selectively sharing files between targets (and now pods), we can avoid unnecessarily making symbols public just because they need to be used by both libraries. However, we should keep this technique to a minimum, since usually anything that’s worth exposing to MapboxNavigation is also worth exposing publicly to dependents of Core Navigation.
I slipped this change into MapboxNavigation.podspec before pushing v0.8.0 to CocoaPods trunk. This PR makes the change permanent.
=> Share some extension files with MapboxNavigation pod

MapboxNavigation/PollyVoiceController.swift
Adds the a custom Polly ssml effect `<amazon:effect name="drc">`. From the docs:
> Depending on the text, language, and voice used in an audio file, the sounds range from soft to loud. Environmental sounds, such as the sound of a moving vehicle, can often mask the softer sounds, which makes the audio track difficult to hear clearly. To enhance the volume of certain sounds in your audio file, use the dynamic range compression (drc) tag.
[ref](https://docs.aws.amazon.com/polly/latest/dg/supported-ssml.html#drc-tag)
=> Add  dynamic range compression (drc) ssml effect

Examples/Swift/ViewController.swift, MapboxNavigation/NavigationViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/643
This turns on auto style switching at sunset and the feedback button by default. These features help users and have been tested now are ready.
=> Make feedback and style switching on by default

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/RouteProgress.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/639
This addresses two issues:
1. When a step has coordinates that are close to the current step (think in a uturn), we sometimes snap to the wrong step coordinates. To fix this, when the upcoming maneuver modifier is a uturn, we only look at the current step coordinates for snapping
1. There is a bug in OSRM where exit bearings are calculated incorrectly. This prevents us from incrementing the step counter because the users course never is equal to the exit bearing. This hack should be removed when fixed upstream.
/cc @danpat @1ec5 @frederoni
=> Fix uturn step increment and snapping

MapboxCoreNavigation/RouteController.swift
If the user is moving away from the maneuver (whips a uturn on a country road half way down a step), we should reroute them once we know they are really moving away.
The gist:
* Calculate distance to maneuver
* add to an array
* check the last distance in the array. If it's greater than the previous distance, add it
* if this array grows to be greater than 3 distances, reroute.
=> Reroute when the user is moving away from maneuver

MapboxNavigation/PollyVoiceController.swift
This times out polly requests after 2 seconds. I'm keeping this low because voice instructions are very time/location based and can become outdated quickly.
=> Timeout polly requests sooner

MapboxNavigation/RouteVoiceController.swift
Now that https://github.com/mapbox/mapbox-navigation-ios/pull/635 is in, we do not need to overcompensate by increasing the voice volume. https://github.com/mapbox/mapbox-navigation-ios/pull/635 itself does increase the volume slightly.
=> Reduce default volume

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/SpokenInstructionFormatter.swift
We've been omitting departure instructions like `Head west on foo street.`
This change now makes departure instructions:
* Upcoming maneuver is > 2000 meters: `Continue west on foo street for 5 miles.`
* Upcoming maneuver is relatively close, less than 2000 meters: `Head west on foo street, then in 0.7 miles, turn right onto bar street.`
* Upcoming maneuver is very close: `Turn right onto bar street`.
Note, this only can occur when on the departure step and the alert level is .depart or .low.
=> Improve departure announcement

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/RouteProgress.swift, MapboxCoreNavigationTests/RouteProgressTests.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/659
I ran into a rough intersection (https://github.com/mapbox/mapbox-navigation-ios/issues/659) this weekend that surfaced a few issues. Noting, whether this intersection should only be one maneuver (it should) is outside of the scope of this PR.
1. Our final check before rerouting to see if the user is on the next step should also check on the followOnStep
1. Using `.uTurn` as the red flag to only snap to the current step, is false. it should be the angle of the maneuver. When sharp, look 
1. In some cases on shorter steps, location updates might be very scarce. Because of this, we don't have a user course to compare to see if they user has completed a maneuver. In this case, we can check if the user has first entered the …
=> Improve steps with short distances

MapboxCoreNavigationTests/RouteProgressTests.swift, MapboxNavigation/PollyVoiceController.swift
We're getting reports of overlapping polly and speech synth instructions. This perhaps is a sledgehammer approach to fixing the bug, however at some point this addition makes sense.
This also makes sure the audio player is ready to play before playing the audio.
=> If audioPlayer is playing, don't also play fallback voice

MapboxNavigation/PollyVoiceController.swift
We need to make sure we stop the audio player and also cancel any outstanding polly requests before playing another instruction. 
I sincerely hope this is the last of the overlapping-voice-bug-reports.
=> Cancel outstanding polly requests and stop player

MapboxCoreNavigation/NavigationLocationManager.swift
We're getting reports that the user puck is drifting a lot when the device is unplugged. In this case, we `kCLLocationAccuracyBest`. Let's test using `kCLLocationAccuracyBestForNavigation` in all situations.
/cc @1ec5 @pveugen @frederoni @ericrwolfe
=> Force kCLLocationAccuracyBestForNavigation

MapboxNavigation/PollyVoiceController.swift
We removed setting the delegate when playing Polly instructions. This prevents the audio from ducking and unducking.
ref https://github.com/mapbox/mapbox-navigation-ios/pull/661/files#diff-28c26f31f650815a074b41e628688918L157
=> Make sure to set audio player delegate

MapboxNavigation/NavigationViewController.swift
Fixes #676 
We reload the table view’s data when the `RouteController` triggers a reroute but it was left out for manually setting a new route.
@bsudekum 👀 
/cc @AFcgi
=> Reload table view data after updating route manually

MapboxCoreNavigation/NavigationRouteOptions.swift, MapboxCoreNavigation/SimulatedLocationManager.swift
Fixes #440 - Simulate expected speed
Falls back to turn penalty based speed if `RouteLeg.segmentSpeeds` is missing.
=> Simulate expected speed

MapboxCoreNavigation/NavigationRouteOptions.swift, MapboxCoreNavigation/SimulatedLocationManager.swift
Addresses https://github.com/mapbox/mapbox-navigation-ios/pull/683#discussion_r142565325
Instead of increasing the response payload by adding speed, derive it from expected travel time.
=> Optimize simulation

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/RouteController.swift
This seeks to improve the user puck snapping feature. The goal here is to not allow bad location updates from moving the user puck off the route when the user is clearly on the route. There are two ideas here I'm moving towards:
1. Snapping should always snap. It should have to worry about filtering bad locations. We should just always snap.
1. Rerouting can occur while snapped. 
It's important though to allow movement when the user is actually moving off the route- taking a left instead of a right for example. I did add a bit of code to allow actual locations and course to be used. If the user's course/location is not what we expect it to be and their location accuracy is high, use the raw location/coordinate. 
Tested this today, it performed well.
=> Improve location snapping and filtering

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/SpokenInstructionFormatter.swift
Detect a U-turn or wrong turn based on the distance the user covered while backtracking; don’t compound the distance from the maneuver, which may be far away in the first place. For example, if the last three location updates are 51, 52, and 53 meters away from the maneuver, the user has backtracked by two or so meters, not 156 meters. Also renamed a couple constants.
This is a followup to #679 and #646.
/cc @cammace @bsudekum
=> Fix U-turn detection

MapboxNavigation.podspec
Solar 2.1.0 breaks backwards compatibility, causes it to stop compiling:
```Incorrect argument labels in call (have 'latitude:longitude:', expected 'for:coordinate:'...```
So I fixed the dependency version on minor version 2.0.0
=> Fix Solar dependency on minor version 2.0 to prevent from updating to 2.1

MapboxNavigation/NavigationMapView.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/695 & https://github.com/mapbox/mapbox-navigation-ios/issues/691
I'm uncertain in which cases this can occur, but we should check and guard first before making this lookup.
=> Guard out of bounds

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/RouteController.swift
Reverts https://github.com/mapbox/mapbox-navigation-ios/pull/84
We can rely on not rerouting the user until they have moved x meters away from the last location instead of waiting x seconds. I think this can cause a delay in rerouting when starting a route with poor wifi signal.
=> remove departure timer

MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/702
It seems in some cases, `didReroute`  is not called after `willReroute`. To prevent the statusView from sticking around, we should hide it after a few seconds.
/cc @frederoni
=> Always hide reroute UI

MapboxNavigation/NavigationViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/651
It's just not necessary to give this notification. They should only be given when the user is approaching a maneuver.
=> Remove local notification after rerouting

MapboxCoreNavigation/RouteController.swift
I noticed quite a few times this weekend the user puck would spin when I was not moving at stop lights. This should prevent this while still allowing the actual course while rerouting.
=> Prevent spinning when user is not moving

MapboxNavigation/NavigationMapView.swift
Fixes #722 
Disable throttling during frame by frame positioning of the user course view.
@bsudekum 👀
=> Don't throttle during frameByFrame tracking

Examples/Swift/ViewController.swift
Fixing issue in Example swift app where a "Multiple Stops" action gets added multiple times and is selectable at inappropriate times.
Fun screenie:
=> Swift Example App - "Multiple Stops" bug

MapboxNavigation/NavigationMapView.swift
Fixes #725 
Specify max zoom for shape source to overcome issues like → https://github.com/mapbox/mapbox-gl-native/issues/9529
@bsudekum @kkaefer 👀
=> Set max zoom on shape sources

MapboxNavigation/FeedbackViewController.swift
We need to set the delegate here so we can listen on when the [audio recorder did finish](https://github.com/mapbox/mapbox-navigation-ios/blob/cbbf7f8696e9a445ded53269c2b6b18226255d34/MapboxNavigation/FeedbackViewController.swift#L143).
/cc @frederoni
=> Set AVAudioRecorderDelegate

MapboxNavigation/PollyVoiceController.swift
_Prerequisite https://github.com/mapbox/mapbox-navigation-ios/pull/614_
It's relatively dumb right now, when we fire the notification to say something:
1. Check if the instruction is a key on `RouteProgress.spokenInstructionsForRoute` and has data.
1. If so, use this data to give the instruction
1. If not, first say the instruction using the normal methods
1. After we say it, we then look and see if the user has any upcoming steps
1. If so, get all instructions for step, download the data and add it to `RouteProgress.spokenInstructionsForRoute`
1. Repeat
/cc @1ec5 @frederoni @ericrwolfe @JThramer
=> Prefetch audio instructions

MapboxNavigation/NavigationViewController.swift
The value set on showsReportFeedback is ignored as it is used only on init.
This PR fixes that.
=> Use value set on showsReportFeedback

MapboxNavigation/FeedbackViewController.swift
Fixing issue where the FeedbackViewController never advertised itself as a `UIGestureRecognizerDelegate`, so it was never asked if the gesture recognizer `shouldRecieveTouch`.
/cc @frederoni @bsudekum @ericrwolfe
=> UITapGestureRecognizer / UICollectionViewDelegate issues

MapboxCoreNavigation/RouteController.swift
This fixes an issue where we were not returning the delegate method for arriving at the final way point and also, while the user is not at the final waypoint, we should always be tracking user progress. Progress updates should only end when arriving at the final waypoint.
/cc @ericdeveloper @1ec5 @frederoni @ericrwolfe @JThramer
=> Waypoints fix

MapboxCoreNavigation/Feedback.swift, MapboxCoreNavigation/MMEEventsManager.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/DayStyle.swift, MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/Resources/Base.lproj/Navigation.strings, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/Style.swift
Fixes #780 and right align floating buttons
Note that the reroute items were removed after the recording.
@ericrwolfe @bsudekum 👀
=> Post-reroute feedback

MapboxNavigation/FeedbackViewController.swift
We've seen a few crashes when requesting mic permissions. This change allows self to nil in some cases, ref [stack overflow](https://stackoverflow.com/questions/24177973/why-self-is-deallocated-when-calling-unowned-self).
/cc @frederoni @1ec5 @JThramer
=> Allow optional self

MapboxCoreNavigation/RouteProgress.swift
We've been seeing a few crashes at this array lookup. This first to makes sure `spokenInstructionIndex` is not larger than `instructionsSpokenAlongStep` before doing a lookup .
=> Check spokenInstructionIndex is less than instructionsSpokenAlongStep

MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/RoutePageViewController.swift
Implements #795. Not the most elegant solution in the world, but without `RouteManeuverViewController` knowing about the concept of `RouteProgress`/`StepProgress`, `notifyDidChange(routeProgress:stepProgress:)` is the only real way (without going down a rabbit hole) to prompt the RMVC to update the `InstructionsBannerView` to the correct values.
-  Fixing issue where carousel would display incorrect information momentarily when recentering by notifying current maneuver cell about it's progress immediately after presentation.
=> update currentManeuverPage with current values immediately after transition

MapboxNavigation/PollyVoiceController.swift
Since Polly is played via an `AudioPlayer`, we need to set it to the active audio session to allow it to play while the physical mute switch is enabled. `duckAudio`, does just accomplished this for us. I feel like I've re-added this line a few times now.
/cc @frederoni @ericrwolfe @JThramer
=> Allow audio while mute switch enabled

MapboxNavigation.xcodeproj/project.pbxproj
The Swift and Objective-C example applications now rely on [a Run Script build phase](https://www.mapbox.com/help/ios-private-access-token/) to apply the Mapbox access token at build time. This makes it less likely that those working in this repository will inadvertently expose their own access tokens to the public.
/cc @bsudekum
=> Manage access token via unversioned file

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/Instruction.swift, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/DayStyle.swift, MapboxNavigation/InstructionLabel.swift, MapboxNavigation/NextBannerView.swift, MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/UIImage.swift, MapboxNavigationTests/InstructionsBannerViewTests.swift
Fixes #469 
Adds a banner for the subsequent step under the instructions banner.
@bsudekum @ericrwolfe @JThramer
=> Show subsequent step under banner

MapboxNavigation/RouteMapViewController.swift
Do not show next banner if lanes are visible and ensure the next banner is hidden when showing lanes.
@bsudekum 👀
=> Avoid showing next banner if lanes are visible

MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
Previously, the bottom of the feedback UI cutoff some text on the iphone x.
/cc @frederoni
=> Expand feedback UI slightly

Examples/Swift/ViewController.swift, MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/FeedbackViewController.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
Property names should never begin with an imperative verb, in part because that makes it impossible to distinguish a property from an action method in Objective-C. The same requirement [holds true in Swift](https://swift.org/documentation/api-design-guidelines/#boolean-assertions):
> Uses of Boolean methods and properties should read as assertions about the receiver when the use is nonmutating.
This PR also makes the opportunistic background rerouting interval configurable and moves the spoken instruction debugging option from RouteController to NavigationViewController, where UI options belong.
Fixes #756 and fixes #757.
/cc @bsudekum @JThramer
=> Eliminate imperative mood from property names

MapboxCoreNavigation/CLLocation.swift
We're seeing strangely high vertical accuracy on the iPhone X. Vertical accuracy does not really help us determine whether or not a location is good except in the case it is -1 when the location is determined by wifi only.
/cc @1ec5 @frederoni @ericrwolfe @JThramer 
Example json:
```
{
"locations": [
{
"altitude": 8.340122319829732,
"course": 268.9399826448163,
"horizontalAccuracy": 32,
"lat": 38.912786807157765,
"lng": -77.00992836558446,
"speed": 6.848177433013916,
"timestamp": "2017-11-10T03:09:36.011+0000",
"verticalAccuracy": 48.44074249267578
},
{
"altitude": 7.344383967021443,
"course": 265.8569718572559,
"horizontalAccuracy": 32,
"lat": 38.912782113908065,
"lng": -77.01002210271703,
"speed": 7.3876190185546875,
"timestamp": "2017-11-10T03:09:37.011+0000",
"verticalAccuracy": …
```
=> Rely less on vertical accuracy for filtering out bad locations

MapboxNavigation/NavigationMapView.swift
Fixes #847 
Unlike subclasses in Objective-C, Swift 4 subclasses do not inherit their superclass initializers by default, unless it's safe to do so, such as generic classes.
@bsudekum 👀 
/cc @ericdeveloper
=> Expose MGLMapView init(frame:styleURL:)

MapboxNavigation/NavigationMapView.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/812
If the upcoming maneuver is easy and straight, we can remain in throttled fps mode.
=>  Allow throttled FPS if upcoming maneuver is straight

MapboxNavigation/RouteMapViewController.swift
It's hanging around for too long. It gets awkward when you don't want to tap it after a reroute.
=> Show report feedback button for 5 seconds

Examples/Swift/ViewController.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/PollyVoiceController.swift, MapboxNavigation/RouteVoiceController.swift
Followup to https://github.com/mapbox/mapbox-navigation-ios/pull/800
This adds:
* ~~A routeProgress object to both voice delegate methods.~~
* Overlap will be triggered in `RouteVoiceController` as well.
* Improves the named arguments in the overlap method.
/cc @1ec5
=> Improve voice delegates

MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/862
We want to show the nextBanner when:
* the user is close to the end of their current step
* The follow on step is short
This cleans up the logic to make it a little more clear.
/cc @1ec5 @ericrwolfe @JThramer @frederoni
=> Fix when next banner is visible

Examples/Swift/Info.plist, Examples/Swift/ViewController.swift, MapboxCoreNavigation/MMEEventsManager.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/FeedbackItem.swift, MapboxNavigation/FeedbackViewController.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/RouteMapViewController.swift
Fixes: https://github.com/mapbox/mapbox-navigation-ios/issues/866
This removed audio recording since it was not used very much and it required developers to provide 
`NSMicrophoneUsageDescription` even if they were not using the feature.
/cc @frederoni @diegogarciar
=> Remove audio recording

README.md
The current documentation for installing `v0.11.0-rc.1` will fail due to a syntax error.
=> Fix pod installation syntax in documentation

MapboxNavigation/RouteMapViewController.swift
Fixes #880 
Update course tracking when the application will enter foreground.
=> Resume tracking quickly when application will enter foreground

MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/LanesContainerView.swift, MapboxNavigation/NextBannerView.swift, MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/StatusView.swift, MapboxNavigation/Style.swift, MapboxNavigationTests/InstructionsBannerViewTests.swift
Fixes #844 
This PR moves constraints responsible for the intrinsic content size away from the storyboard into each component (Next banner, status view, lanes).
=> Move constraints from storyboard into components

MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/877
We were piggy backing off of voice announcements to trigger waypoint arrivals. This is not really a good idea in practice since we don't really know when a voice announcement will be given. Instead, when we know the user is within x meters of the waypoint, say that they are there.
/cc @TCOA @ashishke2m @mapbox/navigation-ios
=> Decouple waypoint arrival from voice announcements

MapboxNavigation/RouteMapViewController.swift
We're getting a few crash reports that looks like
```
#0. Crashed: com.apple.main-thread
0  MapboxNavigation               0x10093eae4 RouteMapViewController.updateETA() (RouteMapViewController.swift:620)
1  MapboxNavigation               0x10093eb04 @objc RouteMapViewController.updateETA() (RouteMapViewController.swift)
2  Foundation                     0x19085e2e4 __NSFireTimer + 88
3  CoreFoundation                 0x18fcf71d8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
4  CoreFoundation                 0x18fcf6eec __CFRunLoopDoTimer + 872
5  CoreFoundation                 0x18fcf67a8 __CFRunLoopDoTimers + 244
6  CoreFoundation                 0x18fcf43a4 __CFRunLoopRun + 1572
7  CoreFoundation                 0x18fc222b8 CFRunLoopRunSpecific + 444
8 …
```
=> Fix leaky timer

MapboxNavigation/RouteMapViewController.swift
Before, the user puck would float back to the beginning of the route and then jump back to the current location. Now:
=> Better initial view when completing leg

MapboxCoreNavigation/RouteController.swift
Reverts change in https://github.com/mapbox/mapbox-navigation-ios/pull/883/files#diff-1a2149692b3d7c58b6a0392120d6011aR764
We shouldn't be incrementing the steps/leg index if there are not any waypoints remaining. Without this, we crash.
=> Fix incrementing beyond steps.count

MapboxNavigation/BottomBannerView.swift
Fixes unknown traffic color when we can't calculate congestion level.
@bsudekum @pveugen 👀
=> Fix unknown traffic color

MapboxCoreNavigation/String.swift, MapboxNavigation/PollyVoiceController.swift, MapboxNavigation/RouteVoiceController.swift
This change provides AVSpeechSynthesizer with the same phonetic names that #622 provides Polly with. This way the AVSpeechSynthesizer fallback remains consistent with Polly in terms of its pronunciation of difficult names. The closer the two voices’ pronunciation, the less jarring it is when the fallback kicks in.
AVSpeechSynthesizer doesn’t support SSML; instead, on iOS 10 and above, it uses the native NSAttributedString type to hold attributes such as pronunciations. It turns out that the Alex voice (#612) does not support attributed strings, but it manages to correctly pronounce just about all the roads that are currently tagged with pronunciations anyways.
~~Depends on #621, mapbox/MapboxDirections.swift#174, and Project-OSRM/osrm-text-instructions.swift#39.~~
=> Supply phonetic road names to AVSpeechSynthesizer

MapboxNavigation/RouteVoiceController.swift
The code applying pronunciation attributes to an instruction string in #624 was off by one step. It also crashed if the step’s street name was absent from the instruction for some reason.
/cc @bsudekum
=> Fix crash adding pronunciation to instructions

MapboxCoreNavigation/SimulatedLocationManager.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/Resources/Base.lproj/Navigation.strings, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/StatusView.swift
Fixes #694 
Slide left or right on the "Simulation Navigation" banner to increase or decrease the speed respectively.
The user puck is not really in sync at these high speeds.
@bsudekum @JThramer  👀
=> Adjustable simulation speed

MapboxNavigation/RouteMapViewController.swift
Fixes #919, where an order-of-operations issue was causing UIKit to trigger for unsatisfiable constraints. This did not manifest at runtime before because the constraints "satisfied" themselves before the next layout pass.
* Changing constraint order-of-operations to avoid a `UIViewAlertForUnsatisfiableConstraints` breakpoint.
=> Constraint Fix

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/RouteProgress.swift
We currently have a last ditch effort before rerouting to see if the user is somehow on the upcoming or follow on step.
This changes to check if the user is on any future step. If the user is with a certain radius to this new step, we increment the stepIndex to this new step.
/cc @mapbox/navigation
=> Check all future steps

MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile, MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock, MapboxNavigation.xcodeproj/project.pbxproj
This removes last vestige leftover from #767. Not all instances of OSRM Text Instructions were removed.
=> Remove OSRM Text Instructions fully

MapboxNavigation.xcodeproj/project.pbxproj
Fixes #927 avoid nested dependencies
@1ec5 @bsudekum
=> Remove copy frameworks script

CONTRIBUTING.md, README.md
Added a Markdown document that describes how someone from the open source community can contribute to this project, whether in the form of a bug report, feature request, translation, or code. This document is loosely based on [the corresponding iOS map SDK document](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md) published in mapbox/mapbox-gl-native#3416.
@mapbox/navigation-ios @mapbox/guidance @captainbarbosa, can you think of anything else worth noting?
/ref https://github.com/mapbox/mapbox-navigation-ios/pull/928#issuecomment-351517617
=> Offer contributing guidelines

MapboxCoreNavigation/RouteProgress.swift, MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
_Followup to: https://github.com/mapbox/mapbox-navigation-ios/pull/910_
In this final check, we are not accounting for the fact that we're are looking at the [slice](https://github.com/mapbox/mapbox-navigation-ios/compare/fix-reroute-future-check?expand=1#diff-851f438872328e98cbe395ac0733c16bR315) of the route's steps.
Take for example:
The current stepIndex is 5, we look at the remaining steps, find the closest to be 6. The closest step would be found in the iteration through this for loop, with a `currentStepIndex `. We Should return the index count in the for loop _plus_ the current stepIndex to get 6.
=> Account for current stepIndex as well

MapboxNavigation/RouteMapViewController.swift
We were basically only showing the then banner when arriving at a waypoint and if that final step is short.
=> Fix when we show the then banner

README.md
A usage example in the readme referred to a non-existent initializer of NavigationRouteOptions.
/cc @bsudekum @captainbarbosa
=> Correct usage example in readme

MapboxCoreNavigation/NavigationRouteOptions.swift
By default, this is false.
/cc @mapbox/navigation
=> Include roundabout exits

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
While investigating https://github.com/mapbox/mapbox-navigation-ios/pull/937, I found another bug: we're often times doing the `ultimate-is-the-user-on-another-step` check too often. 
I was able to debug https://github.com/mapbox/mapbox-navigation-ios/pull/937 because when the user is moving quickly over straight maneuvers, we call the `ultimate-is-the-user-on-another-step`. This is totally unnecessary, we should only be doing this check when the user is not on the route. 
The change here, changes `monitorStepProgress ` to run before `userIsOnRoute `. This allows us to increment the step if the user has completed the step before checking if the user is on the route. This is important because when the user is moving quickly, the user can be beyond the last coordinate in on the step. In …
=> Allow step to increment before checking for reroute

MapboxCoreNavigation/MMEEventsManager.swift
This was always either 0 or 100.
=> Fix battery level

MapboxNavigation/ManeuverView.swift
As far as I know, the U-turn icon is already flipped correctly in countries that drive on the left. But checking the turn angle is unintuitive compared to checking the driving side.
The only downside would be U-turns that turn to the wrong side, which are pretty uncommon as far as I know. I can only think of [one example](http://www.openstreetmap.org/way/524469535) of a U-turn to the right in a right-sided country, and that’s more of a fanciful turn lane indication than an actual U-turn.
/cc @bsudekum
=> Flip U-turn icon in right-side regions only

MapboxNavigation/RouteMapViewController.swift
Third times a charm 😄 
We should not be comparing the current duration remaining, but rather the length in time the upcoming step is expected to take.
=> Fix next step banner

MapboxCoreNavigation/RouteController.swift
When snapping and looking at points ahead/behind user, we should not use the point ahead/behind if it has a distance of zero. In this case, the user is either at the beginning or end of the route. When using a point that has a distance of zero, the calculated course becomes wildly inaccurate causing spinning. 
=> Prevent user puck spinning at end of route

MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/964
This moves to call the cancel feedback event when the RouteController is deinited. Unfortunately had to make some properties public.
/cc @mapbox/navigation-ios @ericrwolfe
=> Always send cancel event even when using mapbox-core-navigation

MapboxNavigation/EndOfRouteViewController.swift, MapboxNavigation/RatingControl.swift, MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/Resources/Base.lproj/Navigation.strings
Minor tail work from https://github.com/mapbox/mapbox-navigation-ios/pull/848
- Add `DO NOT TRANSLATE` to placeholder labels in IB
- Provide a default translated string for `NSLocalizedString(_:tableName:bundle:value:comment:)`
- Run `extract_localizable`
@JThramer 👀
=> Localize feedback

MapboxNavigation/BottomBannerView.swift
Seeing a few crashes come through that look like:
```
0  MapboxNavigation               0x103757004 RouteMapViewController.updateETA() (RouteMapViewController.swift:761)
1  MapboxNavigation               0x103757024 @objc RouteMapViewController.updateETA() (RouteMapViewController.swift)
2  Foundation                     0x183e7bd24 __NSFireTimer + 88
3  CoreFoundation                 0x18343292c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
4  CoreFoundation                 0x183432650 __CFRunLoopDoTimer + 864
5  CoreFoundation                 0x183431e50 __CFRunLoopDoTimers + 248
6  CoreFoundation                 0x18342fa38 __CFRunLoopRun + 1928
7  CoreFoundation                 0x18334ffb8 CFRunLoopRunSpecific + 436
8  GraphicsServices               0x1851e7f84 …
```
=> Account for a few optionals

MapboxCoreNavigation/RouteProgress.swift
Follow up to https://github.com/mapbox/mapbox-navigation-ios/pull/937
We should never just return `currentStepIndex`, it should always be `currentStepIndex` plus the route progress `stepIndex`.
=> Return correct index on first loop

MapboxCoreNavigation/RouteController.swift
Seeing crashes that look like:
```
Crashed: com.apple.main-thread
0  MapboxCoreNavigation           0x10284b8c8 RouteController.advanceStepIndex(to:) (RouteController.swift:810)
1  MapboxCoreNavigation           0x102856754 specialized RouteController.userIsOnRoute(_:) (RouteController.swift:616)
2  MapboxCoreNavigation           0x10284b8fc @objc RouteController.userIsOnRoute(_:) (RouteController.swift)
3  MapboxCoreNavigation           0x102855d94 specialized RouteController.locationManager(_:didUpdateLocations:) (RouteController.swift:556)
4  MapboxCoreNavigation           0x10284b3f4 @objc RouteController.locationManager(_:didUpdateLocations:) (RouteController.swift)
5  CoreLocation                   0x18cf68d48 CLClientRetrieveData + 77436
6  CoreLocation …
```
=> Don't allow advancing to non-existent  step

Examples/Swift/ViewController.swift, MapboxNavigation/NavigationViewController.swift
As of right now, this function is only returning didArriveAt waypoint for the last waypoint and not all waypoints.
=> Emit didArriveAt waypoint delegate for all waypoints

MapboxNavigation/RouteMapViewController.swift
We need to make sure the view is loaded before we can call  `RouteMapViewController.updateETA(_:)`. Followup to https://github.com/mapbox/mapbox-navigation-ios/pull/958.
/cc @1ec5
=> Check if view is loaded before calling func on outlet

MapboxCoreNavigation/RouteController.swift
This fixes the following crash:
```
#0. Crashed: com.apple.main-thread
0  MapboxCoreNavigation           0x104c0f4c0 RouteController.advanceStepIndex(to:) (RouteController.swift:840)
1  MapboxCoreNavigation           0x104c1a0a0 specialized RouteController.userIsOnRoute(_:) (RouteController.swift:644)
2  MapboxCoreNavigation           0x104c0f4f8 @objc RouteController.userIsOnRoute(_:) (RouteController.swift)
3  MapboxCoreNavigation           0x104c196fc specialized RouteController.locationManager(_:didUpdateLocations:) (RouteController.swift:587)
4  MapboxCoreNavigation           0x104c0eee4 @objc RouteController.locationManager(_:didUpdateLocations:) (RouteController.swift)
5  CoreLocation                   0x1886a07bc (null) + 77412
6  CoreLocation                   0x1886a001c (null) …
```
=> Don't increment legIndex if there are none left

MapboxNavigation/NavigationMapView.swift
This changes:
* fixes a bug where we would not actually remain in throttled fps mode when the maneuver was straight
* remain in throttled fps mode while the upcoming maneuver is slight right/left
* reduces the time around the maneuver we are in non-throttled mode slightly.
_Note, these changes are only while the device is unplugged._
=> Remain in throttled fps mode longer

MapboxNavigation/NavigationViewController.swift
Followup to https://github.com/mapbox/mapbox-navigation-ios/pull/969
In cases where the developer did not implement `shouldIncrementLegWhenArrivingAtWaypoint`, the didArriveAt delegate would never fire.
=> Fix arrival delegates

README.md
It's necessary to `import MapboxCoreNavigation` because `NavigationRouteOptions` depends on it.
=> Add MapboxCoreNavigation to readme

Examples/Swift/ViewController.swift, MapboxNavigation/PollyVoiceController.swift, MapboxNavigation/RouteVoiceController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/846
This adds a method for listening on when a voice instruction will be spoken and allows developers to change the instruction as needed. Some things to chew on:
- developers will be on their own when it comes to SSML. It'll be about as difficult or easy as they want to make it.
- I with the dev did not have to include `distanceAlongStep` since it will have no impact on when the instruction is said.
Other than that, I think this a pretty clean addition.
=> add voiceController willSpeak delegate method

LICENSE.md, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/String.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/818
This PR seeks to stick to the route the user has selected when rerouting. This occurs by comparing the previous route summary to the new route(s) summary. 
/cc @mapbox/navigation-ios @mapbox/navigation-android
=> Stick to chosen route

.github/ISSUE_TEMPLATE.md, README.md
This adds a few links to https://github.com/mapbox/navigation-ios-examples and also adds an issue template.
=> Link to mapbox/navigation-ios-examples, add issue template

Examples/Swift/ViewController.swift, MapboxNavigation/StyleManager.swift
Fixes #989 
This change will apply a style even if the receiver doesn't have a fixed
location or if only a day _or_ night style is provided.
=> Support for style w/o location and single style

MapboxNavigation/NavigationMapView.swift, MapboxNavigation/UserCourseView.swift
This change provides a default implementation for the user puck’s
rotation, perspective and scale transformations, making it as easy as:
```swift
mapView.userCourseView = UIImageView(image: UIImage(named: "car_icon"))
```
to use a custom user puck.
@mapbox/navigation-ios 👀
=> Allow any UIView to be used as a custom user puck

CHANGELOG.md, CONTRIBUTING.md
Added a changelog, where we’ll draft a running set of release notes for each release, using the wonderful [github-release](https://github.com/aktau/github-release/) tool. Added instructions for opening a pull request, mentioning updating the changelog.
This will add eight points to [this library’s CocoaPods quality score](https://cocoapods.org/pods/MapboxNavigation/quality). 🥇
=> Add a running changelog

Examples/Swift/ViewController.swift, MapboxNavigation/PollyVoiceController.swift, MapboxNavigation/RouteVoiceController.swift
@1ec5 pointed out it might be necessary to also give the developer access to the current route progress when this delegate method is emitted. 
=> Change VoiceController delegate signature

MapboxNavigation/NavigationMapView.swift
This change makes it possible to reuse `NavigationMapView`’s course tracking.
=> Expose tracksUserCourse

MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift
If a developer is only using class methods on NavigationMapView and nothing on RouteMapViewController, the arrow tip will never be added. `addArrow` should be repressible for adding it's own arrow tip.
=> Add arrow tip in NavigationMapView

MapboxCoreNavigation/RouteController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1025
We need to not only check for the presence of a key on the notification dictionary but also that it is true.
/cc @ericrwolfe @mapbox/navigation-ios
=> Check if key in notification is true

CONTRIBUTING.md, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/RatingControl.swift, MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/Resources/en.lproj/Localizable.stringsdict
Use a stringsdict to correctly pluralize the star rating UI’s accessibility values. A localization that distinguishes one from two from many, such as Russian, will be able to translate these values accurately.
Fixes #971.
=> Pluralize star accessibility values in stringsdict

MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/Resources/Base.lproj/Navigation.strings, MapboxNavigation/Resources/es.lproj/Navigation.strings, MapboxNavigation/Resources/vi.lproj/Navigation.strings
If the user chooses to walk or bike, asking them to rate a “drive” would be illogical. “Trip” is just as understandable to motorists.
/cc @JThramer
=> Avoid asking pedestrians, cyclists to rate drives

CHANGELOG.md, Examples/Swift/ViewController.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift
Removed `RouteControllerDelegate.routeController(_:shouldIncrementLegWhenArrivingAtWaypoint:)` and `NavigationViewControllerDelegate.navigationViewController(_:shouldIncrementLegWhenArrivingAtWaypoint:)`. `RouteControllerDelegate.routeController(_:didArriveAt:)` and `NavigationViewControllerDelegate.navigationViewController(_:didArriveAt:)` now return a Boolean that determines whether the route controller automatically advances to the next leg of the route.
Fixed an issue where `NavigationViewControllerDelegate.navigationViewController(_:didArriveAt:)` was called twice at the end of the route, once immediately and once after the user dismissed the end-of-route feedback view controller.
Fixes #1009 and fixes #1037. Depends on #1010.
/cc @JThramer @bsudekum
=> Consolidated arrival delegate methods

CHANGELOG.md, Examples/Swift/ViewController.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift
Renamed `RouteControllerDelegate.routeController(_:shouldIncrementLegWhenArrivingAtWaypoint:)` to `RouteControllerDelegate.routeController(_:shouldAdvanceToNextLegWhenArrivingAt:)` to conform to Swift naming guidelines. (The Objective-C signature has changed to `-routeController:shouldAdvanceToNextLegWhenArrivingAtWaypoint:`.)
Fixes the easy part of #1009.
/cc @bsudekum @JThramer
=> Omit needless words from delegate method name

MapboxNavigation/RatingControl.swift, MapboxNavigation/Resources/Base.lproj/Localizable.strings, MapboxNavigation/Resources/en.lproj/Localizable.stringsdict, MapboxNavigation/Resources/es.lproj/Localizable.strings, MapboxNavigation/Resources/vi.lproj/Localizable.strings
Restored a string that was removed in #1034 and removed the `zero` case from an English stringsdict file.
Fixes #1035.
/cc @JThramer
=> Localize zero-rating accessibility label as separate string

.tx/config, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/Resources/es.lproj/Localizable.stringsdict, MapboxNavigation/Resources/fr.lproj/Localizable.stringsdict, MapboxNavigation/Resources/vi.lproj/Localizable.stringsdict
In #1034, I neglected to add the .stringsdict file to the Transifex configuration file, so #1042 omitted the translations of this file into French, Spanish, and Vietnamese.
/cc @JThramer
=> Add localized stringsdicts

MapboxNavigation/Style.swift
This got dropped recently and caused the way name label to be square.
=> clipsToBounds on wayNameLabel

MapboxNavigation.xcodeproj/project.pbxproj
Fixes #1065 
Copying frameworks should only happen in the example target, not the framework.
=> Do not nest frameworks

MapboxCoreNavigation/RouteController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1072
We're throwing out the first location, which is often times not a great location. This let's the first location slip through so we update UI elements with some initial data.
/cc @mapbox/navigation-ios @zijiazhai @Sealos
=> Let at least one location update through even if non-qualified

MapboxNavigation-Documentation.podspec, docs/jazzy.yml, scripts/document.sh
This PR contains various jazzy-related documentation fixes:
* Updated the MapboxDirections.swift version number and the list of MapboxDirections.swift classes to automatically link in this SDK’s jazzy documentation.
* Updated the copyright year in the footer of every documentation page.
* Restored the “Storyboards” guide (to fix #1014)
/cc @bsudekum @captainbarbosa
=> Various documentation fixes

Examples/Swift/Base.lproj/Main.storyboard, Examples/Swift/ViewController.swift, docs/guides/reduce-memory-usage.md
In the example app, we keep around the preview map view after presenting the NavigationViewController. This map is unnecessary to keep around and uses up a far amount of memory. This PR shows how it can be removed and added and adds some documentation around this concept. In my tests, this frees up around 100mb.
=> Remove and nil mapView when presenting NavigationViewController

MapboxNavigation/PollyVoiceController.swift, languages.md
This PR adds Polly voice support for Danish. I’ve split it out from #1031 because the Directions API doesn’t yet incorporate the Danish instructions in Project-OSRM/osrm-text-instructions#208, falling back to English instructions instead. Once the Danish instructions are deployed in the Directions API, we can quickly land this PR and issue a patch release so that they are pronounced by a Danish voice. Alternatively, if we switch to the Mapbox Voice API first in #617, then this PR becomes unnecessary.
/cc @bsudekum
=> Add Danish voice support

CHANGELOG.md, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/RouteProgress.swift
Seeing a few crashes that look like: 
```
#0. Crashed: com.apple.main-thread
0  MapboxCoreNavigation           0x104c30430 specialized RouteController.updateRouteStepProgress(for:) (RouteController.swift:869)
1  MapboxCoreNavigation           0x104c31ec0 specialized RouteController.locationManager(_:didUpdateLocations:) (RouteController.swift:568)
2  MapboxCoreNavigation           0x104c276c8 @objc RouteController.locationManager(_:didUpdateLocations:) (RouteController.swift)
3  CoreLocation                   0x188f4e62c CLClientRetrieveData + 72260
4  CoreLocation                   0x188f4de90 CLClientRetrieveData + 70312
5  CoreLocation                   0x188f37864 CLClientInvalidate + 1240
6  CoreFoundation                 0x18200c8ac <redacted> + 20
7  CoreFoundation …
```
=> Fix voice instruction crash

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/RouteProgress.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1081
If there are no more steps on a given leg, we should not check nor attempt to increment the step index.
=>  Do not check to increment stepIndex if no steps remain

MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1060
We've had issues with this outlet for a while now. By making it optional when `bottomBannerView?.updateETA(routeProgress:)` is called and  `bottomBannerView` is nil, the function will not be called.
=> Make bottomBannerView outlet optional

MapboxNavigation/StyleManager.swift
This fixes an infinite call to `timeOfDayChanged` when only using one style. There's no need to check when the time of day changes if only one style was provided.
@bsudekum 👀
=> Avoid infinite loop when only using one style

MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1097
4th times a charm. We should be comparing the current step duration remaining, not the duration of the upcoming step (which does not change). This part of the bool ensures then is only shown near the end of the current step.
=> Fix then banner

MapboxCoreNavigation/CLLocation.swift, MapboxCoreNavigation/Constants.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1100
This removes `speed` from checking whether a location is qualified or not. Since speed is not necessary to know whether a user is on the route, where to snap, or if they have completed a maneuver, we can investigate more meaningful clues like the horizontal accuracy. 
=>  Remove speed from isQualified check

CHANGELOG.md, MapboxCoreNavigation/Constants.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift
This exposes the function which fits the camera view overhead from the users current location to the end of the route. 
The use case here is a developer who is using MapboxCoreNavigation. On a progress update while the user has enabled overhead view, the dev would call this function.
=> Expose overhead camera view func

Examples/Swift/ViewController.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift
This PR makes it so developers can inspect locations before they are thrown out and conditionally keep the location if they so choose.
=> Allow developers to filter in locations

CHANGELOG.md, MapboxNavigation/PollyVoiceController.swift
Changes made to meet the expected behavior proposed in - [Issue #1026: Allow overriding speak() function for voice synthesis](https://github.com/mapbox/mapbox-navigation-ios/issues/1026)
**Intent**: The `open` access level applied to the `speak` method allows the method to be overridden by subclasses of the  `PollyVoiceController`class, which wasn't attainable with the previous `public` access level.
cc @mapbox/navigation-ios @1ec5
=> Modified PollyVoiceController's speak method qualifier

MapboxNavigation/NavigationMapView.swift
This change fixes a small regression introduced in #1101 where it took slightly longer to snap the user course view to the route when switching between overview mode and normal tracking mode.
@bsudekum 👀
=> Revert update course tracking

MapboxNavigation/NavigationMapView.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/987
This exposes the strings that are used in any `attributeName` so the developer can style legs and congestion values however they like.
=> Make necessary strings public

MapboxCoreNavigation/DistanceFormatter.swift, MapboxCoreNavigationTests/DistanceFormatterTests.swift, MapboxNavigation/BottomBannerView.swift
Some tail work for #1055 
@bsudekum
=> Fix distance in the U.K

CHANGELOG.md, Examples/Swift/ViewController.swift, MapboxNavigation/MGLVectorSource.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift, languages.md
Added a public `localizeLabels()` method to NavigationMapView for localizing all the labels: road labels are localized into the local language (the `name` tag in OpenStreetMap, matching the Mapbox Directions API), while place and POI labels are localized into the system’s preferred language if supported by the Mapbox Streets source, falling back to the local language.
The map view embedded in NavigationViewController calls this method automatically, so no developer intervention is typically required for the turn-by-turn map. However, the developer is encouraged to call `localizesLabels()` on any standalone NavigationMapView from within `MGLMapViewDelegate.mapView(_:didFinishLoading:)`.
This change required porting about half of the `MGLStyle.localizesLabels` implementation from …
=> Localize map labels

MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationMapView.swift
Two delegate method documentation comments were outdated with respect to the arguments they documented. These issues showed up as compiler warnings when building the Objective-C example application, because documentation warnings are enabled by default in Objective-C but not in Swift.
/cc @JThramer @bsudekum
=> Update delegate method argument documentation

MapboxCoreNavigation/MBRouteController.h, MapboxCoreNavigation/MBRouteController.m, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift
This removes the notification key `MBRouteControllerEstimatedTimeUntilManeuverKey` in favor of using durationRemaining on `currentStepProgress`, and makes sure progress updates are always fired when the location is deemed qualified.
When a user begins to go off route near a maneuver, this check `if distanceTraveled != currentStepProgress.distanceTraveled {` would fail because the distance traveled is a snapped distance. Although the distance is not changing, we still need to emit progress updates. This was not surfaced because we're updating the user puck via [this delegate method](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/NavigationViewController.swift#L530) instead of progress update notifications. This is important for developers who are implementing …
=> Always send progress update except when location is unqualified

MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-Objective-C.xcscheme, MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-Swift.xcscheme, MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme, MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
Removes duplicated framework reference and adds MapboxSpeech as an embedded framework to the Obj-C and Swift example.
Fixes 
@bsudekum 👀
=> Remove duplicated framework reference

MapboxNavigation/NextBannerView.swift
I think this got undone during a merge conflict recently. 
=> Fix next banner

MapboxNavigation/RouteVoiceController.swift
It sort of bugged me this weekend that my audio would duck for the ding, then unduck, then duck again for the new instruction when rerouting.
This PR plays the ding audio when rerouting over the users current audio. 
=> Don't pause music while playing reroute ding

MapboxCoreNavigation.podspec, MapboxNavigation-Documentation.podspec, MapboxNavigation.podspec
CocoaPods 1.4.0 supports a [`swift_version` setting in podspecs](https://blog.cocoapods.org/CocoaPods-1.4.0/#swift-version-dsl), so this adds that.
CocoaPods also says that the `.swift-version` file is being deprecated, but they’re not the only consumers of this file, so let's leave it around for the time being.
/cc @frederoni
=> Specify Swift version in podspecs

MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1060#issuecomment-367155913
We're still unclear in which situations `routeController` would be nil here, but we can apply a bandaid for this issue by first checking if it's nil.
This property is set  here:
https://github.com/mapbox/mapbox-navigation-ios/blob/0275c068d09dbf0cde3cff99a6ea14de3a204216/MapboxNavigation/NavigationViewController.swift#L345
Which occurs after we start the routeController here:
https://github.com/mapbox/mapbox-navigation-ios/blob/0275c068d09dbf0cde3cff99a6ea14de3a204216/MapboxNavigation/NavigationViewController.swift#L328
Perhaps when the view is shown and the user is at the same time rerouted, we could be firing a `userDidReroute` notification (which triggers an updateETA()). In this case, …
=> Check if routeController is nil

MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/StatusView.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/973
If the `StatusView` is already shown, we should prevent other status updates from showing. The stacking updates caused the view to grow.
=> Prevent statusView from being shown if it is already visible

README.md, docs/guides/Localization and Internationalization.md, docs/jazzy.yml, languages.md
Converted this repository’s “Languages” Markdown file into a guide for inclusion in the jazzy-generated docset. Updated the guide to reflect the changes to spoken instructions in #617. Also rewrote the feature list in the readme to focus on differentiators.
Fixes #1073.
/cc @bsudekum @captainbarbosa
=> Convert language documentation into a guide

MapboxCoreNavigationTests/RouteControllerTests.swift, MapboxNavigation.xcodeproj/project.pbxproj
This adds a few more tests for `RouteController`. I'm trying to extract these tests as far away from a particular route as possible so when a fixture update occurs, these tests should not be effected. Going to add a few more, this is just a start.
=> Add more RouteController tests

MapboxCoreNavigation/RouteController.swift, MapboxNavigation/InstructionsBannerView.swift
Because of https://github.com/mapbox/mapbox-navigation-ios/issues/901, when starting a trip, the user may not cross the threshold of when a voice instruction or banner should be updated. 
This change ensures that at the beginning of any route, if the spoken/visual index is zero, we make sure to update the user. Otherwise, the banner instruction could be blank or we could delay the voice instruction if the user is standing still.
=> Always update banner and voice instruction when beginning

CHANGELOG.md, MapboxNavigation/StepsViewController.swift
This fixes #1146, where a user was unable to use a convenience initializer because of its `internal` protection level.
=> Making StepsViewController.init(routeProgress:) public

docs/guides/Localization and Internationalization.md
Reformatted the table added in #928 to use dashes instead of emoji. This avoids calling undue attention to any missing language support, since not all the columns are within our control. Also centered the table’s columns.
/cc @brsbl @JThramer
=> Reformat language support table

CHANGELOG.md, MapboxCoreNavigation/DistanceFormatter.swift, MapboxCoreNavigationTests/DistanceFormatterTests.swift, MapboxNavigation/InstructionsBannerView.swift, MapboxNavigation/Style.swift
Implemented `DistanceFormatter.attributedString(for:)`, which applies a `quantity` attribute to the numeric quantity part of the returned attributed string. This method relies on finding the formatted number within the distance string, as opposed to finding the unit, which turned out to be unreliable in some locales.
Simplified `BaseInstructionsBannerView.distance`’s setter to pass this attributed string directly to DistanceLabel instead of attempting to split the distance string on its quantity and unit. DistanceLabel now emphasizes the quantity relative to the unit based on the presence of the quantity attribute.
All this is to work around [a Foundation bug](http://openradar.appspot.com/radar?id=5061404864282624) in which `LengthFormatter.unitString(fromValue:unit:)` is unreliable in …
=> More robust distance formatting

CHANGELOG.md, MapboxNavigation/LanesView.swift
Prevent the lanes view from swapping the order of the lanes in right-to-left environments:
Fixes #1174.
/cc @frederoni
=> Avoid mirroring lanes

CHANGELOG.md, MapboxNavigation/RouteMapViewController.swift
Fixed a crash that occurred because the application didn’t provide an access token, yet the current road name label depended on force-adding the Mapbox Streets source to the style. Now if no access token is available, the current road name label is hidden.
This is a speculative fix for #735.
/cc @bsudekum
=> Disable current road name if access token is omitted

MapboxNavigation/NavigationMapView.swift
Previously, this function would first set the pitch and heading to zero, then animate the camera based on the bounds of the line.
This change now does everything in one camera motion.
=> Only update the camera once for setOverheadCameraView

MapboxNavigation/NavigationMapView.swift
Reverts mapbox/mapbox-navigation-ios#1189
Two camera functions are fighting each other here, causes a strange effect in some cases. Need to reassess.
=> Revert "Only update the camera once for setOverheadCameraView"

MapboxNavigation/Resources/Assets.xcassets/report_checkmark.imageset/Contents.json
Apparently checkmarks [look the same](https://mdn.mozillademos.org/files/10211/persistentdrawer.png) in right-to-left languages as they do in left-to-right languages. There’s the separate issue of a checkmark having negative connotations in some languages, but that’s best handled as part of #1181.
=> Avoid mirroring checkmark in right-to-left layout

MapboxNavigation/NavigationMapView.swift
This animation caused the user puck to slide around when going to and from overhead mode. Removing this causes the puck to remain tighter snapped to the route line.
=> Remove unnecessary animation

MapboxCoreNavigation/NavigationLocationManager.swift, MapboxCoreNavigation/UIDevice.swift, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/NavigationMapView.swift
Through some first hand tests, I have come to the conclusion that `kCLLocationAccuracyBestForNavigation` is pretty dangerous if the phone is not held very still in, especially in environments where signal is bad. The result is many false positives. IMO, it's almost dangerous enough to warrant only using `kCLLocationAccuracyBest`, baby steps though.
This brings back logic (https://github.com/mapbox/mapbox-navigation-ios/pull/670) that checks whether the phone is plugged in before using `kCLLocationAccuracyBestForNavigation`. 
=> Re-enable kCLLocationAccuracyBestForNavigation while phone is plugged in

MapboxNavigation/NavigationView.swift
Fixes the little blue bubble in: https://github.com/mapbox/mapbox-navigation-ios/issues/1198#issuecomment-370612614
Having a hard time reproducing this often, but I think this is a good move nonetheless. 
/cc @JThramer
=> Hide wayNameView initially

MapboxNavigation/NavigationMapView.swift
fixes `#1` in https://github.com/mapbox/mapbox-navigation-ios/issues/1199
There is still however a quick snap after rerouting which is not as a big as issue as `#2` in https://github.com/mapbox/mapbox-navigation-ios/issues/1199
=> Improve re-centering user puck

Cartfile, MapboxCoreNavigation.podspec, MapboxNavigation-Documentation.podspec
We have [a](https://github.com/mapbox/MapboxDirections.swift/pull/244) [few](https://github.com/mapbox/MapboxDirections.swift/pull/243) [breaking](https://github.com/mapbox/MapboxDirections.swift/pull/236) changes coming down the line in MapboxDirections.swift. If we put out a release of MapboxDirections.swift without updating and releasing this library, people who install this library will get compile errors.
By pinning, we can guarantee releases of MapboxDirections.swift will not interfere with developers here.
=> Pin MapboxDirections.swift dependency 

MapboxCoreNavigation/SimulatedLocationManager.swift, MapboxNavigation/NavigationViewController.swift
#![Lazy robot.](https://i.imgur.com/SAakSXg.gif)
Addresses #1203 partially and is a parallel attempt alongside #1204.
* Changing the `voiceController` over to a `lazy` loaded property, that's referenced initially (and the only time) at `viewWillAppear:`
This gives a developer the opportunity to initialize the `NavigationViewController` and set a custom (or no) `VoiceController` anytime between initialization and `viewWillAppear:` time.
To-Do: 
/cc @mapbox/navigation-ios @Sealos
=> Making NavigationViewController.voiceController a lazy var

CHANGELOG.md, MapboxCoreNavigation/CLLocation.swift, MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/MBRouteController.h, MapboxCoreNavigation/MBRouteController.m, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigationTests/LocationTests.swift, MapboxCoreNavigationTests/RouteControllerTests.swift
Work in progress. Fixes #1142, by breaking out route snapping into more clearly defined components, and also by exposing the raw location update to the notification consumer.
To-do: 
=> Improve RouteController location mechanism

MapboxNavigation/MapboxVoiceController.swift
We have a few reports of the the RouteVoiceController and the MapboxVoiceController are speaking over each other in a few cases:
1. Turned on my car in a parking lot, bluetooth connected, was playing from Audible
2. Entered my address, got a route telling me to go around the block (Original route above)
3. Realized I didn't need to go around because I could drive out of the parking lot directly onto SE 23rd Ave, which triggered a reroute (Rerouted route above)
4. The reroute paused the Audible playback
5. "Turn left onto Southeast Morrison Street" was spoken simultaneously by Polly _and_ the fallback robot phone voice
6. When the announcement was done, Audible did not start playing again
It's difficult to reproduce but these are changes that I see as pretty valid changes. 
/cc …
=> Don't speak over each other

MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/RouteController.swift
Followup to: https://github.com/mapbox/mapbox-navigation-ios/pull/1121
We look to see if the user is on future steps before rerouting. In cases where the user is actually closer to a future step but also actively rerouting, we should just reroute. This PR prevents false positives when rerouting by using `RouteControllerUserLocationSnappingDistance`. This way, we only advance you to a future step if we are very very confident that you are actually on one.
In the case above, we were getting a voice instruction on the step that is headed to the right because it so happens the user is 23.5m of this step before rerouting (rerouting threshold in this case is 25m).
=> Prevent double voice instruction before rerouting

Cartfile.resolved, MapboxNavigation/RouteMapViewController.swift
* Fixing issue where an unsafe force-unwrap could cause a crash under certain circumstances.
Fixes #1221.
=> Force-Unwrap anchor crash fix

MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift
This change fixes course view tracking when in overview mode and stops fitting the camera to the remaining route on each location update. Please disregard the low framerate which is just to keep the gif at a reasonable size.
| Before  | After |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/764476/37404601-a003f90a-2792-11e8-8038-3bb983abeb9a.gif" width=200>  | <img src="https://user-images.githubusercontent.com/764476/37404597-9e5053ba-2792-11e8-9c8c-01aa52d1155a.gif" width=200> |
@mapbox/navigation-ios 👀
=> Update user course view when in overview mode

CONTRIBUTING.md
Updated instructions for localizing this SDK. The list of related projects to translate has been expanded with additional details. The step about importing abbreviations has been removed, now that banners come abbreviated from the server using abbreviation lists in OSRM Text Instructions: #1169. Also fixed a broken link to the language guide following #1112.
/cc @JThramer
=> Update localization instructions

CONTRIBUTING.md
The Directions Feedback tool now redirects to the Mapbox Navigation product page, which doesn’t have any option for providing feedback. The general Feedback tool is the next best thing.
/cc @brsbl @bsudekum
=> Directions Feedback tool is no more

CHANGELOG.md, MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/MBRouteController.h, MapboxCoreNavigation/MBRouteController.m, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/RouteVoiceController.swift
“Opportunistic” can have a negative connotation. The automatic rerouting feature is just trying to be helpful, proactively. So the following symbols have been renamed:
* `RouteController.reroutesOpportunistically` to `RouteController.reroutesProactively`
* `RouteControllerOpportunisticReroutingInterval` to `RouteControllerProactiveReroutingInterval`
* `RouteControllerNotificationUserInfoKey.isOpportunisticKey` to `RouteControllerNotificationUserInfoKey.isProactiveKey`
/cc @bsudekum
=> Reroute proactively, not opportunistically

CHANGELOG.md, MapboxNavigation/DayStyle.swift
This fixes the poor contrast of the severe congestion `TimeRemainingLabel` color when navigation night style (theme) is enabled. 
Fixes issue https://github.com/mapbox/mapbox-navigation-ios/issues/1192
/cc @mapbox/navigation-ios 
BEFORE (_left_) `-->`   AFTER (_right_)
=> Insufficient contrast for severe congestion text in night theme.

MapboxNavigation/DataCache.swift, MapboxNavigationTests/DataCacheTests.swift
Fixes a crash in the DataCache. Unowned should be used if the instance has the same lifetime or longer which seems to be correct in this case. It's almost as if the removal of the observer is not really removing it or it's being delayed one cycle?
@akitchen 👀 
<details>
```md
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x18330c2e8 __pthread_kill + 8
1  libsystem_pthread.dylib        0x183425748 pthread_kill$VARIANT$armv81 + 360
2  libsystem_c.dylib              0x18327afbc abort + 140
3  libswiftCore.dylib             0x103ac0f08 swift_reportError + 256
4  libswiftCore.dylib             0x103ac1010 swift_deletedMethodError + 104
5  libswiftCore.dylib             0x103aeec30 swift_unknownUnownedLoadStrong + 74
6  MapboxNavigation               0x1034ac828 closure #1 in …
```
=> Fix SIGABRT in DataCache and add test

MapboxNavigation/DataCache.swift, MapboxNavigation/ImageCache.swift, MapboxNavigationTests/DataCacheTests.swift, MapboxNavigationTests/ImageCacheTests.swift
`NSNotificationCenter.addObserver(_:selector:name:object:)` removes the observer automatically for apps targeting iOS 9.0 and higher.
@akitchen 👀
=> Use autoreleased observers

MapboxNavigation/BottomBannerView.swift, MapboxNavigation/BottomBannerViewLayout.swift, MapboxNavigation/DayStyle.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/Style.swift
The progress bar has been hidden under the navigation view since we moved away from the storyboard.
This PR brings the progress bar back on top of the bottom banner.
The fact that we forgot about it could also be an indication that it's unnecessary.
Haven't been able to reproduce but this change will potentially fix https://github.com/mapbox/mapbox-navigation-ios/issues/1236 which indicates an invalid position of the progress bar.
@JThramer @bsudekum
=> Bring back progress bar

MapboxNavigation/Cache.swift
This log was getting printed quite often. I think we can silently continue if the audio is not found on disk. 
=> Remove log

CHANGELOG.md, Examples/Swift/ViewController.swift, MapboxNavigation/DayStyle.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/Style.swift, MapboxNavigation/StyleManager.swift, MapboxNavigation/StyleType.swift, MapboxNavigationTests/StyleManagerTests.swift
Fixes #1249 
`StyleType.nightStyle` is redundantly named according to Swift’s naming conventions and should be written as `StyleType.night`. In ObjC, this bridges to `MBStyleTypeNight`.
@bsudekum
=> Refactor style types

MapboxNavigation/NavigationMapView.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1246
=> Fix center point

.tx/config, CHANGELOG.md, Examples/Objective-C/ar.lproj/Main.strings, Examples/Objective-C/pt-PT.lproj/Main.strings, Examples/Swift/ar.lproj/Main.strings, Examples/Swift/pt-PT.lproj/Main.strings, MapboxCoreNavigation/Resources/ar.lproj/Localizable.strings, MapboxCoreNavigation/Resources/pt-PT.lproj/Localizable.strings, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/Resources/ar.lproj/Navigation.strings, MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings, MapboxNavigation/Resources/pt-PT.lproj/Localizable.stringsdict, MapboxNavigation/Resources/pt-PT.lproj/Navigation.strings, docs/guides/Localization and Internationalization.md
Added a partial Arabic localization and a complete European Portuguese localization from Transifex. Thanks to @safaalfulaij for the Arabic translations and @Rui-Santos for the European Portuguese translations!
In order to pull these localizations from Transifex, some remnants of the old `localizableabbreviations` resource needed to be removed from the `tx` configuration. (This resource went away as part of #1050.)
/cc @vincethecoder @frederoni
=> Add Arabic, European Portuguese localizations

CHANGELOG.md, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
Fixes: https://github.com/mapbox/navigation-ios-examples/pull/16#issuecomment-375712695
Unsure how this regressed.
/cc @mapbox/navigation-ios @maxhawkins
=> Fix custom image for annotation

MapboxNavigation/BottomBannerView.swift, MapboxNavigation/BottomBannerViewLayout.swift
This change removes the progress bar from the bottom banner as it's suboptimal for trips with reroutes.
The `ProgressBar` is also being used as a countdown indicator in the feedback form.
@bsudekum 👀
=> Remove progress bar from bottom banner

MapboxCoreNavigation/Constants.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/939
I did some tests this weekend and logged each time the puck becomes unsnapped while on a route. Basically, on any 90 degree turn, the puck always becomes unsnapped momentarily. To counteract this, I increased `RouteSnappingMaxManipulatedCourseAngle` to 36 in https://github.com/mapbox/mapbox-navigation-ios/commit/5b84e08a1547adb2e886ab74c19ea668a7dd565e. This was a value I found that worked well from many tests I did.
=> Increase RouteSnappingMaxManipulatedCourseAngle threshold

MapboxCoreNavigation/MMEEventsManager.swift
It'd be helpful to understand how the desiredAccuracy prop on the location manager impacts navigation.
=> Include location manager desired accuracy

CHANGELOG.md
FYI, the documentation publishing script relies on the current release’s section being the first second-level header in the document:
https://github.com/mapbox/mapbox-navigation-ios/blob/17ab0869b6f55b5ad4a4ae757de314bc2002c574/scripts/document.sh#L46-L47
As a result of #1148, [the v0.16.0 documentation](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.16.0/) has empty release notes.
=> Fix syntax error in changelog

MapboxCoreNavigation/CLLocation.swift
We're not really interested in verticalAccuracy, nor is a good litmus test for whether a location is accuracy. Personally, I've seen many cases where the vertical accuracy would previously be unqualified but the horizontal accuracy would be qualified:
```json
{
"lng": -122.3928341989904,
"horizontalAccuracy": 48,
"course": 253.165305586835,
"verticalAccuracy": 63.95016860961914,
"speed": 21.015432357788086,
"lat": 37.61509585378829,
"altitude": -13.206028914186902,
"timestamp": "2018-04-01T23:43:58.999+0000"
},
{
"lng": -122.39305106695443,
"horizontalAccuracy": 48,
"course": 253.52910878278655,
"verticalAccuracy": 52.994686126708984,
"speed": 21.015432357788086,
"lat": 37.61503088880565,
"altitude": -11.841697524188362,
"timestamp": "2018-04-01T23:43:59.999+0000"
},
```
This PR removes …
=> Only use horizontal accuracy for checking isQualified

MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
Previously, we were only updating the maneuver arrow when a voice instruction was given. Since https://github.com/mapbox/mapbox-navigation-ios/pull/1263, we no longer give a voice instruction directly when completing a step. Now we wait until a voice instruction should be given, not necessarily if spokenVoiceInstructionIndex == 0.
When the step distance is equal to the first `distanceAlongGeometry` value, the maneuver arrow would hang around on the previous step.
This now ensures the maneuver arrow is always updated when completing a step.
=> Update maneuver arrow after completing step

MapboxCoreNavigation/RouteController.swift
This fixes two issues:
We advance the step index when the user is with 40 meters of the maneuver and their course is similar to the expected exit heading. When the user was within 40 meters of the traffic circle, we'd increment the step index. However, the tolerance for rerouting could potentially be 25 meters. At this point, we just put them onto a new step but they are essentially 40 meters away from it. This would cause reroutes on many traffics circles. Now, the threshold to advance a step and to reroute are the same at the very least. It can be larger in some instances.
Driving this weekend, I gunned it a few times driving very quickly into a maneuver with a right hand turn. In `userIsOnRoute ` we project ahead looking at an absolute angle ahead of the user to see where the user will …
=> Prevent rerouting when moving fast into intersection and in traffic circles

CHANGELOG.md, MapboxNavigation/MapboxVoiceController.swift
We should not be falling back to the default speech synthesizer if the audioPlayer does not [prepareToPlay](https://developer.apple.com/documentation/avfoundation/avaudioplayer/1386886-preparetoplay) properly.
Even if `prepareToPlay` fails, the audio can still play as `prepareToPlay` is just there to preload audio.
I was able to hit this code repeatedly by removing alls checks and playing an audio instruction on every update. When rerouting, we would interrupt the current audio, stopping the audioPlayer and rendering it "unprepared".
=> Don't fallback to default speech synthesizer if prepareToPlay fails

MapboxNavigation.podspec
Include Sequence.swift in MapboxNavigation, fixing a compilation error when building a version of MapboxNavigation that is assembled by CocoaPods instead of being built from the checked-in Xcode project.
Fixes #1295.
/cc @frederoni @JThramer @bsudekum
=> Add Sequence.swift to MapboxNavigation podspec

MapboxNavigation.xcodeproj/project.pbxproj
Removed most target-specific version specializations in order to allow them to be inherited, with the exception of MapboxCoreNavigation and its tests which target a lower version of iOS
=> Adjusts deployment target versions to be consistent with docs

scripts/document.sh
Automatically derive the MapboxDirections.swift version from Cartfile.resolved when generating documentation.
Fixes #1302.
/cc @akitchen @frederoni
=> Derive MapboxDirections.swift version from Cartfile

MapboxNavigation/ImageDownload.swift, MapboxNavigation/ImageDownloader.swift, MapboxNavigationTests/DataCacheTests.swift, MapboxNavigationTests/ImageCacheTests.swift, MapboxNavigationTests/ImageDownloaderTests.swift, MapboxNavigationTests/ImageRepositoryTests.swift, MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift, MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift, MapboxNavigationTests/Support/ImageDownloadOperationSpy.swift
Also introduces a runUntil(condition:, pollingInterval:) helper which should be incrementally better than a raw runLoop advancement
TODO: semaphore wait()'s currently don't have a timeout, which might be bad for CI
=> Removes many usages of async expectations in favor of semaphores

MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
Fixes #1312 
Not sure how this happened. It's almost as if CI had both MapboxDirections 0.19.0 and 0.20.0 in the cache. 🤔 
A `VisualInstructionComponent` no longer takes a maneuverDirection and maneuverType. These properties belongs to the `VisualInstruction`.
@1ec5 @JThramer 👀
=> Update tests for MapboxDirections 0.20.0

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift, MapboxCoreNavigationTests/RouteControllerTests.swift, MapboxCoreNavigationTests/Support/DirectionsSpy.swift, MapboxCoreNavigationTests/Support/DummyURLSessionDataTask.swift, MapboxCoreNavigationTests/Support/EventsManagerSpy.swift, MapboxCoreNavigationTests/Support/RouteControllerDelegateSpy.swift, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme, MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift, MapboxNavigationTests/LaneTests.swift, MapboxNavigationTests/Support/SpeechAPISpy.swift
This is still WIP in terms of resolving #1200 , however the plan is to:
I would like to do this in a way which can be merged to master early and often in the spirit of True Continuous Integration™ and in order to avoid semantic disconnects with other work streams.
I'll be tidying up / squashing down the commit log a bit, but the tests we have so far are high value and can/should be merged to master more or less immediately with a 👍 from the team.
/cc @vincethecoder who helped bootstrap this work
=> Backfill events tests & decouple events from RouteController

CHANGELOG.md, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigationTests/BridgingTests.m, MapboxCoreNavigationTests/Fixture.swift, MapboxCoreNavigationTests/Support/DirectionsSpy.swift, MapboxCoreNavigationTests/Support/EventsManagerSpy.swift, MapboxNavigation.xcodeproj/project.pbxproj
Fixes #1320 Make it possible to update route from Objective-C
@mapbox/navigation-ios 👀
=> Expose RouteController.routeProgress to Objective-C

MapboxNavigationTests/XCTestCase.swift
Fixes #1327 and other unexpected timeout failures.
This is being done as a read-only computed property to minimize the need for other changes. Not sure if converting to a function might be more appropriate / less unexpected. Opinions welcome.
=> Updates semaphore timeout to a read-only computed property

scripts/convert_string_files.sh, scripts/extract_localizable.sh
Now you can executing `extract_localizable.sh` and `convert_string_files.sh` at any directories rather than the directory where it is 😉
=> Using absolute paths for scripts run

MapboxNavigation/ImageDownloader.swift, MapboxNavigationTests/ImageDownloaderTests.swift, MapboxNavigationTests/ImageRepositoryTests.swift, MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift, MapboxNavigationTests/MapboxNavigationTests.swift, MapboxNavigationTests/MapboxVoiceControllerTests.swift
Removing this statefulness (the `lazy var`) should make sense here; we're registering & unregistering the `URLProtocol` subclass in a loop while the URL loading system may be doing other work. I'm hopeful this will help with the test instabilities noted in #1327 and elsewhere.
I also noticed that the `ImageDownloader`'s `OperationQueue`'s `maxConcurrentOperationCount` was set semi-arbitrarily, so I removed it. This defaults the configuration to `NSOperationQueueDefaultMaxConcurrentOperationCount`. We could also consider setting it to `2`.
=> Adjust ImageDownloaderTests to use a new instance each time

MapboxNavigation/NavigationViewController.swift
The previous documentation had a typo. Also, “qualified” is not a term of art when it comes to describing a location update, so the new documentation instead describes the act of considering or ignoring the location update.
/cc @vincethecoder @bsudekum
=> Rewrite discarding delegate method documentation

MapboxNavigationTests/ImageDownloaderTests.swift
This code isn't necessary, in fact it can be harmful since URL loading hangs on
our test requests when the URLProtocol isn't registered in time. 
Reasonably sure this is the root cause of the semaphore timeouts we've been running into.
=> Removes code which registers & unregisters the URLProtocol

Examples/Objective-C/ViewController.m, MapboxNavigation/NavigationViewController.swift
`NavigationViewController.init(for:directions:style:locationManager:)` takes multiple styles.
@JThramer @vincethecoder  👀
=> Fix typo in NavigationViewController’s refined Obj-C init

CHANGELOG.md, MapboxCoreNavigation/DistanceFormatter.swift, MapboxCoreNavigation/ReplayLocationManager.swift, MapboxCoreNavigation/SimulatedLocationManager.swift, MapboxNavigation/LanesView.swift, MapboxNavigation/ManeuverView.swift, MapboxNavigation/NavigationViewController.swift
Fixes #1344 - Allow subclassing NavigationViewController
This PR also modifies the access level in order to allow subclassing of the following classes:
- DistanceFormatter
- ~NavigationSettings~
- ReplayLocationManager
- SimulatedLocationManager
- LanesView
- ManeuverView
@captainbarbosa @1ec5 👀
=> Modify access level for various classes

CHANGELOG.md, Examples/Swift/ViewController.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift, README.md, RouteTest/AppDelegate.swift
Renamed `NavigationViewControllerDelegate.navigationViewControllerDidEndNavigation(_:cancelled:)` to `navigationViewControllerDidDismiss(_:byCanceling:)`, which reads more like one of the standard UIKit view controller delegate methods. Also prefer the American spelling of cancel* over the British spelling.
Removed the delegate method section of the readme. That documentation was not only redundant to NavigationViewControllerDelegate’s documentation comments, but it also used inaccurate or outdated names.
/ref #1318
/cc @frederoni @vincethecoder
=> Rename dismissal delegate method; removed documentation

CHANGELOG.md, Examples/Swift/ar.lproj/Main.strings, MapboxCoreNavigation/Resources/ko.lproj/Localizable.strings, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/Resources/ko.lproj/Localizable.strings, MapboxNavigation/Resources/ko.lproj/Localizable.stringsdict, MapboxNavigation/Resources/ko.lproj/Navigation.strings, MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings, MapboxNavigation/Resources/ru.lproj/Localizable.strings, docs/guides/Localization and Internationalization.md
Added a Korean localization, courtesy of @tan-tran-ea. Updated a couple translations in Arabic and European Portuguese.
/cc @frederoni
=> Add Korean localization

MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-Swift.xcscheme
MapboxNavigationTests and MapboxCoreNavigationTests are tested through their own targets, no need to run the same tests another time via the Example target.
@vincethecoder @akitchen 👀
=> Remove excessive tests from the example target

docs/guides/Localization and Internationalization.md
Revised the “Localization and Internationalization” guide to clarify that spoken instructions are only announced in languages supported by the Directions API, regardless of which speech synthesizer supports the language.
Since the Voice API is used by default, the table no longer calls out its use explicitly; instead, the VoiceOver and third-party fallbacks are called out as exceptions. Languages that lack UI support have been added with the caveat that the developer needs to opt into them explicitly.
Finally, the table now notes that instructions are spoken in Mandarin as opposed to Cantonese or another Chinese spoken language.
Thanks to @danesfeder for digging up [this VoiceOver language support document](https://support.apple.com/en-us/HT206175).
/cc @brsbl @danesfeder @frederoni
=> Clarify language support table

CHANGELOG.md, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
_Addresses a few issues in https://github.com/mapbox/mapbox-navigation-ios/issues/1306_
Previously, when arriving at a waypoint, we would redraw the waypoints on the map and remove the completed the waypoint. This caused the upcoming waypoint to always be 1. 
Now, completed waypoints are kept on the map but made more translucent.
> Completed waypoint 1
/cc @mapbox/navigation-ios @srikanthsrnvs
=> Keep completed waypoints on map

CHANGELOG.md, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift, MapboxCoreNavigationTests/Support/DirectionsSpy.swift, MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1355
This prevents the reroute status view update from being visible indefinitely.
=> Dismiss reroute status view if request fails

MapboxNavigation/NavigationViewController.swift
This property was deprecated a while back. No need to keep it around any longer.
=> Remove deprecated destination prop

MapboxNavigation/StepsViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1386
`didProcessCurrentStep` was always false because we are essentially comparing `routeProgress.currentLegProgress.stepIndex + 1` to `routeProgress.currentLegProgress.stepIndex` on every update. 
/cc @frederoni @vincethecoder @JThramer
=> Fix steps list pulsing

MapboxNavigation/InstructionLabel.swift, MapboxNavigation/InstructionsBannerViewLayout.swift, MapboxNavigation/StepsViewController.swift
Fixes #1390 - Abbreviate less by using a correct non-zero frame for calculating available bounds initially.
As @bsudekum assumed, the issue was previously mitigated by the frequent updates.
=> Fix initial abbreviation of steps

MapboxNavigation/InstructionPresenter.swift
This change allows the exit view to show on all maneuver types, not just `.takeOffRamp, .reachFork, .merge`. Otherwise, for all other types, we would get the text `Exit foobar...`.
/cc @JThramer @1ec5
=> Allow exit view for all maneuver types

MapboxCoreNavigation/SimulatedLocationManager.swift
Retrieves a unique successive coordinate after the current coordinate.
Here is the console log from inspecting the `routeProgress?.route.coordinates` at that deadlock location:
```
(lldb) po closestCoordinateOnRoute.index
4
(lldb) po coordinates[closestCoordinateOnRoute.index]
▿ CLLocationCoordinate2D
- latitude : 37.790279999999996
- longitude : -122.40714999999999
(lldb) po coordinates[5]
▿ CLLocationCoordinate2D
- latitude : 37.790279999999996
- longitude : -122.40714999999999
(lldb) po coordinates[6]
▿ CLLocationCoordinate2D
- latitude : 37.789969999999997
- longitude : -122.40708999999998
```
Fixes #1383 
=> Fixed user puck stuck while in simulation mode.

MapboxNavigation/ExitView.swift, MapboxNavigation/InstructionPresenter.swift, MapboxNavigation/VisualInstructionComponent.swift
Fixes: https://github.com/mapbox/mapbox-navigation-ios/issues/1392
We need to use a more descriptive cache key for exit views since a single exit view can be displayed with many different colors.
Ideally, we'd cache based on the `Style` the exit view is used within, but unfortunately we do not have this information available to us in this section of the code.
/cc @JThramer
=> Key exit view cache with more information

MapboxNavigationTests/ImageDownloaderTests.swift, MapboxNavigationTests/Support/ImageLoadingURLProtocolSpy.swift
URL loading is deferred until after the current run loop iteration. The two reentrancy tests are adjusted to use the download operation's `isFinished` flag as a continuation criteria, and assertions are done in a more appropriate place for better failure localization.
=> Adjust ImageDownloader tests

MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-Objective-C.xcscheme
Rolled back part of #188 that set the `OS_ACTIVITY_MODE` flag when running the example application. This flag was only needed in older Xcode versions to suppress console spew, but it also suppresses legitimate logging from the SDK and its dependencies.
This flag has already been removed from the Swift example application’s scheme as of #1063.
/cc @bsudekum @JThramer
=> Remove OS_ACTIVITY_MODE from Objective-C example scheme

CHANGELOG.md, Examples/Objective-C/Base.lproj/Main.storyboard, Examples/Swift/Base.lproj/Main.storyboard, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/BottomBannerView.swift, MapboxNavigation/BottomBannerViewLayout.swift, MapboxNavigation/DayStyle.swift, MapboxNavigation/InstructionsBannerViewLayout.swift, MapboxNavigation/MGLStyle.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/NavigationView.swift, MapboxNavigation/NavigationViewLayout.swift, MapboxNavigation/NextBannerView.swift, MapboxNavigation/Resources/Base.lproj/Navigation.storyboard, MapboxNavigation/StepsViewController.swift, MapboxNavigation/Style.swift
Partially closes #1347 
This PR updates the color palette for v3 guidance day/night styles.
v2 guidance map styles will still be used by default but convenient methods for any version has been added in the form of (`MGLStyle.navigationGuidance{Day/Night}StyleURL(version:)`.
=> Update style color palette for v3

CHANGELOG.md, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
Reverted some NavigationMapViewDelegate method names to conform to Objective-C naming conventions and be more consistent.
Relative to master:
Old (Swift) | New (Swift) | Old (Objective-C) | New (Objective-C)
----|----|----|----
`navigationMapView(_:shapeDescribing:)` | `navigationMapView(_:shapeFor:)` | `-navigationMapView:shapeDescribing:` | `-navigationMapView:shapeForRoute:`
`navigationMapView(_:simplifiedShapeDescribing:)` | `navigationMapView(_:simplifiedShapeFor:)` | `-navigationMapView:simplifiedShapeDescribing:` | `-navigationMapView:simplifiedShapeForRoute:`
`navigationMapView(_:shapeFor:legIndex:)` | `navigationMapView(_:shapeFor:legIndex:)` | `-navigationMapView:shapeFor:legIndex:` | `-navigationMapView:shapeForWaypoints:legIndex:`
`navigationMapView(_:imageFor:)` | …
=> Clean up NavigationMapViewDelegate method names

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/TunnelIntersectionManager.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1403
This documents a few public tunnel properties and methods.
/cc @1ec5 @vincethecoder
=> Document public tunnel methods

CHANGELOG.md, Examples/Swift/ViewController.swift, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/TunnelIntersectionManager.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift, docs/examples/Advanced.md, docs/examples/Custom Destination Marker.md, docs/examples/Custom Server.md, docs/examples/Embedded Navigation.md, docs/examples/Waypoint Arrival Screen.md
This one is a doozy. Hot on the heels of #1378, most public NavigationViewControllerDelegate methods and some RouteControllerDelegate and TunnelIntersectionManagerDelegate methods have been renamed to conform to Cocoa naming conventions in both Swift and Objective-C. The biggest change is that all the NavigationViewControllerDelegate methods now begin with `navigationViewController` instead of sometimes beginning with `navigationMapView`. If an implementation needs access to the map view, it can use `navigationViewController.mapView`.
NavigationViewControllerDelegate changes:
v0.16._x_ | This PR
----|----
`navigationMapView(_:routeStyleLayerWithIdentifier:source:)` | `navigationViewController(_:routeStyleLayerWithIdentifier:source:)` …
=> Clean up delegate method names; use UUIDs for feedback IDs

CHANGELOG.md, MapboxNavigation.xcodeproj/project.pbxproj
Fixes #1377 
The i386 slice has been removed from the Maps SDK but Carthage sometimes tries to build MapboxNavigation with i386 included, depending on the destination. This change sets the available architectures to 64 bit only.
cc @friedbunny @bsudekum
=> Stop building i386

MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1259
This keyboard logic is specific to the end of route view controller, specifically when the user touches the info field. If the view is nil (and thus not shown), there is no need to run this logic.
/cc @JThramer
=> Do not change EORVC constraints if view is nil

MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigationTests/RouteControllerTests.swift
Fixes #1408. Two issues are root cause here:
- A strong reference capture in a `RouteController` completion closure that causes a retain cycle,
- A unsafe_unretained reference persisting in the `NavigationLocationManager` that causes a crash.
=> RouteController - Retain Cycles & Zombie Refs

MapboxNavigation/ImageDownloader.swift, MapboxNavigationTests/ImageDownloaderTests.swift, MapboxNavigationTests/Support/ImageLoadingURLProtocolSpy.swift, MapboxNavigationTests/XCTestCase.swift
Reads are done synchronously while writes are performed with a barrier.
The occasionally flaky test was pointing out the lack of thread-safety
here, as `downloadImage(with:)` and URL loading callbacks happen on
different queues.
=> Moves access to active download operations to a dispatch queue.

Examples/Swift/ViewController.swift, MapboxCoreNavigation/Constants.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift
This fixes a few issues:
* Animations when showing the end of route view controller: https://github.com/mapbox/mapbox-navigation-ios/issues/975
* The location at which the arrival screen is shown
Previously, we had a hardcoded duration at which the arrival screen was shown. Now this is being handled by the server.
=> Improve arrival location and end of route screen animation

MapboxNavigation/DayStyle.swift
The background of the map view is transparent until the map style is loaded and the same goes for the NavigationView.
This causes a glitchy transition when the NavigationViewController is presented. To create an illusion that the style is preloaded even when the cache is empty, I've added the same background color on the NavigationView as the corresponding style’s background layer.
cc @bsudekum
=> Add background color to NavigationView

MapboxNavigation/StyleManager.swift, MapboxNavigationTests/NavigationViewControllerTests.swift
In the case where a developer has all tunnel flags turned on, we're force refreshing the map style on every update which causes the map style to flash on and off:
https://github.com/mapbox/mapbox-navigation-ios/blob/026fddd1bc07080f33d0cf3f5e7df3b41a04781a/MapboxNavigation/NavigationViewController.swift#L431-L437
=> Add failing test for tunnel + style refreshes

MapboxNavigation/StyleManager.swift, MapboxNavigationTests/NavigationViewControllerTests.swift
If tunnel flags are enabled, and we detect that the style needs to change for a given location, we should not try and force update the style if we only have one style or if we don't have that style type.
Example case:
1. inits with tunnel flags and a single style, say night for example.
1. Start in a location where it's day time, the opposite of the style we have.
1. We should not emit a force style update because we do not have a style to update to.
=> Do not force refresh style if we don't have the style type

CHANGELOG.md, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/NavigationViewController.swift
Now that we have tested tunnel style switching and animations for the past couple of months, I think it's about time we enable this feature by default since it is a very helpful feature.
=> Enable tunnel style switching and animation by default

MapboxCoreNavigation/CLLocation.swift, MapboxCoreNavigationTests/RouteControllerTests.swift
Building on https://github.com/mapbox/mapbox-navigation-ios/pull/1425, https://github.com/mapbox/mapbox-navigation-ios/pull/1425 was a good addition, but does not seem to catch all cases. There still seems to be situations where the user puck can end up snapping the course in between steps.
This change will snap the puck to the current step coordinates when the user's course is dissimilar from the heading on their upcoming step.
The one place where this could fall apart is when moving very fast through a sharp/windy maneuver. One that comes to mind is a looping on ramp onto a motorway- your course may not be similar to the final heading until the very last second. Still need to test this a bit.
/cc @1ec5
=> Use current step for snapping course

MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/RouteMapViewController.swift, MapboxNavigationTests/Fixtures/EmptyStyle.json, MapboxNavigationTests/Fixtures/Fixture.swift, MapboxNavigationTests/NavigationViewControllerTests.swift
Fixes #1326. Issue was caused by a missing `showWaypoints(route:)` call.
It's worth calling out that the order-of-operations for the route that the NVC gets initialized with is _really_ obscure and brittle. For instance, unless I manually do `navigationViewController.route = initialRoute` _after_ I wait for the styles to load, I cannot find any annotations on the map, which doesn't seem like reasonable behavior. I thought it out of scope for this issue, but I'll cut a ticket for this as I close this PR out.
=> Updating destination waypoint when route changes

CHANGELOG.md, MapboxNavigation/NavigationMapView.swift
Addresses the bug in https://github.com/mapbox/mapbox-navigation-ios/issues/1455
Previously, if the user only had a few meters left on the route, we'd flip up the camera, then break early and never actually set the correct center coordinate.
Now, if we detect there is not much left on the route, we simple flip the camera and set the center coordinates to the user.
=> Fix setOverheadCameraView for short routes

CHANGELOG.md, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigationTests/RouteControllerTests.swift, MapboxCoreNavigationTests/Support/RouteControllerDelegateSpy.swift, MapboxNavigation/NavigationViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1444
This change makes it so the user is no longer rerouted after reaching a waypoint. Also, upon arriving, the user puck becomes unsnapped to give a more precise depiction of where they actually are. If they move beyond the waypoint, it's important we show this.
> Example of arriving and moving beyond waypoint
todo:
=> Stop rerouting when arriving at waypoint

MapboxNavigation/NavigationView.swift, MapboxNavigation/NavigationViewLayout.swift, MapboxNavigation/RouteMapViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1438
I have the feeling the "Report Problem" button that is shown after rerouting is more confusing, loud and distracting for drivers than helpful. It takes the same amount of clicks to give feedback after rerouting anyways. 
This PR simply removes the button. The string remains because it's used in the actual feedback UI.
/cc @mapbox/navigation-ios @leonyuu
=> Remove report problem button after rerouting

CHANGELOG.md, Examples/Swift/Base.lproj/Main.storyboard, Examples/Swift/CustomViewController.swift, Examples/Swift/ViewController.swift, MapboxNavigation/NavigationMapView.swift
This updates the Custom UI example which has sadly been lagging behind a bit in terms of best practices. 
todo:
/cc @mapbox/navigation-ios @riastrad @captainbarbosa
=> Modernize custom UI example

MapboxNavigation/ImageDownload.swift, MapboxNavigation/ImageDownloader.swift
ImageDownload also uses a barrier when appending completions.
These two changes should address the instability in ImageDownloaderTests
[#1453]
=> ImageDownloader creates and mutates downloads within a barrier block

docs/guides/Simulating Routes.md, docs/jazzy.yml
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1443
=> Add guide for simulating locations with custom UI

MapboxCoreNavigation/MMEEventsManager.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/InstructionPresenter.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift, RouteTest/Fixture.swift
As pointed in the WWDC talk "Building Faster in Xcode", relying on the compiler to infer the return type  from a map/filter/compactMap can add up to a slower build time. This PR finds a few places we're creating variables from a map/reduce/compactMap and explicitly names the return type.
Thoughts on adopting this as a best practice going forward? Beyond helping the compiler, it does in fact make it easier to review the code by knowing exactly what is returned. 
=> Describe return type fom map/reduce

MapboxNavigation.podspec
Without this change, Xcode 10 fails with the error:
```
Showing Recent Messages
:-1: Multiple commands produce '/Users/bobby/Library/Developer/Xcode/DerivedData/Voyage-bxmobzxqvtumspcofllpykcoymjs/Build/Products/Debug-iphonesimulator/MapboxNavigation/MapboxNavigation.framework/Info.plist':
1) Target 'MapboxNavigation' has copy command from '/Users/bobby/Documents/mapbox/mapbox-navigation-ios/MapboxNavigation/Info.plist' to '/Users/bobby/Library/Developer/Xcode/DerivedData/Voyage-bxmobzxqvtumspcofllpykcoymjs/Build/Products/Debug-iphonesimulator/MapboxNavigation/MapboxNavigation.framework/Info.plist'
2) Target 'MapboxNavigation' has process command with input '/Users/bobby/Documents/mapbox/voyage-ios/Pods/Target Support Files/MapboxNavigation/Info.plist'
```
Cocoapods seems to be including …
=> Fix Xcode 10 build error

MapboxNavigation/InstructionsBannerView.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1473
If the developer has not implemented the ability to show the steps list view, we should not show the steps list indicator.
=> Do not show steps indicator if delegate is not implemented

CHANGELOG.md, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/TunnelIntersectionManager.swift, MapboxCoreNavigationTests/TunnelIntersectionManagerTests.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigationTests/NavigationViewControllerTests.swift
As pointed out in https://github.com/mapbox/mapbox-navigation-ios/issues/1486, calling `styleManager.timeOfDayChanged()` is expensive because we have to re-init `Solar` on every call to check. 
Now with this change, we're only changing the style from/to day/night when the tunnel manager tells us we have entered/exited a tunnel.
=> Use tunnel manager delegate for changing styles

CHANGELOG.md, MapboxCoreNavigation.podspec, MapboxCoreNavigation/NavigationLocationManager.swift, MapboxNavigation.xcodeproj/project.pbxproj
Now that the Mapbox Maps SDK for iOS has increased the minimum deployment target to iOS 9, we can follow this in MapboxCoreNavigation as well.
ref https://github.com/mapbox/mapbox-gl-native/pull/11776
=> Increase minimum deployment target to iOS 9

CHANGELOG.md, MapboxCoreNavigation/RouteController.swift, MapboxNavigation.xcodeproj/project.pbxproj
Addresses part 1 of https://github.com/mapbox/mapbox-navigation-ios/issues/1474
If an app sets `UIDevice.isBatteryMonitoringEnabled` on their own, we should not reset this property when initing/deiniting. 
This new prop makes it so developers can control whether this `UIDevice.isBatteryMonitoringEnabled` is enabled internally.
/cc @mapbox/navigation-ios @simonseyer
=> Allow developers to control whether battery monitoring is enabled

CHANGELOG.md, MapboxNavigation/NavigationMapView.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1505
Fixes and adds a few optimizations around going into overhead mode. The sliding issue mainly is due to the fact we were animating to the position of the puck which is not necessary when going into overhead mode.
=> Fix UserCourseView sliding

MapboxNavigation/RouteMapViewController.swift
Fixes #1467. Problem was in the `RouteMapViewController` where setting `InstructionsView` instructions before adding the view to the hierarchy could cause issues with the appearance engine in some cases.
=> Exit View Sizing Fix

CHANGELOG.md, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/StyleManager.swift, MapboxNavigationTests/NavigationViewControllerTests.swift, MapboxNavigationTests/StyleManagerTests.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1511
This makes `StyleManager.locationFor(styleManager:)` allows developer to optionally return a location. The optionality we do in https://github.com/mapbox/mapbox-navigation-ios/blob/96b2d6e7902c529b475e939288615935c2197c2b/MapboxNavigation/NavigationViewController.swift#L611-L621
doesn't seem to help us much in the case where `routeController.location ` is nil.
=> Allow locationFor(styleManager:) to optionally return location

CHANGELOG.md, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/StepsViewController.swift
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/1497
There were a handful of issues here:
* We were using the currentLegProgress. This means you can only look at steps on the current leg.
* `sections` is continually being groomed and only includes the remaining steps. We need to make sure the selected index maps correctly to the correct step.
=> Fix off by one when selecting steps view

CHANGELOG.md, Examples/Objective-C/Info.plist, Examples/Swift/Info.plist, MapboxNavigation/DayStyle.swift, MapboxNavigation/NavigationViewController.swift
`UIApplication.shared.statusBarStyle` was deprecated in iOS 9 in favor of `UIViewController.preferredStatusBarStyle`. This PR adopts the new non-global way of styling the status bar. A welcome side effect is that it no longer flashes instantly from light to dark but instead transitions between the updates.
cc @bsudekum
=> Replace deprecated way of styling the status bar

MapboxNavigation/NavigationViewController.swift
One good piece of learning that has come out of #1542, is starting progress updates from the route controller sooner. This came out of the fact we could not call `NavigationMapView.updateCourseTracking(location:animated:)` when init in RouteMapViewController, [ref](https://github.com/mapbox/mapbox-navigation-ios/pull/1542/files#diff-292af689ce88d5b5aa06966456abc0e9L162). To make sure the user puck starts in the right place in the world, we need to make sure the route controller is emiting progress updates by the time we show the view.
While we figure out what is happening in #1542, let's merge this now so we don't have to rely on the user puck starting at the first coordinate on the route, but rather their actual location.
=> Start route controller progress updates sooner

MapboxCoreNavigation/RouteController.swift
Followup to https://github.com/mapbox/mapbox-navigation-ios/pull/1534
This fixes an issue where the past fist instruction on a previous route stuck around and uses the same logic we have in place for calculating the currentSpokenInstruction.
/cc @vincethecoder
=> Fix visual index when rerouting

README.md, docs/cover.md
Updated the readme and the jazzy docset’s cover page to reflect the change in #1494 that increased Core Navigation’s minimum deployment target from iOS 8.0 to iOS 9.0.
/cc @bsudekum
=> Core Navigation no longer supports iOS 8

scripts/document.sh
Adds a few missing classes to our docs.
/cc @1ec5
=> Add missing MapboxDirections.swift classes to docs

Cartfile, Cartfile.resolved, MapboxNavigation-Documentation.podspec, MapboxNavigation.podspec, MapboxNavigation/NavigationMapView.swift
This updates the maps SDK to v4.2.0 and takes advantage of a newly exposed API, `MGLMapCamera(_:fitting:edgePadding:)`. This makes the transition to overhead view much smoother since we no longer need to first set the pitch and heading to zero.
=> Update Maps SDK, use new camera fitting api

MapboxNavigation/RouteVoiceController.swift
As pointed out in https://github.com/mapbox/mapbox-navigation-ios/issues/1553, there are a few properties on RouteVoiceController that do no do much.
This PR removes these.
=> Remove unused properties on RouteVoiceController

MapboxNavigation.xcodeproj/project.pbxproj
Ensure the access token build phase takes precedence over the standard Info.plist copying step under the new build system.
/cc @bsudekum @JThramer
=> Ensure build phase inserts access token

MapboxNavigation/NavigationViewController.swift
https://github.com/mapbox/mapbox-navigation-ios/pull/1547 caused a regression where the first instruction on the first step was never announced.
We need to first initialize the voice controller before we begin listening in on spoken instruction notifications.
=> Fix missing instruction on first step

CHANGELOG.md, MapboxNavigation/NavigationViewController.swift
Removed UIApplication.shared.isIdleTimerDisabled management from NavigationViewController to avoid conflicting with app-specific idle timer strategies.
=> Allow opting out of idle timer management

CHANGELOG.md, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift
When the style manager made changes to the current theme, we formerly updated the banner instruction view's background color at the wrong spot. This pull request addresses the issue by setting the banner instruction view's background color within the `NavigationViewController`. 
Fixes #1540 
TODO:
=> Fixed the partial style of user interface whenever styles are switched. 

CHANGELOG.md, MapboxNavigation/RouteMapViewController.swift
Seeing a few rare crashes around this code. To be safe, we should not force unwrap these userInfo key/values.
=> Don't force unwrap userInfo keys

MapboxCoreNavigation/EventDetails.swift
Hey all,
So @bsudekum recently caught that #1533 dropped a few datapoints in the new `EventDetails` class. This PR re-adds them.
* adding platform, operatingSystem, and device datapoints to `EventDeta…ils`. Also alphabetized the properties list.
=> Missing telemetry vales

scripts/document.sh
#1552 removed update-guides.sh but not the reference to it within document.sh. So generating the jazzy docset at release time resulted in a shell error. This PR removes the stray reference, fixing the documentation generation script.
/cc @JThramer @vincethecoder
=> Remove stray reference to nonexistent script

CHANGELOG.md, MapboxNavigation/StyleManager.swift
Fixes #1603
This change exposes `automaticallyAdjustsStyleForTimeOfDay`, `delegate`, and
`styles` on StyleManager. It also fixes a bug which could lead to duplicated observers where setting `automaticallyAdjustsStyleForTimeOfDay` called `resumeNotifications()` instead of `resetTimeOfDayTimer()`.
=> Expose additional properties on StyleManager

CHANGELOG.md, MapboxNavigation/MGLMapView.swift
Added an `MGLMapView.showsIncidents` property to toggle the visibility of any Mapbox Incidents data on a map view. Mapbox Incidents source v1 is a new public tileset that indicates incidents, such as road closures and detours. It is a companion to [Mapbox Traffic source v1](https://www.mapbox.com/vector-tiles/mapbox-traffic-v1/).
The `MGLMapView.showsIncidents` property is based on the existing `MGLMapView.showsTraffic` property. Like `showsTraffic`, `showsIncidents` only toggles the visibility of the relevant layers; it doesn’t add incidents to a style that lacks those layers. (Public styles that come with incidents layers are forthcoming.) Applications that provide a “Shows Traffic” toggle may want to set both `showsTraffic` and `showsIncidents`, since users generally conflate the two …
=> Add incidents toggle

CHANGELOG.md, Examples/Objective-C/Base.lproj/Main.storyboard, Examples/Swift/Base.lproj/Main.storyboard, MapboxNavigation/MGLStyle.swift
The `MGLStyle.navigationGuidanceDayStyleURL` and `MGLStyle.navigationGuidanceNightStyleURL` properties now return [version 4 of the Mapbox Navigation Guidance Day and Night styles](https://blog.mapbox.com/incidents-are-live-on-the-map-beeff6b84bf9), respectively. These styles indicate incidents such as road closures and detours, allowing them to take advantage of the toggle added in #1613.
Fixes #1347.
/cc @mapbox/navigation-ios @danesfeder
=> Upgrade to v4 navigation styles

MapboxNavigation/RouteMapViewController.swift
We only use the feedback view controller in one place so there is no need to keep a global ref.
cc @bsudekum
=> Remove unneeded ref to FeedbackViewController

MapboxCoreNavigation/RouteController.swift
Proposed solution is to make *suspendLocationUpdates* cancel the next scheduled location interpolation. This way calling *suspendLocationUpdates* or *endNavigation* then releasing all references to the RouteController allows it to be released.
Note that releasing all references to the RouteController object without calling *suspendLocationUpdates* first still leads to a memory leak + parasites notifications being triggered, etc
fixes #1623
=> Fix retain cycle if dead reckoning is enabled on RouteController.

circle.yml
=> Cache pod master repo on CircleCI

MapboxCoreNavigation/EventDetails.swift, MapboxCoreNavigation/EventsManager.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/CarPlayManager.swift, MapboxNavigation/FeedbackViewController.swift
Provided optional `sessionState` and `routeController` for specific telemetry events where these fields are not required.
/cc @frederoni @1ec5 @akitchen
=> Permit routeless events manager for unique telemetry events

MapboxNavigation/CarPlayManager.swift, MapboxNavigation/CarPlayMapViewController.swift, MapboxNavigation/CarPlayNavigationViewController.swift
Restore the map template’s buttons when exiting navigation via an additional intermediate class around CPMapTemplate. This keeps the CarPlay interface usable after exiting navigation.
There are still a bunch of code smells in this PR, not least of which is the fact that the navigation session is begin within the navigation view controller’s initializer. NavigationMapTemplateController started out as a subclass of CPMapTemplate, since it isn’t possible for the interface controller to present a CPMapTemplate subclass, but it might end up getting folded back into CarPlayNavigationViewController.
Also renamed some CarPlayNavigationViewController properties.
=> Restore map template when exiting navigation

Examples/Swift/AppDelegate.swift, MapboxNavigation/CarPlayManager.swift, MapboxNavigationTests/CarPlayManagerTests.swift
When navigation starts within CarPlay, we should reuse some of the
dependencies, not just the route.
Triggers needed to set up this flow should be provided in the CarPlay SDK but the implementation should be deferred to the developer.
@akitchen
=> Re-use directions, location manager, and route controller from CarPlay

Examples/Swift/AppDelegate.swift, MapboxNavigation/CarPlayManager.swift
The goal here is to avoid developers needing to implement an empty stub that returns nil. I've kept the optional return values, but made the methods for map buttons and leading buttons optional
I've left the method for trailing buttons alone for now, as we need to do a bit more to decouple it from our stubbed example locations for testing. Ideally it would follow this pattern as well, but more thought on organizing the example stub locations is needed.
=> Adjust optionality of CarPlayManagerDelegate methods

MapboxNavigation/CarPlayMapViewController.swift, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/DayStyle.swift
The navigation v4 styles are now visible in CarPlay, both on the main map and in turn-by-turn navigation.
/cc @vincethecoder @bsudekum
=> Enable style manager in CarPlay

Examples/Swift/AppDelegate.swift, MapboxNavigation/CarPlayManager.swift, MapboxNavigation/CarPlayNavigationViewController.swift
Added a back button to the CarPlay route preview screen. The key is to push a new map template onto the stack for previewing rather than blowing away the stack. (The map templates all share the same map view controller; this is only about managing overlays and such.) The same approach might allow us to effortlessly push and pop a navigation-centric map template as an alternative to #1644.
The route preview items have been refined to more closely match Maps. Each route is summarized by the expected travel time and secondarily by the major road names. Setting the major road names in a smaller font allows more of each name to be visible. The user can still compare travel times using the absolute travel times.
The Simulate / Don’t Simulate toggle button has been moved to the route preview …
=> Refine navigation among CarPlay templates

MapboxNavigation/CarPlayMapViewController.swift, MapboxNavigation/CarPlayNavigationViewController.swift
This PR fixes switching between day and night styles in CarPlay (following up on #1654), as well as the Overview button in CarPlay turn-by-turn navigation.
In both the main map view and the navigation map view, switch between day and night styles based on a location retrieved from a location manager, not a route controller or map view. The route controller may disqualify any location in the iOS simulator due to a lack of course readings, while the map view may not have a location by the time the style manager asks for it.
When tapping the Overview button in turn-by-turn navigation in CarPlay, use the location manager’s location instead of the route controller’s location, just as RouteMapViewController does. Once again, the route controller disqualifies just about any location in the iOS …
=> Use location manager for overview, style switching in CarPlay

Examples/Objective-C/ViewController.m, Examples/Swift/CustomViewController.swift, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift, MapboxCoreNavigationTests/RouteControllerTests.swift, MapboxCoreNavigationTests/Support/MMEEventsManagerSpy.swift, MapboxCoreNavigationTests/TunnelIntersectionManagerTests.swift, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/NavigationViewController.swift, MapboxNavigationTests/LaneTests.swift, MapboxNavigationTests/LeaksSpec.swift, MapboxNavigationTests/NavigationViewControllerTests.swift, MapboxNavigationTests/StepsViewControllerTests.swift
By removing the implicit creation of the EventsManager inside RouteController's initializer a number of flaky test issues are resolved and our dependency graph is made more clear.
Once merged, I will need to port this over to the carplay branch
=> Refactor RouteController's dependency on EventsManager to remove implicit creation

MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile, MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
By removing the transitive dependency on MapboxMobileEvents in the CocoaPods integration test, we'll parse the same version as stated in `MapboxCoreNavigation.podspec`, making it a more thorough and safe integration test.
cc @akitchen @vincethecoder
=> Avoid transitive dependency in CocoaPods integration test

MapboxCoreNavigationTests/Info.plist, MapboxNavigationTests/Info.plist, circle.yml
The output of the XCT process contains relevant information needed to track down an async crash in tests.
@akitchen
=> Store CI test results

MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/NSAttributedString.swift, MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
Before adding an attributed string to a maneuver’s attributed instructions, downgrade any instance of a custom text attachment subclass, such as ShieldAttachment, to NSTextAttachment. This ensures that the attributed string can be marshaled over to the CarPlay unit. Unfortunately, even standard NSTextAttachments don’t show up in the CarPlay simulator, but apparently they do show up on an actual CarPlay device.
Along the way, secondary and tertiary text instructions are now included in plain-text maneuver instructions for CarPlay units that lack support for attributed strings.
Fixes #1652.
/cc @JThramer
=> Fix crash displaying shields in CarPlay

MapboxCoreNavigation/NavigationLocationManager.swift, MapboxCoreNavigation/SimulatedLocationManager.swift, MapboxNavigation/CarPlayManager.swift, MapboxNavigation/NavigationViewController.swift
The regression was caused by passing a reference to the location manager instead of copying which lead to the NavigationViewController receiving the location updates and the RouteController associated with CarPlay never arrived at the destination.
cc @akitchen @1ec5
=> Show rating on CarPlay if connected

MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/CarPlayManager+Search.swift, MapboxNavigation/Locale.swift
When searching for something like "Yerba Buena" with focal location set to SF and locale set to `en`, the geocoder’s top result is Argentina. IIRC, this happens because "Yerba Buena" in the US is not translated into English but it's using English as a base language.
This change omits the language query parameter if the locale’s language code is equal to `en` and also sets a focal location.
cc @akitchen @1ec5
=> Avoid irrelevant search results

MapboxNavigation/CarPlayManager.swift
The intention is to prevent the scenario where the system puts the device into a sleep state. Unfortunately, this impacts the map interactions on a carplay head unit. As a recommendation by Apple developer documentation, mapping apps should disable the idle timer to allow the continuous display or interaction with content.
=> Application sleep mode is disabled when carplay is connected.

circle.yml
This should help with the pod integration failures on CI due to external toolchain update(s)
=> Use a more flexible destination description for pod integration test

CHANGELOG.md, MapboxNavigation/CarPlayMapViewController.swift, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/DayStyle.swift, MapboxNavigation/MGLStyle.swift, MapboxNavigation/Style.swift
Removed CarPlayDayStyle and CarPlayNightStyle in favor of using DayStyle and NightStyle in all user interface idioms. Vary ExitView and GenericShieldView by idiom.
Added a `Style.previewMapStyleURL` property, which is used by CarPlayMapViewController but can also be used in the future for the preview view controller proposed by #808. In the meantime, the property is visible to applications for custom preview view controller implementations.
=> Fold CarPlay-specific styles into main styles

MapboxNavigation/InstructionPresenter.swift, MapboxNavigation/VisualInstruction.swift
Add CarPlay’s throwaway instruction label to the car window while rendering the instruction. While taking a snapshot of GenericShieldView or ExitView, add the view to the data source’s window if the data source is a view, but not necessarily the application’s main window.
Depends on #1695. I’ll retarget this PR against the `carplay` branch before merging.
=> Fix generic shields in CarPlay

MapboxNavigation/CarPlayManager.swift
We can reintroduce this later if needed, as a part of a bigger design discussion around managing the navigation bar and map buttons during different navigation states.
=> Removes code hiding map template buttons during panning

MapboxNavigation/NavigationMapView.swift
[Before Video](https://www.dropbox.com/s/yxzpn6vw4tnte43/camera-angle-before.mov?dl=0)
[After Video](https://www.dropbox.com/s/ymdxxjfh45ad2fp/nofly.mov?dl=0)
Fixing issue where layout update overrides custom camera with hardcoded camera, causing angle/distance shift when you tapped on the screen.
=> Camera Angle Fix

MapboxNavigation/CarPlayManager.swift, MapboxNavigation/CarPlayMapViewController.swift
Fixed behavior with panning, and fixed bug where recenter button shows just by showing the panning interface. It should not show until you actually move.
=> Panning Gesture Fixes

CHANGELOG.md, MapboxCoreNavigation/CLLocation.swift, MapboxCoreNavigationTests/LocationTests.swift, MapboxCoreNavigationTests/RouteControllerTests.swift
This reverts commit #1385, which resulted in the puck overshooting at turns and detaching from the route line along curved roads. In some cases, it may have exacerbated other issues with course tracking.
When we revisit this feature in the future, we’ll need to ensure that dead reckoning is only part of the solution: the result of dead reckoning needs to be snapped to the route line. That wasn’t happening before, so this feature tended to foil any attempt at snapping the user’s location to the route line, at least visually. As well, we’ll need to find an alternative to `CLLocation.speed`, which is an instantaneous reading that is documented to be unsuitable for dead reckoning.
=> Revert user puck dead reckoning

Examples/Swift/AppDelegate+CarPlay.swift, MapboxNavigation/CarPlayManager.swift, MapboxNavigation/MapboxVoiceController.swift
We're relying on a compiler bug in a few places:
```swift
guard let `self` = self else { return }
```
according to https://github.com/apple/swift-evolution/blob/master/proposals/0079-upgrade-self-from-weak-to-strong.md#relying-on-a-compiler-bug
However, Swift 4.2 supports the following syntax:
```swift
guard let self = self else { return }
```
=> Avoid abusing a compiler bug

MapboxNavigation.xcodeproj/project.pbxproj
Despite the Geocoder being optional, it's still required to build `MapboxNavigation`. `MapboxGeocoder.swift` is still being link against in the `Example-CarPlay` target.
This change removes `MapboxGeocoder.swift` from `MapboxNavigation`’s build phase.
@akitchen @1ec5  @chezzdev
=> Optional Geocoder

CHANGELOG.md, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift
`NavigationMapView` no longer mutates its own frame rate implicitly. A new `NavigationMapView.updatePreferredFrameRate(for:)` method allows the developer to update the frame rate in response to route progress change notifications. Previously, if the developer wanted to customize the frame rate, they would’ve had to install their own notification observer anyways and hope that it would respond to route progress change notifications after NavigationMapView’s built-in observer.
This change gets NavigationMapView out of the business of snooping on the stream of route progress updates coming from every active route controller. This is particularly beneficial when CarPlay is connected, because there are two active route controllers in that case that may deliver staggered route progress updates. …
=> Make NavigationMapView’s frame rate more easily configurable

MapboxCoreNavigation/NavigationService.swift
That was fun.
* Fixing issue where merge clobber caused regression where native location source could influence progress during location updates when simulationMode is `.always`.
/cc @mapbox/navigation-ios @nitaliano
=> Service yo-yo fix

CHANGELOG.md, Examples/Swift/CustomViewController.swift, Examples/Swift/ViewController.swift, MapboxCoreNavigation/RouteProgress.swift, MapboxNavigation/InstructionsBannerView.swift, MapboxNavigation/InstructionsBannerViewLayout.swift, MapboxNavigation/RouteMapViewController.swift
* Added `swipeable` property to `InstructionsBannerView`
* Added `didSwipeInstructionsBanner` to `InstructionsBannerViewDelegate`
* Deprecated `didDragInstructionsBanner` for `InstructionsBannerViewDelegate`
* Updates `RouteMapViewController` to implement swipeable banner
@1ec5 @frederoni
=> Ability to swipe InstructionsBannerView

CHANGELOG.md, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/RouteMapViewController.swift, MapboxNavigationTests/UIViewAnimationOptionsTests.swift
Worked around a compiler crash due to an exhaustive switch statement that, through no fault of its own, failed to account for a common yet private enumeration value.
Fixes #1600 real good.
/cc @akitchen @JThramer
=> Safely convert UIViewAnimationCurve to UIViewAnimationOptions

CHANGELOG.md, MapboxCoreNavigation/CountdownTimer.swift, MapboxCoreNavigation/NavigationService.swift, MapboxCoreNavigationTests/NavigationServiceTests.swift
Fixes #1756.
* Default GPS Patience is now 2.5 seconds.
* Ability to adjust patience has been added.
Todo: 
=> Adjustable GPS Patience

CHANGELOG.md, MapboxNavigation/CarPlayNavigationViewController.swift
Copied the `NavigationViewController.location(for:)` implementation over to `CarPlayNavigationViewController.location(for:)` so that the CarPlay navigation map view can show the night style even before the navigation service is able to say where the day/night choice should be made from.
Fixes #1760.
=> Add location fallback for CarPlay navigation style

CHANGELOG.md, Examples/Swift/CustomViewController.swift, MapboxNavigation/InstructionsBannerView.swift, MapboxNavigation/NavigationMapView.swift
* Adds ` InstructionsBannerView.showStepIndicator` so we have control over whether we want to show the indicator in our custom UI or not. Not everyone will show the steps list from the top so this needs to be configurable.
* Makes `BaseInstructionsBannerView.init(frame: CGRect)` public so we can actually initialize this outside of the SDK.
* Makes `NavigationMapView.enableFrameByFrameCourseViewTracking` public so when you want to move the map camera in navigation, this can help prevent the puck from flying across the screen.
=> Swipeable Banner Custom UI

MapboxCoreNavigation.podspec, circle.yml
In addition to `pod install` we should test `pod update` to make sure we're compliant with recent releases of the dependencies.
cc @akitchen @JThramer @vincethecoder
=> Add CI bot to test cocoapods update

MapboxCoreNavigation/Feedback.swift, MapboxCoreNavigation/NavigationService.swift, MapboxCoreNavigation/RouteController.swift, MapboxNavigation/FeedbackViewController.swift, MapboxNavigation/NavigationViewController.swift
- Resolved warnings for deprecated `EventsManager`, renamed `NavigationEventsManager`.
/cc @akitchen @JThramer @frederoni
=> Fixed the warnings for deprecated events manager.

CHANGELOG.md, MapboxNavigation/NavigationMapView.swift
Opted the route line shape sources into line distance metrics so that the map view delegate can apply a gradient to associated line style layers.
Fixes #1798.
/cc @frederoni @vincethecoder
=> Allow map view delegate to apply gradient to route line

MapboxNavigationTests/Fixtures/Fixture.swift, MapboxNavigationTests/RouteControllerSnapshotTests.swift, MapboxNavigationTests/SimulatedLocationManagerTests.swift
~~Stick to MapboxDirections’ public API but stub out Map Matching API access using OHHTTPStubs, the same library that MapboxDirections.swift’s unit tests use.~~ Stick to MapboxDirections’ public API, adapting some internal MapboxDirections code for converting a Map Matching API response to a Route.
Fixes #1753.
=> Remove dependency on debug build of MapboxDirections

CHANGELOG.md, Examples/Swift/ViewController.swift, MapboxNavigation/CarPlayMapViewController.swift, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/NavigationView.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigationTests/NavigationViewControllerTests.swift
Removed RouteMapViewController dependency on MGLMapViewDelegate. It’s now safe to set `NavigationMapView.delegate` on the value of `NavigationViewController.mapView` and implement MGLMapViewDelegate in application code. RouteMapViewController now relies on key-value observation to manipulate NavigationMapView, including localizing the style’s labels.
The upside is that developers automatically get access to any customization hooks as they’re added to the map SDK, without any intervention on the part of the navigation SDK. This is feasible today because the navigation SDK wasn’t actually using a whole lot from MGLMapViewDelegate. The downside is that we may in the future need to hook into more of MGLMapViewDelegate, requiring some code that’s a lot more obtuse than key-value observation. …
=> Remove RouteMapViewController dependency on MGLMapViewDelegate

LICENSE.md, README.md
@frederoni @1ec5 - This is a first pass attempt at adding the Navigator license to this repo to create some license clarity for contributors and users.
This is related to the Android PR found here: https://github.com/mapbox/mapbox-navigation-android/pull/1494
cc @akitchen
=> Add license for Navigator

Examples/Swift/CustomViewController.swift
Removed unnecessary guard of a non-optional subscript.
cc @1ec5
=> Fix various compiler warnings

MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme, MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme, circle.yml
Enabled code coverage for MapboxCoreNavigation and MapboxNavigation.
Let's give it a few iterations until we enforce ✅ covecov protection on the master branch.
=> Gather Code Coverage data

CHANGELOG.md, Cartfile.resolved, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/CarPlayManager.swift, MapboxNavigation/CarPlayManagerDelegate.swift, MapboxNavigationTests/CarPlayManagerTests.swift
Fixes #1824. Allowing user to inject custom Directions client @ `CarPlayManager` init time.
=> Customize Directions Client in CarPlayManager.

CHANGELOG.md, MapboxNavigation/CarPlayManager.swift, MapboxNavigation/CarPlayManagerDelegate.swift, MapboxNavigation/CarPlayMapViewController.swift, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/StyleManager.swift, MapboxNavigationTests/CarPlayManagerTests.swift, MapboxNavigationTests/StyleManagerTests.swift, TestHelper/Fixture.swift
Applications can now customize the style of the map in CarPlay (nominally the rest of the CarPlay interface, but really just the map style).
Renamed `CarPlayManager(_:)` to `CarPlayManager(styles:eventsManager:)` and `CarPlayNavigationViewController(with:mapTemplate:interfaceController:manager:styles:)` to `CarPlayNavigationViewController(navigationService:mapTemplate:interfaceController:manager:styles:)`. These initializers now accept Style objects as arguments, which are applied throughout the CarPlay interface, similar to NavigationViewController. DayStyle and NightStyle are still used by default but no longer hard-coded everywhere. The application can set `CarPlayManager.styles` at any time to change the map style, for example if it sets the style of NavigationViewController or a …
=> Allow style customization in CarPlay

CHANGELOG.md, MapboxNavigation/NavigationMapView.swift
Fixes #1731 
- Update UserCourseView instantaneously when a camera change is triggered by a user interaction.
- Update UserCourseView instantaneously when the map view’s layout margin changes.
| Before  | After         |
| ------------- |:-------------:|
| ![before](https://user-images.githubusercontent.com/764476/48488042-2ad50080-e820-11e8-8160-245ca5508042.gif) | ![after](https://user-images.githubusercontent.com/764476/48488049-2dcff100-e820-11e8-9f81-2d2cf9ab38a9.gif) |
| ![rotate_before](https://user-images.githubusercontent.com/764476/48488056-3294a500-e820-11e8-9ff3-7a5d3711b16b.gif) | ![rotate_after](https://user-images.githubusercontent.com/764476/48488064-36282c00-e820-11e8-92be-d5091a8f93d4.gif) |
cc @1ec5 @vincethecoder @JThramer
=> Update UserCourseView instantaneously

codecov.yml
Fluctuations of ~0.1% occur now and then but should not mark the PR with a big 🔴.
As the tests stabilize, we can try to lower the threshold until we find a sweet spot.
cc @JThramer @akitchen
=> Adjust codecov threshold

CHANGELOG.md, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/NavigationMapView.swift
Fixed an issue where the user puck pointed away from the route line during turn-by-turn navigation in CarPlay. The map’s vanishing point now accounts for safe area insets, including the side maneuver view. As described in https://github.com/mapbox/mapbox-navigation-ios/issues/1681#issuecomment-440119219, we now place the map view’s horizontal center where we want the vanishing point to be. This approach is preferable to rotating the map because it preserves the angles at which cross streets meet the route line.
Before:
After:
Before this PR can land, I need to fix a regression where standalone NavigationMapViews on the iPhone fail to respect the safe area insets.
Fixes #1681.
/cc @mapbox/navigation-ios @d-prukop
=> Fix CarPlay navigation map vanishing point

CHANGELOG.md, MapboxCoreNavigation/DistanceFormatter.swift, MapboxCoreNavigationTests/DistanceFormatterTests.swift
In CarPlay, the meter is once again defined as the distance such that the speed of light in vacuum _c_ is 299&nbsp;792&nbsp;458 when expressed in meters per second, where the second is defined in terms of the cesium frequency Δν<sub>Cs</sub>. Likewise with the centimeter and millimeter.
Fixes #1853.
=> Fix metric measurements in CarPlay

CHANGELOG.md, MapboxNavigation/CarPlayNavigationViewController.swift
This is a followup to #1845 that balances out the CarPlay navigation map view’s safe area insets, accounting for the maneuver panel, on initialization. #1845 had waited until the first change to the safe area insets, which meant that the user puck was also incorrectly positioned (though consistent with the vanishing point) when starting navigation.
=> Balance safe area insets when initializing CarPlay navigation map view

CHANGELOG.md, MapboxNavigation/CarPlayManager+Search.swift
When selecting a search result in CarPlay, the resulting routes lead to the search result’s routable location when available. `CarPlayManager.forwardGeocodeOptions(_:)` was already requesting routable locations from the geocoder.
Fixes #1739.
/cc @frederoni @vincethecoder
=> Calculate route to routable location in CarPlay

CHANGELOG.md, MapboxNavigation/InstructionsBannerView.swift
This PR updates most of the views, and distance members public so it is easier to build custom UI's on top of the `BaseInstructionsBannerView`
**cc** @akitchen @vincethecoder @1ec5
=> Updates views on BaseInstructionsBannerView to be public

CHANGELOG.md, MapboxNavigation/VisualInstruction.swift
Fixes #1851 
Made `VisualInstruction.containsLaneIndications`, `VisualInstruction.maneuverImageSet(side:)`, `VisualInstruction.shouldFlipImage(side:)`, and `VisualInstruction.carPlayManeuverLabelAttributedText(bounds:shieldHeight:window:)` public.
cc @1ec5 @JThramer
=> Publicize VisualInstruction helper methods

CHANGELOG.md, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/ImageDownload.swift, MapboxNavigation/NSAttributedString.swift
When preparing attributed instruction strings for CarPlay, resize any text attachment image taller than 16 points, preserving the aspect ratio.
Here’s a before and after:
Shields on the phone are unaffected:
Fixes #1867 and speculatively fixes #1866. A more correct fix for #1866 would require adjustments to the constraints in ExitView and GenericRouteShield.
=> Downsize shields in instructions in CarPlay

CHANGELOG.md, MapboxCoreNavigation/RouteController.swift
* Speculatively fixing issue where, upon starting a new leg of a route, a situation can occur where the RouteController interpolates user-course incorrectly, causing it to think that an off-route event has occured.
=> Speculative route-start course quick-fix

MapboxNavigation/VisualInstruction.swift
Added missing documentation for `VisualInstruction` that were publicized in #1860 
cc @1ec5 @vincethecoder
=> Add missing VisualInstruction documentation

CHANGELOG.md, MapboxCoreNavigation/NavigationSettings.swift
The `NavigationSettings.shared` property is now accessible in Objective-C code as the class property `MBNavigationSettings.sharedSettings`.
/cc @frederoni @JThramer @riastrad
=> Make NavigationSettings.shared accessible in Objective-C

MapboxNavigation/NavigationMapView.swift
Calculating line distance metrics is flaky in some scenarios. See https://github.com/mapbox/mapbox-gl-native/issues/13378 for more information.
cc @1ec5 @akitchen
=> Disable line distance metrics

CHANGELOG.md, MapboxCoreNavigation/PortableRouteController.swift, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/Router.swift
Fixes #1878, where the navigator can get out-of-sync with the route controller when navigating multi-leg routes. This could potentially cause a situation where the navigator always reports you as on-route for any leg other than the first.
=> Incrementing navigator index for multi-leg routes.

CHANGELOG.md, MapboxCoreNavigation/CLLocation.swift, MapboxCoreNavigation/EventDetails.swift, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/RouteProgress.swift, MapboxCoreNavigationTests/LocationTests.swift, MapboxCoreNavigationTests/NavigationServiceTests.swift, MapboxCoreNavigationTests/RouteProgressTests.swift, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigation/RouteVoiceController.swift, MapboxNavigationTests/NavigationViewControllerTests.swift, MapboxNavigationTests/StepsViewControllerTests.swift
Fixes #1879. Allows for look-behind when you're on the first step of a leg, and look-ahead when you're on the last step.
=> Multi-leg nearby coordinate lookups.

CHANGELOG.md, MapboxNavigation/InstructionPresenter.swift
If there’s no image after the shield downloading operation completes, then there’s no reason to regenerate the attributed text that would embed that image. Bailing instead of regenerating the attributed text heads off infinite recursion that results whenever the shield image URL can’t be reached for some reason, such as the situation described in mapbox/MapboxDirections.swift#322.
Fixes #1887.
/cc @mapbox/navigation-ios @kevinkreiser
=> Fix infinite recursion when failing to download shield image

Example/Base.lproj/Localizable.strings, Example/OfflineViewController.swift
Provides reasonable error messages to the user when tile downloads fail due to access token or bounding box issues.
Centers the map on the user since they probably want to download routing tiles and generate a route near their location.
=> Update the offline tile downloading example

CHANGELOG.md, MapboxCoreNavigation/OfflineDirections.swift, MapboxCoreNavigationTests/BridgingTests.m, MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme
Tail work from https://github.com/mapbox/mapbox-navigation-ios/pull/1808 , offline routing now bridges to Obj-C.
cc @1ec5 @JThramer
=> Expose offline routing functionality to Obj-C

MapboxNavigation/NavigationViewController.swift
Fixes #1899.
I really spent some time here looking for a better interface into `NavigationViewController`, but I just couldn't really find one that made sense. Stop is normally called when the navigation service receives a `endNavigation(feedback:)` call, which happens at the EORVC. We could expose an `endNavigation` mechanism to the UI SDK, but that brings along its' own considerations.
=> Moving navigation service stop into deinit method.

CHANGELOG.md, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/MGLVectorTileSource.swift, MapboxNavigation/NavigationMapView.swift, MapboxNavigation/RouteMapViewController.swift, MapboxNavigationTests/MGLVectorTileSourceTests.swift
Both label localization and feature querying for the current road name label now support styles powered by Mapbox Streets source v8. If the current style doesn’t use the Streets source, version 8 is now added automatically instead of v7.
Fixes #1896.
=> Upgrade to Mapbox Streets source v8

README.md
The traffic coverage page on the Mapbox website notes at least 55 countries with "moderate" or better traffic coverage, updated this stat in the README
=> Updated traffic coverage stat

Cartfile.resolved, MapboxCoreNavigation/NavigationService.swift, MapboxCoreNavigation/SimulatedLocationManager.swift, MapboxCoreNavigationTests/NavigationServiceTests.swift
Fixes #1922. Updates route model of simulator when reroute occurs. 
=> Location Simulator Reroute Report

MapboxCoreNavigation/RouteController.swift
=> Silence reroute questioning if reroute is already inflight

MapboxCoreNavigation/RouteController.swift
Another Quick Fix. Implements #1927.
=> Silence `willReroute` when changing route via property.

MapboxNavigation/NavigationViewController.swift
Quick fix the third. Fixes #1926. Turns out that you can already [end navigation manually](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/NavigationService.swift#L106) through the `NavigationService`.
=> Publicly exposing the EORVC presentation in the NVC

MapboxNavigation/RouteMapViewController.swift
Fixes #1958 
Minor change to two local uses of the `snappedLocation` variable in `RouteMapViewController`'s `labelCurrentRoad` function.
More of an aesthetic change than anything else, so feel free to reject if it poses too much of a headache for `semver` conversations.
=> Correct Local Variable Typo

CHANGELOG.md, MapboxNavigation/NavigationViewController.swift
Another quick fix. Locking down the `navigationService` so it can't be mutated after init.
=> Locking down the navigationService after initialization.

MapboxNavigation/InstructionsBannerView.swift
This won’t quite streamline CocoaPods trunk-pushing, due to #1966, but it’s better than nothing.
Fixes #1758.
/cc @JThramer
=> Fix compiler warning about deprecated delegate method

MapboxCoreNavigation/LegacyRouteController.swift
Folded some extensions of LegacyRouteController into the main implementation of LegacyRouteController. Removed an extraneous type declaration.
Fixes #1966.
=> Silence warnings in LegacyRouteController about LegacyRouteController

Example/OfflineViewController.swift
This is a temporary workaround for mapbox/MapboxDirections.swift#349. mapbox/MapboxDirections.swift#348 surfaced in mapbox/mapbox-navigation-ios#1913, when I optimistically switched to the more strongly typed CoordinateBounds initializer, unaware that it was backwards.
=> Fix coordinate bounds in offline region downloads

CHANGELOG.md, MapboxCoreNavigation/LegacyRouteController.swift
In addition to posting a notification, LegacyRouteController now tells its delegate when the user passes a visual instruction point, for consistency with RouteController.
Fixes #1972.
=> Tell delegate when passing visual instruction point

CHANGELOG.md, Example/CustomStyles.swift, MapboxNavigation/CarPlayMapViewController.swift, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/StyleManager.swift, MapboxNavigationTests/StyleManagerTests.swift
Fixed an issue where custom styles weren’t getting applied. Fixed compiler warnings about mismatched StyleManagerDelegate methods.
Fixes #1970.
=> Update StyleManagerDelegate method signatures

CHANGELOG.md, MapboxCoreNavigation/LegacyRouteController.swift
I noticed a while ago a minor edge case in the step advancement heuristic that I fixed in our fork but never took time to contribute back, so here it is.
Basically if the user doesn't have a valid course, the wrap of the value gives **359**, which is then used as a valid value to compare against the maneuver final heading.
This can lead to advancing the step too early.
I guess it is better to let the fallback mechanism kick in in this case (user moving away from the maneuver location) to trigger the step advancement.
=> Do not use invalid location course in step advancement heuristic.

CHANGELOG.md, Example/AppDelegate+CarPlay.swift, MapboxNavigation/CarPlayManager.swift, MapboxNavigation/CarPlayManagerDelegate.swift, MapboxNavigationTests/CarPlayManagerTests.swift
Adding a delegate message notifying the developer of a route-fetch failure. Developer can optionally return an alert which will be presented to the user.
To-Do: 
=> Carplay Route Failure Delegate Messaging

MapboxNavigation/RouteMapViewController.swift, MapboxNavigationTests/NavigationViewControllerTests.swift
Fixes #1995 
nav-native needs three location updates to fully initialize so we don't have an instructions banner at the very beginning.
This PR fixes that by using the first instruction initially.
cc @1ec5 @JThramer
=> Fix blank banner

MapboxNavigationTests/SimulatedLocationManagerTests.swift
One could say that its... 
..._time has come._
=> Remove testTimerMechanism

CHANGELOG.md, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
Implements #2000. 
* Removing CarPlay arrival UI. 
* Creating delegate method for arrival event. 
* Also renaming navService -> navigationService and taking it public.
To-do: 
=> Carplay Arrival UI - Removal

BenchTests/BenchTests.swift, CHANGELOG.md, Example/AppDelegate+CarPlay.swift, Example/CustomViewController.swift, MapboxNavigation/CarPlayManager.swift, MapboxNavigation/CarPlayManagerDelegate.swift, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/MapboxVoiceController.swift, MapboxNavigation/NavigationViewController.swift, MapboxNavigation/RouteVoiceController.swift, MapboxNavigationTests/CarPlayManagerTests.swift, MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift, MapboxNavigationTests/LeaksSpec.swift, MapboxNavigationTests/MapboxVoiceControllerTests.swift, MapboxNavigationTests/NavigationViewControllerTests.swift
Implements deliverable 2 & 3 in #2017. 
Manifest: 
=> CarPlay Fixes (Short-term)

Example/ViewController.swift
Like it says on the box.
Ending the CarPlay navigation session when the session is cancelled on the device.
=> End CarPlay when Phone Cancels Nav

Example/ViewController.swift, MapboxNavigation/NavigationViewController.swift
Fixing issue where CarPlay would not end navigation gracefully when phone was connected, due to an assumption made in code that was no-longer true. 
=> Carplay Natural End Navigation

MapboxNavigation/CarPlayManager.swift, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigationTests/CarPlayManagerTests.swift
Fixing issue where the signature we obsoleted was never released.
=> Correct Signature Obsoletion for CarPlay

MapboxNavigation/CarPlayMapViewController.swift, MapboxNavigation/CarPlayNavigationViewController.swift, MapboxNavigation/UIEdgeInsets.swift
This PR attempts to fix the compass visibility in the CarPlayNavigationViewController
It still goes out of bounds along with the map view when the correct content inset is applied after the first time the navigation bar is toggled.
cc @1ec5
=> Fix CarPlay compass visibility

CHANGELOG.md, MapboxCoreNavigation/RouteLeg.swift, MapboxCoreNavigation/RouteOptions.swift, MapboxCoreNavigation/RouteProgress.swift, MapboxCoreNavigationTests/RouteProgressTests.swift, MapboxNavigation.xcodeproj/project.pbxproj
Fixed an issue where rerouting would ignore any waypoints from the original route options where the `Waypoint.separatesLegs` property was set to `false`.
~~This is still a work in progress – some test cases fail because the algorithm doesn’t adequately account for edge cases when backtracking.~~
Fixes #2003.
=> Preserve via points after rerouting

MapboxCoreNavigation/EventDetails.swift, MapboxCoreNavigation/LegacyRouteController.swift, MapboxCoreNavigation/NavigationEventsManager.swift, MapboxCoreNavigation/NavigationService.swift, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigation/Router.swift, MapboxCoreNavigationTests/NavigationEventsManagerTests.swift, MapboxNavigation/CarPlayNavigationViewController.swift, TestHelper/CoreLocation.swift, TestHelper/NavigationEventsManagerTestDoubles.swift
Regarding the reroute timestamp, `NavigationEventDetails.created` is now mutable to support the reroute case.
=> Fix depart and arrive event

CHANGELOG.md, MapboxCoreNavigation/RouteController.swift, MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
`updateSpokenInstructionProgress(status:willReRoute:)` must happen after step progress and leg progress has been updated to keep the indexes in sync.
cc @1ec5 @JThramer
=> Fix progress updates order of execution

CHANGELOG.md, MapboxNavigation/BottomBannerViewController.swift, MapboxNavigation/NavigationViewController.swift
Deprecated `BottomBannerViewController(delegate:)` in favor of setting the `BottomBannerViewController.delegate` property separately after initializing a `BottomBannerViewController`.
Fixes #1968.
=> Deprecate BottomBannerViewController(delegate:)

CHANGELOG.md, Example/ja.lproj/Main.strings, MapboxCoreNavigation/Resources/ja.lproj/Localizable.strings, MapboxNavigation.xcodeproj/project.pbxproj, MapboxNavigation/Resources/ja.lproj/Localizable.strings, MapboxNavigation/Resources/ja.lproj/Localizable.stringsdict, MapboxNavigation/Resources/ja.lproj/Navigation.strings
Added a Japanese localization from Transifex, courtesy of [joshpa](https://www.transifex.com/user/profile/joshpa/).
/cc @mapbox/navigation-ios @friedbunny
=> Add Japanese localization

CHANGELOG.md, MapboxNavigation/LaneView.swift
Updated a method call to reflect the renaming that occurred in #1910. This code path only runs inside Interface Builder, so the outdated call site didn’t get caught by CI.
Fixes #2038.
=> Fix Interface Builder designable compilation error

Example/ViewController.swift
Fixed an issue where the example application wouldn’t allow the user to select multiple destinations by long-pressing on the map view. The first destination would be selected just fine, but long-pressing again would delete the first destination in favor of the second, and so on.
This line was intended to retain all but the first element of the array, which would represent the user’s location from the last Directions API request. However, it called `Array.suffix(_:)` instead of `Array.suffix(from:)`. `Array.suffix(_:)` takes a maximum length, not a minimum index. `ViewController.waypoints` got truncated, preventing it from ever holding more than one destination at a time. This change fixes the issue but goes one further by calling `Array.dropFirst()`, which requires a little less mental …
=> Fix multi-waypoint selection in example application

CHANGELOG.md, Example/ViewController.swift, MapboxNavigation/CarPlayManager.swift, MapboxNavigationTests/CarPlayManagerTests.swift
Fixes #2035 and #2034.
* Fixing race-condition bug by waiting until presentation completion to trigger carplay nav
* also changing trip-starting logic to not ask for a NavigationService if the user has already provided one
To-Do: 
=> Car Play Quick Fixes: Data Race Bug

MapboxCoreNavigation/CLLocation.swift, MapboxCoreNavigation/MBNavigator.swift, MapboxCoreNavigationTests/CLLocationTests.swift
`speed` , `course` and `horizontalAccuracy` can all hold invalid values. `MBFixLocation` uses `nil` to communicate the omission of an optional value.
Interestingly an invalid `horizontalAccuracy` also means that the `CLLocationCoordinate2D` will also be bunk, but I've not taken any measures there as that is a required parameter by `MBFixLocation`
I've also made the changes in the other direction as well and marked omitted values from `MBFixLocation` as invalid in the constructed `CLLocation`
=> Marking Invalid Values as Omitted

MapboxNavigation/CarPlayNavigationViewController.swift
Assert that `CarPlayNavigationDelegate.carPlayNavigationViewControllerDidArrive(_:)` has not been implemented by the delegate.
Fixes #2040.
=> Assert that obsoleted delegate method is not implemented
